// Code generated by bonkgen. DO NOT EDIT.

package proto

import "context"

// AccessibilityDisableParams Disables the accessibility domain.
type AccessibilityDisableParams struct{}

// AccessibilityDisable creates a new AccessibilityDisableParams.
func AccessibilityDisable() *AccessibilityDisableParams {
	return &AccessibilityDisableParams{}
}

// Do executes Accessibility.disable.
func (p *AccessibilityDisableParams) Do(ctx context.Context) error {
	return Execute(ctx, AccessibilityCommandDisable, p, nil)
}

// AccessibilityEnableParams Enables the accessibility domain which causes `AXNodeId`s to remain consistent between method calls.
// This turns on accessibility for the page, which can impact performance until accessibility is disabled.
type AccessibilityEnableParams struct{}

// AccessibilityEnable creates a new AccessibilityEnableParams.
func AccessibilityEnable() *AccessibilityEnableParams {
	return &AccessibilityEnableParams{}
}

// Do executes Accessibility.enable.
func (p *AccessibilityEnableParams) Do(ctx context.Context) error {
	return Execute(ctx, AccessibilityCommandEnable, p, nil)
}

// AccessibilityGetPartialAXTreeParams Fetches the accessibility node and partial accessibility tree for this DOM node, if it exists.
type AccessibilityGetPartialAXTreeParams struct {
	// NodeID Identifier of the node to get the partial accessibility tree for.
	NodeID NodeID `json:"nodeId,omitempty"`
	// BackendNodeID Identifier of the backend node to get the partial accessibility tree for.
	BackendNodeID BackendNodeID `json:"backendNodeId,omitempty"`
	// ObjectID JavaScript object id of the node wrapper to get the partial accessibility tree for.
	ObjectID RemoteObjectID `json:"objectId,omitempty"`
	// FetchRelatives Whether to fetch this node's ancestors, siblings and children. Defaults to true.
	FetchRelatives bool `json:"fetchRelatives,omitempty"`
}

// AccessibilityGetPartialAXTreeReturns holds the return values for getPartialAXTree.
type AccessibilityGetPartialAXTreeReturns struct {
	// Nodes The `Accessibility.AXNode` for this DOM node, if it exists, plus its ancestors, siblings and
	// children, if requested.
	Nodes []AccessibilityAXNode `json:"nodes"`
}

// AccessibilityGetPartialAXTree creates a new AccessibilityGetPartialAXTreeParams.
func AccessibilityGetPartialAXTree() *AccessibilityGetPartialAXTreeParams {
	return &AccessibilityGetPartialAXTreeParams{}
}

// WithNodeID sets the nodeId parameter.
func (p *AccessibilityGetPartialAXTreeParams) WithNodeID(nodeID NodeID) *AccessibilityGetPartialAXTreeParams {
	p.NodeID = nodeID
	return p
}

// WithBackendNodeID sets the backendNodeId parameter.
func (p *AccessibilityGetPartialAXTreeParams) WithBackendNodeID(backendNodeID BackendNodeID) *AccessibilityGetPartialAXTreeParams {
	p.BackendNodeID = backendNodeID
	return p
}

// WithObjectID sets the objectId parameter.
func (p *AccessibilityGetPartialAXTreeParams) WithObjectID(objectID RemoteObjectID) *AccessibilityGetPartialAXTreeParams {
	p.ObjectID = objectID
	return p
}

// WithFetchRelatives sets the fetchRelatives parameter.
func (p *AccessibilityGetPartialAXTreeParams) WithFetchRelatives(fetchRelatives bool) *AccessibilityGetPartialAXTreeParams {
	p.FetchRelatives = fetchRelatives
	return p
}

// Do executes Accessibility.getPartialAXTree.
func (p *AccessibilityGetPartialAXTreeParams) Do(ctx context.Context) (*AccessibilityGetPartialAXTreeReturns, error) {
	var res AccessibilityGetPartialAXTreeReturns
	if err := Execute(ctx, AccessibilityCommandGetPartialAXTree, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// AccessibilityGetFullAXTreeParams Fetches the entire accessibility tree for the root Document
type AccessibilityGetFullAXTreeParams struct {
	// Depth The maximum depth at which descendants of the root node should be retrieved.
	// If omitted, the full tree is returned.
	Depth int64 `json:"depth,omitempty"`
	// FrameID The frame for whose document the AX tree should be retrieved.
	// If omitted, the root frame is used.
	FrameID FrameID `json:"frameId,omitempty"`
}

// AccessibilityGetFullAXTreeReturns holds the return values for getFullAXTree.
type AccessibilityGetFullAXTreeReturns struct {
	Nodes []AccessibilityAXNode `json:"nodes"`
}

// AccessibilityGetFullAXTree creates a new AccessibilityGetFullAXTreeParams.
func AccessibilityGetFullAXTree() *AccessibilityGetFullAXTreeParams {
	return &AccessibilityGetFullAXTreeParams{}
}

// WithDepth sets the depth parameter.
func (p *AccessibilityGetFullAXTreeParams) WithDepth(depth int64) *AccessibilityGetFullAXTreeParams {
	p.Depth = depth
	return p
}

// WithFrameID sets the frameId parameter.
func (p *AccessibilityGetFullAXTreeParams) WithFrameID(frameID FrameID) *AccessibilityGetFullAXTreeParams {
	p.FrameID = frameID
	return p
}

// Do executes Accessibility.getFullAXTree.
func (p *AccessibilityGetFullAXTreeParams) Do(ctx context.Context) (*AccessibilityGetFullAXTreeReturns, error) {
	var res AccessibilityGetFullAXTreeReturns
	if err := Execute(ctx, AccessibilityCommandGetFullAXTree, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// AccessibilityGetRootAXNodeParams Fetches the root node.
// Requires `enable()` to have been called previously.
type AccessibilityGetRootAXNodeParams struct {
	// FrameID The frame in whose document the node resides.
	// If omitted, the root frame is used.
	FrameID FrameID `json:"frameId,omitempty"`
}

// AccessibilityGetRootAXNodeReturns holds the return values for getRootAXNode.
type AccessibilityGetRootAXNodeReturns struct {
	Node AccessibilityAXNode `json:"node"`
}

// AccessibilityGetRootAXNode creates a new AccessibilityGetRootAXNodeParams.
func AccessibilityGetRootAXNode() *AccessibilityGetRootAXNodeParams {
	return &AccessibilityGetRootAXNodeParams{}
}

// WithFrameID sets the frameId parameter.
func (p *AccessibilityGetRootAXNodeParams) WithFrameID(frameID FrameID) *AccessibilityGetRootAXNodeParams {
	p.FrameID = frameID
	return p
}

// Do executes Accessibility.getRootAXNode.
func (p *AccessibilityGetRootAXNodeParams) Do(ctx context.Context) (*AccessibilityGetRootAXNodeReturns, error) {
	var res AccessibilityGetRootAXNodeReturns
	if err := Execute(ctx, AccessibilityCommandGetRootAXNode, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// AccessibilityGetAXNodeAndAncestorsParams Fetches a node and all ancestors up to and including the root.
// Requires `enable()` to have been called previously.
type AccessibilityGetAXNodeAndAncestorsParams struct {
	// NodeID Identifier of the node to get.
	NodeID NodeID `json:"nodeId,omitempty"`
	// BackendNodeID Identifier of the backend node to get.
	BackendNodeID BackendNodeID `json:"backendNodeId,omitempty"`
	// ObjectID JavaScript object id of the node wrapper to get.
	ObjectID RemoteObjectID `json:"objectId,omitempty"`
}

// AccessibilityGetAXNodeAndAncestorsReturns holds the return values for getAXNodeAndAncestors.
type AccessibilityGetAXNodeAndAncestorsReturns struct {
	Nodes []AccessibilityAXNode `json:"nodes"`
}

// AccessibilityGetAXNodeAndAncestors creates a new AccessibilityGetAXNodeAndAncestorsParams.
func AccessibilityGetAXNodeAndAncestors() *AccessibilityGetAXNodeAndAncestorsParams {
	return &AccessibilityGetAXNodeAndAncestorsParams{}
}

// WithNodeID sets the nodeId parameter.
func (p *AccessibilityGetAXNodeAndAncestorsParams) WithNodeID(nodeID NodeID) *AccessibilityGetAXNodeAndAncestorsParams {
	p.NodeID = nodeID
	return p
}

// WithBackendNodeID sets the backendNodeId parameter.
func (p *AccessibilityGetAXNodeAndAncestorsParams) WithBackendNodeID(backendNodeID BackendNodeID) *AccessibilityGetAXNodeAndAncestorsParams {
	p.BackendNodeID = backendNodeID
	return p
}

// WithObjectID sets the objectId parameter.
func (p *AccessibilityGetAXNodeAndAncestorsParams) WithObjectID(objectID RemoteObjectID) *AccessibilityGetAXNodeAndAncestorsParams {
	p.ObjectID = objectID
	return p
}

// Do executes Accessibility.getAXNodeAndAncestors.
func (p *AccessibilityGetAXNodeAndAncestorsParams) Do(ctx context.Context) (*AccessibilityGetAXNodeAndAncestorsReturns, error) {
	var res AccessibilityGetAXNodeAndAncestorsReturns
	if err := Execute(ctx, AccessibilityCommandGetAXNodeAndAncestors, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// AccessibilityGetChildAXNodesParams Fetches a particular accessibility node by AXNodeId.
// Requires `enable()` to have been called previously.
type AccessibilityGetChildAXNodesParams struct {
	ID AccessibilityAXNodeID `json:"id"`
	// FrameID The frame in whose document the node resides.
	// If omitted, the root frame is used.
	FrameID FrameID `json:"frameId,omitempty"`
}

// AccessibilityGetChildAXNodesReturns holds the return values for getChildAXNodes.
type AccessibilityGetChildAXNodesReturns struct {
	Nodes []AccessibilityAXNode `json:"nodes"`
}

// AccessibilityGetChildAXNodes creates a new AccessibilityGetChildAXNodesParams.
func AccessibilityGetChildAXNodes(id AccessibilityAXNodeID) *AccessibilityGetChildAXNodesParams {
	return &AccessibilityGetChildAXNodesParams{
		ID: id,
	}
}

// WithFrameID sets the frameId parameter.
func (p *AccessibilityGetChildAXNodesParams) WithFrameID(frameID FrameID) *AccessibilityGetChildAXNodesParams {
	p.FrameID = frameID
	return p
}

// Do executes Accessibility.getChildAXNodes.
func (p *AccessibilityGetChildAXNodesParams) Do(ctx context.Context) (*AccessibilityGetChildAXNodesReturns, error) {
	var res AccessibilityGetChildAXNodesReturns
	if err := Execute(ctx, AccessibilityCommandGetChildAXNodes, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// AccessibilityQueryAXTreeParams Query a DOM node's accessibility subtree for accessible name and role.
// This command computes the name and role for all nodes in the subtree, including those that are
// ignored for accessibility, and returns those that match the specified name and role. If no DOM
// node is specified, or the DOM node does not exist, the command returns an error. If neither
// `accessibleName` or `role` is specified, it returns all the accessibility nodes in the subtree.
type AccessibilityQueryAXTreeParams struct {
	// NodeID Identifier of the node for the root to query.
	NodeID NodeID `json:"nodeId,omitempty"`
	// BackendNodeID Identifier of the backend node for the root to query.
	BackendNodeID BackendNodeID `json:"backendNodeId,omitempty"`
	// ObjectID JavaScript object id of the node wrapper for the root to query.
	ObjectID RemoteObjectID `json:"objectId,omitempty"`
	// AccessibleName Find nodes with this computed name.
	AccessibleName string `json:"accessibleName,omitempty"`
	// Role Find nodes with this computed role.
	Role string `json:"role,omitempty"`
}

// AccessibilityQueryAXTreeReturns holds the return values for queryAXTree.
type AccessibilityQueryAXTreeReturns struct {
	// Nodes A list of `Accessibility.AXNode` matching the specified attributes,
	// including nodes that are ignored for accessibility.
	Nodes []AccessibilityAXNode `json:"nodes"`
}

// AccessibilityQueryAXTree creates a new AccessibilityQueryAXTreeParams.
func AccessibilityQueryAXTree() *AccessibilityQueryAXTreeParams {
	return &AccessibilityQueryAXTreeParams{}
}

// WithNodeID sets the nodeId parameter.
func (p *AccessibilityQueryAXTreeParams) WithNodeID(nodeID NodeID) *AccessibilityQueryAXTreeParams {
	p.NodeID = nodeID
	return p
}

// WithBackendNodeID sets the backendNodeId parameter.
func (p *AccessibilityQueryAXTreeParams) WithBackendNodeID(backendNodeID BackendNodeID) *AccessibilityQueryAXTreeParams {
	p.BackendNodeID = backendNodeID
	return p
}

// WithObjectID sets the objectId parameter.
func (p *AccessibilityQueryAXTreeParams) WithObjectID(objectID RemoteObjectID) *AccessibilityQueryAXTreeParams {
	p.ObjectID = objectID
	return p
}

// WithAccessibleName sets the accessibleName parameter.
func (p *AccessibilityQueryAXTreeParams) WithAccessibleName(accessibleName string) *AccessibilityQueryAXTreeParams {
	p.AccessibleName = accessibleName
	return p
}

// WithRole sets the role parameter.
func (p *AccessibilityQueryAXTreeParams) WithRole(role string) *AccessibilityQueryAXTreeParams {
	p.Role = role
	return p
}

// Do executes Accessibility.queryAXTree.
func (p *AccessibilityQueryAXTreeParams) Do(ctx context.Context) (*AccessibilityQueryAXTreeReturns, error) {
	var res AccessibilityQueryAXTreeReturns
	if err := Execute(ctx, AccessibilityCommandQueryAXTree, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// Accessibility command names.
const (
	AccessibilityCommandDisable               Method = "Accessibility.disable"
	AccessibilityCommandEnable                Method = "Accessibility.enable"
	AccessibilityCommandGetPartialAXTree      Method = "Accessibility.getPartialAXTree"
	AccessibilityCommandGetFullAXTree         Method = "Accessibility.getFullAXTree"
	AccessibilityCommandGetRootAXNode         Method = "Accessibility.getRootAXNode"
	AccessibilityCommandGetAXNodeAndAncestors Method = "Accessibility.getAXNodeAndAncestors"
	AccessibilityCommandGetChildAXNodes       Method = "Accessibility.getChildAXNodes"
	AccessibilityCommandQueryAXTree           Method = "Accessibility.queryAXTree"
)
