// Code generated by bonkgen. DO NOT EDIT.

package proto

import "encoding/json"

// AccessibilityAXNodeID Unique accessibility node identifier.
type AccessibilityAXNodeID string

// String returns the AccessibilityAXNodeID as a string.
func (t AccessibilityAXNodeID) String() string {
	return string(t)
}

// AccessibilityAXValueType Enum of possible property types.
type AccessibilityAXValueType string

const (
	AccessibilityAXValueTypeBoolean            AccessibilityAXValueType = "boolean"
	AccessibilityAXValueTypeTristate           AccessibilityAXValueType = "tristate"
	AccessibilityAXValueTypeBooleanOrUndefined AccessibilityAXValueType = "booleanOrUndefined"
	AccessibilityAXValueTypeIdref              AccessibilityAXValueType = "idref"
	AccessibilityAXValueTypeIdrefList          AccessibilityAXValueType = "idrefList"
	AccessibilityAXValueTypeInteger            AccessibilityAXValueType = "integer"
	AccessibilityAXValueTypeNode               AccessibilityAXValueType = "node"
	AccessibilityAXValueTypeNodeList           AccessibilityAXValueType = "nodeList"
	AccessibilityAXValueTypeNumber             AccessibilityAXValueType = "number"
	AccessibilityAXValueTypeString             AccessibilityAXValueType = "string"
	AccessibilityAXValueTypeComputedString     AccessibilityAXValueType = "computedString"
	AccessibilityAXValueTypeToken              AccessibilityAXValueType = "token"
	AccessibilityAXValueTypeTokenList          AccessibilityAXValueType = "tokenList"
	AccessibilityAXValueTypeDomRelation        AccessibilityAXValueType = "domRelation"
	AccessibilityAXValueTypeRole               AccessibilityAXValueType = "role"
	AccessibilityAXValueTypeInternalRole       AccessibilityAXValueType = "internalRole"
	AccessibilityAXValueTypeValueUndefined     AccessibilityAXValueType = "valueUndefined"
)

// IsValid reports whether the value is a known enum value.
func (t AccessibilityAXValueType) IsValid() bool {
	switch t {
	case AccessibilityAXValueTypeBoolean:
		return true
	case AccessibilityAXValueTypeTristate:
		return true
	case AccessibilityAXValueTypeBooleanOrUndefined:
		return true
	case AccessibilityAXValueTypeIdref:
		return true
	case AccessibilityAXValueTypeIdrefList:
		return true
	case AccessibilityAXValueTypeInteger:
		return true
	case AccessibilityAXValueTypeNode:
		return true
	case AccessibilityAXValueTypeNodeList:
		return true
	case AccessibilityAXValueTypeNumber:
		return true
	case AccessibilityAXValueTypeString:
		return true
	case AccessibilityAXValueTypeComputedString:
		return true
	case AccessibilityAXValueTypeToken:
		return true
	case AccessibilityAXValueTypeTokenList:
		return true
	case AccessibilityAXValueTypeDomRelation:
		return true
	case AccessibilityAXValueTypeRole:
		return true
	case AccessibilityAXValueTypeInternalRole:
		return true
	case AccessibilityAXValueTypeValueUndefined:
		return true
	}
	return false
}

// Values returns all known values of AccessibilityAXValueType.
func (t AccessibilityAXValueType) Values() []AccessibilityAXValueType {
	return []AccessibilityAXValueType{
		AccessibilityAXValueTypeBoolean,
		AccessibilityAXValueTypeTristate,
		AccessibilityAXValueTypeBooleanOrUndefined,
		AccessibilityAXValueTypeIdref,
		AccessibilityAXValueTypeIdrefList,
		AccessibilityAXValueTypeInteger,
		AccessibilityAXValueTypeNode,
		AccessibilityAXValueTypeNodeList,
		AccessibilityAXValueTypeNumber,
		AccessibilityAXValueTypeString,
		AccessibilityAXValueTypeComputedString,
		AccessibilityAXValueTypeToken,
		AccessibilityAXValueTypeTokenList,
		AccessibilityAXValueTypeDomRelation,
		AccessibilityAXValueTypeRole,
		AccessibilityAXValueTypeInternalRole,
		AccessibilityAXValueTypeValueUndefined,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t AccessibilityAXValueType) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *AccessibilityAXValueType) UnmarshalText(data []byte) error {
	*t = AccessibilityAXValueType(data)
	return nil
}

// String returns the string representation.
func (t AccessibilityAXValueType) String() string {
	return string(t)
}

// AccessibilityAXValueSourceType Enum of possible property sources.
type AccessibilityAXValueSourceType string

const (
	AccessibilityAXValueSourceTypeAttribute      AccessibilityAXValueSourceType = "attribute"
	AccessibilityAXValueSourceTypeImplicit       AccessibilityAXValueSourceType = "implicit"
	AccessibilityAXValueSourceTypeStyle          AccessibilityAXValueSourceType = "style"
	AccessibilityAXValueSourceTypeContents       AccessibilityAXValueSourceType = "contents"
	AccessibilityAXValueSourceTypePlaceholder    AccessibilityAXValueSourceType = "placeholder"
	AccessibilityAXValueSourceTypeRelatedElement AccessibilityAXValueSourceType = "relatedElement"
)

// IsValid reports whether the value is a known enum value.
func (t AccessibilityAXValueSourceType) IsValid() bool {
	switch t {
	case AccessibilityAXValueSourceTypeAttribute:
		return true
	case AccessibilityAXValueSourceTypeImplicit:
		return true
	case AccessibilityAXValueSourceTypeStyle:
		return true
	case AccessibilityAXValueSourceTypeContents:
		return true
	case AccessibilityAXValueSourceTypePlaceholder:
		return true
	case AccessibilityAXValueSourceTypeRelatedElement:
		return true
	}
	return false
}

// Values returns all known values of AccessibilityAXValueSourceType.
func (t AccessibilityAXValueSourceType) Values() []AccessibilityAXValueSourceType {
	return []AccessibilityAXValueSourceType{
		AccessibilityAXValueSourceTypeAttribute,
		AccessibilityAXValueSourceTypeImplicit,
		AccessibilityAXValueSourceTypeStyle,
		AccessibilityAXValueSourceTypeContents,
		AccessibilityAXValueSourceTypePlaceholder,
		AccessibilityAXValueSourceTypeRelatedElement,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t AccessibilityAXValueSourceType) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *AccessibilityAXValueSourceType) UnmarshalText(data []byte) error {
	*t = AccessibilityAXValueSourceType(data)
	return nil
}

// String returns the string representation.
func (t AccessibilityAXValueSourceType) String() string {
	return string(t)
}

// AccessibilityAXValueNativeSourceType Enum of possible native property sources (as a subtype of a particular AXValueSourceType).
type AccessibilityAXValueNativeSourceType string

const (
	AccessibilityAXValueNativeSourceTypeDescription    AccessibilityAXValueNativeSourceType = "description"
	AccessibilityAXValueNativeSourceTypeFigcaption     AccessibilityAXValueNativeSourceType = "figcaption"
	AccessibilityAXValueNativeSourceTypeLabel          AccessibilityAXValueNativeSourceType = "label"
	AccessibilityAXValueNativeSourceTypeLabelfor       AccessibilityAXValueNativeSourceType = "labelfor"
	AccessibilityAXValueNativeSourceTypeLabelwrapped   AccessibilityAXValueNativeSourceType = "labelwrapped"
	AccessibilityAXValueNativeSourceTypeLegend         AccessibilityAXValueNativeSourceType = "legend"
	AccessibilityAXValueNativeSourceTypeRubyannotation AccessibilityAXValueNativeSourceType = "rubyannotation"
	AccessibilityAXValueNativeSourceTypeTablecaption   AccessibilityAXValueNativeSourceType = "tablecaption"
	AccessibilityAXValueNativeSourceTypeTitle          AccessibilityAXValueNativeSourceType = "title"
	AccessibilityAXValueNativeSourceTypeOther          AccessibilityAXValueNativeSourceType = "other"
)

// IsValid reports whether the value is a known enum value.
func (t AccessibilityAXValueNativeSourceType) IsValid() bool {
	switch t {
	case AccessibilityAXValueNativeSourceTypeDescription:
		return true
	case AccessibilityAXValueNativeSourceTypeFigcaption:
		return true
	case AccessibilityAXValueNativeSourceTypeLabel:
		return true
	case AccessibilityAXValueNativeSourceTypeLabelfor:
		return true
	case AccessibilityAXValueNativeSourceTypeLabelwrapped:
		return true
	case AccessibilityAXValueNativeSourceTypeLegend:
		return true
	case AccessibilityAXValueNativeSourceTypeRubyannotation:
		return true
	case AccessibilityAXValueNativeSourceTypeTablecaption:
		return true
	case AccessibilityAXValueNativeSourceTypeTitle:
		return true
	case AccessibilityAXValueNativeSourceTypeOther:
		return true
	}
	return false
}

// Values returns all known values of AccessibilityAXValueNativeSourceType.
func (t AccessibilityAXValueNativeSourceType) Values() []AccessibilityAXValueNativeSourceType {
	return []AccessibilityAXValueNativeSourceType{
		AccessibilityAXValueNativeSourceTypeDescription,
		AccessibilityAXValueNativeSourceTypeFigcaption,
		AccessibilityAXValueNativeSourceTypeLabel,
		AccessibilityAXValueNativeSourceTypeLabelfor,
		AccessibilityAXValueNativeSourceTypeLabelwrapped,
		AccessibilityAXValueNativeSourceTypeLegend,
		AccessibilityAXValueNativeSourceTypeRubyannotation,
		AccessibilityAXValueNativeSourceTypeTablecaption,
		AccessibilityAXValueNativeSourceTypeTitle,
		AccessibilityAXValueNativeSourceTypeOther,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t AccessibilityAXValueNativeSourceType) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *AccessibilityAXValueNativeSourceType) UnmarshalText(data []byte) error {
	*t = AccessibilityAXValueNativeSourceType(data)
	return nil
}

// String returns the string representation.
func (t AccessibilityAXValueNativeSourceType) String() string {
	return string(t)
}

// AccessibilityAXValueSource A single source for a computed AX property.
type AccessibilityAXValueSource struct {
	// Type What type of source this is.
	Type AccessibilityAXValueSourceType `json:"type"`
	// Value The value of this property source.
	Value AccessibilityAXValue `json:"value,omitempty"`
	// Attribute The name of the relevant attribute, if any.
	Attribute string `json:"attribute,omitempty"`
	// AttributeValue The value of the relevant attribute, if any.
	AttributeValue AccessibilityAXValue `json:"attributeValue,omitempty"`
	// Superseded Whether this source is superseded by a higher priority source.
	Superseded bool `json:"superseded,omitempty"`
	// NativeSource The native markup source for this value, e.g. a `<label>` element.
	NativeSource AccessibilityAXValueNativeSourceType `json:"nativeSource,omitempty"`
	// NativeSourceValue The value, such as a node or node list, of the native source.
	NativeSourceValue AccessibilityAXValue `json:"nativeSourceValue,omitempty"`
	// Invalid Whether the value for this property is invalid.
	Invalid bool `json:"invalid,omitempty"`
	// InvalidReason Reason for the value being invalid, if it is.
	InvalidReason string `json:"invalidReason,omitempty"`
}

type AccessibilityAXRelatedNode struct {
	// BackendDOMNodeID The BackendNodeId of the related DOM node.
	BackendDOMNodeID BackendNodeID `json:"backendDOMNodeId"`
	// Idref The IDRef value provided, if any.
	Idref string `json:"idref,omitempty"`
	// Text The text alternative of this node in the current context.
	Text string `json:"text,omitempty"`
}

type AccessibilityAXProperty struct {
	// Name The name of this property.
	Name AccessibilityAXPropertyName `json:"name"`
	// Value The value of this property.
	Value AccessibilityAXValue `json:"value"`
}

// AccessibilityAXValue A single computed AX property.
type AccessibilityAXValue struct {
	// Type The type of this value.
	Type AccessibilityAXValueType `json:"type"`
	// Value The computed value of this property.
	Value json.RawMessage `json:"value,omitempty"`
	// RelatedNodes One or more related nodes, if applicable.
	RelatedNodes []AccessibilityAXRelatedNode `json:"relatedNodes,omitempty"`
	// Sources The sources which contributed to the computation of this property.
	Sources []AccessibilityAXValueSource `json:"sources,omitempty"`
}

// AccessibilityAXPropertyName Values of AXProperty name:
// - from 'busy' to 'roledescription': states which apply to every AX node
// - from 'live' to 'root': attributes which apply to nodes in live regions
// - from 'autocomplete' to 'valuetext': attributes which apply to widgets
// - from 'checked' to 'selected': states which apply to widgets
// - from 'activedescendant' to 'owns': relationships between elements other than parent/child/sibling
// - from 'activeFullscreenElement' to 'uninteresting': reasons why this noode is hidden
type AccessibilityAXPropertyName string

const (
	AccessibilityAXPropertyNameActions                    AccessibilityAXPropertyName = "actions"
	AccessibilityAXPropertyNameBusy                       AccessibilityAXPropertyName = "busy"
	AccessibilityAXPropertyNameDisabled                   AccessibilityAXPropertyName = "disabled"
	AccessibilityAXPropertyNameEditable                   AccessibilityAXPropertyName = "editable"
	AccessibilityAXPropertyNameFocusable                  AccessibilityAXPropertyName = "focusable"
	AccessibilityAXPropertyNameFocused                    AccessibilityAXPropertyName = "focused"
	AccessibilityAXPropertyNameHidden                     AccessibilityAXPropertyName = "hidden"
	AccessibilityAXPropertyNameHiddenRoot                 AccessibilityAXPropertyName = "hiddenRoot"
	AccessibilityAXPropertyNameInvalid                    AccessibilityAXPropertyName = "invalid"
	AccessibilityAXPropertyNameKeyshortcuts               AccessibilityAXPropertyName = "keyshortcuts"
	AccessibilityAXPropertyNameSettable                   AccessibilityAXPropertyName = "settable"
	AccessibilityAXPropertyNameRoledescription            AccessibilityAXPropertyName = "roledescription"
	AccessibilityAXPropertyNameLive                       AccessibilityAXPropertyName = "live"
	AccessibilityAXPropertyNameAtomic                     AccessibilityAXPropertyName = "atomic"
	AccessibilityAXPropertyNameRelevant                   AccessibilityAXPropertyName = "relevant"
	AccessibilityAXPropertyNameRoot                       AccessibilityAXPropertyName = "root"
	AccessibilityAXPropertyNameAutocomplete               AccessibilityAXPropertyName = "autocomplete"
	AccessibilityAXPropertyNameHasPopup                   AccessibilityAXPropertyName = "hasPopup"
	AccessibilityAXPropertyNameLevel                      AccessibilityAXPropertyName = "level"
	AccessibilityAXPropertyNameMultiselectable            AccessibilityAXPropertyName = "multiselectable"
	AccessibilityAXPropertyNameOrientation                AccessibilityAXPropertyName = "orientation"
	AccessibilityAXPropertyNameMultiline                  AccessibilityAXPropertyName = "multiline"
	AccessibilityAXPropertyNameReadonly                   AccessibilityAXPropertyName = "readonly"
	AccessibilityAXPropertyNameRequired                   AccessibilityAXPropertyName = "required"
	AccessibilityAXPropertyNameValuemin                   AccessibilityAXPropertyName = "valuemin"
	AccessibilityAXPropertyNameValuemax                   AccessibilityAXPropertyName = "valuemax"
	AccessibilityAXPropertyNameValuetext                  AccessibilityAXPropertyName = "valuetext"
	AccessibilityAXPropertyNameChecked                    AccessibilityAXPropertyName = "checked"
	AccessibilityAXPropertyNameExpanded                   AccessibilityAXPropertyName = "expanded"
	AccessibilityAXPropertyNameModal                      AccessibilityAXPropertyName = "modal"
	AccessibilityAXPropertyNamePressed                    AccessibilityAXPropertyName = "pressed"
	AccessibilityAXPropertyNameSelected                   AccessibilityAXPropertyName = "selected"
	AccessibilityAXPropertyNameActivedescendant           AccessibilityAXPropertyName = "activedescendant"
	AccessibilityAXPropertyNameControls                   AccessibilityAXPropertyName = "controls"
	AccessibilityAXPropertyNameDescribedby                AccessibilityAXPropertyName = "describedby"
	AccessibilityAXPropertyNameDetails                    AccessibilityAXPropertyName = "details"
	AccessibilityAXPropertyNameErrormessage               AccessibilityAXPropertyName = "errormessage"
	AccessibilityAXPropertyNameFlowto                     AccessibilityAXPropertyName = "flowto"
	AccessibilityAXPropertyNameLabelledby                 AccessibilityAXPropertyName = "labelledby"
	AccessibilityAXPropertyNameOwns                       AccessibilityAXPropertyName = "owns"
	AccessibilityAXPropertyNameURL                        AccessibilityAXPropertyName = "url"
	AccessibilityAXPropertyNameActiveFullscreenElement    AccessibilityAXPropertyName = "activeFullscreenElement"
	AccessibilityAXPropertyNameActiveModalDialog          AccessibilityAXPropertyName = "activeModalDialog"
	AccessibilityAXPropertyNameActiveAriaModalDialog      AccessibilityAXPropertyName = "activeAriaModalDialog"
	AccessibilityAXPropertyNameAriaHiddenElement          AccessibilityAXPropertyName = "ariaHiddenElement"
	AccessibilityAXPropertyNameAriaHiddenSubtree          AccessibilityAXPropertyName = "ariaHiddenSubtree"
	AccessibilityAXPropertyNameEmptyAlt                   AccessibilityAXPropertyName = "emptyAlt"
	AccessibilityAXPropertyNameEmptyText                  AccessibilityAXPropertyName = "emptyText"
	AccessibilityAXPropertyNameInertElement               AccessibilityAXPropertyName = "inertElement"
	AccessibilityAXPropertyNameInertSubtree               AccessibilityAXPropertyName = "inertSubtree"
	AccessibilityAXPropertyNameLabelContainer             AccessibilityAXPropertyName = "labelContainer"
	AccessibilityAXPropertyNameLabelFor                   AccessibilityAXPropertyName = "labelFor"
	AccessibilityAXPropertyNameNotRendered                AccessibilityAXPropertyName = "notRendered"
	AccessibilityAXPropertyNameNotVisible                 AccessibilityAXPropertyName = "notVisible"
	AccessibilityAXPropertyNamePresentationalRole         AccessibilityAXPropertyName = "presentationalRole"
	AccessibilityAXPropertyNameProbablyPresentational     AccessibilityAXPropertyName = "probablyPresentational"
	AccessibilityAXPropertyNameInactiveCarouselTabContent AccessibilityAXPropertyName = "inactiveCarouselTabContent"
	AccessibilityAXPropertyNameUninteresting              AccessibilityAXPropertyName = "uninteresting"
)

// IsValid reports whether the value is a known enum value.
func (t AccessibilityAXPropertyName) IsValid() bool {
	switch t {
	case AccessibilityAXPropertyNameActions:
		return true
	case AccessibilityAXPropertyNameBusy:
		return true
	case AccessibilityAXPropertyNameDisabled:
		return true
	case AccessibilityAXPropertyNameEditable:
		return true
	case AccessibilityAXPropertyNameFocusable:
		return true
	case AccessibilityAXPropertyNameFocused:
		return true
	case AccessibilityAXPropertyNameHidden:
		return true
	case AccessibilityAXPropertyNameHiddenRoot:
		return true
	case AccessibilityAXPropertyNameInvalid:
		return true
	case AccessibilityAXPropertyNameKeyshortcuts:
		return true
	case AccessibilityAXPropertyNameSettable:
		return true
	case AccessibilityAXPropertyNameRoledescription:
		return true
	case AccessibilityAXPropertyNameLive:
		return true
	case AccessibilityAXPropertyNameAtomic:
		return true
	case AccessibilityAXPropertyNameRelevant:
		return true
	case AccessibilityAXPropertyNameRoot:
		return true
	case AccessibilityAXPropertyNameAutocomplete:
		return true
	case AccessibilityAXPropertyNameHasPopup:
		return true
	case AccessibilityAXPropertyNameLevel:
		return true
	case AccessibilityAXPropertyNameMultiselectable:
		return true
	case AccessibilityAXPropertyNameOrientation:
		return true
	case AccessibilityAXPropertyNameMultiline:
		return true
	case AccessibilityAXPropertyNameReadonly:
		return true
	case AccessibilityAXPropertyNameRequired:
		return true
	case AccessibilityAXPropertyNameValuemin:
		return true
	case AccessibilityAXPropertyNameValuemax:
		return true
	case AccessibilityAXPropertyNameValuetext:
		return true
	case AccessibilityAXPropertyNameChecked:
		return true
	case AccessibilityAXPropertyNameExpanded:
		return true
	case AccessibilityAXPropertyNameModal:
		return true
	case AccessibilityAXPropertyNamePressed:
		return true
	case AccessibilityAXPropertyNameSelected:
		return true
	case AccessibilityAXPropertyNameActivedescendant:
		return true
	case AccessibilityAXPropertyNameControls:
		return true
	case AccessibilityAXPropertyNameDescribedby:
		return true
	case AccessibilityAXPropertyNameDetails:
		return true
	case AccessibilityAXPropertyNameErrormessage:
		return true
	case AccessibilityAXPropertyNameFlowto:
		return true
	case AccessibilityAXPropertyNameLabelledby:
		return true
	case AccessibilityAXPropertyNameOwns:
		return true
	case AccessibilityAXPropertyNameURL:
		return true
	case AccessibilityAXPropertyNameActiveFullscreenElement:
		return true
	case AccessibilityAXPropertyNameActiveModalDialog:
		return true
	case AccessibilityAXPropertyNameActiveAriaModalDialog:
		return true
	case AccessibilityAXPropertyNameAriaHiddenElement:
		return true
	case AccessibilityAXPropertyNameAriaHiddenSubtree:
		return true
	case AccessibilityAXPropertyNameEmptyAlt:
		return true
	case AccessibilityAXPropertyNameEmptyText:
		return true
	case AccessibilityAXPropertyNameInertElement:
		return true
	case AccessibilityAXPropertyNameInertSubtree:
		return true
	case AccessibilityAXPropertyNameLabelContainer:
		return true
	case AccessibilityAXPropertyNameLabelFor:
		return true
	case AccessibilityAXPropertyNameNotRendered:
		return true
	case AccessibilityAXPropertyNameNotVisible:
		return true
	case AccessibilityAXPropertyNamePresentationalRole:
		return true
	case AccessibilityAXPropertyNameProbablyPresentational:
		return true
	case AccessibilityAXPropertyNameInactiveCarouselTabContent:
		return true
	case AccessibilityAXPropertyNameUninteresting:
		return true
	}
	return false
}

// Values returns all known values of AccessibilityAXPropertyName.
func (t AccessibilityAXPropertyName) Values() []AccessibilityAXPropertyName {
	return []AccessibilityAXPropertyName{
		AccessibilityAXPropertyNameActions,
		AccessibilityAXPropertyNameBusy,
		AccessibilityAXPropertyNameDisabled,
		AccessibilityAXPropertyNameEditable,
		AccessibilityAXPropertyNameFocusable,
		AccessibilityAXPropertyNameFocused,
		AccessibilityAXPropertyNameHidden,
		AccessibilityAXPropertyNameHiddenRoot,
		AccessibilityAXPropertyNameInvalid,
		AccessibilityAXPropertyNameKeyshortcuts,
		AccessibilityAXPropertyNameSettable,
		AccessibilityAXPropertyNameRoledescription,
		AccessibilityAXPropertyNameLive,
		AccessibilityAXPropertyNameAtomic,
		AccessibilityAXPropertyNameRelevant,
		AccessibilityAXPropertyNameRoot,
		AccessibilityAXPropertyNameAutocomplete,
		AccessibilityAXPropertyNameHasPopup,
		AccessibilityAXPropertyNameLevel,
		AccessibilityAXPropertyNameMultiselectable,
		AccessibilityAXPropertyNameOrientation,
		AccessibilityAXPropertyNameMultiline,
		AccessibilityAXPropertyNameReadonly,
		AccessibilityAXPropertyNameRequired,
		AccessibilityAXPropertyNameValuemin,
		AccessibilityAXPropertyNameValuemax,
		AccessibilityAXPropertyNameValuetext,
		AccessibilityAXPropertyNameChecked,
		AccessibilityAXPropertyNameExpanded,
		AccessibilityAXPropertyNameModal,
		AccessibilityAXPropertyNamePressed,
		AccessibilityAXPropertyNameSelected,
		AccessibilityAXPropertyNameActivedescendant,
		AccessibilityAXPropertyNameControls,
		AccessibilityAXPropertyNameDescribedby,
		AccessibilityAXPropertyNameDetails,
		AccessibilityAXPropertyNameErrormessage,
		AccessibilityAXPropertyNameFlowto,
		AccessibilityAXPropertyNameLabelledby,
		AccessibilityAXPropertyNameOwns,
		AccessibilityAXPropertyNameURL,
		AccessibilityAXPropertyNameActiveFullscreenElement,
		AccessibilityAXPropertyNameActiveModalDialog,
		AccessibilityAXPropertyNameActiveAriaModalDialog,
		AccessibilityAXPropertyNameAriaHiddenElement,
		AccessibilityAXPropertyNameAriaHiddenSubtree,
		AccessibilityAXPropertyNameEmptyAlt,
		AccessibilityAXPropertyNameEmptyText,
		AccessibilityAXPropertyNameInertElement,
		AccessibilityAXPropertyNameInertSubtree,
		AccessibilityAXPropertyNameLabelContainer,
		AccessibilityAXPropertyNameLabelFor,
		AccessibilityAXPropertyNameNotRendered,
		AccessibilityAXPropertyNameNotVisible,
		AccessibilityAXPropertyNamePresentationalRole,
		AccessibilityAXPropertyNameProbablyPresentational,
		AccessibilityAXPropertyNameInactiveCarouselTabContent,
		AccessibilityAXPropertyNameUninteresting,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t AccessibilityAXPropertyName) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *AccessibilityAXPropertyName) UnmarshalText(data []byte) error {
	*t = AccessibilityAXPropertyName(data)
	return nil
}

// String returns the string representation.
func (t AccessibilityAXPropertyName) String() string {
	return string(t)
}

// AccessibilityAXNode A node in the accessibility tree.
type AccessibilityAXNode struct {
	// NodeID Unique identifier for this node.
	NodeID AccessibilityAXNodeID `json:"nodeId"`
	// Ignored Whether this node is ignored for accessibility
	Ignored bool `json:"ignored"`
	// IgnoredReasons Collection of reasons why this node is hidden.
	IgnoredReasons []AccessibilityAXProperty `json:"ignoredReasons,omitempty"`
	// Role This `Node`'s role, whether explicit or implicit.
	Role AccessibilityAXValue `json:"role,omitempty"`
	// ChromeRole This `Node`'s Chrome raw role.
	ChromeRole AccessibilityAXValue `json:"chromeRole,omitempty"`
	// Name The accessible name for this `Node`.
	Name AccessibilityAXValue `json:"name,omitempty"`
	// Description The accessible description for this `Node`.
	Description AccessibilityAXValue `json:"description,omitempty"`
	// Value The value for this `Node`.
	Value AccessibilityAXValue `json:"value,omitempty"`
	// Properties All other properties
	Properties []AccessibilityAXProperty `json:"properties,omitempty"`
	// ParentID ID for this node's parent.
	ParentID AccessibilityAXNodeID `json:"parentId,omitempty"`
	// ChildIds IDs for each of this node's child nodes.
	ChildIds []AccessibilityAXNodeID `json:"childIds,omitempty"`
	// BackendDOMNodeID The backend ID for the associated DOM node, if any.
	BackendDOMNodeID BackendNodeID `json:"backendDOMNodeId,omitempty"`
	// FrameID The frame ID for the frame associated with this nodes document.
	FrameID FrameID `json:"frameId,omitempty"`
}
