// Code generated by bonkgen. DO NOT EDIT.

package proto

import "context"

// AutofillTriggerParams Trigger autofill on a form identified by the fieldId.
// If the field and related form cannot be autofilled, returns an error.
type AutofillTriggerParams struct {
	// FieldID Identifies a field that serves as an anchor for autofill.
	FieldID BackendNodeID `json:"fieldId"`
	// FrameID Identifies the frame that field belongs to.
	FrameID FrameID `json:"frameId,omitempty,omitzero"`
	// Card Credit card information to fill out the form. Credit card data is not saved.  Mutually exclusive with `address`.
	Card AutofillCreditCard `json:"card,omitempty,omitzero"`
	// Address Address to fill out the form. Address data is not saved. Mutually exclusive with `card`.
	Address AutofillAddress `json:"address,omitempty,omitzero"`
}

// AutofillTrigger creates a new AutofillTriggerParams.
func AutofillTrigger(fieldID BackendNodeID) *AutofillTriggerParams {
	return &AutofillTriggerParams{
		FieldID: fieldID,
	}
}

// WithFrameID sets the frameId parameter.
func (p *AutofillTriggerParams) WithFrameID(frameID FrameID) *AutofillTriggerParams {
	p.FrameID = frameID
	return p
}

// WithCard sets the card parameter.
func (p *AutofillTriggerParams) WithCard(card AutofillCreditCard) *AutofillTriggerParams {
	p.Card = card
	return p
}

// WithAddress sets the address parameter.
func (p *AutofillTriggerParams) WithAddress(address AutofillAddress) *AutofillTriggerParams {
	p.Address = address
	return p
}

// Do executes Autofill.trigger.
func (p *AutofillTriggerParams) Do(ctx context.Context) error {
	return Execute(ctx, AutofillCommandTrigger, p, nil)
}

// AutofillSetAddressesParams Set addresses so that developers can verify their forms implementation.
type AutofillSetAddressesParams struct {
	Addresses []AutofillAddress `json:"addresses"`
}

// AutofillSetAddresses creates a new AutofillSetAddressesParams.
func AutofillSetAddresses(addresses []AutofillAddress) *AutofillSetAddressesParams {
	return &AutofillSetAddressesParams{
		Addresses: addresses,
	}
}

// Do executes Autofill.setAddresses.
func (p *AutofillSetAddressesParams) Do(ctx context.Context) error {
	return Execute(ctx, AutofillCommandSetAddresses, p, nil)
}

// AutofillDisableParams Disables autofill domain notifications.
type AutofillDisableParams struct{}

// AutofillDisable creates a new AutofillDisableParams.
func AutofillDisable() *AutofillDisableParams {
	return &AutofillDisableParams{}
}

// Do executes Autofill.disable.
func (p *AutofillDisableParams) Do(ctx context.Context) error {
	return Execute(ctx, AutofillCommandDisable, p, nil)
}

// AutofillEnableParams Enables autofill domain notifications.
type AutofillEnableParams struct{}

// AutofillEnable creates a new AutofillEnableParams.
func AutofillEnable() *AutofillEnableParams {
	return &AutofillEnableParams{}
}

// Do executes Autofill.enable.
func (p *AutofillEnableParams) Do(ctx context.Context) error {
	return Execute(ctx, AutofillCommandEnable, p, nil)
}

// Autofill command names.
const (
	AutofillCommandTrigger      Method = "Autofill.trigger"
	AutofillCommandSetAddresses Method = "Autofill.setAddresses"
	AutofillCommandDisable      Method = "Autofill.disable"
	AutofillCommandEnable       Method = "Autofill.enable"
)
