// Code generated by bonkgen. DO NOT EDIT.

package proto

// BackgroundServiceEventRecordingStateChanged Called when the recording state for the service has been updated.
type BackgroundServiceEventRecordingStateChanged struct {
	IsRecording bool                         `json:"isRecording"`
	Service     BackgroundServiceServiceName `json:"service"`
}

// BackgroundServiceEventBackgroundServiceEventReceived Called with all existing backgroundServiceEvents when enabled, and all new
// events afterwards if enabled and recording.
type BackgroundServiceEventBackgroundServiceEventReceived struct {
	BackgroundServiceEvent BackgroundServiceBackgroundServiceEvent `json:"backgroundServiceEvent"`
}

// BackgroundService event names.
const (
	BackgroundServiceEventRecordingStateChangedMethod          Method = "BackgroundService.recordingStateChanged"
	BackgroundServiceEventBackgroundServiceEventReceivedMethod Method = "BackgroundService.backgroundServiceEventReceived"
)
