// Code generated by bonkgen. DO NOT EDIT.

package proto

import "context"

// BluetoothEmulationEnableParams Enable the BluetoothEmulation domain.
type BluetoothEmulationEnableParams struct {
	// State State of the simulated central.
	State BluetoothEmulationCentralState `json:"state"`
	// LeSupported If the simulated central supports low-energy.
	LeSupported bool `json:"leSupported"`
}

// BluetoothEmulationEnable creates a new BluetoothEmulationEnableParams.
func BluetoothEmulationEnable(state BluetoothEmulationCentralState, leSupported bool) *BluetoothEmulationEnableParams {
	return &BluetoothEmulationEnableParams{
		State:       state,
		LeSupported: leSupported,
	}
}

// Do executes BluetoothEmulation.enable.
func (p *BluetoothEmulationEnableParams) Do(ctx context.Context) error {
	return Execute(ctx, BluetoothEmulationCommandEnable, p, nil)
}

// BluetoothEmulationSetSimulatedCentralStateParams Set the state of the simulated central.
type BluetoothEmulationSetSimulatedCentralStateParams struct {
	// State State of the simulated central.
	State BluetoothEmulationCentralState `json:"state"`
}

// BluetoothEmulationSetSimulatedCentralState creates a new BluetoothEmulationSetSimulatedCentralStateParams.
func BluetoothEmulationSetSimulatedCentralState(state BluetoothEmulationCentralState) *BluetoothEmulationSetSimulatedCentralStateParams {
	return &BluetoothEmulationSetSimulatedCentralStateParams{
		State: state,
	}
}

// Do executes BluetoothEmulation.setSimulatedCentralState.
func (p *BluetoothEmulationSetSimulatedCentralStateParams) Do(ctx context.Context) error {
	return Execute(ctx, BluetoothEmulationCommandSetSimulatedCentralState, p, nil)
}

// BluetoothEmulationDisableParams Disable the BluetoothEmulation domain.
type BluetoothEmulationDisableParams struct{}

// BluetoothEmulationDisable creates a new BluetoothEmulationDisableParams.
func BluetoothEmulationDisable() *BluetoothEmulationDisableParams {
	return &BluetoothEmulationDisableParams{}
}

// Do executes BluetoothEmulation.disable.
func (p *BluetoothEmulationDisableParams) Do(ctx context.Context) error {
	return Execute(ctx, BluetoothEmulationCommandDisable, p, nil)
}

// BluetoothEmulationSimulatePreconnectedPeripheralParams Simulates a peripheral with |address|, |name| and |knownServiceUuids|
// that has already been connected to the system.
type BluetoothEmulationSimulatePreconnectedPeripheralParams struct {
	Address           string                               `json:"address"`
	Name              string                               `json:"name"`
	ManufacturerData  []BluetoothEmulationManufacturerData `json:"manufacturerData"`
	KnownServiceUuids []string                             `json:"knownServiceUuids"`
}

// BluetoothEmulationSimulatePreconnectedPeripheral creates a new BluetoothEmulationSimulatePreconnectedPeripheralParams.
func BluetoothEmulationSimulatePreconnectedPeripheral(address string, name string, manufacturerData []BluetoothEmulationManufacturerData, knownServiceUuids []string) *BluetoothEmulationSimulatePreconnectedPeripheralParams {
	return &BluetoothEmulationSimulatePreconnectedPeripheralParams{
		Address:           address,
		Name:              name,
		ManufacturerData:  manufacturerData,
		KnownServiceUuids: knownServiceUuids,
	}
}

// Do executes BluetoothEmulation.simulatePreconnectedPeripheral.
func (p *BluetoothEmulationSimulatePreconnectedPeripheralParams) Do(ctx context.Context) error {
	return Execute(ctx, BluetoothEmulationCommandSimulatePreconnectedPeripheral, p, nil)
}

// BluetoothEmulationSimulateAdvertisementParams Simulates an advertisement packet described in |entry| being received by
// the central.
type BluetoothEmulationSimulateAdvertisementParams struct {
	Entry BluetoothEmulationScanEntry `json:"entry"`
}

// BluetoothEmulationSimulateAdvertisement creates a new BluetoothEmulationSimulateAdvertisementParams.
func BluetoothEmulationSimulateAdvertisement(entry BluetoothEmulationScanEntry) *BluetoothEmulationSimulateAdvertisementParams {
	return &BluetoothEmulationSimulateAdvertisementParams{
		Entry: entry,
	}
}

// Do executes BluetoothEmulation.simulateAdvertisement.
func (p *BluetoothEmulationSimulateAdvertisementParams) Do(ctx context.Context) error {
	return Execute(ctx, BluetoothEmulationCommandSimulateAdvertisement, p, nil)
}

// BluetoothEmulationSimulateGATTOperationResponseParams Simulates the response code from the peripheral with |address| for a
// GATT operation of |type|. The |code| value follows the HCI Error Codes from
// Bluetooth Core Specification Vol 2 Part D 1.3 List Of Error Codes.
type BluetoothEmulationSimulateGATTOperationResponseParams struct {
	Address string                              `json:"address"`
	Type    BluetoothEmulationGATTOperationType `json:"type"`
	Code    int64                               `json:"code"`
}

// BluetoothEmulationSimulateGATTOperationResponse creates a new BluetoothEmulationSimulateGATTOperationResponseParams.
func BluetoothEmulationSimulateGATTOperationResponse(address string, typ BluetoothEmulationGATTOperationType, code int64) *BluetoothEmulationSimulateGATTOperationResponseParams {
	return &BluetoothEmulationSimulateGATTOperationResponseParams{
		Address: address,
		Type:    typ,
		Code:    code,
	}
}

// Do executes BluetoothEmulation.simulateGATTOperationResponse.
func (p *BluetoothEmulationSimulateGATTOperationResponseParams) Do(ctx context.Context) error {
	return Execute(ctx, BluetoothEmulationCommandSimulateGATTOperationResponse, p, nil)
}

// BluetoothEmulationSimulateCharacteristicOperationResponseParams Simulates the response from the characteristic with |characteristicId| for a
// characteristic operation of |type|. The |code| value follows the Error
// Codes from Bluetooth Core Specification Vol 3 Part F 3.4.1.1 Error Response.
// The |data| is expected to exist when simulating a successful read operation
// response.
type BluetoothEmulationSimulateCharacteristicOperationResponseParams struct {
	CharacteristicID string                                        `json:"characteristicId"`
	Type             BluetoothEmulationCharacteristicOperationType `json:"type"`
	Code             int64                                         `json:"code"`
	Data             []byte                                        `json:"data,omitempty,omitzero"`
}

// BluetoothEmulationSimulateCharacteristicOperationResponse creates a new BluetoothEmulationSimulateCharacteristicOperationResponseParams.
func BluetoothEmulationSimulateCharacteristicOperationResponse(characteristicID string, typ BluetoothEmulationCharacteristicOperationType, code int64) *BluetoothEmulationSimulateCharacteristicOperationResponseParams {
	return &BluetoothEmulationSimulateCharacteristicOperationResponseParams{
		CharacteristicID: characteristicID,
		Type:             typ,
		Code:             code,
	}
}

// WithData sets the data parameter.
func (p *BluetoothEmulationSimulateCharacteristicOperationResponseParams) WithData(data []byte) *BluetoothEmulationSimulateCharacteristicOperationResponseParams {
	p.Data = data
	return p
}

// Do executes BluetoothEmulation.simulateCharacteristicOperationResponse.
func (p *BluetoothEmulationSimulateCharacteristicOperationResponseParams) Do(ctx context.Context) error {
	return Execute(ctx, BluetoothEmulationCommandSimulateCharacteristicOperationResponse, p, nil)
}

// BluetoothEmulationSimulateDescriptorOperationResponseParams Simulates the response from the descriptor with |descriptorId| for a
// descriptor operation of |type|. The |code| value follows the Error
// Codes from Bluetooth Core Specification Vol 3 Part F 3.4.1.1 Error Response.
// The |data| is expected to exist when simulating a successful read operation
// response.
type BluetoothEmulationSimulateDescriptorOperationResponseParams struct {
	DescriptorID string                                    `json:"descriptorId"`
	Type         BluetoothEmulationDescriptorOperationType `json:"type"`
	Code         int64                                     `json:"code"`
	Data         []byte                                    `json:"data,omitempty,omitzero"`
}

// BluetoothEmulationSimulateDescriptorOperationResponse creates a new BluetoothEmulationSimulateDescriptorOperationResponseParams.
func BluetoothEmulationSimulateDescriptorOperationResponse(descriptorID string, typ BluetoothEmulationDescriptorOperationType, code int64) *BluetoothEmulationSimulateDescriptorOperationResponseParams {
	return &BluetoothEmulationSimulateDescriptorOperationResponseParams{
		DescriptorID: descriptorID,
		Type:         typ,
		Code:         code,
	}
}

// WithData sets the data parameter.
func (p *BluetoothEmulationSimulateDescriptorOperationResponseParams) WithData(data []byte) *BluetoothEmulationSimulateDescriptorOperationResponseParams {
	p.Data = data
	return p
}

// Do executes BluetoothEmulation.simulateDescriptorOperationResponse.
func (p *BluetoothEmulationSimulateDescriptorOperationResponseParams) Do(ctx context.Context) error {
	return Execute(ctx, BluetoothEmulationCommandSimulateDescriptorOperationResponse, p, nil)
}

// BluetoothEmulationAddServiceParams Adds a service with |serviceUuid| to the peripheral with |address|.
type BluetoothEmulationAddServiceParams struct {
	Address     string `json:"address"`
	ServiceUUID string `json:"serviceUuid"`
}

// BluetoothEmulationAddServiceReturns holds the return values for addService.
type BluetoothEmulationAddServiceReturns struct {
	// ServiceID An identifier that uniquely represents this service.
	ServiceID string `json:"serviceId"`
}

// BluetoothEmulationAddService creates a new BluetoothEmulationAddServiceParams.
func BluetoothEmulationAddService(address string, serviceUUID string) *BluetoothEmulationAddServiceParams {
	return &BluetoothEmulationAddServiceParams{
		Address:     address,
		ServiceUUID: serviceUUID,
	}
}

// Do executes BluetoothEmulation.addService.
func (p *BluetoothEmulationAddServiceParams) Do(ctx context.Context) (*BluetoothEmulationAddServiceReturns, error) {
	var res BluetoothEmulationAddServiceReturns
	if err := Execute(ctx, BluetoothEmulationCommandAddService, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// BluetoothEmulationRemoveServiceParams Removes the service respresented by |serviceId| from the simulated central.
type BluetoothEmulationRemoveServiceParams struct {
	ServiceID string `json:"serviceId"`
}

// BluetoothEmulationRemoveService creates a new BluetoothEmulationRemoveServiceParams.
func BluetoothEmulationRemoveService(serviceID string) *BluetoothEmulationRemoveServiceParams {
	return &BluetoothEmulationRemoveServiceParams{
		ServiceID: serviceID,
	}
}

// Do executes BluetoothEmulation.removeService.
func (p *BluetoothEmulationRemoveServiceParams) Do(ctx context.Context) error {
	return Execute(ctx, BluetoothEmulationCommandRemoveService, p, nil)
}

// BluetoothEmulationAddCharacteristicParams Adds a characteristic with |characteristicUuid| and |properties| to the
// service represented by |serviceId|.
type BluetoothEmulationAddCharacteristicParams struct {
	ServiceID          string                                     `json:"serviceId"`
	CharacteristicUUID string                                     `json:"characteristicUuid"`
	Properties         BluetoothEmulationCharacteristicProperties `json:"properties"`
}

// BluetoothEmulationAddCharacteristicReturns holds the return values for addCharacteristic.
type BluetoothEmulationAddCharacteristicReturns struct {
	// CharacteristicID An identifier that uniquely represents this characteristic.
	CharacteristicID string `json:"characteristicId"`
}

// BluetoothEmulationAddCharacteristic creates a new BluetoothEmulationAddCharacteristicParams.
func BluetoothEmulationAddCharacteristic(serviceID string, characteristicUUID string, properties BluetoothEmulationCharacteristicProperties) *BluetoothEmulationAddCharacteristicParams {
	return &BluetoothEmulationAddCharacteristicParams{
		ServiceID:          serviceID,
		CharacteristicUUID: characteristicUUID,
		Properties:         properties,
	}
}

// Do executes BluetoothEmulation.addCharacteristic.
func (p *BluetoothEmulationAddCharacteristicParams) Do(ctx context.Context) (*BluetoothEmulationAddCharacteristicReturns, error) {
	var res BluetoothEmulationAddCharacteristicReturns
	if err := Execute(ctx, BluetoothEmulationCommandAddCharacteristic, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// BluetoothEmulationRemoveCharacteristicParams Removes the characteristic respresented by |characteristicId| from the
// simulated central.
type BluetoothEmulationRemoveCharacteristicParams struct {
	CharacteristicID string `json:"characteristicId"`
}

// BluetoothEmulationRemoveCharacteristic creates a new BluetoothEmulationRemoveCharacteristicParams.
func BluetoothEmulationRemoveCharacteristic(characteristicID string) *BluetoothEmulationRemoveCharacteristicParams {
	return &BluetoothEmulationRemoveCharacteristicParams{
		CharacteristicID: characteristicID,
	}
}

// Do executes BluetoothEmulation.removeCharacteristic.
func (p *BluetoothEmulationRemoveCharacteristicParams) Do(ctx context.Context) error {
	return Execute(ctx, BluetoothEmulationCommandRemoveCharacteristic, p, nil)
}

// BluetoothEmulationAddDescriptorParams Adds a descriptor with |descriptorUuid| to the characteristic respresented
// by |characteristicId|.
type BluetoothEmulationAddDescriptorParams struct {
	CharacteristicID string `json:"characteristicId"`
	DescriptorUUID   string `json:"descriptorUuid"`
}

// BluetoothEmulationAddDescriptorReturns holds the return values for addDescriptor.
type BluetoothEmulationAddDescriptorReturns struct {
	// DescriptorID An identifier that uniquely represents this descriptor.
	DescriptorID string `json:"descriptorId"`
}

// BluetoothEmulationAddDescriptor creates a new BluetoothEmulationAddDescriptorParams.
func BluetoothEmulationAddDescriptor(characteristicID string, descriptorUUID string) *BluetoothEmulationAddDescriptorParams {
	return &BluetoothEmulationAddDescriptorParams{
		CharacteristicID: characteristicID,
		DescriptorUUID:   descriptorUUID,
	}
}

// Do executes BluetoothEmulation.addDescriptor.
func (p *BluetoothEmulationAddDescriptorParams) Do(ctx context.Context) (*BluetoothEmulationAddDescriptorReturns, error) {
	var res BluetoothEmulationAddDescriptorReturns
	if err := Execute(ctx, BluetoothEmulationCommandAddDescriptor, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// BluetoothEmulationRemoveDescriptorParams Removes the descriptor with |descriptorId| from the simulated central.
type BluetoothEmulationRemoveDescriptorParams struct {
	DescriptorID string `json:"descriptorId"`
}

// BluetoothEmulationRemoveDescriptor creates a new BluetoothEmulationRemoveDescriptorParams.
func BluetoothEmulationRemoveDescriptor(descriptorID string) *BluetoothEmulationRemoveDescriptorParams {
	return &BluetoothEmulationRemoveDescriptorParams{
		DescriptorID: descriptorID,
	}
}

// Do executes BluetoothEmulation.removeDescriptor.
func (p *BluetoothEmulationRemoveDescriptorParams) Do(ctx context.Context) error {
	return Execute(ctx, BluetoothEmulationCommandRemoveDescriptor, p, nil)
}

// BluetoothEmulationSimulateGATTDisconnectionParams Simulates a GATT disconnection from the peripheral with |address|.
type BluetoothEmulationSimulateGATTDisconnectionParams struct {
	Address string `json:"address"`
}

// BluetoothEmulationSimulateGATTDisconnection creates a new BluetoothEmulationSimulateGATTDisconnectionParams.
func BluetoothEmulationSimulateGATTDisconnection(address string) *BluetoothEmulationSimulateGATTDisconnectionParams {
	return &BluetoothEmulationSimulateGATTDisconnectionParams{
		Address: address,
	}
}

// Do executes BluetoothEmulation.simulateGATTDisconnection.
func (p *BluetoothEmulationSimulateGATTDisconnectionParams) Do(ctx context.Context) error {
	return Execute(ctx, BluetoothEmulationCommandSimulateGATTDisconnection, p, nil)
}

// BluetoothEmulation command names.
const (
	BluetoothEmulationCommandEnable                                  Method = "BluetoothEmulation.enable"
	BluetoothEmulationCommandSetSimulatedCentralState                Method = "BluetoothEmulation.setSimulatedCentralState"
	BluetoothEmulationCommandDisable                                 Method = "BluetoothEmulation.disable"
	BluetoothEmulationCommandSimulatePreconnectedPeripheral          Method = "BluetoothEmulation.simulatePreconnectedPeripheral"
	BluetoothEmulationCommandSimulateAdvertisement                   Method = "BluetoothEmulation.simulateAdvertisement"
	BluetoothEmulationCommandSimulateGATTOperationResponse           Method = "BluetoothEmulation.simulateGATTOperationResponse"
	BluetoothEmulationCommandSimulateCharacteristicOperationResponse Method = "BluetoothEmulation.simulateCharacteristicOperationResponse"
	BluetoothEmulationCommandSimulateDescriptorOperationResponse     Method = "BluetoothEmulation.simulateDescriptorOperationResponse"
	BluetoothEmulationCommandAddService                              Method = "BluetoothEmulation.addService"
	BluetoothEmulationCommandRemoveService                           Method = "BluetoothEmulation.removeService"
	BluetoothEmulationCommandAddCharacteristic                       Method = "BluetoothEmulation.addCharacteristic"
	BluetoothEmulationCommandRemoveCharacteristic                    Method = "BluetoothEmulation.removeCharacteristic"
	BluetoothEmulationCommandAddDescriptor                           Method = "BluetoothEmulation.addDescriptor"
	BluetoothEmulationCommandRemoveDescriptor                        Method = "BluetoothEmulation.removeDescriptor"
	BluetoothEmulationCommandSimulateGATTDisconnection               Method = "BluetoothEmulation.simulateGATTDisconnection"
)
