// Code generated by bonkgen. DO NOT EDIT.

package proto

import "context"

// BrowserSetPermissionParams Set permission settings for given embedding and embedded origins.
type BrowserSetPermissionParams struct {
	// Permission Descriptor of permission to override.
	Permission BrowserPermissionDescriptor `json:"permission"`
	// Setting Setting of the permission.
	Setting BrowserPermissionSetting `json:"setting"`
	// Origin Embedding origin the permission applies to, all origins if not specified.
	Origin string `json:"origin,omitempty"`
	// EmbeddedOrigin Embedded origin the permission applies to. It is ignored unless the embedding origin is
	// present and valid. If the embedding origin is provided but the embedded origin isn't, the
	// embedding origin is used as the embedded origin.
	EmbeddedOrigin string `json:"embeddedOrigin,omitempty"`
	// BrowserContextID Context to override. When omitted, default browser context is used.
	BrowserContextID BrowserContextID `json:"browserContextId,omitempty"`
}

// BrowserSetPermission creates a new BrowserSetPermissionParams.
func BrowserSetPermission(permission BrowserPermissionDescriptor, setting BrowserPermissionSetting) *BrowserSetPermissionParams {
	return &BrowserSetPermissionParams{
		Permission: permission,
		Setting:    setting,
	}
}

// WithOrigin sets the origin parameter.
func (p *BrowserSetPermissionParams) WithOrigin(origin string) *BrowserSetPermissionParams {
	p.Origin = origin
	return p
}

// WithEmbeddedOrigin sets the embeddedOrigin parameter.
func (p *BrowserSetPermissionParams) WithEmbeddedOrigin(embeddedOrigin string) *BrowserSetPermissionParams {
	p.EmbeddedOrigin = embeddedOrigin
	return p
}

// WithBrowserContextID sets the browserContextId parameter.
func (p *BrowserSetPermissionParams) WithBrowserContextID(browserContextID BrowserContextID) *BrowserSetPermissionParams {
	p.BrowserContextID = browserContextID
	return p
}

// Do executes Browser.setPermission.
func (p *BrowserSetPermissionParams) Do(ctx context.Context) error {
	return Execute(ctx, BrowserCommandSetPermission, p, nil)
}

// BrowserGrantPermissionsParams Grant specific permissions to the given origin and reject all others. Deprecated. Use
// setPermission instead.
type BrowserGrantPermissionsParams struct {
	Permissions []BrowserPermissionType `json:"permissions"`
	// Origin Origin the permission applies to, all origins if not specified.
	Origin string `json:"origin,omitempty"`
	// BrowserContextID BrowserContext to override permissions. When omitted, default browser context is used.
	BrowserContextID BrowserContextID `json:"browserContextId,omitempty"`
}

// BrowserGrantPermissions creates a new BrowserGrantPermissionsParams.
func BrowserGrantPermissions(permissions []BrowserPermissionType) *BrowserGrantPermissionsParams {
	return &BrowserGrantPermissionsParams{
		Permissions: permissions,
	}
}

// WithOrigin sets the origin parameter.
func (p *BrowserGrantPermissionsParams) WithOrigin(origin string) *BrowserGrantPermissionsParams {
	p.Origin = origin
	return p
}

// WithBrowserContextID sets the browserContextId parameter.
func (p *BrowserGrantPermissionsParams) WithBrowserContextID(browserContextID BrowserContextID) *BrowserGrantPermissionsParams {
	p.BrowserContextID = browserContextID
	return p
}

// Do executes Browser.grantPermissions.
func (p *BrowserGrantPermissionsParams) Do(ctx context.Context) error {
	return Execute(ctx, BrowserCommandGrantPermissions, p, nil)
}

// BrowserResetPermissionsParams Reset all permission management for all origins.
type BrowserResetPermissionsParams struct {
	// BrowserContextID BrowserContext to reset permissions. When omitted, default browser context is used.
	BrowserContextID BrowserContextID `json:"browserContextId,omitempty"`
}

// BrowserResetPermissions creates a new BrowserResetPermissionsParams.
func BrowserResetPermissions() *BrowserResetPermissionsParams {
	return &BrowserResetPermissionsParams{}
}

// WithBrowserContextID sets the browserContextId parameter.
func (p *BrowserResetPermissionsParams) WithBrowserContextID(browserContextID BrowserContextID) *BrowserResetPermissionsParams {
	p.BrowserContextID = browserContextID
	return p
}

// Do executes Browser.resetPermissions.
func (p *BrowserResetPermissionsParams) Do(ctx context.Context) error {
	return Execute(ctx, BrowserCommandResetPermissions, p, nil)
}

// BrowserSetDownloadBehaviorParams Set the behavior when downloading a file.
type BrowserSetDownloadBehaviorParams struct {
	// Behavior Whether to allow all or deny all download requests, or use default Chrome behavior if
	// available (otherwise deny). |allowAndName| allows download and names files according to
	// their download guids.
	Behavior BrowserSetDownloadBehaviorBehavior `json:"behavior"`
	// BrowserContextID BrowserContext to set download behavior. When omitted, default browser context is used.
	BrowserContextID BrowserContextID `json:"browserContextId,omitempty"`
	// DownloadPath The default path to save downloaded files to. This is required if behavior is set to 'allow'
	// or 'allowAndName'.
	DownloadPath string `json:"downloadPath,omitempty"`
	// EventsEnabled Whether to emit download events (defaults to false).
	EventsEnabled bool `json:"eventsEnabled,omitempty"`
}

// BrowserSetDownloadBehavior creates a new BrowserSetDownloadBehaviorParams.
func BrowserSetDownloadBehavior(behavior BrowserSetDownloadBehaviorBehavior) *BrowserSetDownloadBehaviorParams {
	return &BrowserSetDownloadBehaviorParams{
		Behavior: behavior,
	}
}

// WithBrowserContextID sets the browserContextId parameter.
func (p *BrowserSetDownloadBehaviorParams) WithBrowserContextID(browserContextID BrowserContextID) *BrowserSetDownloadBehaviorParams {
	p.BrowserContextID = browserContextID
	return p
}

// WithDownloadPath sets the downloadPath parameter.
func (p *BrowserSetDownloadBehaviorParams) WithDownloadPath(downloadPath string) *BrowserSetDownloadBehaviorParams {
	p.DownloadPath = downloadPath
	return p
}

// WithEventsEnabled sets the eventsEnabled parameter.
func (p *BrowserSetDownloadBehaviorParams) WithEventsEnabled(eventsEnabled bool) *BrowserSetDownloadBehaviorParams {
	p.EventsEnabled = eventsEnabled
	return p
}

// Do executes Browser.setDownloadBehavior.
func (p *BrowserSetDownloadBehaviorParams) Do(ctx context.Context) error {
	return Execute(ctx, BrowserCommandSetDownloadBehavior, p, nil)
}

// BrowserCancelDownloadParams Cancel a download if in progress
type BrowserCancelDownloadParams struct {
	// Guid Global unique identifier of the download.
	Guid string `json:"guid"`
	// BrowserContextID BrowserContext to perform the action in. When omitted, default browser context is used.
	BrowserContextID BrowserContextID `json:"browserContextId,omitempty"`
}

// BrowserCancelDownload creates a new BrowserCancelDownloadParams.
func BrowserCancelDownload(guid string) *BrowserCancelDownloadParams {
	return &BrowserCancelDownloadParams{
		Guid: guid,
	}
}

// WithBrowserContextID sets the browserContextId parameter.
func (p *BrowserCancelDownloadParams) WithBrowserContextID(browserContextID BrowserContextID) *BrowserCancelDownloadParams {
	p.BrowserContextID = browserContextID
	return p
}

// Do executes Browser.cancelDownload.
func (p *BrowserCancelDownloadParams) Do(ctx context.Context) error {
	return Execute(ctx, BrowserCommandCancelDownload, p, nil)
}

// BrowserCloseParams Close browser gracefully.
type BrowserCloseParams struct{}

// BrowserClose creates a new BrowserCloseParams.
func BrowserClose() *BrowserCloseParams {
	return &BrowserCloseParams{}
}

// Do executes Browser.close.
func (p *BrowserCloseParams) Do(ctx context.Context) error {
	return Execute(ctx, BrowserCommandClose, p, nil)
}

// BrowserCrashParams Crashes browser on the main thread.
type BrowserCrashParams struct{}

// BrowserCrash creates a new BrowserCrashParams.
func BrowserCrash() *BrowserCrashParams {
	return &BrowserCrashParams{}
}

// Do executes Browser.crash.
func (p *BrowserCrashParams) Do(ctx context.Context) error {
	return Execute(ctx, BrowserCommandCrash, p, nil)
}

// BrowserCrashGPUProcessParams Crashes GPU process.
type BrowserCrashGPUProcessParams struct{}

// BrowserCrashGPUProcess creates a new BrowserCrashGPUProcessParams.
func BrowserCrashGPUProcess() *BrowserCrashGPUProcessParams {
	return &BrowserCrashGPUProcessParams{}
}

// Do executes Browser.crashGpuProcess.
func (p *BrowserCrashGPUProcessParams) Do(ctx context.Context) error {
	return Execute(ctx, BrowserCommandCrashGPUProcess, p, nil)
}

// BrowserGetVersionParams Returns version information.
type BrowserGetVersionParams struct{}

// BrowserGetVersionReturns holds the return values for getVersion.
type BrowserGetVersionReturns struct {
	// ProtocolVersion Protocol version.
	ProtocolVersion string `json:"protocolVersion"`
	// Product Product name.
	Product string `json:"product"`
	// Revision Product revision.
	Revision string `json:"revision"`
	// UserAgent User-Agent.
	UserAgent string `json:"userAgent"`
	// JSVersion V8 version.
	JSVersion string `json:"jsVersion"`
}

// BrowserGetVersion creates a new BrowserGetVersionParams.
func BrowserGetVersion() *BrowserGetVersionParams {
	return &BrowserGetVersionParams{}
}

// Do executes Browser.getVersion.
func (p *BrowserGetVersionParams) Do(ctx context.Context) (*BrowserGetVersionReturns, error) {
	var res BrowserGetVersionReturns
	if err := Execute(ctx, BrowserCommandGetVersion, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// BrowserGetBrowserCommandLineParams Returns the command line switches for the browser process if, and only if
// --enable-automation is on the commandline.
type BrowserGetBrowserCommandLineParams struct{}

// BrowserGetBrowserCommandLineReturns holds the return values for getBrowserCommandLine.
type BrowserGetBrowserCommandLineReturns struct {
	// Arguments Commandline parameters
	Arguments []string `json:"arguments"`
}

// BrowserGetBrowserCommandLine creates a new BrowserGetBrowserCommandLineParams.
func BrowserGetBrowserCommandLine() *BrowserGetBrowserCommandLineParams {
	return &BrowserGetBrowserCommandLineParams{}
}

// Do executes Browser.getBrowserCommandLine.
func (p *BrowserGetBrowserCommandLineParams) Do(ctx context.Context) (*BrowserGetBrowserCommandLineReturns, error) {
	var res BrowserGetBrowserCommandLineReturns
	if err := Execute(ctx, BrowserCommandGetBrowserCommandLine, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// BrowserGetHistogramsParams Get Chrome histograms.
type BrowserGetHistogramsParams struct {
	// Query Requested substring in name. Only histograms which have query as a
	// substring in their name are extracted. An empty or absent query returns
	// all histograms.
	Query string `json:"query,omitempty"`
	// Delta If true, retrieve delta since last delta call.
	Delta bool `json:"delta,omitempty"`
}

// BrowserGetHistogramsReturns holds the return values for getHistograms.
type BrowserGetHistogramsReturns struct {
	// Histograms Histograms.
	Histograms []BrowserHistogram `json:"histograms"`
}

// BrowserGetHistograms creates a new BrowserGetHistogramsParams.
func BrowserGetHistograms() *BrowserGetHistogramsParams {
	return &BrowserGetHistogramsParams{}
}

// WithQuery sets the query parameter.
func (p *BrowserGetHistogramsParams) WithQuery(query string) *BrowserGetHistogramsParams {
	p.Query = query
	return p
}

// WithDelta sets the delta parameter.
func (p *BrowserGetHistogramsParams) WithDelta(delta bool) *BrowserGetHistogramsParams {
	p.Delta = delta
	return p
}

// Do executes Browser.getHistograms.
func (p *BrowserGetHistogramsParams) Do(ctx context.Context) (*BrowserGetHistogramsReturns, error) {
	var res BrowserGetHistogramsReturns
	if err := Execute(ctx, BrowserCommandGetHistograms, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// BrowserGetHistogramParams Get a Chrome histogram by name.
type BrowserGetHistogramParams struct {
	// Name Requested histogram name.
	Name string `json:"name"`
	// Delta If true, retrieve delta since last delta call.
	Delta bool `json:"delta,omitempty"`
}

// BrowserGetHistogramReturns holds the return values for getHistogram.
type BrowserGetHistogramReturns struct {
	// Histogram Histogram.
	Histogram BrowserHistogram `json:"histogram"`
}

// BrowserGetHistogram creates a new BrowserGetHistogramParams.
func BrowserGetHistogram(name string) *BrowserGetHistogramParams {
	return &BrowserGetHistogramParams{
		Name: name,
	}
}

// WithDelta sets the delta parameter.
func (p *BrowserGetHistogramParams) WithDelta(delta bool) *BrowserGetHistogramParams {
	p.Delta = delta
	return p
}

// Do executes Browser.getHistogram.
func (p *BrowserGetHistogramParams) Do(ctx context.Context) (*BrowserGetHistogramReturns, error) {
	var res BrowserGetHistogramReturns
	if err := Execute(ctx, BrowserCommandGetHistogram, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// BrowserGetWindowBoundsParams Get position and size of the browser window.
type BrowserGetWindowBoundsParams struct {
	// WindowID Browser window id.
	WindowID BrowserWindowID `json:"windowId"`
}

// BrowserGetWindowBoundsReturns holds the return values for getWindowBounds.
type BrowserGetWindowBoundsReturns struct {
	// Bounds Bounds information of the window. When window state is 'minimized', the restored window
	// position and size are returned.
	Bounds BrowserBounds `json:"bounds"`
}

// BrowserGetWindowBounds creates a new BrowserGetWindowBoundsParams.
func BrowserGetWindowBounds(windowID BrowserWindowID) *BrowserGetWindowBoundsParams {
	return &BrowserGetWindowBoundsParams{
		WindowID: windowID,
	}
}

// Do executes Browser.getWindowBounds.
func (p *BrowserGetWindowBoundsParams) Do(ctx context.Context) (*BrowserGetWindowBoundsReturns, error) {
	var res BrowserGetWindowBoundsReturns
	if err := Execute(ctx, BrowserCommandGetWindowBounds, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// BrowserGetWindowForTargetParams Get the browser window that contains the devtools target.
type BrowserGetWindowForTargetParams struct {
	// TargetID Devtools agent host id. If called as a part of the session, associated targetId is used.
	TargetID TargetTargetID `json:"targetId,omitempty"`
}

// BrowserGetWindowForTargetReturns holds the return values for getWindowForTarget.
type BrowserGetWindowForTargetReturns struct {
	// WindowID Browser window id.
	WindowID BrowserWindowID `json:"windowId"`
	// Bounds Bounds information of the window. When window state is 'minimized', the restored window
	// position and size are returned.
	Bounds BrowserBounds `json:"bounds"`
}

// BrowserGetWindowForTarget creates a new BrowserGetWindowForTargetParams.
func BrowserGetWindowForTarget() *BrowserGetWindowForTargetParams {
	return &BrowserGetWindowForTargetParams{}
}

// WithTargetID sets the targetId parameter.
func (p *BrowserGetWindowForTargetParams) WithTargetID(targetID TargetTargetID) *BrowserGetWindowForTargetParams {
	p.TargetID = targetID
	return p
}

// Do executes Browser.getWindowForTarget.
func (p *BrowserGetWindowForTargetParams) Do(ctx context.Context) (*BrowserGetWindowForTargetReturns, error) {
	var res BrowserGetWindowForTargetReturns
	if err := Execute(ctx, BrowserCommandGetWindowForTarget, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// BrowserSetWindowBoundsParams Set position and/or size of the browser window.
type BrowserSetWindowBoundsParams struct {
	// WindowID Browser window id.
	WindowID BrowserWindowID `json:"windowId"`
	// Bounds New window bounds. The 'minimized', 'maximized' and 'fullscreen' states cannot be combined
	// with 'left', 'top', 'width' or 'height'. Leaves unspecified fields unchanged.
	Bounds BrowserBounds `json:"bounds"`
}

// BrowserSetWindowBounds creates a new BrowserSetWindowBoundsParams.
func BrowserSetWindowBounds(windowID BrowserWindowID, bounds BrowserBounds) *BrowserSetWindowBoundsParams {
	return &BrowserSetWindowBoundsParams{
		WindowID: windowID,
		Bounds:   bounds,
	}
}

// Do executes Browser.setWindowBounds.
func (p *BrowserSetWindowBoundsParams) Do(ctx context.Context) error {
	return Execute(ctx, BrowserCommandSetWindowBounds, p, nil)
}

// BrowserSetContentsSizeParams Set size of the browser contents resizing browser window as necessary.
type BrowserSetContentsSizeParams struct {
	// WindowID Browser window id.
	WindowID BrowserWindowID `json:"windowId"`
	// Width The window contents width in DIP. Assumes current width if omitted.
	// Must be specified if 'height' is omitted.
	Width int64 `json:"width,omitempty"`
	// Height The window contents height in DIP. Assumes current height if omitted.
	// Must be specified if 'width' is omitted.
	Height int64 `json:"height,omitempty"`
}

// BrowserSetContentsSize creates a new BrowserSetContentsSizeParams.
func BrowserSetContentsSize(windowID BrowserWindowID) *BrowserSetContentsSizeParams {
	return &BrowserSetContentsSizeParams{
		WindowID: windowID,
	}
}

// WithWidth sets the width parameter.
func (p *BrowserSetContentsSizeParams) WithWidth(width int64) *BrowserSetContentsSizeParams {
	p.Width = width
	return p
}

// WithHeight sets the height parameter.
func (p *BrowserSetContentsSizeParams) WithHeight(height int64) *BrowserSetContentsSizeParams {
	p.Height = height
	return p
}

// Do executes Browser.setContentsSize.
func (p *BrowserSetContentsSizeParams) Do(ctx context.Context) error {
	return Execute(ctx, BrowserCommandSetContentsSize, p, nil)
}

// BrowserSetDockTileParams Set dock tile details, platform-specific.
type BrowserSetDockTileParams struct {
	BadgeLabel string `json:"badgeLabel,omitempty"`
	// Image Png encoded image.
	Image []byte `json:"image,omitempty"`
}

// BrowserSetDockTile creates a new BrowserSetDockTileParams.
func BrowserSetDockTile() *BrowserSetDockTileParams {
	return &BrowserSetDockTileParams{}
}

// WithBadgeLabel sets the badgeLabel parameter.
func (p *BrowserSetDockTileParams) WithBadgeLabel(badgeLabel string) *BrowserSetDockTileParams {
	p.BadgeLabel = badgeLabel
	return p
}

// WithImage sets the image parameter.
func (p *BrowserSetDockTileParams) WithImage(image []byte) *BrowserSetDockTileParams {
	p.Image = image
	return p
}

// Do executes Browser.setDockTile.
func (p *BrowserSetDockTileParams) Do(ctx context.Context) error {
	return Execute(ctx, BrowserCommandSetDockTile, p, nil)
}

// BrowserExecuteBrowserCommandParams Invoke custom browser commands used by telemetry.
type BrowserExecuteBrowserCommandParams struct {
	CommandID BrowserBrowserCommandID `json:"commandId"`
}

// BrowserExecuteBrowserCommand creates a new BrowserExecuteBrowserCommandParams.
func BrowserExecuteBrowserCommand(commandID BrowserBrowserCommandID) *BrowserExecuteBrowserCommandParams {
	return &BrowserExecuteBrowserCommandParams{
		CommandID: commandID,
	}
}

// Do executes Browser.executeBrowserCommand.
func (p *BrowserExecuteBrowserCommandParams) Do(ctx context.Context) error {
	return Execute(ctx, BrowserCommandExecuteBrowserCommand, p, nil)
}

// BrowserAddPrivacySandboxEnrollmentOverrideParams Allows a site to use privacy sandbox features that require enrollment
// without the site actually being enrolled. Only supported on page targets.
type BrowserAddPrivacySandboxEnrollmentOverrideParams struct {
	URL string `json:"url"`
}

// BrowserAddPrivacySandboxEnrollmentOverride creates a new BrowserAddPrivacySandboxEnrollmentOverrideParams.
func BrowserAddPrivacySandboxEnrollmentOverride(url string) *BrowserAddPrivacySandboxEnrollmentOverrideParams {
	return &BrowserAddPrivacySandboxEnrollmentOverrideParams{
		URL: url,
	}
}

// Do executes Browser.addPrivacySandboxEnrollmentOverride.
func (p *BrowserAddPrivacySandboxEnrollmentOverrideParams) Do(ctx context.Context) error {
	return Execute(ctx, BrowserCommandAddPrivacySandboxEnrollmentOverride, p, nil)
}

// BrowserAddPrivacySandboxCoordinatorKeyConfigParams Configures encryption keys used with a given privacy sandbox API to talk
// to a trusted coordinator.  Since this is intended for test automation only,
// coordinatorOrigin must be a .test domain. No existing coordinator
// configuration for the origin may exist.
type BrowserAddPrivacySandboxCoordinatorKeyConfigParams struct {
	API               BrowserPrivacySandboxAPI `json:"api"`
	CoordinatorOrigin string                   `json:"coordinatorOrigin"`
	KeyConfig         string                   `json:"keyConfig"`
	// BrowserContextID BrowserContext to perform the action in. When omitted, default browser
	// context is used.
	BrowserContextID BrowserContextID `json:"browserContextId,omitempty"`
}

// BrowserAddPrivacySandboxCoordinatorKeyConfig creates a new BrowserAddPrivacySandboxCoordinatorKeyConfigParams.
func BrowserAddPrivacySandboxCoordinatorKeyConfig(api BrowserPrivacySandboxAPI, coordinatorOrigin string, keyConfig string) *BrowserAddPrivacySandboxCoordinatorKeyConfigParams {
	return &BrowserAddPrivacySandboxCoordinatorKeyConfigParams{
		API:               api,
		CoordinatorOrigin: coordinatorOrigin,
		KeyConfig:         keyConfig,
	}
}

// WithBrowserContextID sets the browserContextId parameter.
func (p *BrowserAddPrivacySandboxCoordinatorKeyConfigParams) WithBrowserContextID(browserContextID BrowserContextID) *BrowserAddPrivacySandboxCoordinatorKeyConfigParams {
	p.BrowserContextID = browserContextID
	return p
}

// Do executes Browser.addPrivacySandboxCoordinatorKeyConfig.
func (p *BrowserAddPrivacySandboxCoordinatorKeyConfigParams) Do(ctx context.Context) error {
	return Execute(ctx, BrowserCommandAddPrivacySandboxCoordinatorKeyConfig, p, nil)
}

// Browser command names.
const (
	BrowserCommandSetPermission                         Method = "Browser.setPermission"
	BrowserCommandGrantPermissions                      Method = "Browser.grantPermissions"
	BrowserCommandResetPermissions                      Method = "Browser.resetPermissions"
	BrowserCommandSetDownloadBehavior                   Method = "Browser.setDownloadBehavior"
	BrowserCommandCancelDownload                        Method = "Browser.cancelDownload"
	BrowserCommandClose                                 Method = "Browser.close"
	BrowserCommandCrash                                 Method = "Browser.crash"
	BrowserCommandCrashGPUProcess                       Method = "Browser.crashGpuProcess"
	BrowserCommandGetVersion                            Method = "Browser.getVersion"
	BrowserCommandGetBrowserCommandLine                 Method = "Browser.getBrowserCommandLine"
	BrowserCommandGetHistograms                         Method = "Browser.getHistograms"
	BrowserCommandGetHistogram                          Method = "Browser.getHistogram"
	BrowserCommandGetWindowBounds                       Method = "Browser.getWindowBounds"
	BrowserCommandGetWindowForTarget                    Method = "Browser.getWindowForTarget"
	BrowserCommandSetWindowBounds                       Method = "Browser.setWindowBounds"
	BrowserCommandSetContentsSize                       Method = "Browser.setContentsSize"
	BrowserCommandSetDockTile                           Method = "Browser.setDockTile"
	BrowserCommandExecuteBrowserCommand                 Method = "Browser.executeBrowserCommand"
	BrowserCommandAddPrivacySandboxEnrollmentOverride   Method = "Browser.addPrivacySandboxEnrollmentOverride"
	BrowserCommandAddPrivacySandboxCoordinatorKeyConfig Method = "Browser.addPrivacySandboxCoordinatorKeyConfig"
)
