// Code generated by bonkgen. DO NOT EDIT.

package proto

// CastEventSinksUpdated This is fired whenever the list of available sinks changes. A sink is a
// device or a software surface that you can cast to.
type CastEventSinksUpdated struct {
	Sinks []CastSink `json:"sinks"`
}

// CastEventIssueUpdated This is fired whenever the outstanding issue/error message changes.
// |issueMessage| is empty if there is no issue.
type CastEventIssueUpdated struct {
	IssueMessage string `json:"issueMessage"`
}

// Cast event names.
const (
	CastEventSinksUpdatedMethod Method = "Cast.sinksUpdated"
	CastEventIssueUpdatedMethod Method = "Cast.issueUpdated"
)
