// Code generated by bonkgen. DO NOT EDIT.

package proto

// ConsoleEventMessageAdded Issued when new console message is added.
type ConsoleEventMessageAdded struct {
	// Message Console message that has been added.
	Message ConsoleConsoleMessage `json:"message"`
}

// Console event names.
const (
	ConsoleEventMessageAddedMethod Method = "Console.messageAdded"
)
