// Code generated by bonkgen. DO NOT EDIT.

package proto

// ConsoleConsoleMessage Console message.
type ConsoleConsoleMessage struct {
	// Source Message source.
	Source ConsoleConsoleMessageSource `json:"source"`
	// Level Message severity.
	Level ConsoleConsoleMessageLevel `json:"level"`
	// Text Message text.
	Text string `json:"text"`
	// URL URL of the message origin.
	URL string `json:"url,omitempty"`
	// Line Line number in the resource that generated this message (1-based).
	Line int64 `json:"line,omitempty"`
	// Column Column number in the resource that generated this message (1-based).
	Column int64 `json:"column,omitempty"`
}

// ConsoleConsoleMessageSource Message source.
type ConsoleConsoleMessageSource string

const (
	ConsoleConsoleMessageSourceXML         ConsoleConsoleMessageSource = "xml"
	ConsoleConsoleMessageSourceJavascript  ConsoleConsoleMessageSource = "javascript"
	ConsoleConsoleMessageSourceNetwork     ConsoleConsoleMessageSource = "network"
	ConsoleConsoleMessageSourceConsoleAPI  ConsoleConsoleMessageSource = "console-api"
	ConsoleConsoleMessageSourceStorage     ConsoleConsoleMessageSource = "storage"
	ConsoleConsoleMessageSourceAppcache    ConsoleConsoleMessageSource = "appcache"
	ConsoleConsoleMessageSourceRendering   ConsoleConsoleMessageSource = "rendering"
	ConsoleConsoleMessageSourceSecurity    ConsoleConsoleMessageSource = "security"
	ConsoleConsoleMessageSourceOther       ConsoleConsoleMessageSource = "other"
	ConsoleConsoleMessageSourceDeprecation ConsoleConsoleMessageSource = "deprecation"
	ConsoleConsoleMessageSourceWorker      ConsoleConsoleMessageSource = "worker"
)

// IsValid reports whether the value is a known enum value.
func (t ConsoleConsoleMessageSource) IsValid() bool {
	switch t {
	case ConsoleConsoleMessageSourceXML:
		return true
	case ConsoleConsoleMessageSourceJavascript:
		return true
	case ConsoleConsoleMessageSourceNetwork:
		return true
	case ConsoleConsoleMessageSourceConsoleAPI:
		return true
	case ConsoleConsoleMessageSourceStorage:
		return true
	case ConsoleConsoleMessageSourceAppcache:
		return true
	case ConsoleConsoleMessageSourceRendering:
		return true
	case ConsoleConsoleMessageSourceSecurity:
		return true
	case ConsoleConsoleMessageSourceOther:
		return true
	case ConsoleConsoleMessageSourceDeprecation:
		return true
	case ConsoleConsoleMessageSourceWorker:
		return true
	}
	return false
}

// Values returns all known values of ConsoleConsoleMessageSource.
func (t ConsoleConsoleMessageSource) Values() []ConsoleConsoleMessageSource {
	return []ConsoleConsoleMessageSource{
		ConsoleConsoleMessageSourceXML,
		ConsoleConsoleMessageSourceJavascript,
		ConsoleConsoleMessageSourceNetwork,
		ConsoleConsoleMessageSourceConsoleAPI,
		ConsoleConsoleMessageSourceStorage,
		ConsoleConsoleMessageSourceAppcache,
		ConsoleConsoleMessageSourceRendering,
		ConsoleConsoleMessageSourceSecurity,
		ConsoleConsoleMessageSourceOther,
		ConsoleConsoleMessageSourceDeprecation,
		ConsoleConsoleMessageSourceWorker,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t ConsoleConsoleMessageSource) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *ConsoleConsoleMessageSource) UnmarshalText(data []byte) error {
	*t = ConsoleConsoleMessageSource(data)
	return nil
}

// String returns the string representation.
func (t ConsoleConsoleMessageSource) String() string {
	return string(t)
}

// ConsoleConsoleMessageLevel Message severity.
type ConsoleConsoleMessageLevel string

const (
	ConsoleConsoleMessageLevelLog     ConsoleConsoleMessageLevel = "log"
	ConsoleConsoleMessageLevelWarning ConsoleConsoleMessageLevel = "warning"
	ConsoleConsoleMessageLevelError   ConsoleConsoleMessageLevel = "error"
	ConsoleConsoleMessageLevelDebug   ConsoleConsoleMessageLevel = "debug"
	ConsoleConsoleMessageLevelInfo    ConsoleConsoleMessageLevel = "info"
)

// IsValid reports whether the value is a known enum value.
func (t ConsoleConsoleMessageLevel) IsValid() bool {
	switch t {
	case ConsoleConsoleMessageLevelLog:
		return true
	case ConsoleConsoleMessageLevelWarning:
		return true
	case ConsoleConsoleMessageLevelError:
		return true
	case ConsoleConsoleMessageLevelDebug:
		return true
	case ConsoleConsoleMessageLevelInfo:
		return true
	}
	return false
}

// Values returns all known values of ConsoleConsoleMessageLevel.
func (t ConsoleConsoleMessageLevel) Values() []ConsoleConsoleMessageLevel {
	return []ConsoleConsoleMessageLevel{
		ConsoleConsoleMessageLevelLog,
		ConsoleConsoleMessageLevelWarning,
		ConsoleConsoleMessageLevelError,
		ConsoleConsoleMessageLevelDebug,
		ConsoleConsoleMessageLevelInfo,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t ConsoleConsoleMessageLevel) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *ConsoleConsoleMessageLevel) UnmarshalText(data []byte) error {
	*t = ConsoleConsoleMessageLevel(data)
	return nil
}

// String returns the string representation.
func (t ConsoleConsoleMessageLevel) String() string {
	return string(t)
}
