// Code generated by bonkgen. DO NOT EDIT.

package proto

import (
	"context"
	"encoding/json"
)

// CSSAddRuleParams Inserts a new rule with the given `ruleText` in a stylesheet with given `styleSheetId`, at the
// position specified by `location`.
type CSSAddRuleParams struct {
	// StyleSheetID The css style sheet identifier where a new rule should be inserted.
	StyleSheetID DOMStyleSheetID `json:"styleSheetId"`
	// RuleText The text of a new rule.
	RuleText string `json:"ruleText"`
	// Location Text position of a new rule in the target style sheet.
	Location CSSSourceRange `json:"location"`
	// NodeForPropertySyntaxValidation NodeId for the DOM node in whose context custom property declarations for registered properties should be
	// validated. If omitted, declarations in the new rule text can only be validated statically, which may produce
	// incorrect results if the declaration contains a var() for example.
	NodeForPropertySyntaxValidation NodeID `json:"nodeForPropertySyntaxValidation,omitempty,omitzero"`
}

// CSSAddRuleReturns holds the return values for addRule.
type CSSAddRuleReturns struct {
	// Rule The newly created rule.
	Rule CSSCSSRule `json:"rule"`
}

// CSSAddRule creates a new CSSAddRuleParams.
func CSSAddRule(styleSheetID DOMStyleSheetID, ruleText string, location CSSSourceRange) *CSSAddRuleParams {
	return &CSSAddRuleParams{
		StyleSheetID: styleSheetID,
		RuleText:     ruleText,
		Location:     location,
	}
}

// WithNodeForPropertySyntaxValidation sets the nodeForPropertySyntaxValidation parameter.
func (p *CSSAddRuleParams) WithNodeForPropertySyntaxValidation(nodeForPropertySyntaxValidation NodeID) *CSSAddRuleParams {
	p.NodeForPropertySyntaxValidation = nodeForPropertySyntaxValidation
	return p
}

// Do executes CSS.addRule.
func (p *CSSAddRuleParams) Do(ctx context.Context) (*CSSAddRuleReturns, error) {
	var res CSSAddRuleReturns
	if err := Execute(ctx, CSSCommandAddRule, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSCollectClassNamesParams Returns all class names from specified stylesheet.
type CSSCollectClassNamesParams struct {
	StyleSheetID DOMStyleSheetID `json:"styleSheetId"`
}

// CSSCollectClassNamesReturns holds the return values for collectClassNames.
type CSSCollectClassNamesReturns struct {
	// ClassNames Class name list.
	ClassNames []string `json:"classNames"`
}

// CSSCollectClassNames creates a new CSSCollectClassNamesParams.
func CSSCollectClassNames(styleSheetID DOMStyleSheetID) *CSSCollectClassNamesParams {
	return &CSSCollectClassNamesParams{
		StyleSheetID: styleSheetID,
	}
}

// Do executes CSS.collectClassNames.
func (p *CSSCollectClassNamesParams) Do(ctx context.Context) (*CSSCollectClassNamesReturns, error) {
	var res CSSCollectClassNamesReturns
	if err := Execute(ctx, CSSCommandCollectClassNames, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSCreateStyleSheetParams Creates a new special "via-inspector" stylesheet in the frame with given `frameId`.
type CSSCreateStyleSheetParams struct {
	// FrameID Identifier of the frame where "via-inspector" stylesheet should be created.
	FrameID FrameID `json:"frameId"`
	// Force If true, creates a new stylesheet for every call. If false,
	// returns a stylesheet previously created by a call with force=false
	// for the frame's document if it exists or creates a new stylesheet
	// (default: false).
	Force bool `json:"force,omitempty,omitzero"`
}

// CSSCreateStyleSheetReturns holds the return values for createStyleSheet.
type CSSCreateStyleSheetReturns struct {
	// StyleSheetID Identifier of the created "via-inspector" stylesheet.
	StyleSheetID DOMStyleSheetID `json:"styleSheetId"`
}

// CSSCreateStyleSheet creates a new CSSCreateStyleSheetParams.
func CSSCreateStyleSheet(frameID FrameID) *CSSCreateStyleSheetParams {
	return &CSSCreateStyleSheetParams{
		FrameID: frameID,
	}
}

// WithForce sets the force parameter.
func (p *CSSCreateStyleSheetParams) WithForce(force bool) *CSSCreateStyleSheetParams {
	p.Force = force
	return p
}

// Do executes CSS.createStyleSheet.
func (p *CSSCreateStyleSheetParams) Do(ctx context.Context) (*CSSCreateStyleSheetReturns, error) {
	var res CSSCreateStyleSheetReturns
	if err := Execute(ctx, CSSCommandCreateStyleSheet, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSDisableParams Disables the CSS agent for the given page.
type CSSDisableParams struct{}

// CSSDisable creates a new CSSDisableParams.
func CSSDisable() *CSSDisableParams {
	return &CSSDisableParams{}
}

// Do executes CSS.disable.
func (p *CSSDisableParams) Do(ctx context.Context) error {
	return Execute(ctx, CSSCommandDisable, p, nil)
}

// CSSEnableParams Enables the CSS agent for the given page. Clients should not assume that the CSS agent has been
// enabled until the result of this command is received.
type CSSEnableParams struct{}

// CSSEnable creates a new CSSEnableParams.
func CSSEnable() *CSSEnableParams {
	return &CSSEnableParams{}
}

// Do executes CSS.enable.
func (p *CSSEnableParams) Do(ctx context.Context) error {
	return Execute(ctx, CSSCommandEnable, p, nil)
}

// CSSForcePseudoStateParams Ensures that the given node will have specified pseudo-classes whenever its style is computed by
// the browser.
type CSSForcePseudoStateParams struct {
	// NodeID The element id for which to force the pseudo state.
	NodeID NodeID `json:"nodeId"`
	// ForcedPseudoClasses Element pseudo classes to force when computing the element's style.
	ForcedPseudoClasses []string `json:"forcedPseudoClasses"`
}

// CSSForcePseudoState creates a new CSSForcePseudoStateParams.
func CSSForcePseudoState(nodeID NodeID, forcedPseudoClasses []string) *CSSForcePseudoStateParams {
	return &CSSForcePseudoStateParams{
		NodeID:              nodeID,
		ForcedPseudoClasses: forcedPseudoClasses,
	}
}

// Do executes CSS.forcePseudoState.
func (p *CSSForcePseudoStateParams) Do(ctx context.Context) error {
	return Execute(ctx, CSSCommandForcePseudoState, p, nil)
}

// CSSForceStartingStyleParams Ensures that the given node is in its starting-style state.
type CSSForceStartingStyleParams struct {
	// NodeID The element id for which to force the starting-style state.
	NodeID NodeID `json:"nodeId"`
	// Forced Boolean indicating if this is on or off.
	Forced bool `json:"forced"`
}

// CSSForceStartingStyle creates a new CSSForceStartingStyleParams.
func CSSForceStartingStyle(nodeID NodeID, forced bool) *CSSForceStartingStyleParams {
	return &CSSForceStartingStyleParams{
		NodeID: nodeID,
		Forced: forced,
	}
}

// Do executes CSS.forceStartingStyle.
func (p *CSSForceStartingStyleParams) Do(ctx context.Context) error {
	return Execute(ctx, CSSCommandForceStartingStyle, p, nil)
}

type CSSGetBackgroundColorsParams struct {
	// NodeID Id of the node to get background colors for.
	NodeID NodeID `json:"nodeId"`
}

// CSSGetBackgroundColorsReturns holds the return values for getBackgroundColors.
type CSSGetBackgroundColorsReturns struct {
	// BackgroundColors The range of background colors behind this element, if it contains any visible text. If no
	// visible text is present, this will be undefined. In the case of a flat background color,
	// this will consist of simply that color. In the case of a gradient, this will consist of each
	// of the color stops. For anything more complicated, this will be an empty array. Images will
	// be ignored (as if the image had failed to load).
	BackgroundColors []string `json:"backgroundColors,omitempty,omitzero"`
	// ComputedFontSize The computed font size for this node, as a CSS computed value string (e.g. '12px').
	ComputedFontSize string `json:"computedFontSize,omitempty,omitzero"`
	// ComputedFontWeight The computed font weight for this node, as a CSS computed value string (e.g. 'normal' or
	// '100').
	ComputedFontWeight string `json:"computedFontWeight,omitempty,omitzero"`
}

// CSSGetBackgroundColors creates a new CSSGetBackgroundColorsParams.
func CSSGetBackgroundColors(nodeID NodeID) *CSSGetBackgroundColorsParams {
	return &CSSGetBackgroundColorsParams{
		NodeID: nodeID,
	}
}

// Do executes CSS.getBackgroundColors.
func (p *CSSGetBackgroundColorsParams) Do(ctx context.Context) (*CSSGetBackgroundColorsReturns, error) {
	var res CSSGetBackgroundColorsReturns
	if err := Execute(ctx, CSSCommandGetBackgroundColors, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSGetComputedStyleForNodeParams Returns the computed style for a DOM node identified by `nodeId`.
type CSSGetComputedStyleForNodeParams struct {
	NodeID NodeID `json:"nodeId"`
}

// CSSGetComputedStyleForNodeReturns holds the return values for getComputedStyleForNode.
type CSSGetComputedStyleForNodeReturns struct {
	// ComputedStyle Computed style for the specified DOM node.
	ComputedStyle []CSSCSSComputedStyleProperty `json:"computedStyle"`
	// ExtraFields A list of non-standard "extra fields" which blink stores alongside each
	// computed style.
	ExtraFields CSSComputedStyleExtraFields `json:"extraFields"`
}

// CSSGetComputedStyleForNode creates a new CSSGetComputedStyleForNodeParams.
func CSSGetComputedStyleForNode(nodeID NodeID) *CSSGetComputedStyleForNodeParams {
	return &CSSGetComputedStyleForNodeParams{
		NodeID: nodeID,
	}
}

// Do executes CSS.getComputedStyleForNode.
func (p *CSSGetComputedStyleForNodeParams) Do(ctx context.Context) (*CSSGetComputedStyleForNodeReturns, error) {
	var res CSSGetComputedStyleForNodeReturns
	if err := Execute(ctx, CSSCommandGetComputedStyleForNode, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSResolveValuesParams Resolve the specified values in the context of the provided element.
// For example, a value of '1em' is evaluated according to the computed
// 'font-size' of the element and a value 'calc(1px + 2px)' will be
// resolved to '3px'.
// If the `propertyName` was specified the `values` are resolved as if
// they were property's declaration. If a value cannot be parsed according
// to the provided property syntax, the value is parsed using combined
// syntax as if null `propertyName` was provided. If the value cannot be
// resolved even then, return the provided value without any changes.
// Note: this function currently does not resolve CSS random() function,
// it returns unmodified random() function parts.`
type CSSResolveValuesParams struct {
	// Values Cascade-dependent keywords (revert/revert-layer) do not work.
	Values []string `json:"values"`
	// NodeID Id of the node in whose context the expression is evaluated
	NodeID NodeID `json:"nodeId"`
	// PropertyName Only longhands and custom property names are accepted.
	PropertyName string `json:"propertyName,omitempty,omitzero"`
	// PseudoType Pseudo element type, only works for pseudo elements that generate
	// elements in the tree, such as ::before and ::after.
	PseudoType DOMPseudoType `json:"pseudoType,omitempty,omitzero"`
	// PseudoIdentifier Pseudo element custom ident.
	PseudoIdentifier string `json:"pseudoIdentifier,omitempty,omitzero"`
}

// CSSResolveValuesReturns holds the return values for resolveValues.
type CSSResolveValuesReturns struct {
	Results []string `json:"results"`
}

// CSSResolveValues creates a new CSSResolveValuesParams.
func CSSResolveValues(values []string, nodeID NodeID) *CSSResolveValuesParams {
	return &CSSResolveValuesParams{
		Values: values,
		NodeID: nodeID,
	}
}

// WithPropertyName sets the propertyName parameter.
func (p *CSSResolveValuesParams) WithPropertyName(propertyName string) *CSSResolveValuesParams {
	p.PropertyName = propertyName
	return p
}

// WithPseudoType sets the pseudoType parameter.
func (p *CSSResolveValuesParams) WithPseudoType(pseudoType DOMPseudoType) *CSSResolveValuesParams {
	p.PseudoType = pseudoType
	return p
}

// WithPseudoIdentifier sets the pseudoIdentifier parameter.
func (p *CSSResolveValuesParams) WithPseudoIdentifier(pseudoIdentifier string) *CSSResolveValuesParams {
	p.PseudoIdentifier = pseudoIdentifier
	return p
}

// Do executes CSS.resolveValues.
func (p *CSSResolveValuesParams) Do(ctx context.Context) (*CSSResolveValuesReturns, error) {
	var res CSSResolveValuesReturns
	if err := Execute(ctx, CSSCommandResolveValues, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type CSSGetLonghandPropertiesParams struct {
	ShorthandName string `json:"shorthandName"`
	Value         string `json:"value"`
}

// CSSGetLonghandPropertiesReturns holds the return values for getLonghandProperties.
type CSSGetLonghandPropertiesReturns struct {
	LonghandProperties []CSSCSSProperty `json:"longhandProperties"`
}

// CSSGetLonghandProperties creates a new CSSGetLonghandPropertiesParams.
func CSSGetLonghandProperties(shorthandName string, value string) *CSSGetLonghandPropertiesParams {
	return &CSSGetLonghandPropertiesParams{
		ShorthandName: shorthandName,
		Value:         value,
	}
}

// Do executes CSS.getLonghandProperties.
func (p *CSSGetLonghandPropertiesParams) Do(ctx context.Context) (*CSSGetLonghandPropertiesReturns, error) {
	var res CSSGetLonghandPropertiesReturns
	if err := Execute(ctx, CSSCommandGetLonghandProperties, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSGetInlineStylesForNodeParams Returns the styles defined inline (explicitly in the "style" attribute and implicitly, using DOM
// attributes) for a DOM node identified by `nodeId`.
type CSSGetInlineStylesForNodeParams struct {
	NodeID NodeID `json:"nodeId"`
}

// CSSGetInlineStylesForNodeReturns holds the return values for getInlineStylesForNode.
type CSSGetInlineStylesForNodeReturns struct {
	// InlineStyle Inline style for the specified DOM node.
	InlineStyle CSSCSSStyle `json:"inlineStyle,omitempty,omitzero"`
	// AttributesStyle Attribute-defined element style (e.g. resulting from "width=20 height=100%").
	AttributesStyle CSSCSSStyle `json:"attributesStyle,omitempty,omitzero"`
}

// CSSGetInlineStylesForNode creates a new CSSGetInlineStylesForNodeParams.
func CSSGetInlineStylesForNode(nodeID NodeID) *CSSGetInlineStylesForNodeParams {
	return &CSSGetInlineStylesForNodeParams{
		NodeID: nodeID,
	}
}

// Do executes CSS.getInlineStylesForNode.
func (p *CSSGetInlineStylesForNodeParams) Do(ctx context.Context) (*CSSGetInlineStylesForNodeReturns, error) {
	var res CSSGetInlineStylesForNodeReturns
	if err := Execute(ctx, CSSCommandGetInlineStylesForNode, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSGetAnimatedStylesForNodeParams Returns the styles coming from animations & transitions
// including the animation & transition styles coming from inheritance chain.
type CSSGetAnimatedStylesForNodeParams struct {
	NodeID NodeID `json:"nodeId"`
}

// CSSGetAnimatedStylesForNodeReturns holds the return values for getAnimatedStylesForNode.
type CSSGetAnimatedStylesForNodeReturns struct {
	// AnimationStyles Styles coming from animations.
	AnimationStyles []CSSCSSAnimationStyle `json:"animationStyles,omitempty,omitzero"`
	// TransitionsStyle Style coming from transitions.
	TransitionsStyle CSSCSSStyle `json:"transitionsStyle,omitempty,omitzero"`
	// Inherited Inherited style entries for animationsStyle and transitionsStyle from
	// the inheritance chain of the element.
	Inherited []CSSInheritedAnimatedStyleEntry `json:"inherited,omitempty,omitzero"`
}

// CSSGetAnimatedStylesForNode creates a new CSSGetAnimatedStylesForNodeParams.
func CSSGetAnimatedStylesForNode(nodeID NodeID) *CSSGetAnimatedStylesForNodeParams {
	return &CSSGetAnimatedStylesForNodeParams{
		NodeID: nodeID,
	}
}

// Do executes CSS.getAnimatedStylesForNode.
func (p *CSSGetAnimatedStylesForNodeParams) Do(ctx context.Context) (*CSSGetAnimatedStylesForNodeReturns, error) {
	var res CSSGetAnimatedStylesForNodeReturns
	if err := Execute(ctx, CSSCommandGetAnimatedStylesForNode, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSGetMatchedStylesForNodeParams Returns requested styles for a DOM node identified by `nodeId`.
type CSSGetMatchedStylesForNodeParams struct {
	NodeID NodeID `json:"nodeId"`
}

// CSSGetMatchedStylesForNodeReturns holds the return values for getMatchedStylesForNode.
type CSSGetMatchedStylesForNodeReturns struct {
	// InlineStyle Inline style for the specified DOM node.
	InlineStyle CSSCSSStyle `json:"inlineStyle,omitempty,omitzero"`
	// AttributesStyle Attribute-defined element style (e.g. resulting from "width=20 height=100%").
	AttributesStyle CSSCSSStyle `json:"attributesStyle,omitempty,omitzero"`
	// MatchedCSSRules CSS rules matching this node, from all applicable stylesheets.
	MatchedCSSRules []CSSRuleMatch `json:"matchedCSSRules,omitempty,omitzero"`
	// PseudoElements Pseudo style matches for this node.
	PseudoElements []CSSPseudoElementMatches `json:"pseudoElements,omitempty,omitzero"`
	// Inherited A chain of inherited styles (from the immediate node parent up to the DOM tree root).
	Inherited []CSSInheritedStyleEntry `json:"inherited,omitempty,omitzero"`
	// InheritedPseudoElements A chain of inherited pseudo element styles (from the immediate node parent up to the DOM tree root).
	InheritedPseudoElements []CSSInheritedPseudoElementMatches `json:"inheritedPseudoElements,omitempty,omitzero"`
	// CSSKeyframesRules A list of CSS keyframed animations matching this node.
	CSSKeyframesRules []CSSCSSKeyframesRule `json:"cssKeyframesRules,omitempty,omitzero"`
	// CSSPositionTryRules A list of CSS @position-try rules matching this node, based on the position-try-fallbacks property.
	CSSPositionTryRules []CSSCSSPositionTryRule `json:"cssPositionTryRules,omitempty,omitzero"`
	// ActivePositionFallbackIndex Index of the active fallback in the applied position-try-fallback property,
	// will not be set if there is no active position-try fallback.
	ActivePositionFallbackIndex int64 `json:"activePositionFallbackIndex,omitempty,omitzero"`
	// CSSPropertyRules A list of CSS at-property rules matching this node.
	CSSPropertyRules []CSSCSSPropertyRule `json:"cssPropertyRules,omitempty,omitzero"`
	// CSSPropertyRegistrations A list of CSS property registrations matching this node.
	CSSPropertyRegistrations []CSSCSSPropertyRegistration `json:"cssPropertyRegistrations,omitempty,omitzero"`
	// CSSAtRules A list of simple @rules matching this node or its pseudo-elements.
	CSSAtRules []CSSCSSAtRule `json:"cssAtRules,omitempty,omitzero"`
	// ParentLayoutNodeID Id of the first parent element that does not have display: contents.
	ParentLayoutNodeID NodeID `json:"parentLayoutNodeId,omitempty,omitzero"`
	// CSSFunctionRules A list of CSS at-function rules referenced by styles of this node.
	CSSFunctionRules []CSSCSSFunctionRule `json:"cssFunctionRules,omitempty,omitzero"`
}

// CSSGetMatchedStylesForNode creates a new CSSGetMatchedStylesForNodeParams.
func CSSGetMatchedStylesForNode(nodeID NodeID) *CSSGetMatchedStylesForNodeParams {
	return &CSSGetMatchedStylesForNodeParams{
		NodeID: nodeID,
	}
}

// Do executes CSS.getMatchedStylesForNode.
func (p *CSSGetMatchedStylesForNodeParams) Do(ctx context.Context) (*CSSGetMatchedStylesForNodeReturns, error) {
	var res CSSGetMatchedStylesForNodeReturns
	if err := Execute(ctx, CSSCommandGetMatchedStylesForNode, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSGetEnvironmentVariablesParams Returns the values of the default UA-defined environment variables used in env()
type CSSGetEnvironmentVariablesParams struct{}

// CSSGetEnvironmentVariablesReturns holds the return values for getEnvironmentVariables.
type CSSGetEnvironmentVariablesReturns struct {
	EnvironmentVariables json.RawMessage `json:"environmentVariables"`
}

// CSSGetEnvironmentVariables creates a new CSSGetEnvironmentVariablesParams.
func CSSGetEnvironmentVariables() *CSSGetEnvironmentVariablesParams {
	return &CSSGetEnvironmentVariablesParams{}
}

// Do executes CSS.getEnvironmentVariables.
func (p *CSSGetEnvironmentVariablesParams) Do(ctx context.Context) (*CSSGetEnvironmentVariablesReturns, error) {
	var res CSSGetEnvironmentVariablesReturns
	if err := Execute(ctx, CSSCommandGetEnvironmentVariables, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSGetMediaQueriesParams Returns all media queries parsed by the rendering engine.
type CSSGetMediaQueriesParams struct{}

// CSSGetMediaQueriesReturns holds the return values for getMediaQueries.
type CSSGetMediaQueriesReturns struct {
	Medias []CSSCSSMedia `json:"medias"`
}

// CSSGetMediaQueries creates a new CSSGetMediaQueriesParams.
func CSSGetMediaQueries() *CSSGetMediaQueriesParams {
	return &CSSGetMediaQueriesParams{}
}

// Do executes CSS.getMediaQueries.
func (p *CSSGetMediaQueriesParams) Do(ctx context.Context) (*CSSGetMediaQueriesReturns, error) {
	var res CSSGetMediaQueriesReturns
	if err := Execute(ctx, CSSCommandGetMediaQueries, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSGetPlatformFontsForNodeParams Requests information about platform fonts which we used to render child TextNodes in the given
// node.
type CSSGetPlatformFontsForNodeParams struct {
	NodeID NodeID `json:"nodeId"`
}

// CSSGetPlatformFontsForNodeReturns holds the return values for getPlatformFontsForNode.
type CSSGetPlatformFontsForNodeReturns struct {
	// Fonts Usage statistics for every employed platform font.
	Fonts []CSSPlatformFontUsage `json:"fonts"`
}

// CSSGetPlatformFontsForNode creates a new CSSGetPlatformFontsForNodeParams.
func CSSGetPlatformFontsForNode(nodeID NodeID) *CSSGetPlatformFontsForNodeParams {
	return &CSSGetPlatformFontsForNodeParams{
		NodeID: nodeID,
	}
}

// Do executes CSS.getPlatformFontsForNode.
func (p *CSSGetPlatformFontsForNodeParams) Do(ctx context.Context) (*CSSGetPlatformFontsForNodeReturns, error) {
	var res CSSGetPlatformFontsForNodeReturns
	if err := Execute(ctx, CSSCommandGetPlatformFontsForNode, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSGetStyleSheetTextParams Returns the current textual content for a stylesheet.
type CSSGetStyleSheetTextParams struct {
	StyleSheetID DOMStyleSheetID `json:"styleSheetId"`
}

// CSSGetStyleSheetTextReturns holds the return values for getStyleSheetText.
type CSSGetStyleSheetTextReturns struct {
	// Text The stylesheet text.
	Text string `json:"text"`
}

// CSSGetStyleSheetText creates a new CSSGetStyleSheetTextParams.
func CSSGetStyleSheetText(styleSheetID DOMStyleSheetID) *CSSGetStyleSheetTextParams {
	return &CSSGetStyleSheetTextParams{
		StyleSheetID: styleSheetID,
	}
}

// Do executes CSS.getStyleSheetText.
func (p *CSSGetStyleSheetTextParams) Do(ctx context.Context) (*CSSGetStyleSheetTextReturns, error) {
	var res CSSGetStyleSheetTextReturns
	if err := Execute(ctx, CSSCommandGetStyleSheetText, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSGetLayersForNodeParams Returns all layers parsed by the rendering engine for the tree scope of a node.
// Given a DOM element identified by nodeId, getLayersForNode returns the root
// layer for the nearest ancestor document or shadow root. The layer root contains
// the full layer tree for the tree scope and their ordering.
type CSSGetLayersForNodeParams struct {
	NodeID NodeID `json:"nodeId"`
}

// CSSGetLayersForNodeReturns holds the return values for getLayersForNode.
type CSSGetLayersForNodeReturns struct {
	RootLayer CSSCSSLayerData `json:"rootLayer"`
}

// CSSGetLayersForNode creates a new CSSGetLayersForNodeParams.
func CSSGetLayersForNode(nodeID NodeID) *CSSGetLayersForNodeParams {
	return &CSSGetLayersForNodeParams{
		NodeID: nodeID,
	}
}

// Do executes CSS.getLayersForNode.
func (p *CSSGetLayersForNodeParams) Do(ctx context.Context) (*CSSGetLayersForNodeReturns, error) {
	var res CSSGetLayersForNodeReturns
	if err := Execute(ctx, CSSCommandGetLayersForNode, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSGetLocationForSelectorParams Given a CSS selector text and a style sheet ID, getLocationForSelector
// returns an array of locations of the CSS selector in the style sheet.
type CSSGetLocationForSelectorParams struct {
	StyleSheetID DOMStyleSheetID `json:"styleSheetId"`
	SelectorText string          `json:"selectorText"`
}

// CSSGetLocationForSelectorReturns holds the return values for getLocationForSelector.
type CSSGetLocationForSelectorReturns struct {
	Ranges []CSSSourceRange `json:"ranges"`
}

// CSSGetLocationForSelector creates a new CSSGetLocationForSelectorParams.
func CSSGetLocationForSelector(styleSheetID DOMStyleSheetID, selectorText string) *CSSGetLocationForSelectorParams {
	return &CSSGetLocationForSelectorParams{
		StyleSheetID: styleSheetID,
		SelectorText: selectorText,
	}
}

// Do executes CSS.getLocationForSelector.
func (p *CSSGetLocationForSelectorParams) Do(ctx context.Context) (*CSSGetLocationForSelectorReturns, error) {
	var res CSSGetLocationForSelectorReturns
	if err := Execute(ctx, CSSCommandGetLocationForSelector, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSTrackComputedStyleUpdatesForNodeParams Starts tracking the given node for the computed style updates
// and whenever the computed style is updated for node, it queues
// a `computedStyleUpdated` event with throttling.
// There can only be 1 node tracked for computed style updates
// so passing a new node id removes tracking from the previous node.
// Pass `undefined` to disable tracking.
type CSSTrackComputedStyleUpdatesForNodeParams struct {
	NodeID NodeID `json:"nodeId,omitempty,omitzero"`
}

// CSSTrackComputedStyleUpdatesForNode creates a new CSSTrackComputedStyleUpdatesForNodeParams.
func CSSTrackComputedStyleUpdatesForNode() *CSSTrackComputedStyleUpdatesForNodeParams {
	return &CSSTrackComputedStyleUpdatesForNodeParams{}
}

// WithNodeID sets the nodeId parameter.
func (p *CSSTrackComputedStyleUpdatesForNodeParams) WithNodeID(nodeID NodeID) *CSSTrackComputedStyleUpdatesForNodeParams {
	p.NodeID = nodeID
	return p
}

// Do executes CSS.trackComputedStyleUpdatesForNode.
func (p *CSSTrackComputedStyleUpdatesForNodeParams) Do(ctx context.Context) error {
	return Execute(ctx, CSSCommandTrackComputedStyleUpdatesForNode, p, nil)
}

// CSSTrackComputedStyleUpdatesParams Starts tracking the given computed styles for updates. The specified array of properties
// replaces the one previously specified. Pass empty array to disable tracking.
// Use takeComputedStyleUpdates to retrieve the list of nodes that had properties modified.
// The changes to computed style properties are only tracked for nodes pushed to the front-end
// by the DOM agent. If no changes to the tracked properties occur after the node has been pushed
// to the front-end, no updates will be issued for the node.
type CSSTrackComputedStyleUpdatesParams struct {
	PropertiesToTrack []CSSCSSComputedStyleProperty `json:"propertiesToTrack"`
}

// CSSTrackComputedStyleUpdates creates a new CSSTrackComputedStyleUpdatesParams.
func CSSTrackComputedStyleUpdates(propertiesToTrack []CSSCSSComputedStyleProperty) *CSSTrackComputedStyleUpdatesParams {
	return &CSSTrackComputedStyleUpdatesParams{
		PropertiesToTrack: propertiesToTrack,
	}
}

// Do executes CSS.trackComputedStyleUpdates.
func (p *CSSTrackComputedStyleUpdatesParams) Do(ctx context.Context) error {
	return Execute(ctx, CSSCommandTrackComputedStyleUpdates, p, nil)
}

// CSSTakeComputedStyleUpdatesParams Polls the next batch of computed style updates.
type CSSTakeComputedStyleUpdatesParams struct{}

// CSSTakeComputedStyleUpdatesReturns holds the return values for takeComputedStyleUpdates.
type CSSTakeComputedStyleUpdatesReturns struct {
	// NodeIds The list of node Ids that have their tracked computed styles updated.
	NodeIds []NodeID `json:"nodeIds"`
}

// CSSTakeComputedStyleUpdates creates a new CSSTakeComputedStyleUpdatesParams.
func CSSTakeComputedStyleUpdates() *CSSTakeComputedStyleUpdatesParams {
	return &CSSTakeComputedStyleUpdatesParams{}
}

// Do executes CSS.takeComputedStyleUpdates.
func (p *CSSTakeComputedStyleUpdatesParams) Do(ctx context.Context) (*CSSTakeComputedStyleUpdatesReturns, error) {
	var res CSSTakeComputedStyleUpdatesReturns
	if err := Execute(ctx, CSSCommandTakeComputedStyleUpdates, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSSetEffectivePropertyValueForNodeParams Find a rule with the given active property for the given node and set the new value for this
// property
type CSSSetEffectivePropertyValueForNodeParams struct {
	// NodeID The element id for which to set property.
	NodeID       NodeID `json:"nodeId"`
	PropertyName string `json:"propertyName"`
	Value        string `json:"value"`
}

// CSSSetEffectivePropertyValueForNode creates a new CSSSetEffectivePropertyValueForNodeParams.
func CSSSetEffectivePropertyValueForNode(nodeID NodeID, propertyName string, value string) *CSSSetEffectivePropertyValueForNodeParams {
	return &CSSSetEffectivePropertyValueForNodeParams{
		NodeID:       nodeID,
		PropertyName: propertyName,
		Value:        value,
	}
}

// Do executes CSS.setEffectivePropertyValueForNode.
func (p *CSSSetEffectivePropertyValueForNodeParams) Do(ctx context.Context) error {
	return Execute(ctx, CSSCommandSetEffectivePropertyValueForNode, p, nil)
}

// CSSSetPropertyRulePropertyNameParams Modifies the property rule property name.
type CSSSetPropertyRulePropertyNameParams struct {
	StyleSheetID DOMStyleSheetID `json:"styleSheetId"`
	Range        CSSSourceRange  `json:"range"`
	PropertyName string          `json:"propertyName"`
}

// CSSSetPropertyRulePropertyNameReturns holds the return values for setPropertyRulePropertyName.
type CSSSetPropertyRulePropertyNameReturns struct {
	// PropertyName The resulting key text after modification.
	PropertyName CSSValue `json:"propertyName"`
}

// CSSSetPropertyRulePropertyName creates a new CSSSetPropertyRulePropertyNameParams.
func CSSSetPropertyRulePropertyName(styleSheetID DOMStyleSheetID, rng CSSSourceRange, propertyName string) *CSSSetPropertyRulePropertyNameParams {
	return &CSSSetPropertyRulePropertyNameParams{
		StyleSheetID: styleSheetID,
		Range:        rng,
		PropertyName: propertyName,
	}
}

// Do executes CSS.setPropertyRulePropertyName.
func (p *CSSSetPropertyRulePropertyNameParams) Do(ctx context.Context) (*CSSSetPropertyRulePropertyNameReturns, error) {
	var res CSSSetPropertyRulePropertyNameReturns
	if err := Execute(ctx, CSSCommandSetPropertyRulePropertyName, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSSetKeyframeKeyParams Modifies the keyframe rule key text.
type CSSSetKeyframeKeyParams struct {
	StyleSheetID DOMStyleSheetID `json:"styleSheetId"`
	Range        CSSSourceRange  `json:"range"`
	KeyText      string          `json:"keyText"`
}

// CSSSetKeyframeKeyReturns holds the return values for setKeyframeKey.
type CSSSetKeyframeKeyReturns struct {
	// KeyText The resulting key text after modification.
	KeyText CSSValue `json:"keyText"`
}

// CSSSetKeyframeKey creates a new CSSSetKeyframeKeyParams.
func CSSSetKeyframeKey(styleSheetID DOMStyleSheetID, rng CSSSourceRange, keyText string) *CSSSetKeyframeKeyParams {
	return &CSSSetKeyframeKeyParams{
		StyleSheetID: styleSheetID,
		Range:        rng,
		KeyText:      keyText,
	}
}

// Do executes CSS.setKeyframeKey.
func (p *CSSSetKeyframeKeyParams) Do(ctx context.Context) (*CSSSetKeyframeKeyReturns, error) {
	var res CSSSetKeyframeKeyReturns
	if err := Execute(ctx, CSSCommandSetKeyframeKey, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSSetMediaTextParams Modifies the rule selector.
type CSSSetMediaTextParams struct {
	StyleSheetID DOMStyleSheetID `json:"styleSheetId"`
	Range        CSSSourceRange  `json:"range"`
	Text         string          `json:"text"`
}

// CSSSetMediaTextReturns holds the return values for setMediaText.
type CSSSetMediaTextReturns struct {
	// Media The resulting CSS media rule after modification.
	Media CSSCSSMedia `json:"media"`
}

// CSSSetMediaText creates a new CSSSetMediaTextParams.
func CSSSetMediaText(styleSheetID DOMStyleSheetID, rng CSSSourceRange, text string) *CSSSetMediaTextParams {
	return &CSSSetMediaTextParams{
		StyleSheetID: styleSheetID,
		Range:        rng,
		Text:         text,
	}
}

// Do executes CSS.setMediaText.
func (p *CSSSetMediaTextParams) Do(ctx context.Context) (*CSSSetMediaTextReturns, error) {
	var res CSSSetMediaTextReturns
	if err := Execute(ctx, CSSCommandSetMediaText, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSSetContainerQueryTextParams Modifies the expression of a container query.
type CSSSetContainerQueryTextParams struct {
	StyleSheetID DOMStyleSheetID `json:"styleSheetId"`
	Range        CSSSourceRange  `json:"range"`
	Text         string          `json:"text"`
}

// CSSSetContainerQueryTextReturns holds the return values for setContainerQueryText.
type CSSSetContainerQueryTextReturns struct {
	// ContainerQuery The resulting CSS container query rule after modification.
	ContainerQuery CSSCSSContainerQuery `json:"containerQuery"`
}

// CSSSetContainerQueryText creates a new CSSSetContainerQueryTextParams.
func CSSSetContainerQueryText(styleSheetID DOMStyleSheetID, rng CSSSourceRange, text string) *CSSSetContainerQueryTextParams {
	return &CSSSetContainerQueryTextParams{
		StyleSheetID: styleSheetID,
		Range:        rng,
		Text:         text,
	}
}

// Do executes CSS.setContainerQueryText.
func (p *CSSSetContainerQueryTextParams) Do(ctx context.Context) (*CSSSetContainerQueryTextReturns, error) {
	var res CSSSetContainerQueryTextReturns
	if err := Execute(ctx, CSSCommandSetContainerQueryText, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSSetSupportsTextParams Modifies the expression of a supports at-rule.
type CSSSetSupportsTextParams struct {
	StyleSheetID DOMStyleSheetID `json:"styleSheetId"`
	Range        CSSSourceRange  `json:"range"`
	Text         string          `json:"text"`
}

// CSSSetSupportsTextReturns holds the return values for setSupportsText.
type CSSSetSupportsTextReturns struct {
	// Supports The resulting CSS Supports rule after modification.
	Supports CSSCSSSupports `json:"supports"`
}

// CSSSetSupportsText creates a new CSSSetSupportsTextParams.
func CSSSetSupportsText(styleSheetID DOMStyleSheetID, rng CSSSourceRange, text string) *CSSSetSupportsTextParams {
	return &CSSSetSupportsTextParams{
		StyleSheetID: styleSheetID,
		Range:        rng,
		Text:         text,
	}
}

// Do executes CSS.setSupportsText.
func (p *CSSSetSupportsTextParams) Do(ctx context.Context) (*CSSSetSupportsTextReturns, error) {
	var res CSSSetSupportsTextReturns
	if err := Execute(ctx, CSSCommandSetSupportsText, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSSetNavigationTextParams Modifies the expression of a navigation at-rule.
type CSSSetNavigationTextParams struct {
	StyleSheetID DOMStyleSheetID `json:"styleSheetId"`
	Range        CSSSourceRange  `json:"range"`
	Text         string          `json:"text"`
}

// CSSSetNavigationTextReturns holds the return values for setNavigationText.
type CSSSetNavigationTextReturns struct {
	// Navigation The resulting CSS Navigation rule after modification.
	Navigation CSSCSSNavigation `json:"navigation"`
}

// CSSSetNavigationText creates a new CSSSetNavigationTextParams.
func CSSSetNavigationText(styleSheetID DOMStyleSheetID, rng CSSSourceRange, text string) *CSSSetNavigationTextParams {
	return &CSSSetNavigationTextParams{
		StyleSheetID: styleSheetID,
		Range:        rng,
		Text:         text,
	}
}

// Do executes CSS.setNavigationText.
func (p *CSSSetNavigationTextParams) Do(ctx context.Context) (*CSSSetNavigationTextReturns, error) {
	var res CSSSetNavigationTextReturns
	if err := Execute(ctx, CSSCommandSetNavigationText, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSSetScopeTextParams Modifies the expression of a scope at-rule.
type CSSSetScopeTextParams struct {
	StyleSheetID DOMStyleSheetID `json:"styleSheetId"`
	Range        CSSSourceRange  `json:"range"`
	Text         string          `json:"text"`
}

// CSSSetScopeTextReturns holds the return values for setScopeText.
type CSSSetScopeTextReturns struct {
	// Scope The resulting CSS Scope rule after modification.
	Scope CSSCSSScope `json:"scope"`
}

// CSSSetScopeText creates a new CSSSetScopeTextParams.
func CSSSetScopeText(styleSheetID DOMStyleSheetID, rng CSSSourceRange, text string) *CSSSetScopeTextParams {
	return &CSSSetScopeTextParams{
		StyleSheetID: styleSheetID,
		Range:        rng,
		Text:         text,
	}
}

// Do executes CSS.setScopeText.
func (p *CSSSetScopeTextParams) Do(ctx context.Context) (*CSSSetScopeTextReturns, error) {
	var res CSSSetScopeTextReturns
	if err := Execute(ctx, CSSCommandSetScopeText, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSSetRuleSelectorParams Modifies the rule selector.
type CSSSetRuleSelectorParams struct {
	StyleSheetID DOMStyleSheetID `json:"styleSheetId"`
	Range        CSSSourceRange  `json:"range"`
	Selector     string          `json:"selector"`
}

// CSSSetRuleSelectorReturns holds the return values for setRuleSelector.
type CSSSetRuleSelectorReturns struct {
	// SelectorList The resulting selector list after modification.
	SelectorList CSSSelectorList `json:"selectorList"`
}

// CSSSetRuleSelector creates a new CSSSetRuleSelectorParams.
func CSSSetRuleSelector(styleSheetID DOMStyleSheetID, rng CSSSourceRange, selector string) *CSSSetRuleSelectorParams {
	return &CSSSetRuleSelectorParams{
		StyleSheetID: styleSheetID,
		Range:        rng,
		Selector:     selector,
	}
}

// Do executes CSS.setRuleSelector.
func (p *CSSSetRuleSelectorParams) Do(ctx context.Context) (*CSSSetRuleSelectorReturns, error) {
	var res CSSSetRuleSelectorReturns
	if err := Execute(ctx, CSSCommandSetRuleSelector, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSSetStyleSheetTextParams Sets the new stylesheet text.
type CSSSetStyleSheetTextParams struct {
	StyleSheetID DOMStyleSheetID `json:"styleSheetId"`
	Text         string          `json:"text"`
}

// CSSSetStyleSheetTextReturns holds the return values for setStyleSheetText.
type CSSSetStyleSheetTextReturns struct {
	// SourceMapURL URL of source map associated with script (if any).
	SourceMapURL string `json:"sourceMapURL,omitempty,omitzero"`
}

// CSSSetStyleSheetText creates a new CSSSetStyleSheetTextParams.
func CSSSetStyleSheetText(styleSheetID DOMStyleSheetID, text string) *CSSSetStyleSheetTextParams {
	return &CSSSetStyleSheetTextParams{
		StyleSheetID: styleSheetID,
		Text:         text,
	}
}

// Do executes CSS.setStyleSheetText.
func (p *CSSSetStyleSheetTextParams) Do(ctx context.Context) (*CSSSetStyleSheetTextReturns, error) {
	var res CSSSetStyleSheetTextReturns
	if err := Execute(ctx, CSSCommandSetStyleSheetText, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSSetStyleTextsParams Applies specified style edits one after another in the given order.
type CSSSetStyleTextsParams struct {
	Edits []CSSStyleDeclarationEdit `json:"edits"`
	// NodeForPropertySyntaxValidation NodeId for the DOM node in whose context custom property declarations for registered properties should be
	// validated. If omitted, declarations in the new rule text can only be validated statically, which may produce
	// incorrect results if the declaration contains a var() for example.
	NodeForPropertySyntaxValidation NodeID `json:"nodeForPropertySyntaxValidation,omitempty,omitzero"`
}

// CSSSetStyleTextsReturns holds the return values for setStyleTexts.
type CSSSetStyleTextsReturns struct {
	// Styles The resulting styles after modification.
	Styles []CSSCSSStyle `json:"styles"`
}

// CSSSetStyleTexts creates a new CSSSetStyleTextsParams.
func CSSSetStyleTexts(edits []CSSStyleDeclarationEdit) *CSSSetStyleTextsParams {
	return &CSSSetStyleTextsParams{
		Edits: edits,
	}
}

// WithNodeForPropertySyntaxValidation sets the nodeForPropertySyntaxValidation parameter.
func (p *CSSSetStyleTextsParams) WithNodeForPropertySyntaxValidation(nodeForPropertySyntaxValidation NodeID) *CSSSetStyleTextsParams {
	p.NodeForPropertySyntaxValidation = nodeForPropertySyntaxValidation
	return p
}

// Do executes CSS.setStyleTexts.
func (p *CSSSetStyleTextsParams) Do(ctx context.Context) (*CSSSetStyleTextsReturns, error) {
	var res CSSSetStyleTextsReturns
	if err := Execute(ctx, CSSCommandSetStyleTexts, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSStartRuleUsageTrackingParams Enables the selector recording.
type CSSStartRuleUsageTrackingParams struct{}

// CSSStartRuleUsageTracking creates a new CSSStartRuleUsageTrackingParams.
func CSSStartRuleUsageTracking() *CSSStartRuleUsageTrackingParams {
	return &CSSStartRuleUsageTrackingParams{}
}

// Do executes CSS.startRuleUsageTracking.
func (p *CSSStartRuleUsageTrackingParams) Do(ctx context.Context) error {
	return Execute(ctx, CSSCommandStartRuleUsageTracking, p, nil)
}

// CSSStopRuleUsageTrackingParams Stop tracking rule usage and return the list of rules that were used since last call to
// `takeCoverageDelta` (or since start of coverage instrumentation).
type CSSStopRuleUsageTrackingParams struct{}

// CSSStopRuleUsageTrackingReturns holds the return values for stopRuleUsageTracking.
type CSSStopRuleUsageTrackingReturns struct {
	RuleUsage []CSSRuleUsage `json:"ruleUsage"`
}

// CSSStopRuleUsageTracking creates a new CSSStopRuleUsageTrackingParams.
func CSSStopRuleUsageTracking() *CSSStopRuleUsageTrackingParams {
	return &CSSStopRuleUsageTrackingParams{}
}

// Do executes CSS.stopRuleUsageTracking.
func (p *CSSStopRuleUsageTrackingParams) Do(ctx context.Context) (*CSSStopRuleUsageTrackingReturns, error) {
	var res CSSStopRuleUsageTrackingReturns
	if err := Execute(ctx, CSSCommandStopRuleUsageTracking, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSTakeCoverageDeltaParams Obtain list of rules that became used since last call to this method (or since start of coverage
// instrumentation).
type CSSTakeCoverageDeltaParams struct{}

// CSSTakeCoverageDeltaReturns holds the return values for takeCoverageDelta.
type CSSTakeCoverageDeltaReturns struct {
	Coverage []CSSRuleUsage `json:"coverage"`
	// Timestamp Monotonically increasing time, in seconds.
	Timestamp float64 `json:"timestamp"`
}

// CSSTakeCoverageDelta creates a new CSSTakeCoverageDeltaParams.
func CSSTakeCoverageDelta() *CSSTakeCoverageDeltaParams {
	return &CSSTakeCoverageDeltaParams{}
}

// Do executes CSS.takeCoverageDelta.
func (p *CSSTakeCoverageDeltaParams) Do(ctx context.Context) (*CSSTakeCoverageDeltaReturns, error) {
	var res CSSTakeCoverageDeltaReturns
	if err := Execute(ctx, CSSCommandTakeCoverageDelta, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CSSSetLocalFontsEnabledParams Enables/disables rendering of local CSS fonts (enabled by default).
type CSSSetLocalFontsEnabledParams struct {
	// Enabled Whether rendering of local fonts is enabled.
	Enabled bool `json:"enabled"`
}

// CSSSetLocalFontsEnabled creates a new CSSSetLocalFontsEnabledParams.
func CSSSetLocalFontsEnabled(enabled bool) *CSSSetLocalFontsEnabledParams {
	return &CSSSetLocalFontsEnabledParams{
		Enabled: enabled,
	}
}

// Do executes CSS.setLocalFontsEnabled.
func (p *CSSSetLocalFontsEnabledParams) Do(ctx context.Context) error {
	return Execute(ctx, CSSCommandSetLocalFontsEnabled, p, nil)
}

// CSS command names.
const (
	CSSCommandAddRule                          Method = "CSS.addRule"
	CSSCommandCollectClassNames                Method = "CSS.collectClassNames"
	CSSCommandCreateStyleSheet                 Method = "CSS.createStyleSheet"
	CSSCommandDisable                          Method = "CSS.disable"
	CSSCommandEnable                           Method = "CSS.enable"
	CSSCommandForcePseudoState                 Method = "CSS.forcePseudoState"
	CSSCommandForceStartingStyle               Method = "CSS.forceStartingStyle"
	CSSCommandGetBackgroundColors              Method = "CSS.getBackgroundColors"
	CSSCommandGetComputedStyleForNode          Method = "CSS.getComputedStyleForNode"
	CSSCommandResolveValues                    Method = "CSS.resolveValues"
	CSSCommandGetLonghandProperties            Method = "CSS.getLonghandProperties"
	CSSCommandGetInlineStylesForNode           Method = "CSS.getInlineStylesForNode"
	CSSCommandGetAnimatedStylesForNode         Method = "CSS.getAnimatedStylesForNode"
	CSSCommandGetMatchedStylesForNode          Method = "CSS.getMatchedStylesForNode"
	CSSCommandGetEnvironmentVariables          Method = "CSS.getEnvironmentVariables"
	CSSCommandGetMediaQueries                  Method = "CSS.getMediaQueries"
	CSSCommandGetPlatformFontsForNode          Method = "CSS.getPlatformFontsForNode"
	CSSCommandGetStyleSheetText                Method = "CSS.getStyleSheetText"
	CSSCommandGetLayersForNode                 Method = "CSS.getLayersForNode"
	CSSCommandGetLocationForSelector           Method = "CSS.getLocationForSelector"
	CSSCommandTrackComputedStyleUpdatesForNode Method = "CSS.trackComputedStyleUpdatesForNode"
	CSSCommandTrackComputedStyleUpdates        Method = "CSS.trackComputedStyleUpdates"
	CSSCommandTakeComputedStyleUpdates         Method = "CSS.takeComputedStyleUpdates"
	CSSCommandSetEffectivePropertyValueForNode Method = "CSS.setEffectivePropertyValueForNode"
	CSSCommandSetPropertyRulePropertyName      Method = "CSS.setPropertyRulePropertyName"
	CSSCommandSetKeyframeKey                   Method = "CSS.setKeyframeKey"
	CSSCommandSetMediaText                     Method = "CSS.setMediaText"
	CSSCommandSetContainerQueryText            Method = "CSS.setContainerQueryText"
	CSSCommandSetSupportsText                  Method = "CSS.setSupportsText"
	CSSCommandSetNavigationText                Method = "CSS.setNavigationText"
	CSSCommandSetScopeText                     Method = "CSS.setScopeText"
	CSSCommandSetRuleSelector                  Method = "CSS.setRuleSelector"
	CSSCommandSetStyleSheetText                Method = "CSS.setStyleSheetText"
	CSSCommandSetStyleTexts                    Method = "CSS.setStyleTexts"
	CSSCommandStartRuleUsageTracking           Method = "CSS.startRuleUsageTracking"
	CSSCommandStopRuleUsageTracking            Method = "CSS.stopRuleUsageTracking"
	CSSCommandTakeCoverageDelta                Method = "CSS.takeCoverageDelta"
	CSSCommandSetLocalFontsEnabled             Method = "CSS.setLocalFontsEnabled"
)
