// Code generated by bonkgen. DO NOT EDIT.

package proto

// DeviceAccessDeviceID A device id.
type DeviceAccessDeviceID string

// String returns the DeviceAccessDeviceID as a string.
func (t DeviceAccessDeviceID) String() string {
	return string(t)
}

// DeviceAccessPromptDevice Device information displayed in a user prompt to select a device.
type DeviceAccessPromptDevice struct {
	ID DeviceAccessDeviceID `json:"id"`
	// Name Display name as it appears in a device request user prompt.
	Name string `json:"name"`
}
