// Code generated by bonkgen. DO NOT EDIT.

package proto

import "context"

// DeviceOrientationClearDeviceOrientationOverrideParams Clears the overridden Device Orientation.
type DeviceOrientationClearDeviceOrientationOverrideParams struct{}

// DeviceOrientationClearDeviceOrientationOverride creates a new DeviceOrientationClearDeviceOrientationOverrideParams.
func DeviceOrientationClearDeviceOrientationOverride() *DeviceOrientationClearDeviceOrientationOverrideParams {
	return &DeviceOrientationClearDeviceOrientationOverrideParams{}
}

// Do executes DeviceOrientation.clearDeviceOrientationOverride.
func (p *DeviceOrientationClearDeviceOrientationOverrideParams) Do(ctx context.Context) error {
	return Execute(ctx, DeviceOrientationCommandClearDeviceOrientationOverride, p, nil)
}

// DeviceOrientationSetDeviceOrientationOverrideParams Overrides the Device Orientation.
type DeviceOrientationSetDeviceOrientationOverrideParams struct {
	// Alpha Mock alpha
	Alpha float64 `json:"alpha"`
	// Beta Mock beta
	Beta float64 `json:"beta"`
	// Gamma Mock gamma
	Gamma float64 `json:"gamma"`
}

// DeviceOrientationSetDeviceOrientationOverride creates a new DeviceOrientationSetDeviceOrientationOverrideParams.
func DeviceOrientationSetDeviceOrientationOverride(alpha float64, beta float64, gamma float64) *DeviceOrientationSetDeviceOrientationOverrideParams {
	return &DeviceOrientationSetDeviceOrientationOverrideParams{
		Alpha: alpha,
		Beta:  beta,
		Gamma: gamma,
	}
}

// Do executes DeviceOrientation.setDeviceOrientationOverride.
func (p *DeviceOrientationSetDeviceOrientationOverrideParams) Do(ctx context.Context) error {
	return Execute(ctx, DeviceOrientationCommandSetDeviceOrientationOverride, p, nil)
}

// DeviceOrientation command names.
const (
	DeviceOrientationCommandClearDeviceOrientationOverride Method = "DeviceOrientation.clearDeviceOrientationOverride"
	DeviceOrientationCommandSetDeviceOrientationOverride   Method = "DeviceOrientation.setDeviceOrientationOverride"
)
