// Code generated by bonkgen. DO NOT EDIT.

package proto

import "context"

// DOMCollectClassNamesFromSubtreeParams Collects class names for the node with given id and all of it's child nodes.
type DOMCollectClassNamesFromSubtreeParams struct {
	// NodeID Id of the node to collect class names.
	NodeID NodeID `json:"nodeId"`
}

// DOMCollectClassNamesFromSubtreeReturns holds the return values for collectClassNamesFromSubtree.
type DOMCollectClassNamesFromSubtreeReturns struct {
	// ClassNames Class name list.
	ClassNames []string `json:"classNames"`
}

// DOMCollectClassNamesFromSubtree creates a new DOMCollectClassNamesFromSubtreeParams.
func DOMCollectClassNamesFromSubtree(nodeID NodeID) *DOMCollectClassNamesFromSubtreeParams {
	return &DOMCollectClassNamesFromSubtreeParams{
		NodeID: nodeID,
	}
}

// Do executes DOM.collectClassNamesFromSubtree.
func (p *DOMCollectClassNamesFromSubtreeParams) Do(ctx context.Context) (*DOMCollectClassNamesFromSubtreeReturns, error) {
	var res DOMCollectClassNamesFromSubtreeReturns
	if err := Execute(ctx, DOMCommandCollectClassNamesFromSubtree, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMCopyToParams Creates a deep copy of the specified node and places it into the target container before the
// given anchor.
type DOMCopyToParams struct {
	// NodeID Id of the node to copy.
	NodeID NodeID `json:"nodeId"`
	// TargetNodeID Id of the element to drop the copy into.
	TargetNodeID NodeID `json:"targetNodeId"`
	// InsertBeforeNodeID Drop the copy before this node (if absent, the copy becomes the last child of
	// `targetNodeId`).
	InsertBeforeNodeID NodeID `json:"insertBeforeNodeId,omitempty"`
}

// DOMCopyToReturns holds the return values for copyTo.
type DOMCopyToReturns struct {
	// NodeID Id of the node clone.
	NodeID NodeID `json:"nodeId"`
}

// DOMCopyTo creates a new DOMCopyToParams.
func DOMCopyTo(nodeID NodeID, targetNodeID NodeID) *DOMCopyToParams {
	return &DOMCopyToParams{
		NodeID:       nodeID,
		TargetNodeID: targetNodeID,
	}
}

// WithInsertBeforeNodeID sets the insertBeforeNodeId parameter.
func (p *DOMCopyToParams) WithInsertBeforeNodeID(insertBeforeNodeID NodeID) *DOMCopyToParams {
	p.InsertBeforeNodeID = insertBeforeNodeID
	return p
}

// Do executes DOM.copyTo.
func (p *DOMCopyToParams) Do(ctx context.Context) (*DOMCopyToReturns, error) {
	var res DOMCopyToReturns
	if err := Execute(ctx, DOMCommandCopyTo, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMDescribeNodeParams Describes node given its id, does not require domain to be enabled. Does not start tracking any
// objects, can be used for automation.
type DOMDescribeNodeParams struct {
	// NodeID Identifier of the node.
	NodeID NodeID `json:"nodeId,omitempty"`
	// BackendNodeID Identifier of the backend node.
	BackendNodeID BackendNodeID `json:"backendNodeId,omitempty"`
	// ObjectID JavaScript object id of the node wrapper.
	ObjectID RemoteObjectID `json:"objectId,omitempty"`
	// Depth The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the
	// entire subtree or provide an integer larger than 0.
	Depth int64 `json:"depth,omitempty"`
	// Pierce Whether or not iframes and shadow roots should be traversed when returning the subtree
	// (default is false).
	Pierce bool `json:"pierce,omitempty"`
}

// DOMDescribeNodeReturns holds the return values for describeNode.
type DOMDescribeNodeReturns struct {
	// Node Node description.
	Node DOMNode `json:"node"`
}

// DOMDescribeNode creates a new DOMDescribeNodeParams.
func DOMDescribeNode() *DOMDescribeNodeParams {
	return &DOMDescribeNodeParams{}
}

// WithNodeID sets the nodeId parameter.
func (p *DOMDescribeNodeParams) WithNodeID(nodeID NodeID) *DOMDescribeNodeParams {
	p.NodeID = nodeID
	return p
}

// WithBackendNodeID sets the backendNodeId parameter.
func (p *DOMDescribeNodeParams) WithBackendNodeID(backendNodeID BackendNodeID) *DOMDescribeNodeParams {
	p.BackendNodeID = backendNodeID
	return p
}

// WithObjectID sets the objectId parameter.
func (p *DOMDescribeNodeParams) WithObjectID(objectID RemoteObjectID) *DOMDescribeNodeParams {
	p.ObjectID = objectID
	return p
}

// WithDepth sets the depth parameter.
func (p *DOMDescribeNodeParams) WithDepth(depth int64) *DOMDescribeNodeParams {
	p.Depth = depth
	return p
}

// WithPierce sets the pierce parameter.
func (p *DOMDescribeNodeParams) WithPierce(pierce bool) *DOMDescribeNodeParams {
	p.Pierce = pierce
	return p
}

// Do executes DOM.describeNode.
func (p *DOMDescribeNodeParams) Do(ctx context.Context) (*DOMDescribeNodeReturns, error) {
	var res DOMDescribeNodeReturns
	if err := Execute(ctx, DOMCommandDescribeNode, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMScrollIntoViewIfNeededParams Scrolls the specified rect of the given node into view if not already visible.
// Note: exactly one between nodeId, backendNodeId and objectId should be passed
// to identify the node.
type DOMScrollIntoViewIfNeededParams struct {
	// NodeID Identifier of the node.
	NodeID NodeID `json:"nodeId,omitempty"`
	// BackendNodeID Identifier of the backend node.
	BackendNodeID BackendNodeID `json:"backendNodeId,omitempty"`
	// ObjectID JavaScript object id of the node wrapper.
	ObjectID RemoteObjectID `json:"objectId,omitempty"`
	// Rect The rect to be scrolled into view, relative to the node's border box, in CSS pixels.
	// When omitted, center of the node will be used, similar to Element.scrollIntoView.
	Rect DOMRect `json:"rect,omitempty"`
}

// DOMScrollIntoViewIfNeeded creates a new DOMScrollIntoViewIfNeededParams.
func DOMScrollIntoViewIfNeeded() *DOMScrollIntoViewIfNeededParams {
	return &DOMScrollIntoViewIfNeededParams{}
}

// WithNodeID sets the nodeId parameter.
func (p *DOMScrollIntoViewIfNeededParams) WithNodeID(nodeID NodeID) *DOMScrollIntoViewIfNeededParams {
	p.NodeID = nodeID
	return p
}

// WithBackendNodeID sets the backendNodeId parameter.
func (p *DOMScrollIntoViewIfNeededParams) WithBackendNodeID(backendNodeID BackendNodeID) *DOMScrollIntoViewIfNeededParams {
	p.BackendNodeID = backendNodeID
	return p
}

// WithObjectID sets the objectId parameter.
func (p *DOMScrollIntoViewIfNeededParams) WithObjectID(objectID RemoteObjectID) *DOMScrollIntoViewIfNeededParams {
	p.ObjectID = objectID
	return p
}

// WithRect sets the rect parameter.
func (p *DOMScrollIntoViewIfNeededParams) WithRect(rect DOMRect) *DOMScrollIntoViewIfNeededParams {
	p.Rect = rect
	return p
}

// Do executes DOM.scrollIntoViewIfNeeded.
func (p *DOMScrollIntoViewIfNeededParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandScrollIntoViewIfNeeded, p, nil)
}

// DOMDisableParams Disables DOM agent for the given page.
type DOMDisableParams struct{}

// DOMDisable creates a new DOMDisableParams.
func DOMDisable() *DOMDisableParams {
	return &DOMDisableParams{}
}

// Do executes DOM.disable.
func (p *DOMDisableParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandDisable, p, nil)
}

// DOMDiscardSearchResultsParams Discards search results from the session with the given id. `getSearchResults` should no longer
// be called for that search.
type DOMDiscardSearchResultsParams struct {
	// SearchID Unique search session identifier.
	SearchID string `json:"searchId"`
}

// DOMDiscardSearchResults creates a new DOMDiscardSearchResultsParams.
func DOMDiscardSearchResults(searchID string) *DOMDiscardSearchResultsParams {
	return &DOMDiscardSearchResultsParams{
		SearchID: searchID,
	}
}

// Do executes DOM.discardSearchResults.
func (p *DOMDiscardSearchResultsParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandDiscardSearchResults, p, nil)
}

// DOMEnableParams Enables DOM agent for the given page.
type DOMEnableParams struct {
	// IncludeWhitespace Whether to include whitespaces in the children array of returned Nodes.
	IncludeWhitespace DOMEnableIncludeWhitespace `json:"includeWhitespace,omitempty"`
}

// DOMEnable creates a new DOMEnableParams.
func DOMEnable() *DOMEnableParams {
	return &DOMEnableParams{}
}

// WithIncludeWhitespace sets the includeWhitespace parameter.
func (p *DOMEnableParams) WithIncludeWhitespace(includeWhitespace DOMEnableIncludeWhitespace) *DOMEnableParams {
	p.IncludeWhitespace = includeWhitespace
	return p
}

// Do executes DOM.enable.
func (p *DOMEnableParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandEnable, p, nil)
}

// DOMFocusParams Focuses the given element.
type DOMFocusParams struct {
	// NodeID Identifier of the node.
	NodeID NodeID `json:"nodeId,omitempty"`
	// BackendNodeID Identifier of the backend node.
	BackendNodeID BackendNodeID `json:"backendNodeId,omitempty"`
	// ObjectID JavaScript object id of the node wrapper.
	ObjectID RemoteObjectID `json:"objectId,omitempty"`
}

// DOMFocus creates a new DOMFocusParams.
func DOMFocus() *DOMFocusParams {
	return &DOMFocusParams{}
}

// WithNodeID sets the nodeId parameter.
func (p *DOMFocusParams) WithNodeID(nodeID NodeID) *DOMFocusParams {
	p.NodeID = nodeID
	return p
}

// WithBackendNodeID sets the backendNodeId parameter.
func (p *DOMFocusParams) WithBackendNodeID(backendNodeID BackendNodeID) *DOMFocusParams {
	p.BackendNodeID = backendNodeID
	return p
}

// WithObjectID sets the objectId parameter.
func (p *DOMFocusParams) WithObjectID(objectID RemoteObjectID) *DOMFocusParams {
	p.ObjectID = objectID
	return p
}

// Do executes DOM.focus.
func (p *DOMFocusParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandFocus, p, nil)
}

// DOMGetAttributesParams Returns attributes for the specified node.
type DOMGetAttributesParams struct {
	// NodeID Id of the node to retrieve attributes for.
	NodeID NodeID `json:"nodeId"`
}

// DOMGetAttributesReturns holds the return values for getAttributes.
type DOMGetAttributesReturns struct {
	// Attributes An interleaved array of node attribute names and values.
	Attributes []string `json:"attributes"`
}

// DOMGetAttributes creates a new DOMGetAttributesParams.
func DOMGetAttributes(nodeID NodeID) *DOMGetAttributesParams {
	return &DOMGetAttributesParams{
		NodeID: nodeID,
	}
}

// Do executes DOM.getAttributes.
func (p *DOMGetAttributesParams) Do(ctx context.Context) (*DOMGetAttributesReturns, error) {
	var res DOMGetAttributesReturns
	if err := Execute(ctx, DOMCommandGetAttributes, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMGetBoxModelParams Returns boxes for the given node.
type DOMGetBoxModelParams struct {
	// NodeID Identifier of the node.
	NodeID NodeID `json:"nodeId,omitempty"`
	// BackendNodeID Identifier of the backend node.
	BackendNodeID BackendNodeID `json:"backendNodeId,omitempty"`
	// ObjectID JavaScript object id of the node wrapper.
	ObjectID RemoteObjectID `json:"objectId,omitempty"`
}

// DOMGetBoxModelReturns holds the return values for getBoxModel.
type DOMGetBoxModelReturns struct {
	// Model Box model for the node.
	Model DOMBoxModel `json:"model"`
}

// DOMGetBoxModel creates a new DOMGetBoxModelParams.
func DOMGetBoxModel() *DOMGetBoxModelParams {
	return &DOMGetBoxModelParams{}
}

// WithNodeID sets the nodeId parameter.
func (p *DOMGetBoxModelParams) WithNodeID(nodeID NodeID) *DOMGetBoxModelParams {
	p.NodeID = nodeID
	return p
}

// WithBackendNodeID sets the backendNodeId parameter.
func (p *DOMGetBoxModelParams) WithBackendNodeID(backendNodeID BackendNodeID) *DOMGetBoxModelParams {
	p.BackendNodeID = backendNodeID
	return p
}

// WithObjectID sets the objectId parameter.
func (p *DOMGetBoxModelParams) WithObjectID(objectID RemoteObjectID) *DOMGetBoxModelParams {
	p.ObjectID = objectID
	return p
}

// Do executes DOM.getBoxModel.
func (p *DOMGetBoxModelParams) Do(ctx context.Context) (*DOMGetBoxModelReturns, error) {
	var res DOMGetBoxModelReturns
	if err := Execute(ctx, DOMCommandGetBoxModel, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMGetContentQuadsParams Returns quads that describe node position on the page. This method
// might return multiple quads for inline nodes.
type DOMGetContentQuadsParams struct {
	// NodeID Identifier of the node.
	NodeID NodeID `json:"nodeId,omitempty"`
	// BackendNodeID Identifier of the backend node.
	BackendNodeID BackendNodeID `json:"backendNodeId,omitempty"`
	// ObjectID JavaScript object id of the node wrapper.
	ObjectID RemoteObjectID `json:"objectId,omitempty"`
}

// DOMGetContentQuadsReturns holds the return values for getContentQuads.
type DOMGetContentQuadsReturns struct {
	// Quads Quads that describe node layout relative to viewport.
	Quads []DOMQuad `json:"quads"`
}

// DOMGetContentQuads creates a new DOMGetContentQuadsParams.
func DOMGetContentQuads() *DOMGetContentQuadsParams {
	return &DOMGetContentQuadsParams{}
}

// WithNodeID sets the nodeId parameter.
func (p *DOMGetContentQuadsParams) WithNodeID(nodeID NodeID) *DOMGetContentQuadsParams {
	p.NodeID = nodeID
	return p
}

// WithBackendNodeID sets the backendNodeId parameter.
func (p *DOMGetContentQuadsParams) WithBackendNodeID(backendNodeID BackendNodeID) *DOMGetContentQuadsParams {
	p.BackendNodeID = backendNodeID
	return p
}

// WithObjectID sets the objectId parameter.
func (p *DOMGetContentQuadsParams) WithObjectID(objectID RemoteObjectID) *DOMGetContentQuadsParams {
	p.ObjectID = objectID
	return p
}

// Do executes DOM.getContentQuads.
func (p *DOMGetContentQuadsParams) Do(ctx context.Context) (*DOMGetContentQuadsReturns, error) {
	var res DOMGetContentQuadsReturns
	if err := Execute(ctx, DOMCommandGetContentQuads, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMGetDocumentParams Returns the root DOM node (and optionally the subtree) to the caller.
// Implicitly enables the DOM domain events for the current target.
type DOMGetDocumentParams struct {
	// Depth The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the
	// entire subtree or provide an integer larger than 0.
	Depth int64 `json:"depth,omitempty"`
	// Pierce Whether or not iframes and shadow roots should be traversed when returning the subtree
	// (default is false).
	Pierce bool `json:"pierce,omitempty"`
}

// DOMGetDocumentReturns holds the return values for getDocument.
type DOMGetDocumentReturns struct {
	// Root Resulting node.
	Root DOMNode `json:"root"`
}

// DOMGetDocument creates a new DOMGetDocumentParams.
func DOMGetDocument() *DOMGetDocumentParams {
	return &DOMGetDocumentParams{}
}

// WithDepth sets the depth parameter.
func (p *DOMGetDocumentParams) WithDepth(depth int64) *DOMGetDocumentParams {
	p.Depth = depth
	return p
}

// WithPierce sets the pierce parameter.
func (p *DOMGetDocumentParams) WithPierce(pierce bool) *DOMGetDocumentParams {
	p.Pierce = pierce
	return p
}

// Do executes DOM.getDocument.
func (p *DOMGetDocumentParams) Do(ctx context.Context) (*DOMGetDocumentReturns, error) {
	var res DOMGetDocumentReturns
	if err := Execute(ctx, DOMCommandGetDocument, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMGetFlattenedDocumentParams Returns the root DOM node (and optionally the subtree) to the caller.
// Deprecated, as it is not designed to work well with the rest of the DOM agent.
// Use DOMSnapshot.captureSnapshot instead.
type DOMGetFlattenedDocumentParams struct {
	// Depth The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the
	// entire subtree or provide an integer larger than 0.
	Depth int64 `json:"depth,omitempty"`
	// Pierce Whether or not iframes and shadow roots should be traversed when returning the subtree
	// (default is false).
	Pierce bool `json:"pierce,omitempty"`
}

// DOMGetFlattenedDocumentReturns holds the return values for getFlattenedDocument.
type DOMGetFlattenedDocumentReturns struct {
	// Nodes Resulting node.
	Nodes []DOMNode `json:"nodes"`
}

// DOMGetFlattenedDocument creates a new DOMGetFlattenedDocumentParams.
func DOMGetFlattenedDocument() *DOMGetFlattenedDocumentParams {
	return &DOMGetFlattenedDocumentParams{}
}

// WithDepth sets the depth parameter.
func (p *DOMGetFlattenedDocumentParams) WithDepth(depth int64) *DOMGetFlattenedDocumentParams {
	p.Depth = depth
	return p
}

// WithPierce sets the pierce parameter.
func (p *DOMGetFlattenedDocumentParams) WithPierce(pierce bool) *DOMGetFlattenedDocumentParams {
	p.Pierce = pierce
	return p
}

// Do executes DOM.getFlattenedDocument.
func (p *DOMGetFlattenedDocumentParams) Do(ctx context.Context) (*DOMGetFlattenedDocumentReturns, error) {
	var res DOMGetFlattenedDocumentReturns
	if err := Execute(ctx, DOMCommandGetFlattenedDocument, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMGetNodesForSubtreeByStyleParams Finds nodes with a given computed style in a subtree.
type DOMGetNodesForSubtreeByStyleParams struct {
	// NodeID Node ID pointing to the root of a subtree.
	NodeID NodeID `json:"nodeId"`
	// ComputedStyles The style to filter nodes by (includes nodes if any of properties matches).
	ComputedStyles []DOMCSSComputedStyleProperty `json:"computedStyles"`
	// Pierce Whether or not iframes and shadow roots in the same target should be traversed when returning the
	// results (default is false).
	Pierce bool `json:"pierce,omitempty"`
}

// DOMGetNodesForSubtreeByStyleReturns holds the return values for getNodesForSubtreeByStyle.
type DOMGetNodesForSubtreeByStyleReturns struct {
	// NodeIds Resulting nodes.
	NodeIds []NodeID `json:"nodeIds"`
}

// DOMGetNodesForSubtreeByStyle creates a new DOMGetNodesForSubtreeByStyleParams.
func DOMGetNodesForSubtreeByStyle(nodeID NodeID, computedStyles []DOMCSSComputedStyleProperty) *DOMGetNodesForSubtreeByStyleParams {
	return &DOMGetNodesForSubtreeByStyleParams{
		NodeID:         nodeID,
		ComputedStyles: computedStyles,
	}
}

// WithPierce sets the pierce parameter.
func (p *DOMGetNodesForSubtreeByStyleParams) WithPierce(pierce bool) *DOMGetNodesForSubtreeByStyleParams {
	p.Pierce = pierce
	return p
}

// Do executes DOM.getNodesForSubtreeByStyle.
func (p *DOMGetNodesForSubtreeByStyleParams) Do(ctx context.Context) (*DOMGetNodesForSubtreeByStyleReturns, error) {
	var res DOMGetNodesForSubtreeByStyleReturns
	if err := Execute(ctx, DOMCommandGetNodesForSubtreeByStyle, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMGetNodeForLocationParams Returns node id at given location. Depending on whether DOM domain is enabled, nodeId is
// either returned or not.
type DOMGetNodeForLocationParams struct {
	// X X coordinate.
	X int64 `json:"x"`
	// Y Y coordinate.
	Y int64 `json:"y"`
	// IncludeUserAgentShadowDOM False to skip to the nearest non-UA shadow root ancestor (default: false).
	IncludeUserAgentShadowDOM bool `json:"includeUserAgentShadowDOM,omitempty"`
	// IgnorePointerEventsNone Whether to ignore pointer-events: none on elements and hit test them.
	IgnorePointerEventsNone bool `json:"ignorePointerEventsNone,omitempty"`
}

// DOMGetNodeForLocationReturns holds the return values for getNodeForLocation.
type DOMGetNodeForLocationReturns struct {
	// BackendNodeID Resulting node.
	BackendNodeID BackendNodeID `json:"backendNodeId"`
	// FrameID Frame this node belongs to.
	FrameID FrameID `json:"frameId"`
	// NodeID Id of the node at given coordinates, only when enabled and requested document.
	NodeID NodeID `json:"nodeId,omitempty"`
}

// DOMGetNodeForLocation creates a new DOMGetNodeForLocationParams.
func DOMGetNodeForLocation(x int64, y int64) *DOMGetNodeForLocationParams {
	return &DOMGetNodeForLocationParams{
		X: x,
		Y: y,
	}
}

// WithIncludeUserAgentShadowDOM sets the includeUserAgentShadowDOM parameter.
func (p *DOMGetNodeForLocationParams) WithIncludeUserAgentShadowDOM(includeUserAgentShadowDOM bool) *DOMGetNodeForLocationParams {
	p.IncludeUserAgentShadowDOM = includeUserAgentShadowDOM
	return p
}

// WithIgnorePointerEventsNone sets the ignorePointerEventsNone parameter.
func (p *DOMGetNodeForLocationParams) WithIgnorePointerEventsNone(ignorePointerEventsNone bool) *DOMGetNodeForLocationParams {
	p.IgnorePointerEventsNone = ignorePointerEventsNone
	return p
}

// Do executes DOM.getNodeForLocation.
func (p *DOMGetNodeForLocationParams) Do(ctx context.Context) (*DOMGetNodeForLocationReturns, error) {
	var res DOMGetNodeForLocationReturns
	if err := Execute(ctx, DOMCommandGetNodeForLocation, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMGetOuterHTMLParams Returns node's HTML markup.
type DOMGetOuterHTMLParams struct {
	// NodeID Identifier of the node.
	NodeID NodeID `json:"nodeId,omitempty"`
	// BackendNodeID Identifier of the backend node.
	BackendNodeID BackendNodeID `json:"backendNodeId,omitempty"`
	// ObjectID JavaScript object id of the node wrapper.
	ObjectID RemoteObjectID `json:"objectId,omitempty"`
	// IncludeShadowDOM Include all shadow roots. Equals to false if not specified.
	IncludeShadowDOM bool `json:"includeShadowDOM,omitempty"`
}

// DOMGetOuterHTMLReturns holds the return values for getOuterHTML.
type DOMGetOuterHTMLReturns struct {
	// OuterHTML Outer HTML markup.
	OuterHTML string `json:"outerHTML"`
}

// DOMGetOuterHTML creates a new DOMGetOuterHTMLParams.
func DOMGetOuterHTML() *DOMGetOuterHTMLParams {
	return &DOMGetOuterHTMLParams{}
}

// WithNodeID sets the nodeId parameter.
func (p *DOMGetOuterHTMLParams) WithNodeID(nodeID NodeID) *DOMGetOuterHTMLParams {
	p.NodeID = nodeID
	return p
}

// WithBackendNodeID sets the backendNodeId parameter.
func (p *DOMGetOuterHTMLParams) WithBackendNodeID(backendNodeID BackendNodeID) *DOMGetOuterHTMLParams {
	p.BackendNodeID = backendNodeID
	return p
}

// WithObjectID sets the objectId parameter.
func (p *DOMGetOuterHTMLParams) WithObjectID(objectID RemoteObjectID) *DOMGetOuterHTMLParams {
	p.ObjectID = objectID
	return p
}

// WithIncludeShadowDOM sets the includeShadowDOM parameter.
func (p *DOMGetOuterHTMLParams) WithIncludeShadowDOM(includeShadowDOM bool) *DOMGetOuterHTMLParams {
	p.IncludeShadowDOM = includeShadowDOM
	return p
}

// Do executes DOM.getOuterHTML.
func (p *DOMGetOuterHTMLParams) Do(ctx context.Context) (*DOMGetOuterHTMLReturns, error) {
	var res DOMGetOuterHTMLReturns
	if err := Execute(ctx, DOMCommandGetOuterHTML, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMGetRelayoutBoundaryParams Returns the id of the nearest ancestor that is a relayout boundary.
type DOMGetRelayoutBoundaryParams struct {
	// NodeID Id of the node.
	NodeID NodeID `json:"nodeId"`
}

// DOMGetRelayoutBoundaryReturns holds the return values for getRelayoutBoundary.
type DOMGetRelayoutBoundaryReturns struct {
	// NodeID Relayout boundary node id for the given node.
	NodeID NodeID `json:"nodeId"`
}

// DOMGetRelayoutBoundary creates a new DOMGetRelayoutBoundaryParams.
func DOMGetRelayoutBoundary(nodeID NodeID) *DOMGetRelayoutBoundaryParams {
	return &DOMGetRelayoutBoundaryParams{
		NodeID: nodeID,
	}
}

// Do executes DOM.getRelayoutBoundary.
func (p *DOMGetRelayoutBoundaryParams) Do(ctx context.Context) (*DOMGetRelayoutBoundaryReturns, error) {
	var res DOMGetRelayoutBoundaryReturns
	if err := Execute(ctx, DOMCommandGetRelayoutBoundary, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMGetSearchResultsParams Returns search results from given `fromIndex` to given `toIndex` from the search with the given
// identifier.
type DOMGetSearchResultsParams struct {
	// SearchID Unique search session identifier.
	SearchID string `json:"searchId"`
	// FromIndex Start index of the search result to be returned.
	FromIndex int64 `json:"fromIndex"`
	// ToIndex End index of the search result to be returned.
	ToIndex int64 `json:"toIndex"`
}

// DOMGetSearchResultsReturns holds the return values for getSearchResults.
type DOMGetSearchResultsReturns struct {
	// NodeIds Ids of the search result nodes.
	NodeIds []NodeID `json:"nodeIds"`
}

// DOMGetSearchResults creates a new DOMGetSearchResultsParams.
func DOMGetSearchResults(searchID string, fromIndex int64, toIndex int64) *DOMGetSearchResultsParams {
	return &DOMGetSearchResultsParams{
		SearchID:  searchID,
		FromIndex: fromIndex,
		ToIndex:   toIndex,
	}
}

// Do executes DOM.getSearchResults.
func (p *DOMGetSearchResultsParams) Do(ctx context.Context) (*DOMGetSearchResultsReturns, error) {
	var res DOMGetSearchResultsReturns
	if err := Execute(ctx, DOMCommandGetSearchResults, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMHideHighlightParams Hides any highlight.
type DOMHideHighlightParams struct{}

// DOMHideHighlight creates a new DOMHideHighlightParams.
func DOMHideHighlight() *DOMHideHighlightParams {
	return &DOMHideHighlightParams{}
}

// Do executes DOM.hideHighlight.
func (p *DOMHideHighlightParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandHideHighlight, p, nil)
}

// DOMHighlightNodeParams Highlights DOM node.
type DOMHighlightNodeParams struct{}

// DOMHighlightNode creates a new DOMHighlightNodeParams.
func DOMHighlightNode() *DOMHighlightNodeParams {
	return &DOMHighlightNodeParams{}
}

// Do executes DOM.highlightNode.
func (p *DOMHighlightNodeParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandHighlightNode, p, nil)
}

// DOMHighlightRectParams Highlights given rectangle.
type DOMHighlightRectParams struct{}

// DOMHighlightRect creates a new DOMHighlightRectParams.
func DOMHighlightRect() *DOMHighlightRectParams {
	return &DOMHighlightRectParams{}
}

// Do executes DOM.highlightRect.
func (p *DOMHighlightRectParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandHighlightRect, p, nil)
}

// DOMMarkUndoableStateParams Marks last undoable state.
type DOMMarkUndoableStateParams struct{}

// DOMMarkUndoableState creates a new DOMMarkUndoableStateParams.
func DOMMarkUndoableState() *DOMMarkUndoableStateParams {
	return &DOMMarkUndoableStateParams{}
}

// Do executes DOM.markUndoableState.
func (p *DOMMarkUndoableStateParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandMarkUndoableState, p, nil)
}

// DOMMoveToParams Moves node into the new container, places it before the given anchor.
type DOMMoveToParams struct {
	// NodeID Id of the node to move.
	NodeID NodeID `json:"nodeId"`
	// TargetNodeID Id of the element to drop the moved node into.
	TargetNodeID NodeID `json:"targetNodeId"`
	// InsertBeforeNodeID Drop node before this one (if absent, the moved node becomes the last child of
	// `targetNodeId`).
	InsertBeforeNodeID NodeID `json:"insertBeforeNodeId,omitempty"`
}

// DOMMoveToReturns holds the return values for moveTo.
type DOMMoveToReturns struct {
	// NodeID New id of the moved node.
	NodeID NodeID `json:"nodeId"`
}

// DOMMoveTo creates a new DOMMoveToParams.
func DOMMoveTo(nodeID NodeID, targetNodeID NodeID) *DOMMoveToParams {
	return &DOMMoveToParams{
		NodeID:       nodeID,
		TargetNodeID: targetNodeID,
	}
}

// WithInsertBeforeNodeID sets the insertBeforeNodeId parameter.
func (p *DOMMoveToParams) WithInsertBeforeNodeID(insertBeforeNodeID NodeID) *DOMMoveToParams {
	p.InsertBeforeNodeID = insertBeforeNodeID
	return p
}

// Do executes DOM.moveTo.
func (p *DOMMoveToParams) Do(ctx context.Context) (*DOMMoveToReturns, error) {
	var res DOMMoveToReturns
	if err := Execute(ctx, DOMCommandMoveTo, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMPerformSearchParams Searches for a given string in the DOM tree. Use `getSearchResults` to access search results or
// `cancelSearch` to end this search session.
type DOMPerformSearchParams struct {
	// Query Plain text or query selector or XPath search query.
	Query string `json:"query"`
	// IncludeUserAgentShadowDOM True to search in user agent shadow DOM.
	IncludeUserAgentShadowDOM bool `json:"includeUserAgentShadowDOM,omitempty"`
}

// DOMPerformSearchReturns holds the return values for performSearch.
type DOMPerformSearchReturns struct {
	// SearchID Unique search session identifier.
	SearchID string `json:"searchId"`
	// ResultCount Number of search results.
	ResultCount int64 `json:"resultCount"`
}

// DOMPerformSearch creates a new DOMPerformSearchParams.
func DOMPerformSearch(query string) *DOMPerformSearchParams {
	return &DOMPerformSearchParams{
		Query: query,
	}
}

// WithIncludeUserAgentShadowDOM sets the includeUserAgentShadowDOM parameter.
func (p *DOMPerformSearchParams) WithIncludeUserAgentShadowDOM(includeUserAgentShadowDOM bool) *DOMPerformSearchParams {
	p.IncludeUserAgentShadowDOM = includeUserAgentShadowDOM
	return p
}

// Do executes DOM.performSearch.
func (p *DOMPerformSearchParams) Do(ctx context.Context) (*DOMPerformSearchReturns, error) {
	var res DOMPerformSearchReturns
	if err := Execute(ctx, DOMCommandPerformSearch, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMPushNodeByPathToFrontendParams Requests that the node is sent to the caller given its path. // FIXME, use XPath
type DOMPushNodeByPathToFrontendParams struct {
	// Path Path to node in the proprietary format.
	Path string `json:"path"`
}

// DOMPushNodeByPathToFrontendReturns holds the return values for pushNodeByPathToFrontend.
type DOMPushNodeByPathToFrontendReturns struct {
	// NodeID Id of the node for given path.
	NodeID NodeID `json:"nodeId"`
}

// DOMPushNodeByPathToFrontend creates a new DOMPushNodeByPathToFrontendParams.
func DOMPushNodeByPathToFrontend(path string) *DOMPushNodeByPathToFrontendParams {
	return &DOMPushNodeByPathToFrontendParams{
		Path: path,
	}
}

// Do executes DOM.pushNodeByPathToFrontend.
func (p *DOMPushNodeByPathToFrontendParams) Do(ctx context.Context) (*DOMPushNodeByPathToFrontendReturns, error) {
	var res DOMPushNodeByPathToFrontendReturns
	if err := Execute(ctx, DOMCommandPushNodeByPathToFrontend, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMPushNodesByBackendIdsToFrontendParams Requests that a batch of nodes is sent to the caller given their backend node ids.
type DOMPushNodesByBackendIdsToFrontendParams struct {
	// BackendNodeIds The array of backend node ids.
	BackendNodeIds []BackendNodeID `json:"backendNodeIds"`
}

// DOMPushNodesByBackendIdsToFrontendReturns holds the return values for pushNodesByBackendIdsToFrontend.
type DOMPushNodesByBackendIdsToFrontendReturns struct {
	// NodeIds The array of ids of pushed nodes that correspond to the backend ids specified in
	// backendNodeIds.
	NodeIds []NodeID `json:"nodeIds"`
}

// DOMPushNodesByBackendIdsToFrontend creates a new DOMPushNodesByBackendIdsToFrontendParams.
func DOMPushNodesByBackendIdsToFrontend(backendNodeIds []BackendNodeID) *DOMPushNodesByBackendIdsToFrontendParams {
	return &DOMPushNodesByBackendIdsToFrontendParams{
		BackendNodeIds: backendNodeIds,
	}
}

// Do executes DOM.pushNodesByBackendIdsToFrontend.
func (p *DOMPushNodesByBackendIdsToFrontendParams) Do(ctx context.Context) (*DOMPushNodesByBackendIdsToFrontendReturns, error) {
	var res DOMPushNodesByBackendIdsToFrontendReturns
	if err := Execute(ctx, DOMCommandPushNodesByBackendIdsToFrontend, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMQuerySelectorParams Executes `querySelector` on a given node.
type DOMQuerySelectorParams struct {
	// NodeID Id of the node to query upon.
	NodeID NodeID `json:"nodeId"`
	// Selector Selector string.
	Selector string `json:"selector"`
}

// DOMQuerySelectorReturns holds the return values for querySelector.
type DOMQuerySelectorReturns struct {
	// NodeID Query selector result.
	NodeID NodeID `json:"nodeId"`
}

// DOMQuerySelector creates a new DOMQuerySelectorParams.
func DOMQuerySelector(nodeID NodeID, selector string) *DOMQuerySelectorParams {
	return &DOMQuerySelectorParams{
		NodeID:   nodeID,
		Selector: selector,
	}
}

// Do executes DOM.querySelector.
func (p *DOMQuerySelectorParams) Do(ctx context.Context) (*DOMQuerySelectorReturns, error) {
	var res DOMQuerySelectorReturns
	if err := Execute(ctx, DOMCommandQuerySelector, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMQuerySelectorAllParams Executes `querySelectorAll` on a given node.
type DOMQuerySelectorAllParams struct {
	// NodeID Id of the node to query upon.
	NodeID NodeID `json:"nodeId"`
	// Selector Selector string.
	Selector string `json:"selector"`
}

// DOMQuerySelectorAllReturns holds the return values for querySelectorAll.
type DOMQuerySelectorAllReturns struct {
	// NodeIds Query selector result.
	NodeIds []NodeID `json:"nodeIds"`
}

// DOMQuerySelectorAll creates a new DOMQuerySelectorAllParams.
func DOMQuerySelectorAll(nodeID NodeID, selector string) *DOMQuerySelectorAllParams {
	return &DOMQuerySelectorAllParams{
		NodeID:   nodeID,
		Selector: selector,
	}
}

// Do executes DOM.querySelectorAll.
func (p *DOMQuerySelectorAllParams) Do(ctx context.Context) (*DOMQuerySelectorAllReturns, error) {
	var res DOMQuerySelectorAllReturns
	if err := Execute(ctx, DOMCommandQuerySelectorAll, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMGetTopLayerElementsParams Returns NodeIds of current top layer elements.
// Top layer is rendered closest to the user within a viewport, therefore its elements always
// appear on top of all other content.
type DOMGetTopLayerElementsParams struct{}

// DOMGetTopLayerElementsReturns holds the return values for getTopLayerElements.
type DOMGetTopLayerElementsReturns struct {
	// NodeIds NodeIds of top layer elements
	NodeIds []NodeID `json:"nodeIds"`
}

// DOMGetTopLayerElements creates a new DOMGetTopLayerElementsParams.
func DOMGetTopLayerElements() *DOMGetTopLayerElementsParams {
	return &DOMGetTopLayerElementsParams{}
}

// Do executes DOM.getTopLayerElements.
func (p *DOMGetTopLayerElementsParams) Do(ctx context.Context) (*DOMGetTopLayerElementsReturns, error) {
	var res DOMGetTopLayerElementsReturns
	if err := Execute(ctx, DOMCommandGetTopLayerElements, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMGetElementByRelationParams Returns the NodeId of the matched element according to certain relations.
type DOMGetElementByRelationParams struct {
	// NodeID Id of the node from which to query the relation.
	NodeID NodeID `json:"nodeId"`
	// Relation Type of relation to get.
	Relation DOMGetElementByRelationRelation `json:"relation"`
}

// DOMGetElementByRelationReturns holds the return values for getElementByRelation.
type DOMGetElementByRelationReturns struct {
	// NodeID NodeId of the element matching the queried relation.
	NodeID NodeID `json:"nodeId"`
}

// DOMGetElementByRelation creates a new DOMGetElementByRelationParams.
func DOMGetElementByRelation(nodeID NodeID, relation DOMGetElementByRelationRelation) *DOMGetElementByRelationParams {
	return &DOMGetElementByRelationParams{
		NodeID:   nodeID,
		Relation: relation,
	}
}

// Do executes DOM.getElementByRelation.
func (p *DOMGetElementByRelationParams) Do(ctx context.Context) (*DOMGetElementByRelationReturns, error) {
	var res DOMGetElementByRelationReturns
	if err := Execute(ctx, DOMCommandGetElementByRelation, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMRedoParams Re-does the last undone action.
type DOMRedoParams struct{}

// DOMRedo creates a new DOMRedoParams.
func DOMRedo() *DOMRedoParams {
	return &DOMRedoParams{}
}

// Do executes DOM.redo.
func (p *DOMRedoParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandRedo, p, nil)
}

// DOMRemoveAttributeParams Removes attribute with given name from an element with given id.
type DOMRemoveAttributeParams struct {
	// NodeID Id of the element to remove attribute from.
	NodeID NodeID `json:"nodeId"`
	// Name Name of the attribute to remove.
	Name string `json:"name"`
}

// DOMRemoveAttribute creates a new DOMRemoveAttributeParams.
func DOMRemoveAttribute(nodeID NodeID, name string) *DOMRemoveAttributeParams {
	return &DOMRemoveAttributeParams{
		NodeID: nodeID,
		Name:   name,
	}
}

// Do executes DOM.removeAttribute.
func (p *DOMRemoveAttributeParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandRemoveAttribute, p, nil)
}

// DOMRemoveNodeParams Removes node with given id.
type DOMRemoveNodeParams struct {
	// NodeID Id of the node to remove.
	NodeID NodeID `json:"nodeId"`
}

// DOMRemoveNode creates a new DOMRemoveNodeParams.
func DOMRemoveNode(nodeID NodeID) *DOMRemoveNodeParams {
	return &DOMRemoveNodeParams{
		NodeID: nodeID,
	}
}

// Do executes DOM.removeNode.
func (p *DOMRemoveNodeParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandRemoveNode, p, nil)
}

// DOMRequestChildNodesParams Requests that children of the node with given id are returned to the caller in form of
// `setChildNodes` events where not only immediate children are retrieved, but all children down to
// the specified depth.
type DOMRequestChildNodesParams struct {
	// NodeID Id of the node to get children for.
	NodeID NodeID `json:"nodeId"`
	// Depth The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the
	// entire subtree or provide an integer larger than 0.
	Depth int64 `json:"depth,omitempty"`
	// Pierce Whether or not iframes and shadow roots should be traversed when returning the sub-tree
	// (default is false).
	Pierce bool `json:"pierce,omitempty"`
}

// DOMRequestChildNodes creates a new DOMRequestChildNodesParams.
func DOMRequestChildNodes(nodeID NodeID) *DOMRequestChildNodesParams {
	return &DOMRequestChildNodesParams{
		NodeID: nodeID,
	}
}

// WithDepth sets the depth parameter.
func (p *DOMRequestChildNodesParams) WithDepth(depth int64) *DOMRequestChildNodesParams {
	p.Depth = depth
	return p
}

// WithPierce sets the pierce parameter.
func (p *DOMRequestChildNodesParams) WithPierce(pierce bool) *DOMRequestChildNodesParams {
	p.Pierce = pierce
	return p
}

// Do executes DOM.requestChildNodes.
func (p *DOMRequestChildNodesParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandRequestChildNodes, p, nil)
}

// DOMRequestNodeParams Requests that the node is sent to the caller given the JavaScript node object reference. All
// nodes that form the path from the node to the root are also sent to the client as a series of
// `setChildNodes` notifications.
type DOMRequestNodeParams struct {
	// ObjectID JavaScript object id to convert into node.
	ObjectID RemoteObjectID `json:"objectId"`
}

// DOMRequestNodeReturns holds the return values for requestNode.
type DOMRequestNodeReturns struct {
	// NodeID Node id for given object.
	NodeID NodeID `json:"nodeId"`
}

// DOMRequestNode creates a new DOMRequestNodeParams.
func DOMRequestNode(objectID RemoteObjectID) *DOMRequestNodeParams {
	return &DOMRequestNodeParams{
		ObjectID: objectID,
	}
}

// Do executes DOM.requestNode.
func (p *DOMRequestNodeParams) Do(ctx context.Context) (*DOMRequestNodeReturns, error) {
	var res DOMRequestNodeReturns
	if err := Execute(ctx, DOMCommandRequestNode, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMResolveNodeParams Resolves the JavaScript node object for a given NodeId or BackendNodeId.
type DOMResolveNodeParams struct {
	// NodeID Id of the node to resolve.
	NodeID NodeID `json:"nodeId,omitempty"`
	// BackendNodeID Backend identifier of the node to resolve.
	BackendNodeID BackendNodeID `json:"backendNodeId,omitempty"`
	// ObjectGroup Symbolic group name that can be used to release multiple objects.
	ObjectGroup string `json:"objectGroup,omitempty"`
	// ExecutionContextID Execution context in which to resolve the node.
	ExecutionContextID RuntimeExecutionContextID `json:"executionContextId,omitempty"`
}

// DOMResolveNodeReturns holds the return values for resolveNode.
type DOMResolveNodeReturns struct {
	// Object JavaScript object wrapper for given node.
	Object RuntimeRemoteObject `json:"object"`
}

// DOMResolveNode creates a new DOMResolveNodeParams.
func DOMResolveNode() *DOMResolveNodeParams {
	return &DOMResolveNodeParams{}
}

// WithNodeID sets the nodeId parameter.
func (p *DOMResolveNodeParams) WithNodeID(nodeID NodeID) *DOMResolveNodeParams {
	p.NodeID = nodeID
	return p
}

// WithBackendNodeID sets the backendNodeId parameter.
func (p *DOMResolveNodeParams) WithBackendNodeID(backendNodeID BackendNodeID) *DOMResolveNodeParams {
	p.BackendNodeID = backendNodeID
	return p
}

// WithObjectGroup sets the objectGroup parameter.
func (p *DOMResolveNodeParams) WithObjectGroup(objectGroup string) *DOMResolveNodeParams {
	p.ObjectGroup = objectGroup
	return p
}

// WithExecutionContextID sets the executionContextId parameter.
func (p *DOMResolveNodeParams) WithExecutionContextID(executionContextID RuntimeExecutionContextID) *DOMResolveNodeParams {
	p.ExecutionContextID = executionContextID
	return p
}

// Do executes DOM.resolveNode.
func (p *DOMResolveNodeParams) Do(ctx context.Context) (*DOMResolveNodeReturns, error) {
	var res DOMResolveNodeReturns
	if err := Execute(ctx, DOMCommandResolveNode, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMSetAttributeValueParams Sets attribute for an element with given id.
type DOMSetAttributeValueParams struct {
	// NodeID Id of the element to set attribute for.
	NodeID NodeID `json:"nodeId"`
	// Name Attribute name.
	Name string `json:"name"`
	// Value Attribute value.
	Value string `json:"value"`
}

// DOMSetAttributeValue creates a new DOMSetAttributeValueParams.
func DOMSetAttributeValue(nodeID NodeID, name string, value string) *DOMSetAttributeValueParams {
	return &DOMSetAttributeValueParams{
		NodeID: nodeID,
		Name:   name,
		Value:  value,
	}
}

// Do executes DOM.setAttributeValue.
func (p *DOMSetAttributeValueParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandSetAttributeValue, p, nil)
}

// DOMSetAttributesAsTextParams Sets attributes on element with given id. This method is useful when user edits some existing
// attribute value and types in several attribute name/value pairs.
type DOMSetAttributesAsTextParams struct {
	// NodeID Id of the element to set attributes for.
	NodeID NodeID `json:"nodeId"`
	// Text Text with a number of attributes. Will parse this text using HTML parser.
	Text string `json:"text"`
	// Name Attribute name to replace with new attributes derived from text in case text parsed
	// successfully.
	Name string `json:"name,omitempty"`
}

// DOMSetAttributesAsText creates a new DOMSetAttributesAsTextParams.
func DOMSetAttributesAsText(nodeID NodeID, text string) *DOMSetAttributesAsTextParams {
	return &DOMSetAttributesAsTextParams{
		NodeID: nodeID,
		Text:   text,
	}
}

// WithName sets the name parameter.
func (p *DOMSetAttributesAsTextParams) WithName(name string) *DOMSetAttributesAsTextParams {
	p.Name = name
	return p
}

// Do executes DOM.setAttributesAsText.
func (p *DOMSetAttributesAsTextParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandSetAttributesAsText, p, nil)
}

// DOMSetFileInputFilesParams Sets files for the given file input element.
type DOMSetFileInputFilesParams struct {
	// Files Array of file paths to set.
	Files []string `json:"files"`
	// NodeID Identifier of the node.
	NodeID NodeID `json:"nodeId,omitempty"`
	// BackendNodeID Identifier of the backend node.
	BackendNodeID BackendNodeID `json:"backendNodeId,omitempty"`
	// ObjectID JavaScript object id of the node wrapper.
	ObjectID RemoteObjectID `json:"objectId,omitempty"`
}

// DOMSetFileInputFiles creates a new DOMSetFileInputFilesParams.
func DOMSetFileInputFiles(files []string) *DOMSetFileInputFilesParams {
	return &DOMSetFileInputFilesParams{
		Files: files,
	}
}

// WithNodeID sets the nodeId parameter.
func (p *DOMSetFileInputFilesParams) WithNodeID(nodeID NodeID) *DOMSetFileInputFilesParams {
	p.NodeID = nodeID
	return p
}

// WithBackendNodeID sets the backendNodeId parameter.
func (p *DOMSetFileInputFilesParams) WithBackendNodeID(backendNodeID BackendNodeID) *DOMSetFileInputFilesParams {
	p.BackendNodeID = backendNodeID
	return p
}

// WithObjectID sets the objectId parameter.
func (p *DOMSetFileInputFilesParams) WithObjectID(objectID RemoteObjectID) *DOMSetFileInputFilesParams {
	p.ObjectID = objectID
	return p
}

// Do executes DOM.setFileInputFiles.
func (p *DOMSetFileInputFilesParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandSetFileInputFiles, p, nil)
}

// DOMSetNodeStackTracesEnabledParams Sets if stack traces should be captured for Nodes. See `Node.getNodeStackTraces`. Default is disabled.
type DOMSetNodeStackTracesEnabledParams struct {
	// Enable Enable or disable.
	Enable bool `json:"enable"`
}

// DOMSetNodeStackTracesEnabled creates a new DOMSetNodeStackTracesEnabledParams.
func DOMSetNodeStackTracesEnabled(enable bool) *DOMSetNodeStackTracesEnabledParams {
	return &DOMSetNodeStackTracesEnabledParams{
		Enable: enable,
	}
}

// Do executes DOM.setNodeStackTracesEnabled.
func (p *DOMSetNodeStackTracesEnabledParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandSetNodeStackTracesEnabled, p, nil)
}

// DOMGetNodeStackTracesParams Gets stack traces associated with a Node. As of now, only provides stack trace for Node creation.
type DOMGetNodeStackTracesParams struct {
	// NodeID Id of the node to get stack traces for.
	NodeID NodeID `json:"nodeId"`
}

// DOMGetNodeStackTracesReturns holds the return values for getNodeStackTraces.
type DOMGetNodeStackTracesReturns struct {
	// Creation Creation stack trace, if available.
	Creation RuntimeStackTrace `json:"creation,omitempty"`
}

// DOMGetNodeStackTraces creates a new DOMGetNodeStackTracesParams.
func DOMGetNodeStackTraces(nodeID NodeID) *DOMGetNodeStackTracesParams {
	return &DOMGetNodeStackTracesParams{
		NodeID: nodeID,
	}
}

// Do executes DOM.getNodeStackTraces.
func (p *DOMGetNodeStackTracesParams) Do(ctx context.Context) (*DOMGetNodeStackTracesReturns, error) {
	var res DOMGetNodeStackTracesReturns
	if err := Execute(ctx, DOMCommandGetNodeStackTraces, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMGetFileInfoParams Returns file information for the given
// File wrapper.
type DOMGetFileInfoParams struct {
	// ObjectID JavaScript object id of the node wrapper.
	ObjectID RemoteObjectID `json:"objectId"`
}

// DOMGetFileInfoReturns holds the return values for getFileInfo.
type DOMGetFileInfoReturns struct {
	Path string `json:"path"`
}

// DOMGetFileInfo creates a new DOMGetFileInfoParams.
func DOMGetFileInfo(objectID RemoteObjectID) *DOMGetFileInfoParams {
	return &DOMGetFileInfoParams{
		ObjectID: objectID,
	}
}

// Do executes DOM.getFileInfo.
func (p *DOMGetFileInfoParams) Do(ctx context.Context) (*DOMGetFileInfoReturns, error) {
	var res DOMGetFileInfoReturns
	if err := Execute(ctx, DOMCommandGetFileInfo, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMGetDetachedDOMNodesParams Returns list of detached nodes
type DOMGetDetachedDOMNodesParams struct{}

// DOMGetDetachedDOMNodesReturns holds the return values for getDetachedDomNodes.
type DOMGetDetachedDOMNodesReturns struct {
	// DetachedNodes The list of detached nodes
	DetachedNodes []DOMDetachedElementInfo `json:"detachedNodes"`
}

// DOMGetDetachedDOMNodes creates a new DOMGetDetachedDOMNodesParams.
func DOMGetDetachedDOMNodes() *DOMGetDetachedDOMNodesParams {
	return &DOMGetDetachedDOMNodesParams{}
}

// Do executes DOM.getDetachedDomNodes.
func (p *DOMGetDetachedDOMNodesParams) Do(ctx context.Context) (*DOMGetDetachedDOMNodesReturns, error) {
	var res DOMGetDetachedDOMNodesReturns
	if err := Execute(ctx, DOMCommandGetDetachedDOMNodes, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMSetInspectedNodeParams Enables console to refer to the node with given id via $x (see Command Line API for more details
// $x functions).
type DOMSetInspectedNodeParams struct {
	// NodeID DOM node id to be accessible by means of $x command line API.
	NodeID NodeID `json:"nodeId"`
}

// DOMSetInspectedNode creates a new DOMSetInspectedNodeParams.
func DOMSetInspectedNode(nodeID NodeID) *DOMSetInspectedNodeParams {
	return &DOMSetInspectedNodeParams{
		NodeID: nodeID,
	}
}

// Do executes DOM.setInspectedNode.
func (p *DOMSetInspectedNodeParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandSetInspectedNode, p, nil)
}

// DOMSetNodeNameParams Sets node name for a node with given id.
type DOMSetNodeNameParams struct {
	// NodeID Id of the node to set name for.
	NodeID NodeID `json:"nodeId"`
	// Name New node's name.
	Name string `json:"name"`
}

// DOMSetNodeNameReturns holds the return values for setNodeName.
type DOMSetNodeNameReturns struct {
	// NodeID New node's id.
	NodeID NodeID `json:"nodeId"`
}

// DOMSetNodeName creates a new DOMSetNodeNameParams.
func DOMSetNodeName(nodeID NodeID, name string) *DOMSetNodeNameParams {
	return &DOMSetNodeNameParams{
		NodeID: nodeID,
		Name:   name,
	}
}

// Do executes DOM.setNodeName.
func (p *DOMSetNodeNameParams) Do(ctx context.Context) (*DOMSetNodeNameReturns, error) {
	var res DOMSetNodeNameReturns
	if err := Execute(ctx, DOMCommandSetNodeName, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMSetNodeValueParams Sets node value for a node with given id.
type DOMSetNodeValueParams struct {
	// NodeID Id of the node to set value for.
	NodeID NodeID `json:"nodeId"`
	// Value New node's value.
	Value string `json:"value"`
}

// DOMSetNodeValue creates a new DOMSetNodeValueParams.
func DOMSetNodeValue(nodeID NodeID, value string) *DOMSetNodeValueParams {
	return &DOMSetNodeValueParams{
		NodeID: nodeID,
		Value:  value,
	}
}

// Do executes DOM.setNodeValue.
func (p *DOMSetNodeValueParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandSetNodeValue, p, nil)
}

// DOMSetOuterHTMLParams Sets node HTML markup, returns new node id.
type DOMSetOuterHTMLParams struct {
	// NodeID Id of the node to set markup for.
	NodeID NodeID `json:"nodeId"`
	// OuterHTML Outer HTML markup to set.
	OuterHTML string `json:"outerHTML"`
}

// DOMSetOuterHTML creates a new DOMSetOuterHTMLParams.
func DOMSetOuterHTML(nodeID NodeID, outerHTML string) *DOMSetOuterHTMLParams {
	return &DOMSetOuterHTMLParams{
		NodeID:    nodeID,
		OuterHTML: outerHTML,
	}
}

// Do executes DOM.setOuterHTML.
func (p *DOMSetOuterHTMLParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandSetOuterHTML, p, nil)
}

// DOMUndoParams Undoes the last performed action.
type DOMUndoParams struct{}

// DOMUndo creates a new DOMUndoParams.
func DOMUndo() *DOMUndoParams {
	return &DOMUndoParams{}
}

// Do executes DOM.undo.
func (p *DOMUndoParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMCommandUndo, p, nil)
}

// DOMGetFrameOwnerParams Returns iframe node that owns iframe with the given domain.
type DOMGetFrameOwnerParams struct {
	FrameID FrameID `json:"frameId"`
}

// DOMGetFrameOwnerReturns holds the return values for getFrameOwner.
type DOMGetFrameOwnerReturns struct {
	// BackendNodeID Resulting node.
	BackendNodeID BackendNodeID `json:"backendNodeId"`
	// NodeID Id of the node at given coordinates, only when enabled and requested document.
	NodeID NodeID `json:"nodeId,omitempty"`
}

// DOMGetFrameOwner creates a new DOMGetFrameOwnerParams.
func DOMGetFrameOwner(frameID FrameID) *DOMGetFrameOwnerParams {
	return &DOMGetFrameOwnerParams{
		FrameID: frameID,
	}
}

// Do executes DOM.getFrameOwner.
func (p *DOMGetFrameOwnerParams) Do(ctx context.Context) (*DOMGetFrameOwnerReturns, error) {
	var res DOMGetFrameOwnerReturns
	if err := Execute(ctx, DOMCommandGetFrameOwner, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMGetContainerForNodeParams Returns the query container of the given node based on container query
// conditions: containerName, physical and logical axes, and whether it queries
// scroll-state or anchored elements. If no axes are provided and
// queriesScrollState is false, the style container is returned, which is the
// direct parent or the closest element with a matching container-name.
type DOMGetContainerForNodeParams struct {
	NodeID             NodeID          `json:"nodeId"`
	ContainerName      string          `json:"containerName,omitempty"`
	PhysicalAxes       DOMPhysicalAxes `json:"physicalAxes,omitempty"`
	LogicalAxes        DOMLogicalAxes  `json:"logicalAxes,omitempty"`
	QueriesScrollState bool            `json:"queriesScrollState,omitempty"`
	QueriesAnchored    bool            `json:"queriesAnchored,omitempty"`
}

// DOMGetContainerForNodeReturns holds the return values for getContainerForNode.
type DOMGetContainerForNodeReturns struct {
	// NodeID The container node for the given node, or null if not found.
	NodeID NodeID `json:"nodeId,omitempty"`
}

// DOMGetContainerForNode creates a new DOMGetContainerForNodeParams.
func DOMGetContainerForNode(nodeID NodeID) *DOMGetContainerForNodeParams {
	return &DOMGetContainerForNodeParams{
		NodeID: nodeID,
	}
}

// WithContainerName sets the containerName parameter.
func (p *DOMGetContainerForNodeParams) WithContainerName(containerName string) *DOMGetContainerForNodeParams {
	p.ContainerName = containerName
	return p
}

// WithPhysicalAxes sets the physicalAxes parameter.
func (p *DOMGetContainerForNodeParams) WithPhysicalAxes(physicalAxes DOMPhysicalAxes) *DOMGetContainerForNodeParams {
	p.PhysicalAxes = physicalAxes
	return p
}

// WithLogicalAxes sets the logicalAxes parameter.
func (p *DOMGetContainerForNodeParams) WithLogicalAxes(logicalAxes DOMLogicalAxes) *DOMGetContainerForNodeParams {
	p.LogicalAxes = logicalAxes
	return p
}

// WithQueriesScrollState sets the queriesScrollState parameter.
func (p *DOMGetContainerForNodeParams) WithQueriesScrollState(queriesScrollState bool) *DOMGetContainerForNodeParams {
	p.QueriesScrollState = queriesScrollState
	return p
}

// WithQueriesAnchored sets the queriesAnchored parameter.
func (p *DOMGetContainerForNodeParams) WithQueriesAnchored(queriesAnchored bool) *DOMGetContainerForNodeParams {
	p.QueriesAnchored = queriesAnchored
	return p
}

// Do executes DOM.getContainerForNode.
func (p *DOMGetContainerForNodeParams) Do(ctx context.Context) (*DOMGetContainerForNodeReturns, error) {
	var res DOMGetContainerForNodeReturns
	if err := Execute(ctx, DOMCommandGetContainerForNode, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMGetQueryingDescendantsForContainerParams Returns the descendants of a container query container that have
// container queries against this container.
type DOMGetQueryingDescendantsForContainerParams struct {
	// NodeID Id of the container node to find querying descendants from.
	NodeID NodeID `json:"nodeId"`
}

// DOMGetQueryingDescendantsForContainerReturns holds the return values for getQueryingDescendantsForContainer.
type DOMGetQueryingDescendantsForContainerReturns struct {
	// NodeIds Descendant nodes with container queries against the given container.
	NodeIds []NodeID `json:"nodeIds"`
}

// DOMGetQueryingDescendantsForContainer creates a new DOMGetQueryingDescendantsForContainerParams.
func DOMGetQueryingDescendantsForContainer(nodeID NodeID) *DOMGetQueryingDescendantsForContainerParams {
	return &DOMGetQueryingDescendantsForContainerParams{
		NodeID: nodeID,
	}
}

// Do executes DOM.getQueryingDescendantsForContainer.
func (p *DOMGetQueryingDescendantsForContainerParams) Do(ctx context.Context) (*DOMGetQueryingDescendantsForContainerReturns, error) {
	var res DOMGetQueryingDescendantsForContainerReturns
	if err := Execute(ctx, DOMCommandGetQueryingDescendantsForContainer, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMGetAnchorElementParams Returns the target anchor element of the given anchor query according to
// https://www.w3.org/TR/css-anchor-position-1/#target.
type DOMGetAnchorElementParams struct {
	// NodeID Id of the positioned element from which to find the anchor.
	NodeID NodeID `json:"nodeId"`
	// AnchorSpecifier An optional anchor specifier, as defined in
	// https://www.w3.org/TR/css-anchor-position-1/#anchor-specifier.
	// If not provided, it will return the implicit anchor element for
	// the given positioned element.
	AnchorSpecifier string `json:"anchorSpecifier,omitempty"`
}

// DOMGetAnchorElementReturns holds the return values for getAnchorElement.
type DOMGetAnchorElementReturns struct {
	// NodeID The anchor element of the given anchor query.
	NodeID NodeID `json:"nodeId"`
}

// DOMGetAnchorElement creates a new DOMGetAnchorElementParams.
func DOMGetAnchorElement(nodeID NodeID) *DOMGetAnchorElementParams {
	return &DOMGetAnchorElementParams{
		NodeID: nodeID,
	}
}

// WithAnchorSpecifier sets the anchorSpecifier parameter.
func (p *DOMGetAnchorElementParams) WithAnchorSpecifier(anchorSpecifier string) *DOMGetAnchorElementParams {
	p.AnchorSpecifier = anchorSpecifier
	return p
}

// Do executes DOM.getAnchorElement.
func (p *DOMGetAnchorElementParams) Do(ctx context.Context) (*DOMGetAnchorElementReturns, error) {
	var res DOMGetAnchorElementReturns
	if err := Execute(ctx, DOMCommandGetAnchorElement, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMForceShowPopoverParams When enabling, this API force-opens the popover identified by nodeId
// and keeps it open until disabled.
type DOMForceShowPopoverParams struct {
	// NodeID Id of the popover HTMLElement
	NodeID NodeID `json:"nodeId"`
	// Enable If true, opens the popover and keeps it open. If false, closes the
	// popover if it was previously force-opened.
	Enable bool `json:"enable"`
}

// DOMForceShowPopoverReturns holds the return values for forceShowPopover.
type DOMForceShowPopoverReturns struct {
	// NodeIds List of popovers that were closed in order to respect popover stacking order.
	NodeIds []NodeID `json:"nodeIds"`
}

// DOMForceShowPopover creates a new DOMForceShowPopoverParams.
func DOMForceShowPopover(nodeID NodeID, enable bool) *DOMForceShowPopoverParams {
	return &DOMForceShowPopoverParams{
		NodeID: nodeID,
		Enable: enable,
	}
}

// Do executes DOM.forceShowPopover.
func (p *DOMForceShowPopoverParams) Do(ctx context.Context) (*DOMForceShowPopoverReturns, error) {
	var res DOMForceShowPopoverReturns
	if err := Execute(ctx, DOMCommandForceShowPopover, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOM command names.
const (
	DOMCommandCollectClassNamesFromSubtree       Method = "DOM.collectClassNamesFromSubtree"
	DOMCommandCopyTo                             Method = "DOM.copyTo"
	DOMCommandDescribeNode                       Method = "DOM.describeNode"
	DOMCommandScrollIntoViewIfNeeded             Method = "DOM.scrollIntoViewIfNeeded"
	DOMCommandDisable                            Method = "DOM.disable"
	DOMCommandDiscardSearchResults               Method = "DOM.discardSearchResults"
	DOMCommandEnable                             Method = "DOM.enable"
	DOMCommandFocus                              Method = "DOM.focus"
	DOMCommandGetAttributes                      Method = "DOM.getAttributes"
	DOMCommandGetBoxModel                        Method = "DOM.getBoxModel"
	DOMCommandGetContentQuads                    Method = "DOM.getContentQuads"
	DOMCommandGetDocument                        Method = "DOM.getDocument"
	DOMCommandGetFlattenedDocument               Method = "DOM.getFlattenedDocument"
	DOMCommandGetNodesForSubtreeByStyle          Method = "DOM.getNodesForSubtreeByStyle"
	DOMCommandGetNodeForLocation                 Method = "DOM.getNodeForLocation"
	DOMCommandGetOuterHTML                       Method = "DOM.getOuterHTML"
	DOMCommandGetRelayoutBoundary                Method = "DOM.getRelayoutBoundary"
	DOMCommandGetSearchResults                   Method = "DOM.getSearchResults"
	DOMCommandHideHighlight                      Method = "DOM.hideHighlight"
	DOMCommandHighlightNode                      Method = "DOM.highlightNode"
	DOMCommandHighlightRect                      Method = "DOM.highlightRect"
	DOMCommandMarkUndoableState                  Method = "DOM.markUndoableState"
	DOMCommandMoveTo                             Method = "DOM.moveTo"
	DOMCommandPerformSearch                      Method = "DOM.performSearch"
	DOMCommandPushNodeByPathToFrontend           Method = "DOM.pushNodeByPathToFrontend"
	DOMCommandPushNodesByBackendIdsToFrontend    Method = "DOM.pushNodesByBackendIdsToFrontend"
	DOMCommandQuerySelector                      Method = "DOM.querySelector"
	DOMCommandQuerySelectorAll                   Method = "DOM.querySelectorAll"
	DOMCommandGetTopLayerElements                Method = "DOM.getTopLayerElements"
	DOMCommandGetElementByRelation               Method = "DOM.getElementByRelation"
	DOMCommandRedo                               Method = "DOM.redo"
	DOMCommandRemoveAttribute                    Method = "DOM.removeAttribute"
	DOMCommandRemoveNode                         Method = "DOM.removeNode"
	DOMCommandRequestChildNodes                  Method = "DOM.requestChildNodes"
	DOMCommandRequestNode                        Method = "DOM.requestNode"
	DOMCommandResolveNode                        Method = "DOM.resolveNode"
	DOMCommandSetAttributeValue                  Method = "DOM.setAttributeValue"
	DOMCommandSetAttributesAsText                Method = "DOM.setAttributesAsText"
	DOMCommandSetFileInputFiles                  Method = "DOM.setFileInputFiles"
	DOMCommandSetNodeStackTracesEnabled          Method = "DOM.setNodeStackTracesEnabled"
	DOMCommandGetNodeStackTraces                 Method = "DOM.getNodeStackTraces"
	DOMCommandGetFileInfo                        Method = "DOM.getFileInfo"
	DOMCommandGetDetachedDOMNodes                Method = "DOM.getDetachedDomNodes"
	DOMCommandSetInspectedNode                   Method = "DOM.setInspectedNode"
	DOMCommandSetNodeName                        Method = "DOM.setNodeName"
	DOMCommandSetNodeValue                       Method = "DOM.setNodeValue"
	DOMCommandSetOuterHTML                       Method = "DOM.setOuterHTML"
	DOMCommandUndo                               Method = "DOM.undo"
	DOMCommandGetFrameOwner                      Method = "DOM.getFrameOwner"
	DOMCommandGetContainerForNode                Method = "DOM.getContainerForNode"
	DOMCommandGetQueryingDescendantsForContainer Method = "DOM.getQueryingDescendantsForContainer"
	DOMCommandGetAnchorElement                   Method = "DOM.getAnchorElement"
	DOMCommandForceShowPopover                   Method = "DOM.forceShowPopover"
)
