// Code generated by bonkgen. DO NOT EDIT.

package proto

import "context"

// DOMDebuggerGetEventListenersParams Returns event listeners of the given object.
type DOMDebuggerGetEventListenersParams struct {
	// ObjectID Identifier of the object to return listeners for.
	ObjectID RemoteObjectID `json:"objectId"`
	// Depth The maximum depth at which Node children should be retrieved, defaults to 1. Use -1 for the
	// entire subtree or provide an integer larger than 0.
	Depth int64 `json:"depth,omitempty"`
	// Pierce Whether or not iframes and shadow roots should be traversed when returning the subtree
	// (default is false). Reports listeners for all contexts if pierce is enabled.
	Pierce bool `json:"pierce,omitempty"`
}

// DOMDebuggerGetEventListenersReturns holds the return values for getEventListeners.
type DOMDebuggerGetEventListenersReturns struct {
	// Listeners Array of relevant listeners.
	Listeners []DOMDebuggerEventListener `json:"listeners"`
}

// DOMDebuggerGetEventListeners creates a new DOMDebuggerGetEventListenersParams.
func DOMDebuggerGetEventListeners(objectID RemoteObjectID) *DOMDebuggerGetEventListenersParams {
	return &DOMDebuggerGetEventListenersParams{
		ObjectID: objectID,
	}
}

// WithDepth sets the depth parameter.
func (p *DOMDebuggerGetEventListenersParams) WithDepth(depth int64) *DOMDebuggerGetEventListenersParams {
	p.Depth = depth
	return p
}

// WithPierce sets the pierce parameter.
func (p *DOMDebuggerGetEventListenersParams) WithPierce(pierce bool) *DOMDebuggerGetEventListenersParams {
	p.Pierce = pierce
	return p
}

// Do executes DOMDebugger.getEventListeners.
func (p *DOMDebuggerGetEventListenersParams) Do(ctx context.Context) (*DOMDebuggerGetEventListenersReturns, error) {
	var res DOMDebuggerGetEventListenersReturns
	if err := Execute(ctx, DOMDebuggerCommandGetEventListeners, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DOMDebuggerRemoveDOMBreakpointParams Removes DOM breakpoint that was set using `setDOMBreakpoint`.
type DOMDebuggerRemoveDOMBreakpointParams struct {
	// NodeID Identifier of the node to remove breakpoint from.
	NodeID NodeID `json:"nodeId"`
	// Type Type of the breakpoint to remove.
	Type DOMDebuggerDOMBreakpointType `json:"type"`
}

// DOMDebuggerRemoveDOMBreakpoint creates a new DOMDebuggerRemoveDOMBreakpointParams.
func DOMDebuggerRemoveDOMBreakpoint(nodeID NodeID, typ DOMDebuggerDOMBreakpointType) *DOMDebuggerRemoveDOMBreakpointParams {
	return &DOMDebuggerRemoveDOMBreakpointParams{
		NodeID: nodeID,
		Type:   typ,
	}
}

// Do executes DOMDebugger.removeDOMBreakpoint.
func (p *DOMDebuggerRemoveDOMBreakpointParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMDebuggerCommandRemoveDOMBreakpoint, p, nil)
}

// DOMDebuggerRemoveEventListenerBreakpointParams Removes breakpoint on particular DOM event.
type DOMDebuggerRemoveEventListenerBreakpointParams struct {
	// EventName Event name.
	EventName string `json:"eventName"`
	// TargetName EventTarget interface name.
	TargetName string `json:"targetName,omitempty"`
}

// DOMDebuggerRemoveEventListenerBreakpoint creates a new DOMDebuggerRemoveEventListenerBreakpointParams.
func DOMDebuggerRemoveEventListenerBreakpoint(eventName string) *DOMDebuggerRemoveEventListenerBreakpointParams {
	return &DOMDebuggerRemoveEventListenerBreakpointParams{
		EventName: eventName,
	}
}

// WithTargetName sets the targetName parameter.
func (p *DOMDebuggerRemoveEventListenerBreakpointParams) WithTargetName(targetName string) *DOMDebuggerRemoveEventListenerBreakpointParams {
	p.TargetName = targetName
	return p
}

// Do executes DOMDebugger.removeEventListenerBreakpoint.
func (p *DOMDebuggerRemoveEventListenerBreakpointParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMDebuggerCommandRemoveEventListenerBreakpoint, p, nil)
}

// DOMDebuggerRemoveInstrumentationBreakpointParams Removes breakpoint on particular native event.
type DOMDebuggerRemoveInstrumentationBreakpointParams struct {
	// EventName Instrumentation name to stop on.
	EventName string `json:"eventName"`
}

// DOMDebuggerRemoveInstrumentationBreakpoint creates a new DOMDebuggerRemoveInstrumentationBreakpointParams.
func DOMDebuggerRemoveInstrumentationBreakpoint(eventName string) *DOMDebuggerRemoveInstrumentationBreakpointParams {
	return &DOMDebuggerRemoveInstrumentationBreakpointParams{
		EventName: eventName,
	}
}

// Do executes DOMDebugger.removeInstrumentationBreakpoint.
func (p *DOMDebuggerRemoveInstrumentationBreakpointParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMDebuggerCommandRemoveInstrumentationBreakpoint, p, nil)
}

// DOMDebuggerRemoveXHRBreakpointParams Removes breakpoint from XMLHttpRequest.
type DOMDebuggerRemoveXHRBreakpointParams struct {
	// URL Resource URL substring.
	URL string `json:"url"`
}

// DOMDebuggerRemoveXHRBreakpoint creates a new DOMDebuggerRemoveXHRBreakpointParams.
func DOMDebuggerRemoveXHRBreakpoint(url string) *DOMDebuggerRemoveXHRBreakpointParams {
	return &DOMDebuggerRemoveXHRBreakpointParams{
		URL: url,
	}
}

// Do executes DOMDebugger.removeXHRBreakpoint.
func (p *DOMDebuggerRemoveXHRBreakpointParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMDebuggerCommandRemoveXHRBreakpoint, p, nil)
}

// DOMDebuggerSetBreakOnCSPViolationParams Sets breakpoint on particular CSP violations.
type DOMDebuggerSetBreakOnCSPViolationParams struct {
	// ViolationTypes CSP Violations to stop upon.
	ViolationTypes []DOMDebuggerCSPViolationType `json:"violationTypes"`
}

// DOMDebuggerSetBreakOnCSPViolation creates a new DOMDebuggerSetBreakOnCSPViolationParams.
func DOMDebuggerSetBreakOnCSPViolation(violationTypes []DOMDebuggerCSPViolationType) *DOMDebuggerSetBreakOnCSPViolationParams {
	return &DOMDebuggerSetBreakOnCSPViolationParams{
		ViolationTypes: violationTypes,
	}
}

// Do executes DOMDebugger.setBreakOnCSPViolation.
func (p *DOMDebuggerSetBreakOnCSPViolationParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMDebuggerCommandSetBreakOnCSPViolation, p, nil)
}

// DOMDebuggerSetDOMBreakpointParams Sets breakpoint on particular operation with DOM.
type DOMDebuggerSetDOMBreakpointParams struct {
	// NodeID Identifier of the node to set breakpoint on.
	NodeID NodeID `json:"nodeId"`
	// Type Type of the operation to stop upon.
	Type DOMDebuggerDOMBreakpointType `json:"type"`
}

// DOMDebuggerSetDOMBreakpoint creates a new DOMDebuggerSetDOMBreakpointParams.
func DOMDebuggerSetDOMBreakpoint(nodeID NodeID, typ DOMDebuggerDOMBreakpointType) *DOMDebuggerSetDOMBreakpointParams {
	return &DOMDebuggerSetDOMBreakpointParams{
		NodeID: nodeID,
		Type:   typ,
	}
}

// Do executes DOMDebugger.setDOMBreakpoint.
func (p *DOMDebuggerSetDOMBreakpointParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMDebuggerCommandSetDOMBreakpoint, p, nil)
}

// DOMDebuggerSetEventListenerBreakpointParams Sets breakpoint on particular DOM event.
type DOMDebuggerSetEventListenerBreakpointParams struct {
	// EventName DOM Event name to stop on (any DOM event will do).
	EventName string `json:"eventName"`
	// TargetName EventTarget interface name to stop on. If equal to `"*"` or not provided, will stop on any
	// EventTarget.
	TargetName string `json:"targetName,omitempty"`
}

// DOMDebuggerSetEventListenerBreakpoint creates a new DOMDebuggerSetEventListenerBreakpointParams.
func DOMDebuggerSetEventListenerBreakpoint(eventName string) *DOMDebuggerSetEventListenerBreakpointParams {
	return &DOMDebuggerSetEventListenerBreakpointParams{
		EventName: eventName,
	}
}

// WithTargetName sets the targetName parameter.
func (p *DOMDebuggerSetEventListenerBreakpointParams) WithTargetName(targetName string) *DOMDebuggerSetEventListenerBreakpointParams {
	p.TargetName = targetName
	return p
}

// Do executes DOMDebugger.setEventListenerBreakpoint.
func (p *DOMDebuggerSetEventListenerBreakpointParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMDebuggerCommandSetEventListenerBreakpoint, p, nil)
}

// DOMDebuggerSetInstrumentationBreakpointParams Sets breakpoint on particular native event.
type DOMDebuggerSetInstrumentationBreakpointParams struct {
	// EventName Instrumentation name to stop on.
	EventName string `json:"eventName"`
}

// DOMDebuggerSetInstrumentationBreakpoint creates a new DOMDebuggerSetInstrumentationBreakpointParams.
func DOMDebuggerSetInstrumentationBreakpoint(eventName string) *DOMDebuggerSetInstrumentationBreakpointParams {
	return &DOMDebuggerSetInstrumentationBreakpointParams{
		EventName: eventName,
	}
}

// Do executes DOMDebugger.setInstrumentationBreakpoint.
func (p *DOMDebuggerSetInstrumentationBreakpointParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMDebuggerCommandSetInstrumentationBreakpoint, p, nil)
}

// DOMDebuggerSetXHRBreakpointParams Sets breakpoint on XMLHttpRequest.
type DOMDebuggerSetXHRBreakpointParams struct {
	// URL Resource URL substring. All XHRs having this substring in the URL will get stopped upon.
	URL string `json:"url"`
}

// DOMDebuggerSetXHRBreakpoint creates a new DOMDebuggerSetXHRBreakpointParams.
func DOMDebuggerSetXHRBreakpoint(url string) *DOMDebuggerSetXHRBreakpointParams {
	return &DOMDebuggerSetXHRBreakpointParams{
		URL: url,
	}
}

// Do executes DOMDebugger.setXHRBreakpoint.
func (p *DOMDebuggerSetXHRBreakpointParams) Do(ctx context.Context) error {
	return Execute(ctx, DOMDebuggerCommandSetXHRBreakpoint, p, nil)
}

// DOMDebugger command names.
const (
	DOMDebuggerCommandGetEventListeners               Method = "DOMDebugger.getEventListeners"
	DOMDebuggerCommandRemoveDOMBreakpoint             Method = "DOMDebugger.removeDOMBreakpoint"
	DOMDebuggerCommandRemoveEventListenerBreakpoint   Method = "DOMDebugger.removeEventListenerBreakpoint"
	DOMDebuggerCommandRemoveInstrumentationBreakpoint Method = "DOMDebugger.removeInstrumentationBreakpoint"
	DOMDebuggerCommandRemoveXHRBreakpoint             Method = "DOMDebugger.removeXHRBreakpoint"
	DOMDebuggerCommandSetBreakOnCSPViolation          Method = "DOMDebugger.setBreakOnCSPViolation"
	DOMDebuggerCommandSetDOMBreakpoint                Method = "DOMDebugger.setDOMBreakpoint"
	DOMDebuggerCommandSetEventListenerBreakpoint      Method = "DOMDebugger.setEventListenerBreakpoint"
	DOMDebuggerCommandSetInstrumentationBreakpoint    Method = "DOMDebugger.setInstrumentationBreakpoint"
	DOMDebuggerCommandSetXHRBreakpoint                Method = "DOMDebugger.setXHRBreakpoint"
)
