// Code generated by bonkgen. DO NOT EDIT.

package proto

// DOMDebuggerDOMBreakpointType DOM breakpoint type.
type DOMDebuggerDOMBreakpointType string

const (
	DOMDebuggerDOMBreakpointTypeSubtreeModified   DOMDebuggerDOMBreakpointType = "subtree-modified"
	DOMDebuggerDOMBreakpointTypeAttributeModified DOMDebuggerDOMBreakpointType = "attribute-modified"
	DOMDebuggerDOMBreakpointTypeNodeRemoved       DOMDebuggerDOMBreakpointType = "node-removed"
)

// IsValid reports whether the value is a known enum value.
func (t DOMDebuggerDOMBreakpointType) IsValid() bool {
	switch t {
	case DOMDebuggerDOMBreakpointTypeSubtreeModified:
		return true
	case DOMDebuggerDOMBreakpointTypeAttributeModified:
		return true
	case DOMDebuggerDOMBreakpointTypeNodeRemoved:
		return true
	}
	return false
}

// Values returns all known values of DOMDebuggerDOMBreakpointType.
func (t DOMDebuggerDOMBreakpointType) Values() []DOMDebuggerDOMBreakpointType {
	return []DOMDebuggerDOMBreakpointType{
		DOMDebuggerDOMBreakpointTypeSubtreeModified,
		DOMDebuggerDOMBreakpointTypeAttributeModified,
		DOMDebuggerDOMBreakpointTypeNodeRemoved,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t DOMDebuggerDOMBreakpointType) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *DOMDebuggerDOMBreakpointType) UnmarshalText(data []byte) error {
	*t = DOMDebuggerDOMBreakpointType(data)
	return nil
}

// String returns the string representation.
func (t DOMDebuggerDOMBreakpointType) String() string {
	return string(t)
}

// DOMDebuggerCSPViolationType CSP Violation type.
type DOMDebuggerCSPViolationType string

const (
	DOMDebuggerCSPViolationTypeTrustedtypeSinkViolation   DOMDebuggerCSPViolationType = "trustedtype-sink-violation"
	DOMDebuggerCSPViolationTypeTrustedtypePolicyViolation DOMDebuggerCSPViolationType = "trustedtype-policy-violation"
)

// IsValid reports whether the value is a known enum value.
func (t DOMDebuggerCSPViolationType) IsValid() bool {
	switch t {
	case DOMDebuggerCSPViolationTypeTrustedtypeSinkViolation:
		return true
	case DOMDebuggerCSPViolationTypeTrustedtypePolicyViolation:
		return true
	}
	return false
}

// Values returns all known values of DOMDebuggerCSPViolationType.
func (t DOMDebuggerCSPViolationType) Values() []DOMDebuggerCSPViolationType {
	return []DOMDebuggerCSPViolationType{
		DOMDebuggerCSPViolationTypeTrustedtypeSinkViolation,
		DOMDebuggerCSPViolationTypeTrustedtypePolicyViolation,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t DOMDebuggerCSPViolationType) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *DOMDebuggerCSPViolationType) UnmarshalText(data []byte) error {
	*t = DOMDebuggerCSPViolationType(data)
	return nil
}

// String returns the string representation.
func (t DOMDebuggerCSPViolationType) String() string {
	return string(t)
}

// DOMDebuggerEventListener Object event listener.
type DOMDebuggerEventListener struct {
	// Type `EventListener`'s type.
	Type string `json:"type"`
	// UseCapture `EventListener`'s useCapture.
	UseCapture bool `json:"useCapture"`
	// Passive `EventListener`'s passive flag.
	Passive bool `json:"passive"`
	// Once `EventListener`'s once flag.
	Once bool `json:"once"`
	// ScriptID Script id of the handler code.
	ScriptID RuntimeScriptID `json:"scriptId"`
	// LineNumber Line number in the script (0-based).
	LineNumber int64 `json:"lineNumber"`
	// ColumnNumber Column number in the script (0-based).
	ColumnNumber int64 `json:"columnNumber"`
	// Handler Event handler function value.
	Handler RuntimeRemoteObject `json:"handler,omitempty,omitzero"`
	// OriginalHandler Event original handler function value.
	OriginalHandler RuntimeRemoteObject `json:"originalHandler,omitempty,omitzero"`
	// BackendNodeID Node the listener is added to (if any).
	BackendNodeID BackendNodeID `json:"backendNodeId,omitempty,omitzero"`
}
