// Code generated by bonkgen. DO NOT EDIT.

package proto

type DOMStorageSerializedStorageKey string

// String returns the DOMStorageSerializedStorageKey as a string.
func (t DOMStorageSerializedStorageKey) String() string {
	return string(t)
}

// DOMStorageStorageID DOM Storage identifier.
type DOMStorageStorageID struct {
	// SecurityOrigin Security origin for the storage.
	SecurityOrigin string `json:"securityOrigin,omitempty"`
	// StorageKey Represents a key by which DOM Storage keys its CachedStorageAreas
	StorageKey DOMStorageSerializedStorageKey `json:"storageKey,omitempty"`
	// IsLocalStorage Whether the storage is local storage (not session storage).
	IsLocalStorage bool `json:"isLocalStorage"`
}

// DOMStorageItem DOM Storage item.
type DOMStorageItem string
