// Code generated by bonkgen. DO NOT EDIT.

package proto

import "context"

// EventBreakpointsSetInstrumentationBreakpointParams Sets breakpoint on particular native event.
type EventBreakpointsSetInstrumentationBreakpointParams struct {
	// EventName Instrumentation name to stop on.
	EventName string `json:"eventName"`
}

// EventBreakpointsSetInstrumentationBreakpoint creates a new EventBreakpointsSetInstrumentationBreakpointParams.
func EventBreakpointsSetInstrumentationBreakpoint(eventName string) *EventBreakpointsSetInstrumentationBreakpointParams {
	return &EventBreakpointsSetInstrumentationBreakpointParams{
		EventName: eventName,
	}
}

// Do executes EventBreakpoints.setInstrumentationBreakpoint.
func (p *EventBreakpointsSetInstrumentationBreakpointParams) Do(ctx context.Context) error {
	return Execute(ctx, EventBreakpointsCommandSetInstrumentationBreakpoint, p, nil)
}

// EventBreakpointsRemoveInstrumentationBreakpointParams Removes breakpoint on particular native event.
type EventBreakpointsRemoveInstrumentationBreakpointParams struct {
	// EventName Instrumentation name to stop on.
	EventName string `json:"eventName"`
}

// EventBreakpointsRemoveInstrumentationBreakpoint creates a new EventBreakpointsRemoveInstrumentationBreakpointParams.
func EventBreakpointsRemoveInstrumentationBreakpoint(eventName string) *EventBreakpointsRemoveInstrumentationBreakpointParams {
	return &EventBreakpointsRemoveInstrumentationBreakpointParams{
		EventName: eventName,
	}
}

// Do executes EventBreakpoints.removeInstrumentationBreakpoint.
func (p *EventBreakpointsRemoveInstrumentationBreakpointParams) Do(ctx context.Context) error {
	return Execute(ctx, EventBreakpointsCommandRemoveInstrumentationBreakpoint, p, nil)
}

// EventBreakpointsDisableParams Removes all breakpoints
type EventBreakpointsDisableParams struct{}

// EventBreakpointsDisable creates a new EventBreakpointsDisableParams.
func EventBreakpointsDisable() *EventBreakpointsDisableParams {
	return &EventBreakpointsDisableParams{}
}

// Do executes EventBreakpoints.disable.
func (p *EventBreakpointsDisableParams) Do(ctx context.Context) error {
	return Execute(ctx, EventBreakpointsCommandDisable, p, nil)
}

// EventBreakpoints command names.
const (
	EventBreakpointsCommandSetInstrumentationBreakpoint    Method = "EventBreakpoints.setInstrumentationBreakpoint"
	EventBreakpointsCommandRemoveInstrumentationBreakpoint Method = "EventBreakpoints.removeInstrumentationBreakpoint"
	EventBreakpointsCommandDisable                         Method = "EventBreakpoints.disable"
)
