// Code generated by bonkgen. DO NOT EDIT.

package proto

// ExtensionsStorageArea Storage areas.
type ExtensionsStorageArea string

const (
	ExtensionsStorageAreaSession ExtensionsStorageArea = "session"
	ExtensionsStorageAreaLocal   ExtensionsStorageArea = "local"
	ExtensionsStorageAreaSync    ExtensionsStorageArea = "sync"
	ExtensionsStorageAreaManaged ExtensionsStorageArea = "managed"
)

// IsValid reports whether the value is a known enum value.
func (t ExtensionsStorageArea) IsValid() bool {
	switch t {
	case ExtensionsStorageAreaSession:
		return true
	case ExtensionsStorageAreaLocal:
		return true
	case ExtensionsStorageAreaSync:
		return true
	case ExtensionsStorageAreaManaged:
		return true
	}
	return false
}

// Values returns all known values of ExtensionsStorageArea.
func (t ExtensionsStorageArea) Values() []ExtensionsStorageArea {
	return []ExtensionsStorageArea{
		ExtensionsStorageAreaSession,
		ExtensionsStorageAreaLocal,
		ExtensionsStorageAreaSync,
		ExtensionsStorageAreaManaged,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t ExtensionsStorageArea) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *ExtensionsStorageArea) UnmarshalText(data []byte) error {
	*t = ExtensionsStorageArea(data)
	return nil
}

// String returns the string representation.
func (t ExtensionsStorageArea) String() string {
	return string(t)
}

// ExtensionsExtensionInfo Detailed information about an extension.
type ExtensionsExtensionInfo struct {
	// ID Extension id.
	ID string `json:"id"`
	// Name Extension name.
	Name string `json:"name"`
	// Version Extension version.
	Version string `json:"version"`
	// Path The path from which the extension was loaded.
	Path string `json:"path"`
	// Enabled Extension enabled status.
	Enabled bool `json:"enabled"`
}
