// Code generated by bonkgen. DO NOT EDIT.

package proto

import (
	"context"
	"encoding/json"
)

// ExtensionsTriggerActionParams Runs an extension default action.
// Available if the client is connected using the --remote-debugging-pipe
// flag and the --enable-unsafe-extension-debugging flag is set.
type ExtensionsTriggerActionParams struct {
	// ID Extension id.
	ID string `json:"id"`
	// TargetID A tab target ID to trigger the default extension action on.
	TargetID string `json:"targetId"`
}

// ExtensionsTriggerAction creates a new ExtensionsTriggerActionParams.
func ExtensionsTriggerAction(id string, targetID string) *ExtensionsTriggerActionParams {
	return &ExtensionsTriggerActionParams{
		ID:       id,
		TargetID: targetID,
	}
}

// Do executes Extensions.triggerAction.
func (p *ExtensionsTriggerActionParams) Do(ctx context.Context) error {
	return Execute(ctx, ExtensionsCommandTriggerAction, p, nil)
}

// ExtensionsLoadUnpackedParams Installs an unpacked extension from the filesystem similar to
// --load-extension CLI flags. Returns extension ID once the extension
// has been installed. Available if the client is connected using the
// --remote-debugging-pipe flag and the --enable-unsafe-extension-debugging
// flag is set.
type ExtensionsLoadUnpackedParams struct {
	// Path Absolute file path.
	Path string `json:"path"`
	// EnableInIncognito Enable the extension in incognito
	EnableInIncognito bool `json:"enableInIncognito,omitempty,omitzero"`
}

// ExtensionsLoadUnpackedReturns holds the return values for loadUnpacked.
type ExtensionsLoadUnpackedReturns struct {
	// ID Extension id.
	ID string `json:"id"`
}

// ExtensionsLoadUnpacked creates a new ExtensionsLoadUnpackedParams.
func ExtensionsLoadUnpacked(path string) *ExtensionsLoadUnpackedParams {
	return &ExtensionsLoadUnpackedParams{
		Path: path,
	}
}

// WithEnableInIncognito sets the enableInIncognito parameter.
func (p *ExtensionsLoadUnpackedParams) WithEnableInIncognito(enableInIncognito bool) *ExtensionsLoadUnpackedParams {
	p.EnableInIncognito = enableInIncognito
	return p
}

// Do executes Extensions.loadUnpacked.
func (p *ExtensionsLoadUnpackedParams) Do(ctx context.Context) (*ExtensionsLoadUnpackedReturns, error) {
	var res ExtensionsLoadUnpackedReturns
	if err := Execute(ctx, ExtensionsCommandLoadUnpacked, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ExtensionsGetExtensionsParams Gets a list of all unpacked extensions.
// Available if the client is connected using the --remote-debugging-pipe flag
// and the --enable-unsafe-extension-debugging flag is set.
type ExtensionsGetExtensionsParams struct{}

// ExtensionsGetExtensionsReturns holds the return values for getExtensions.
type ExtensionsGetExtensionsReturns struct {
	Extensions []ExtensionsExtensionInfo `json:"extensions"`
}

// ExtensionsGetExtensions creates a new ExtensionsGetExtensionsParams.
func ExtensionsGetExtensions() *ExtensionsGetExtensionsParams {
	return &ExtensionsGetExtensionsParams{}
}

// Do executes Extensions.getExtensions.
func (p *ExtensionsGetExtensionsParams) Do(ctx context.Context) (*ExtensionsGetExtensionsReturns, error) {
	var res ExtensionsGetExtensionsReturns
	if err := Execute(ctx, ExtensionsCommandGetExtensions, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ExtensionsUninstallParams Uninstalls an unpacked extension (others not supported) from the profile.
// Available if the client is connected using the --remote-debugging-pipe flag
// and the --enable-unsafe-extension-debugging.
type ExtensionsUninstallParams struct {
	// ID Extension id.
	ID string `json:"id"`
}

// ExtensionsUninstall creates a new ExtensionsUninstallParams.
func ExtensionsUninstall(id string) *ExtensionsUninstallParams {
	return &ExtensionsUninstallParams{
		ID: id,
	}
}

// Do executes Extensions.uninstall.
func (p *ExtensionsUninstallParams) Do(ctx context.Context) error {
	return Execute(ctx, ExtensionsCommandUninstall, p, nil)
}

// ExtensionsGetStorageItemsParams Gets data from extension storage in the given `storageArea`. If `keys` is
// specified, these are used to filter the result.
type ExtensionsGetStorageItemsParams struct {
	// ID ID of extension.
	ID string `json:"id"`
	// StorageArea StorageArea to retrieve data from.
	StorageArea ExtensionsStorageArea `json:"storageArea"`
	// Keys Keys to retrieve.
	Keys []string `json:"keys,omitempty,omitzero"`
}

// ExtensionsGetStorageItemsReturns holds the return values for getStorageItems.
type ExtensionsGetStorageItemsReturns struct {
	Data json.RawMessage `json:"data"`
}

// ExtensionsGetStorageItems creates a new ExtensionsGetStorageItemsParams.
func ExtensionsGetStorageItems(id string, storageArea ExtensionsStorageArea) *ExtensionsGetStorageItemsParams {
	return &ExtensionsGetStorageItemsParams{
		ID:          id,
		StorageArea: storageArea,
	}
}

// WithKeys sets the keys parameter.
func (p *ExtensionsGetStorageItemsParams) WithKeys(keys []string) *ExtensionsGetStorageItemsParams {
	p.Keys = keys
	return p
}

// Do executes Extensions.getStorageItems.
func (p *ExtensionsGetStorageItemsParams) Do(ctx context.Context) (*ExtensionsGetStorageItemsReturns, error) {
	var res ExtensionsGetStorageItemsReturns
	if err := Execute(ctx, ExtensionsCommandGetStorageItems, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ExtensionsRemoveStorageItemsParams Removes `keys` from extension storage in the given `storageArea`.
type ExtensionsRemoveStorageItemsParams struct {
	// ID ID of extension.
	ID string `json:"id"`
	// StorageArea StorageArea to remove data from.
	StorageArea ExtensionsStorageArea `json:"storageArea"`
	// Keys Keys to remove.
	Keys []string `json:"keys"`
}

// ExtensionsRemoveStorageItems creates a new ExtensionsRemoveStorageItemsParams.
func ExtensionsRemoveStorageItems(id string, storageArea ExtensionsStorageArea, keys []string) *ExtensionsRemoveStorageItemsParams {
	return &ExtensionsRemoveStorageItemsParams{
		ID:          id,
		StorageArea: storageArea,
		Keys:        keys,
	}
}

// Do executes Extensions.removeStorageItems.
func (p *ExtensionsRemoveStorageItemsParams) Do(ctx context.Context) error {
	return Execute(ctx, ExtensionsCommandRemoveStorageItems, p, nil)
}

// ExtensionsClearStorageItemsParams Clears extension storage in the given `storageArea`.
type ExtensionsClearStorageItemsParams struct {
	// ID ID of extension.
	ID string `json:"id"`
	// StorageArea StorageArea to remove data from.
	StorageArea ExtensionsStorageArea `json:"storageArea"`
}

// ExtensionsClearStorageItems creates a new ExtensionsClearStorageItemsParams.
func ExtensionsClearStorageItems(id string, storageArea ExtensionsStorageArea) *ExtensionsClearStorageItemsParams {
	return &ExtensionsClearStorageItemsParams{
		ID:          id,
		StorageArea: storageArea,
	}
}

// Do executes Extensions.clearStorageItems.
func (p *ExtensionsClearStorageItemsParams) Do(ctx context.Context) error {
	return Execute(ctx, ExtensionsCommandClearStorageItems, p, nil)
}

// ExtensionsSetStorageItemsParams Sets `values` in extension storage in the given `storageArea`. The provided `values`
// will be merged with existing values in the storage area.
type ExtensionsSetStorageItemsParams struct {
	// ID ID of extension.
	ID string `json:"id"`
	// StorageArea StorageArea to set data in.
	StorageArea ExtensionsStorageArea `json:"storageArea"`
	// Values Values to set.
	Values json.RawMessage `json:"values"`
}

// ExtensionsSetStorageItems creates a new ExtensionsSetStorageItemsParams.
func ExtensionsSetStorageItems(id string, storageArea ExtensionsStorageArea, values json.RawMessage) *ExtensionsSetStorageItemsParams {
	return &ExtensionsSetStorageItemsParams{
		ID:          id,
		StorageArea: storageArea,
		Values:      values,
	}
}

// Do executes Extensions.setStorageItems.
func (p *ExtensionsSetStorageItemsParams) Do(ctx context.Context) error {
	return Execute(ctx, ExtensionsCommandSetStorageItems, p, nil)
}

// Extensions command names.
const (
	ExtensionsCommandTriggerAction      Method = "Extensions.triggerAction"
	ExtensionsCommandLoadUnpacked       Method = "Extensions.loadUnpacked"
	ExtensionsCommandGetExtensions      Method = "Extensions.getExtensions"
	ExtensionsCommandUninstall          Method = "Extensions.uninstall"
	ExtensionsCommandGetStorageItems    Method = "Extensions.getStorageItems"
	ExtensionsCommandRemoveStorageItems Method = "Extensions.removeStorageItems"
	ExtensionsCommandClearStorageItems  Method = "Extensions.clearStorageItems"
	ExtensionsCommandSetStorageItems    Method = "Extensions.setStorageItems"
)
