// Code generated by bonkgen. DO NOT EDIT.

package proto

import "context"

// FetchDisableParams Disables the fetch domain.
type FetchDisableParams struct{}

// FetchDisable creates a new FetchDisableParams.
func FetchDisable() *FetchDisableParams {
	return &FetchDisableParams{}
}

// Do executes Fetch.disable.
func (p *FetchDisableParams) Do(ctx context.Context) error {
	return Execute(ctx, FetchCommandDisable, p, nil)
}

// FetchEnableParams Enables issuing of requestPaused events. A request will be paused until client
// calls one of failRequest, fulfillRequest or continueRequest/continueWithAuth.
type FetchEnableParams struct {
	// Patterns If specified, only requests matching any of these patterns will produce
	// fetchRequested event and will be paused until clients response. If not set,
	// all requests will be affected.
	Patterns []FetchRequestPattern `json:"patterns,omitempty"`
	// HandleAuthRequests If true, authRequired events will be issued and requests will be paused
	// expecting a call to continueWithAuth.
	HandleAuthRequests bool `json:"handleAuthRequests,omitempty"`
}

// FetchEnable creates a new FetchEnableParams.
func FetchEnable() *FetchEnableParams {
	return &FetchEnableParams{}
}

// WithPatterns sets the patterns parameter.
func (p *FetchEnableParams) WithPatterns(patterns []FetchRequestPattern) *FetchEnableParams {
	p.Patterns = patterns
	return p
}

// WithHandleAuthRequests sets the handleAuthRequests parameter.
func (p *FetchEnableParams) WithHandleAuthRequests(handleAuthRequests bool) *FetchEnableParams {
	p.HandleAuthRequests = handleAuthRequests
	return p
}

// Do executes Fetch.enable.
func (p *FetchEnableParams) Do(ctx context.Context) error {
	return Execute(ctx, FetchCommandEnable, p, nil)
}

// FetchFailRequestParams Causes the request to fail with specified reason.
type FetchFailRequestParams struct {
	// RequestID An id the client received in requestPaused event.
	RequestID RequestID `json:"requestId"`
	// ErrorReason Causes the request to fail with the given reason.
	ErrorReason NetworkErrorReason `json:"errorReason"`
}

// FetchFailRequest creates a new FetchFailRequestParams.
func FetchFailRequest(requestID RequestID, errorReason NetworkErrorReason) *FetchFailRequestParams {
	return &FetchFailRequestParams{
		RequestID:   requestID,
		ErrorReason: errorReason,
	}
}

// Do executes Fetch.failRequest.
func (p *FetchFailRequestParams) Do(ctx context.Context) error {
	return Execute(ctx, FetchCommandFailRequest, p, nil)
}

// FetchFulfillRequestParams Provides response to the request.
type FetchFulfillRequestParams struct {
	// RequestID An id the client received in requestPaused event.
	RequestID RequestID `json:"requestId"`
	// ResponseCode An HTTP response code.
	ResponseCode int64 `json:"responseCode"`
	// ResponseHeaders Response headers.
	ResponseHeaders []FetchHeaderEntry `json:"responseHeaders,omitempty"`
	// BinaryResponseHeaders Alternative way of specifying response headers as a \0-separated
	// series of name: value pairs. Prefer the above method unless you
	// need to represent some non-UTF8 values that can't be transmitted
	// over the protocol as text.
	BinaryResponseHeaders []byte `json:"binaryResponseHeaders,omitempty"`
	// Body A response body. If absent, original response body will be used if
	// the request is intercepted at the response stage and empty body
	// will be used if the request is intercepted at the request stage.
	Body []byte `json:"body,omitempty"`
	// ResponsePhrase A textual representation of responseCode.
	// If absent, a standard phrase matching responseCode is used.
	ResponsePhrase string `json:"responsePhrase,omitempty"`
}

// FetchFulfillRequest creates a new FetchFulfillRequestParams.
func FetchFulfillRequest(requestID RequestID, responseCode int64) *FetchFulfillRequestParams {
	return &FetchFulfillRequestParams{
		RequestID:    requestID,
		ResponseCode: responseCode,
	}
}

// WithResponseHeaders sets the responseHeaders parameter.
func (p *FetchFulfillRequestParams) WithResponseHeaders(responseHeaders []FetchHeaderEntry) *FetchFulfillRequestParams {
	p.ResponseHeaders = responseHeaders
	return p
}

// WithBinaryResponseHeaders sets the binaryResponseHeaders parameter.
func (p *FetchFulfillRequestParams) WithBinaryResponseHeaders(binaryResponseHeaders []byte) *FetchFulfillRequestParams {
	p.BinaryResponseHeaders = binaryResponseHeaders
	return p
}

// WithBody sets the body parameter.
func (p *FetchFulfillRequestParams) WithBody(body []byte) *FetchFulfillRequestParams {
	p.Body = body
	return p
}

// WithResponsePhrase sets the responsePhrase parameter.
func (p *FetchFulfillRequestParams) WithResponsePhrase(responsePhrase string) *FetchFulfillRequestParams {
	p.ResponsePhrase = responsePhrase
	return p
}

// Do executes Fetch.fulfillRequest.
func (p *FetchFulfillRequestParams) Do(ctx context.Context) error {
	return Execute(ctx, FetchCommandFulfillRequest, p, nil)
}

// FetchContinueRequestParams Continues the request, optionally modifying some of its parameters.
type FetchContinueRequestParams struct {
	// RequestID An id the client received in requestPaused event.
	RequestID RequestID `json:"requestId"`
	// URL If set, the request url will be modified in a way that's not observable by page.
	URL string `json:"url,omitempty"`
	// Method If set, the request method is overridden.
	Method string `json:"method,omitempty"`
	// PostData If set, overrides the post data in the request.
	PostData []byte `json:"postData,omitempty"`
	// Headers If set, overrides the request headers. Note that the overrides do not
	// extend to subsequent redirect hops, if a redirect happens. Another override
	// may be applied to a different request produced by a redirect.
	Headers []FetchHeaderEntry `json:"headers,omitempty"`
	// InterceptResponse If set, overrides response interception behavior for this request.
	InterceptResponse bool `json:"interceptResponse,omitempty"`
}

// FetchContinueRequest creates a new FetchContinueRequestParams.
func FetchContinueRequest(requestID RequestID) *FetchContinueRequestParams {
	return &FetchContinueRequestParams{
		RequestID: requestID,
	}
}

// WithURL sets the url parameter.
func (p *FetchContinueRequestParams) WithURL(url string) *FetchContinueRequestParams {
	p.URL = url
	return p
}

// WithMethod sets the method parameter.
func (p *FetchContinueRequestParams) WithMethod(method string) *FetchContinueRequestParams {
	p.Method = method
	return p
}

// WithPostData sets the postData parameter.
func (p *FetchContinueRequestParams) WithPostData(postData []byte) *FetchContinueRequestParams {
	p.PostData = postData
	return p
}

// WithHeaders sets the headers parameter.
func (p *FetchContinueRequestParams) WithHeaders(headers []FetchHeaderEntry) *FetchContinueRequestParams {
	p.Headers = headers
	return p
}

// WithInterceptResponse sets the interceptResponse parameter.
func (p *FetchContinueRequestParams) WithInterceptResponse(interceptResponse bool) *FetchContinueRequestParams {
	p.InterceptResponse = interceptResponse
	return p
}

// Do executes Fetch.continueRequest.
func (p *FetchContinueRequestParams) Do(ctx context.Context) error {
	return Execute(ctx, FetchCommandContinueRequest, p, nil)
}

// FetchContinueWithAuthParams Continues a request supplying authChallengeResponse following authRequired event.
type FetchContinueWithAuthParams struct {
	// RequestID An id the client received in authRequired event.
	RequestID RequestID `json:"requestId"`
	// AuthChallengeResponse Response to  with an authChallenge.
	AuthChallengeResponse FetchAuthChallengeResponse `json:"authChallengeResponse"`
}

// FetchContinueWithAuth creates a new FetchContinueWithAuthParams.
func FetchContinueWithAuth(requestID RequestID, authChallengeResponse FetchAuthChallengeResponse) *FetchContinueWithAuthParams {
	return &FetchContinueWithAuthParams{
		RequestID:             requestID,
		AuthChallengeResponse: authChallengeResponse,
	}
}

// Do executes Fetch.continueWithAuth.
func (p *FetchContinueWithAuthParams) Do(ctx context.Context) error {
	return Execute(ctx, FetchCommandContinueWithAuth, p, nil)
}

// FetchContinueResponseParams Continues loading of the paused response, optionally modifying the
// response headers. If either responseCode or headers are modified, all of them
// must be present.
type FetchContinueResponseParams struct {
	// RequestID An id the client received in requestPaused event.
	RequestID RequestID `json:"requestId"`
	// ResponseCode An HTTP response code. If absent, original response code will be used.
	ResponseCode int64 `json:"responseCode,omitempty"`
	// ResponsePhrase A textual representation of responseCode.
	// If absent, a standard phrase matching responseCode is used.
	ResponsePhrase string `json:"responsePhrase,omitempty"`
	// ResponseHeaders Response headers. If absent, original response headers will be used.
	ResponseHeaders []FetchHeaderEntry `json:"responseHeaders,omitempty"`
	// BinaryResponseHeaders Alternative way of specifying response headers as a \0-separated
	// series of name: value pairs. Prefer the above method unless you
	// need to represent some non-UTF8 values that can't be transmitted
	// over the protocol as text.
	BinaryResponseHeaders []byte `json:"binaryResponseHeaders,omitempty"`
}

// FetchContinueResponse creates a new FetchContinueResponseParams.
func FetchContinueResponse(requestID RequestID) *FetchContinueResponseParams {
	return &FetchContinueResponseParams{
		RequestID: requestID,
	}
}

// WithResponseCode sets the responseCode parameter.
func (p *FetchContinueResponseParams) WithResponseCode(responseCode int64) *FetchContinueResponseParams {
	p.ResponseCode = responseCode
	return p
}

// WithResponsePhrase sets the responsePhrase parameter.
func (p *FetchContinueResponseParams) WithResponsePhrase(responsePhrase string) *FetchContinueResponseParams {
	p.ResponsePhrase = responsePhrase
	return p
}

// WithResponseHeaders sets the responseHeaders parameter.
func (p *FetchContinueResponseParams) WithResponseHeaders(responseHeaders []FetchHeaderEntry) *FetchContinueResponseParams {
	p.ResponseHeaders = responseHeaders
	return p
}

// WithBinaryResponseHeaders sets the binaryResponseHeaders parameter.
func (p *FetchContinueResponseParams) WithBinaryResponseHeaders(binaryResponseHeaders []byte) *FetchContinueResponseParams {
	p.BinaryResponseHeaders = binaryResponseHeaders
	return p
}

// Do executes Fetch.continueResponse.
func (p *FetchContinueResponseParams) Do(ctx context.Context) error {
	return Execute(ctx, FetchCommandContinueResponse, p, nil)
}

// FetchGetResponseBodyParams Causes the body of the response to be received from the server and
// returned as a single string. May only be issued for a request that
// is paused in the Response stage and is mutually exclusive with
// takeResponseBodyForInterceptionAsStream. Calling other methods that
// affect the request or disabling fetch domain before body is received
// results in an undefined behavior.
// Note that the response body is not available for redirects. Requests
// paused in the _redirect received_ state may be differentiated by
// `responseCode` and presence of `location` response header, see
// comments to `requestPaused` for details.
type FetchGetResponseBodyParams struct {
	// RequestID Identifier for the intercepted request to get body for.
	RequestID RequestID `json:"requestId"`
}

// FetchGetResponseBodyReturns holds the return values for getResponseBody.
type FetchGetResponseBodyReturns struct {
	// Body Response body.
	Body string `json:"body"`
	// Base64Encoded True, if content was sent as base64.
	Base64Encoded bool `json:"base64Encoded"`
}

// FetchGetResponseBody creates a new FetchGetResponseBodyParams.
func FetchGetResponseBody(requestID RequestID) *FetchGetResponseBodyParams {
	return &FetchGetResponseBodyParams{
		RequestID: requestID,
	}
}

// Do executes Fetch.getResponseBody.
func (p *FetchGetResponseBodyParams) Do(ctx context.Context) (*FetchGetResponseBodyReturns, error) {
	var res FetchGetResponseBodyReturns
	if err := Execute(ctx, FetchCommandGetResponseBody, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// FetchTakeResponseBodyAsStreamParams Returns a handle to the stream representing the response body.
// The request must be paused in the HeadersReceived stage.
// Note that after this command the request can't be continued
// as is -- client either needs to cancel it or to provide the
// response body.
// The stream only supports sequential read, IO.read will fail if the position
// is specified.
// This method is mutually exclusive with getResponseBody.
// Calling other methods that affect the request or disabling fetch
// domain before body is received results in an undefined behavior.
type FetchTakeResponseBodyAsStreamParams struct {
	RequestID RequestID `json:"requestId"`
}

// FetchTakeResponseBodyAsStreamReturns holds the return values for takeResponseBodyAsStream.
type FetchTakeResponseBodyAsStreamReturns struct {
	Stream IOStreamHandle `json:"stream"`
}

// FetchTakeResponseBodyAsStream creates a new FetchTakeResponseBodyAsStreamParams.
func FetchTakeResponseBodyAsStream(requestID RequestID) *FetchTakeResponseBodyAsStreamParams {
	return &FetchTakeResponseBodyAsStreamParams{
		RequestID: requestID,
	}
}

// Do executes Fetch.takeResponseBodyAsStream.
func (p *FetchTakeResponseBodyAsStreamParams) Do(ctx context.Context) (*FetchTakeResponseBodyAsStreamReturns, error) {
	var res FetchTakeResponseBodyAsStreamReturns
	if err := Execute(ctx, FetchCommandTakeResponseBodyAsStream, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// Fetch command names.
const (
	FetchCommandDisable                  Method = "Fetch.disable"
	FetchCommandEnable                   Method = "Fetch.enable"
	FetchCommandFailRequest              Method = "Fetch.failRequest"
	FetchCommandFulfillRequest           Method = "Fetch.fulfillRequest"
	FetchCommandContinueRequest          Method = "Fetch.continueRequest"
	FetchCommandContinueWithAuth         Method = "Fetch.continueWithAuth"
	FetchCommandContinueResponse         Method = "Fetch.continueResponse"
	FetchCommandGetResponseBody          Method = "Fetch.getResponseBody"
	FetchCommandTakeResponseBodyAsStream Method = "Fetch.takeResponseBodyAsStream"
)
