// Code generated by bonkgen. DO NOT EDIT.

package proto

import "context"

type FileSystemGetDirectoryParams struct {
	BucketFileSystemLocator FileSystemBucketFileSystemLocator `json:"bucketFileSystemLocator"`
}

// FileSystemGetDirectoryReturns holds the return values for getDirectory.
type FileSystemGetDirectoryReturns struct {
	// Directory Returns the directory object at the path.
	Directory FileSystemDirectory `json:"directory"`
}

// FileSystemGetDirectory creates a new FileSystemGetDirectoryParams.
func FileSystemGetDirectory(bucketFileSystemLocator FileSystemBucketFileSystemLocator) *FileSystemGetDirectoryParams {
	return &FileSystemGetDirectoryParams{
		BucketFileSystemLocator: bucketFileSystemLocator,
	}
}

// Do executes FileSystem.getDirectory.
func (p *FileSystemGetDirectoryParams) Do(ctx context.Context) (*FileSystemGetDirectoryReturns, error) {
	var res FileSystemGetDirectoryReturns
	if err := Execute(ctx, FileSystemCommandGetDirectory, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// FileSystem command names.
const (
	FileSystemCommandGetDirectory Method = "FileSystem.getDirectory"
)
