// Code generated by bonkgen. DO NOT EDIT.

package proto

import "context"

// HeadlessExperimentalBeginFrameParams Sends a BeginFrame to the target and returns when the frame was completed. Optionally captures a
// screenshot from the resulting frame. Requires that the target was created with enabled
// BeginFrameControl. Designed for use with --run-all-compositor-stages-before-draw, see also
// https://goo.gle/chrome-headless-rendering for more background.
type HeadlessExperimentalBeginFrameParams struct {
	// FrameTimeTicks Timestamp of this BeginFrame in Renderer TimeTicks (milliseconds of uptime). If not set,
	// the current time will be used.
	FrameTimeTicks float64 `json:"frameTimeTicks,omitempty,omitzero"`
	// Interval The interval between BeginFrames that is reported to the compositor, in milliseconds.
	// Defaults to a 60 frames/second interval, i.e. about 16.666 milliseconds.
	Interval float64 `json:"interval,omitempty,omitzero"`
	// NoDisplayUpdates Whether updates should not be committed and drawn onto the display. False by default. If
	// true, only side effects of the BeginFrame will be run, such as layout and animations, but
	// any visual updates may not be visible on the display or in screenshots.
	NoDisplayUpdates bool `json:"noDisplayUpdates,omitempty,omitzero"`
	// Screenshot If set, a screenshot of the frame will be captured and returned in the response. Otherwise,
	// no screenshot will be captured. Note that capturing a screenshot can fail, for example,
	// during renderer initialization. In such a case, no screenshot data will be returned.
	Screenshot HeadlessExperimentalScreenshotParams `json:"screenshot,omitempty,omitzero"`
}

// HeadlessExperimentalBeginFrameReturns holds the return values for beginFrame.
type HeadlessExperimentalBeginFrameReturns struct {
	// HasDamage Whether the BeginFrame resulted in damage and, thus, a new frame was committed to the
	// display. Reported for diagnostic uses, may be removed in the future.
	HasDamage bool `json:"hasDamage"`
	// ScreenshotData Base64-encoded image data of the screenshot, if one was requested and successfully taken.
	ScreenshotData []byte `json:"screenshotData,omitempty,omitzero"`
}

// HeadlessExperimentalBeginFrame creates a new HeadlessExperimentalBeginFrameParams.
func HeadlessExperimentalBeginFrame() *HeadlessExperimentalBeginFrameParams {
	return &HeadlessExperimentalBeginFrameParams{}
}

// WithFrameTimeTicks sets the frameTimeTicks parameter.
func (p *HeadlessExperimentalBeginFrameParams) WithFrameTimeTicks(frameTimeTicks float64) *HeadlessExperimentalBeginFrameParams {
	p.FrameTimeTicks = frameTimeTicks
	return p
}

// WithInterval sets the interval parameter.
func (p *HeadlessExperimentalBeginFrameParams) WithInterval(interval float64) *HeadlessExperimentalBeginFrameParams {
	p.Interval = interval
	return p
}

// WithNoDisplayUpdates sets the noDisplayUpdates parameter.
func (p *HeadlessExperimentalBeginFrameParams) WithNoDisplayUpdates(noDisplayUpdates bool) *HeadlessExperimentalBeginFrameParams {
	p.NoDisplayUpdates = noDisplayUpdates
	return p
}

// WithScreenshot sets the screenshot parameter.
func (p *HeadlessExperimentalBeginFrameParams) WithScreenshot(screenshot HeadlessExperimentalScreenshotParams) *HeadlessExperimentalBeginFrameParams {
	p.Screenshot = screenshot
	return p
}

// Do executes HeadlessExperimental.beginFrame.
func (p *HeadlessExperimentalBeginFrameParams) Do(ctx context.Context) (*HeadlessExperimentalBeginFrameReturns, error) {
	var res HeadlessExperimentalBeginFrameReturns
	if err := Execute(ctx, HeadlessExperimentalCommandBeginFrame, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// HeadlessExperimentalDisableParams Disables headless events for the target.
type HeadlessExperimentalDisableParams struct{}

// HeadlessExperimentalDisable creates a new HeadlessExperimentalDisableParams.
func HeadlessExperimentalDisable() *HeadlessExperimentalDisableParams {
	return &HeadlessExperimentalDisableParams{}
}

// Do executes HeadlessExperimental.disable.
func (p *HeadlessExperimentalDisableParams) Do(ctx context.Context) error {
	return Execute(ctx, HeadlessExperimentalCommandDisable, p, nil)
}

// HeadlessExperimentalEnableParams Enables headless events for the target.
type HeadlessExperimentalEnableParams struct{}

// HeadlessExperimentalEnable creates a new HeadlessExperimentalEnableParams.
func HeadlessExperimentalEnable() *HeadlessExperimentalEnableParams {
	return &HeadlessExperimentalEnableParams{}
}

// Do executes HeadlessExperimental.enable.
func (p *HeadlessExperimentalEnableParams) Do(ctx context.Context) error {
	return Execute(ctx, HeadlessExperimentalCommandEnable, p, nil)
}

// HeadlessExperimental command names.
const (
	HeadlessExperimentalCommandBeginFrame Method = "HeadlessExperimental.beginFrame"
	HeadlessExperimentalCommandDisable    Method = "HeadlessExperimental.disable"
	HeadlessExperimentalCommandEnable     Method = "HeadlessExperimental.enable"
)
