// Code generated by bonkgen. DO NOT EDIT.

package proto

type HeapProfilerEventAddHeapSnapshotChunk struct {
	Chunk string `json:"chunk"`
}

// HeapProfilerEventHeapStatsUpdate If heap objects tracking has been started then backend may send update for one or more fragments
type HeapProfilerEventHeapStatsUpdate struct {
	// StatsUpdate An array of triplets. Each triplet describes a fragment. The first integer is the fragment
	// index, the second integer is a total count of objects for the fragment, the third integer is
	// a total size of the objects for the fragment.
	StatsUpdate []int64 `json:"statsUpdate"`
}

// HeapProfilerEventLastSeenObjectID If heap objects tracking has been started then backend regularly sends a current value for last
// seen object id and corresponding timestamp. If the were changes in the heap since last event
// then one or more heapStatsUpdate events will be sent before a new lastSeenObjectId event.
type HeapProfilerEventLastSeenObjectID struct {
	LastSeenObjectID int64   `json:"lastSeenObjectId"`
	Timestamp        float64 `json:"timestamp"`
}

type HeapProfilerEventReportHeapSnapshotProgress struct {
	Done     int64 `json:"done"`
	Total    int64 `json:"total"`
	Finished bool  `json:"finished,omitempty"`
}

type HeapProfilerEventResetProfiles struct{}

// HeapProfiler event names.
const (
	HeapProfilerEventAddHeapSnapshotChunkMethod       Method = "HeapProfiler.addHeapSnapshotChunk"
	HeapProfilerEventHeapStatsUpdateMethod            Method = "HeapProfiler.heapStatsUpdate"
	HeapProfilerEventLastSeenObjectIDMethod           Method = "HeapProfiler.lastSeenObjectId"
	HeapProfilerEventReportHeapSnapshotProgressMethod Method = "HeapProfiler.reportHeapSnapshotProgress"
	HeapProfilerEventResetProfilesMethod              Method = "HeapProfiler.resetProfiles"
)
