// Code generated by bonkgen. DO NOT EDIT.

package proto

import "context"

// IndexedDBClearObjectStoreParams Clears all entries from an object store.
type IndexedDBClearObjectStoreParams struct {
	// SecurityOrigin At least and at most one of securityOrigin, storageKey, or storageBucket must be specified.
	// Security origin.
	SecurityOrigin string `json:"securityOrigin,omitempty"`
	// StorageKey Storage key.
	StorageKey string `json:"storageKey,omitempty"`
	// StorageBucket Storage bucket. If not specified, it uses the default bucket.
	StorageBucket StorageStorageBucket `json:"storageBucket,omitempty"`
	// DatabaseName Database name.
	DatabaseName string `json:"databaseName"`
	// ObjectStoreName Object store name.
	ObjectStoreName string `json:"objectStoreName"`
}

// IndexedDBClearObjectStore creates a new IndexedDBClearObjectStoreParams.
func IndexedDBClearObjectStore(databaseName string, objectStoreName string) *IndexedDBClearObjectStoreParams {
	return &IndexedDBClearObjectStoreParams{
		DatabaseName:    databaseName,
		ObjectStoreName: objectStoreName,
	}
}

// WithSecurityOrigin sets the securityOrigin parameter.
func (p *IndexedDBClearObjectStoreParams) WithSecurityOrigin(securityOrigin string) *IndexedDBClearObjectStoreParams {
	p.SecurityOrigin = securityOrigin
	return p
}

// WithStorageKey sets the storageKey parameter.
func (p *IndexedDBClearObjectStoreParams) WithStorageKey(storageKey string) *IndexedDBClearObjectStoreParams {
	p.StorageKey = storageKey
	return p
}

// WithStorageBucket sets the storageBucket parameter.
func (p *IndexedDBClearObjectStoreParams) WithStorageBucket(storageBucket StorageStorageBucket) *IndexedDBClearObjectStoreParams {
	p.StorageBucket = storageBucket
	return p
}

// Do executes IndexedDB.clearObjectStore.
func (p *IndexedDBClearObjectStoreParams) Do(ctx context.Context) error {
	return Execute(ctx, IndexedDBCommandClearObjectStore, p, nil)
}

// IndexedDBDeleteDatabaseParams Deletes a database.
type IndexedDBDeleteDatabaseParams struct {
	// SecurityOrigin At least and at most one of securityOrigin, storageKey, or storageBucket must be specified.
	// Security origin.
	SecurityOrigin string `json:"securityOrigin,omitempty"`
	// StorageKey Storage key.
	StorageKey string `json:"storageKey,omitempty"`
	// StorageBucket Storage bucket. If not specified, it uses the default bucket.
	StorageBucket StorageStorageBucket `json:"storageBucket,omitempty"`
	// DatabaseName Database name.
	DatabaseName string `json:"databaseName"`
}

// IndexedDBDeleteDatabase creates a new IndexedDBDeleteDatabaseParams.
func IndexedDBDeleteDatabase(databaseName string) *IndexedDBDeleteDatabaseParams {
	return &IndexedDBDeleteDatabaseParams{
		DatabaseName: databaseName,
	}
}

// WithSecurityOrigin sets the securityOrigin parameter.
func (p *IndexedDBDeleteDatabaseParams) WithSecurityOrigin(securityOrigin string) *IndexedDBDeleteDatabaseParams {
	p.SecurityOrigin = securityOrigin
	return p
}

// WithStorageKey sets the storageKey parameter.
func (p *IndexedDBDeleteDatabaseParams) WithStorageKey(storageKey string) *IndexedDBDeleteDatabaseParams {
	p.StorageKey = storageKey
	return p
}

// WithStorageBucket sets the storageBucket parameter.
func (p *IndexedDBDeleteDatabaseParams) WithStorageBucket(storageBucket StorageStorageBucket) *IndexedDBDeleteDatabaseParams {
	p.StorageBucket = storageBucket
	return p
}

// Do executes IndexedDB.deleteDatabase.
func (p *IndexedDBDeleteDatabaseParams) Do(ctx context.Context) error {
	return Execute(ctx, IndexedDBCommandDeleteDatabase, p, nil)
}

// IndexedDBDeleteObjectStoreEntriesParams Delete a range of entries from an object store
type IndexedDBDeleteObjectStoreEntriesParams struct {
	// SecurityOrigin At least and at most one of securityOrigin, storageKey, or storageBucket must be specified.
	// Security origin.
	SecurityOrigin string `json:"securityOrigin,omitempty"`
	// StorageKey Storage key.
	StorageKey string `json:"storageKey,omitempty"`
	// StorageBucket Storage bucket. If not specified, it uses the default bucket.
	StorageBucket   StorageStorageBucket `json:"storageBucket,omitempty"`
	DatabaseName    string               `json:"databaseName"`
	ObjectStoreName string               `json:"objectStoreName"`
	// KeyRange Range of entry keys to delete
	KeyRange IndexedDBKeyRange `json:"keyRange"`
}

// IndexedDBDeleteObjectStoreEntries creates a new IndexedDBDeleteObjectStoreEntriesParams.
func IndexedDBDeleteObjectStoreEntries(databaseName string, objectStoreName string, keyRange IndexedDBKeyRange) *IndexedDBDeleteObjectStoreEntriesParams {
	return &IndexedDBDeleteObjectStoreEntriesParams{
		DatabaseName:    databaseName,
		ObjectStoreName: objectStoreName,
		KeyRange:        keyRange,
	}
}

// WithSecurityOrigin sets the securityOrigin parameter.
func (p *IndexedDBDeleteObjectStoreEntriesParams) WithSecurityOrigin(securityOrigin string) *IndexedDBDeleteObjectStoreEntriesParams {
	p.SecurityOrigin = securityOrigin
	return p
}

// WithStorageKey sets the storageKey parameter.
func (p *IndexedDBDeleteObjectStoreEntriesParams) WithStorageKey(storageKey string) *IndexedDBDeleteObjectStoreEntriesParams {
	p.StorageKey = storageKey
	return p
}

// WithStorageBucket sets the storageBucket parameter.
func (p *IndexedDBDeleteObjectStoreEntriesParams) WithStorageBucket(storageBucket StorageStorageBucket) *IndexedDBDeleteObjectStoreEntriesParams {
	p.StorageBucket = storageBucket
	return p
}

// Do executes IndexedDB.deleteObjectStoreEntries.
func (p *IndexedDBDeleteObjectStoreEntriesParams) Do(ctx context.Context) error {
	return Execute(ctx, IndexedDBCommandDeleteObjectStoreEntries, p, nil)
}

// IndexedDBDisableParams Disables events from backend.
type IndexedDBDisableParams struct{}

// IndexedDBDisable creates a new IndexedDBDisableParams.
func IndexedDBDisable() *IndexedDBDisableParams {
	return &IndexedDBDisableParams{}
}

// Do executes IndexedDB.disable.
func (p *IndexedDBDisableParams) Do(ctx context.Context) error {
	return Execute(ctx, IndexedDBCommandDisable, p, nil)
}

// IndexedDBEnableParams Enables events from backend.
type IndexedDBEnableParams struct{}

// IndexedDBEnable creates a new IndexedDBEnableParams.
func IndexedDBEnable() *IndexedDBEnableParams {
	return &IndexedDBEnableParams{}
}

// Do executes IndexedDB.enable.
func (p *IndexedDBEnableParams) Do(ctx context.Context) error {
	return Execute(ctx, IndexedDBCommandEnable, p, nil)
}

// IndexedDBRequestDataParams Requests data from object store or index.
type IndexedDBRequestDataParams struct {
	// SecurityOrigin At least and at most one of securityOrigin, storageKey, or storageBucket must be specified.
	// Security origin.
	SecurityOrigin string `json:"securityOrigin,omitempty"`
	// StorageKey Storage key.
	StorageKey string `json:"storageKey,omitempty"`
	// StorageBucket Storage bucket. If not specified, it uses the default bucket.
	StorageBucket StorageStorageBucket `json:"storageBucket,omitempty"`
	// DatabaseName Database name.
	DatabaseName string `json:"databaseName"`
	// ObjectStoreName Object store name.
	ObjectStoreName string `json:"objectStoreName"`
	// IndexName Index name. If not specified, it performs an object store data request.
	IndexName string `json:"indexName,omitempty"`
	// SkipCount Number of records to skip.
	SkipCount int64 `json:"skipCount"`
	// PageSize Number of records to fetch.
	PageSize int64 `json:"pageSize"`
	// KeyRange Key range.
	KeyRange IndexedDBKeyRange `json:"keyRange,omitempty"`
}

// IndexedDBRequestDataReturns holds the return values for requestData.
type IndexedDBRequestDataReturns struct {
	// ObjectStoreDataEntries Array of object store data entries.
	ObjectStoreDataEntries []IndexedDBDataEntry `json:"objectStoreDataEntries"`
	// HasMore If true, there are more entries to fetch in the given range.
	HasMore bool `json:"hasMore"`
}

// IndexedDBRequestData creates a new IndexedDBRequestDataParams.
func IndexedDBRequestData(databaseName string, objectStoreName string, skipCount int64, pageSize int64) *IndexedDBRequestDataParams {
	return &IndexedDBRequestDataParams{
		DatabaseName:    databaseName,
		ObjectStoreName: objectStoreName,
		SkipCount:       skipCount,
		PageSize:        pageSize,
	}
}

// WithSecurityOrigin sets the securityOrigin parameter.
func (p *IndexedDBRequestDataParams) WithSecurityOrigin(securityOrigin string) *IndexedDBRequestDataParams {
	p.SecurityOrigin = securityOrigin
	return p
}

// WithStorageKey sets the storageKey parameter.
func (p *IndexedDBRequestDataParams) WithStorageKey(storageKey string) *IndexedDBRequestDataParams {
	p.StorageKey = storageKey
	return p
}

// WithStorageBucket sets the storageBucket parameter.
func (p *IndexedDBRequestDataParams) WithStorageBucket(storageBucket StorageStorageBucket) *IndexedDBRequestDataParams {
	p.StorageBucket = storageBucket
	return p
}

// WithIndexName sets the indexName parameter.
func (p *IndexedDBRequestDataParams) WithIndexName(indexName string) *IndexedDBRequestDataParams {
	p.IndexName = indexName
	return p
}

// WithKeyRange sets the keyRange parameter.
func (p *IndexedDBRequestDataParams) WithKeyRange(keyRange IndexedDBKeyRange) *IndexedDBRequestDataParams {
	p.KeyRange = keyRange
	return p
}

// Do executes IndexedDB.requestData.
func (p *IndexedDBRequestDataParams) Do(ctx context.Context) (*IndexedDBRequestDataReturns, error) {
	var res IndexedDBRequestDataReturns
	if err := Execute(ctx, IndexedDBCommandRequestData, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// IndexedDBGetMetadataParams Gets metadata of an object store.
type IndexedDBGetMetadataParams struct {
	// SecurityOrigin At least and at most one of securityOrigin, storageKey, or storageBucket must be specified.
	// Security origin.
	SecurityOrigin string `json:"securityOrigin,omitempty"`
	// StorageKey Storage key.
	StorageKey string `json:"storageKey,omitempty"`
	// StorageBucket Storage bucket. If not specified, it uses the default bucket.
	StorageBucket StorageStorageBucket `json:"storageBucket,omitempty"`
	// DatabaseName Database name.
	DatabaseName string `json:"databaseName"`
	// ObjectStoreName Object store name.
	ObjectStoreName string `json:"objectStoreName"`
}

// IndexedDBGetMetadataReturns holds the return values for getMetadata.
type IndexedDBGetMetadataReturns struct {
	// EntriesCount the entries count
	EntriesCount float64 `json:"entriesCount"`
	// KeyGeneratorValue the current value of key generator, to become the next inserted
	// key into the object store. Valid if objectStore.autoIncrement
	// is true.
	KeyGeneratorValue float64 `json:"keyGeneratorValue"`
}

// IndexedDBGetMetadata creates a new IndexedDBGetMetadataParams.
func IndexedDBGetMetadata(databaseName string, objectStoreName string) *IndexedDBGetMetadataParams {
	return &IndexedDBGetMetadataParams{
		DatabaseName:    databaseName,
		ObjectStoreName: objectStoreName,
	}
}

// WithSecurityOrigin sets the securityOrigin parameter.
func (p *IndexedDBGetMetadataParams) WithSecurityOrigin(securityOrigin string) *IndexedDBGetMetadataParams {
	p.SecurityOrigin = securityOrigin
	return p
}

// WithStorageKey sets the storageKey parameter.
func (p *IndexedDBGetMetadataParams) WithStorageKey(storageKey string) *IndexedDBGetMetadataParams {
	p.StorageKey = storageKey
	return p
}

// WithStorageBucket sets the storageBucket parameter.
func (p *IndexedDBGetMetadataParams) WithStorageBucket(storageBucket StorageStorageBucket) *IndexedDBGetMetadataParams {
	p.StorageBucket = storageBucket
	return p
}

// Do executes IndexedDB.getMetadata.
func (p *IndexedDBGetMetadataParams) Do(ctx context.Context) (*IndexedDBGetMetadataReturns, error) {
	var res IndexedDBGetMetadataReturns
	if err := Execute(ctx, IndexedDBCommandGetMetadata, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// IndexedDBRequestDatabaseParams Requests database with given name in given frame.
type IndexedDBRequestDatabaseParams struct {
	// SecurityOrigin At least and at most one of securityOrigin, storageKey, or storageBucket must be specified.
	// Security origin.
	SecurityOrigin string `json:"securityOrigin,omitempty"`
	// StorageKey Storage key.
	StorageKey string `json:"storageKey,omitempty"`
	// StorageBucket Storage bucket. If not specified, it uses the default bucket.
	StorageBucket StorageStorageBucket `json:"storageBucket,omitempty"`
	// DatabaseName Database name.
	DatabaseName string `json:"databaseName"`
}

// IndexedDBRequestDatabaseReturns holds the return values for requestDatabase.
type IndexedDBRequestDatabaseReturns struct {
	// DatabaseWithObjectStores Database with an array of object stores.
	DatabaseWithObjectStores IndexedDBDatabaseWithObjectStores `json:"databaseWithObjectStores"`
}

// IndexedDBRequestDatabase creates a new IndexedDBRequestDatabaseParams.
func IndexedDBRequestDatabase(databaseName string) *IndexedDBRequestDatabaseParams {
	return &IndexedDBRequestDatabaseParams{
		DatabaseName: databaseName,
	}
}

// WithSecurityOrigin sets the securityOrigin parameter.
func (p *IndexedDBRequestDatabaseParams) WithSecurityOrigin(securityOrigin string) *IndexedDBRequestDatabaseParams {
	p.SecurityOrigin = securityOrigin
	return p
}

// WithStorageKey sets the storageKey parameter.
func (p *IndexedDBRequestDatabaseParams) WithStorageKey(storageKey string) *IndexedDBRequestDatabaseParams {
	p.StorageKey = storageKey
	return p
}

// WithStorageBucket sets the storageBucket parameter.
func (p *IndexedDBRequestDatabaseParams) WithStorageBucket(storageBucket StorageStorageBucket) *IndexedDBRequestDatabaseParams {
	p.StorageBucket = storageBucket
	return p
}

// Do executes IndexedDB.requestDatabase.
func (p *IndexedDBRequestDatabaseParams) Do(ctx context.Context) (*IndexedDBRequestDatabaseReturns, error) {
	var res IndexedDBRequestDatabaseReturns
	if err := Execute(ctx, IndexedDBCommandRequestDatabase, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// IndexedDBRequestDatabaseNamesParams Requests database names for given security origin.
type IndexedDBRequestDatabaseNamesParams struct {
	// SecurityOrigin At least and at most one of securityOrigin, storageKey, or storageBucket must be specified.
	// Security origin.
	SecurityOrigin string `json:"securityOrigin,omitempty"`
	// StorageKey Storage key.
	StorageKey string `json:"storageKey,omitempty"`
	// StorageBucket Storage bucket. If not specified, it uses the default bucket.
	StorageBucket StorageStorageBucket `json:"storageBucket,omitempty"`
}

// IndexedDBRequestDatabaseNamesReturns holds the return values for requestDatabaseNames.
type IndexedDBRequestDatabaseNamesReturns struct {
	// DatabaseNames Database names for origin.
	DatabaseNames []string `json:"databaseNames"`
}

// IndexedDBRequestDatabaseNames creates a new IndexedDBRequestDatabaseNamesParams.
func IndexedDBRequestDatabaseNames() *IndexedDBRequestDatabaseNamesParams {
	return &IndexedDBRequestDatabaseNamesParams{}
}

// WithSecurityOrigin sets the securityOrigin parameter.
func (p *IndexedDBRequestDatabaseNamesParams) WithSecurityOrigin(securityOrigin string) *IndexedDBRequestDatabaseNamesParams {
	p.SecurityOrigin = securityOrigin
	return p
}

// WithStorageKey sets the storageKey parameter.
func (p *IndexedDBRequestDatabaseNamesParams) WithStorageKey(storageKey string) *IndexedDBRequestDatabaseNamesParams {
	p.StorageKey = storageKey
	return p
}

// WithStorageBucket sets the storageBucket parameter.
func (p *IndexedDBRequestDatabaseNamesParams) WithStorageBucket(storageBucket StorageStorageBucket) *IndexedDBRequestDatabaseNamesParams {
	p.StorageBucket = storageBucket
	return p
}

// Do executes IndexedDB.requestDatabaseNames.
func (p *IndexedDBRequestDatabaseNamesParams) Do(ctx context.Context) (*IndexedDBRequestDatabaseNamesReturns, error) {
	var res IndexedDBRequestDatabaseNamesReturns
	if err := Execute(ctx, IndexedDBCommandRequestDatabaseNames, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// IndexedDB command names.
const (
	IndexedDBCommandClearObjectStore         Method = "IndexedDB.clearObjectStore"
	IndexedDBCommandDeleteDatabase           Method = "IndexedDB.deleteDatabase"
	IndexedDBCommandDeleteObjectStoreEntries Method = "IndexedDB.deleteObjectStoreEntries"
	IndexedDBCommandDisable                  Method = "IndexedDB.disable"
	IndexedDBCommandEnable                   Method = "IndexedDB.enable"
	IndexedDBCommandRequestData              Method = "IndexedDB.requestData"
	IndexedDBCommandGetMetadata              Method = "IndexedDB.getMetadata"
	IndexedDBCommandRequestDatabase          Method = "IndexedDB.requestDatabase"
	IndexedDBCommandRequestDatabaseNames     Method = "IndexedDB.requestDatabaseNames"
)
