// Code generated by bonkgen. DO NOT EDIT.

package proto

// InspectorEventDetached Fired when remote debugging connection is about to be terminated. Contains detach reason.
type InspectorEventDetached struct {
	// Reason The reason why connection has been terminated.
	Reason string `json:"reason"`
}

// InspectorEventTargetCrashed Fired when debugging target has crashed
type InspectorEventTargetCrashed struct{}

// InspectorEventTargetReloadedAfterCrash Fired when debugging target has reloaded after crash
type InspectorEventTargetReloadedAfterCrash struct{}

// InspectorEventWorkerScriptLoaded Fired on worker targets when main worker script and any imported scripts have been evaluated.
type InspectorEventWorkerScriptLoaded struct{}

// Inspector event names.
const (
	InspectorEventDetachedMethod                 Method = "Inspector.detached"
	InspectorEventTargetCrashedMethod            Method = "Inspector.targetCrashed"
	InspectorEventTargetReloadedAfterCrashMethod Method = "Inspector.targetReloadedAfterCrash"
	InspectorEventWorkerScriptLoadedMethod       Method = "Inspector.workerScriptLoaded"
)
