// Code generated by bonkgen. DO NOT EDIT.

package proto

import "context"

// InspectorDisableParams Disables inspector domain notifications.
type InspectorDisableParams struct{}

// InspectorDisable creates a new InspectorDisableParams.
func InspectorDisable() *InspectorDisableParams {
	return &InspectorDisableParams{}
}

// Do executes Inspector.disable.
func (p *InspectorDisableParams) Do(ctx context.Context) error {
	return Execute(ctx, InspectorCommandDisable, p, nil)
}

// InspectorEnableParams Enables inspector domain notifications.
type InspectorEnableParams struct{}

// InspectorEnable creates a new InspectorEnableParams.
func InspectorEnable() *InspectorEnableParams {
	return &InspectorEnableParams{}
}

// Do executes Inspector.enable.
func (p *InspectorEnableParams) Do(ctx context.Context) error {
	return Execute(ctx, InspectorCommandEnable, p, nil)
}

// Inspector command names.
const (
	InspectorCommandDisable Method = "Inspector.disable"
	InspectorCommandEnable  Method = "Inspector.enable"
)
