// Code generated by bonkgen. DO NOT EDIT.

package proto

// LayerTreeLayerID Unique Layer identifier.
type LayerTreeLayerID string

// String returns the LayerTreeLayerID as a string.
func (t LayerTreeLayerID) String() string {
	return string(t)
}

// LayerTreeSnapshotID Unique snapshot identifier.
type LayerTreeSnapshotID string

// String returns the LayerTreeSnapshotID as a string.
func (t LayerTreeSnapshotID) String() string {
	return string(t)
}

// LayerTreeScrollRect Rectangle where scrolling happens on the main thread.
type LayerTreeScrollRect struct {
	// Rect Rectangle itself.
	Rect DOMRect `json:"rect"`
	// Type Reason for rectangle to force scrolling on the main thread
	Type LayerTreeScrollRectType `json:"type"`
}

// LayerTreeStickyPositionConstraint Sticky position constraints.
type LayerTreeStickyPositionConstraint struct {
	// StickyBoxRect Layout rectangle of the sticky element before being shifted
	StickyBoxRect DOMRect `json:"stickyBoxRect"`
	// ContainingBlockRect Layout rectangle of the containing block of the sticky element
	ContainingBlockRect DOMRect `json:"containingBlockRect"`
	// NearestLayerShiftingStickyBox The nearest sticky layer that shifts the sticky box
	NearestLayerShiftingStickyBox LayerTreeLayerID `json:"nearestLayerShiftingStickyBox,omitempty,omitzero"`
	// NearestLayerShiftingContainingBlock The nearest sticky layer that shifts the containing block
	NearestLayerShiftingContainingBlock LayerTreeLayerID `json:"nearestLayerShiftingContainingBlock,omitempty,omitzero"`
}

// LayerTreePictureTile Serialized fragment of layer picture along with its offset within the layer.
type LayerTreePictureTile struct {
	// X Offset from owning layer left boundary
	X float64 `json:"x"`
	// Y Offset from owning layer top boundary
	Y float64 `json:"y"`
	// Picture Base64-encoded snapshot data.
	Picture []byte `json:"picture"`
}

// LayerTreeLayer Information about a compositing layer.
type LayerTreeLayer struct {
	// LayerID The unique id for this layer.
	LayerID LayerTreeLayerID `json:"layerId"`
	// ParentLayerID The id of parent (not present for root).
	ParentLayerID LayerTreeLayerID `json:"parentLayerId,omitempty,omitzero"`
	// BackendNodeID The backend id for the node associated with this layer.
	BackendNodeID BackendNodeID `json:"backendNodeId,omitempty,omitzero"`
	// OffsetX Offset from parent layer, X coordinate.
	OffsetX float64 `json:"offsetX"`
	// OffsetY Offset from parent layer, Y coordinate.
	OffsetY float64 `json:"offsetY"`
	// Width Layer width.
	Width float64 `json:"width"`
	// Height Layer height.
	Height float64 `json:"height"`
	// Transform Transformation matrix for layer, default is identity matrix
	Transform []float64 `json:"transform,omitempty,omitzero"`
	// AnchorX Transform anchor point X, absent if no transform specified
	AnchorX float64 `json:"anchorX,omitempty,omitzero"`
	// AnchorY Transform anchor point Y, absent if no transform specified
	AnchorY float64 `json:"anchorY,omitempty,omitzero"`
	// AnchorZ Transform anchor point Z, absent if no transform specified
	AnchorZ float64 `json:"anchorZ,omitempty,omitzero"`
	// PaintCount Indicates how many time this layer has painted.
	PaintCount int64 `json:"paintCount"`
	// DrawsContent Indicates whether this layer hosts any content, rather than being used for
	// transform/scrolling purposes only.
	DrawsContent bool `json:"drawsContent"`
	// Invisible Set if layer is not visible.
	Invisible bool `json:"invisible,omitempty,omitzero"`
	// ScrollRects Rectangles scrolling on main thread only.
	ScrollRects []LayerTreeScrollRect `json:"scrollRects,omitempty,omitzero"`
	// StickyPositionConstraint Sticky position constraint information
	StickyPositionConstraint LayerTreeStickyPositionConstraint `json:"stickyPositionConstraint,omitempty,omitzero"`
}

// LayerTreePaintProfile Array of timings, one per paint step.
type LayerTreePaintProfile float64

// LayerTreeScrollRectType Reason for rectangle to force scrolling on the main thread
type LayerTreeScrollRectType string

const (
	LayerTreeScrollRectTypeRepaintsOnScroll  LayerTreeScrollRectType = "RepaintsOnScroll"
	LayerTreeScrollRectTypeTouchEventHandler LayerTreeScrollRectType = "TouchEventHandler"
	LayerTreeScrollRectTypeWheelEventHandler LayerTreeScrollRectType = "WheelEventHandler"
)

// IsValid reports whether the value is a known enum value.
func (t LayerTreeScrollRectType) IsValid() bool {
	switch t {
	case LayerTreeScrollRectTypeRepaintsOnScroll:
		return true
	case LayerTreeScrollRectTypeTouchEventHandler:
		return true
	case LayerTreeScrollRectTypeWheelEventHandler:
		return true
	}
	return false
}

// Values returns all known values of LayerTreeScrollRectType.
func (t LayerTreeScrollRectType) Values() []LayerTreeScrollRectType {
	return []LayerTreeScrollRectType{
		LayerTreeScrollRectTypeRepaintsOnScroll,
		LayerTreeScrollRectTypeTouchEventHandler,
		LayerTreeScrollRectTypeWheelEventHandler,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t LayerTreeScrollRectType) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *LayerTreeScrollRectType) UnmarshalText(data []byte) error {
	*t = LayerTreeScrollRectType(data)
	return nil
}

// String returns the string representation.
func (t LayerTreeScrollRectType) String() string {
	return string(t)
}
