// Code generated by bonkgen. DO NOT EDIT.

package proto

import "encoding/json"

// MediaPlayerID Players will get an ID that is unique within the agent context.
type MediaPlayerID string

// String returns the MediaPlayerID as a string.
func (t MediaPlayerID) String() string {
	return string(t)
}

type MediaTimestamp float64

// Float64 returns the MediaTimestamp as a float64.
func (t MediaTimestamp) Float64() float64 {
	return float64(t)
}

// MediaPlayerMessage Have one type per entry in MediaLogRecord::Type
// Corresponds to kMessage
type MediaPlayerMessage struct {
	// Level Keep in sync with MediaLogMessageLevel
	// We are currently keeping the message level 'error' separate from the
	// PlayerError type because right now they represent different things,
	// this one being a DVLOG(ERROR) style log message that gets printed
	// based on what log level is selected in the UI, and the other is a
	// representation of a media::PipelineStatus object. Soon however we're
	// going to be moving away from using PipelineStatus for errors and
	// introducing a new error type which should hopefully let us integrate
	// the error log level into the PlayerError type.
	Level   MediaPlayerMessageLevel `json:"level"`
	Message string                  `json:"message"`
}

// MediaPlayerProperty Corresponds to kMediaPropertyChange
type MediaPlayerProperty struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// MediaPlayerEvent Corresponds to kMediaEventTriggered
type MediaPlayerEvent struct {
	Timestamp MediaTimestamp `json:"timestamp"`
	Value     string         `json:"value"`
}

// MediaPlayerErrorSourceLocation Represents logged source line numbers reported in an error.
// NOTE: file and line are from chromium c++ implementation code, not js.
type MediaPlayerErrorSourceLocation struct {
	File string `json:"file"`
	Line int64  `json:"line"`
}

// MediaPlayerError Corresponds to kMediaError
type MediaPlayerError struct {
	ErrorType string `json:"errorType"`
	// Code Code is the numeric enum entry for a specific set of error codes, such
	// as PipelineStatusCodes in media/base/pipeline_status.h
	Code int64 `json:"code"`
	// Stack A trace of where this error was caused / where it passed through.
	Stack []MediaPlayerErrorSourceLocation `json:"stack"`
	// Cause Errors potentially have a root cause error, ie, a DecoderError might be
	// caused by an WindowsError
	Cause []MediaPlayerError `json:"cause"`
	// Data Extra data attached to an error, such as an HRESULT, Video Codec, etc.
	Data json.RawMessage `json:"data"`
}

type MediaPlayer struct {
	PlayerID  MediaPlayerID `json:"playerId"`
	DOMNodeID BackendNodeID `json:"domNodeId,omitempty,omitzero"`
}

// MediaPlayerMessageLevel Keep in sync with MediaLogMessageLevel
// We are currently keeping the message level 'error' separate from the
// PlayerError type because right now they represent different things,
// this one being a DVLOG(ERROR) style log message that gets printed
// based on what log level is selected in the UI, and the other is a
// representation of a media::PipelineStatus object. Soon however we're
// going to be moving away from using PipelineStatus for errors and
// introducing a new error type which should hopefully let us integrate
// the error log level into the PlayerError type.
type MediaPlayerMessageLevel string

const (
	MediaPlayerMessageLevelError   MediaPlayerMessageLevel = "error"
	MediaPlayerMessageLevelWarning MediaPlayerMessageLevel = "warning"
	MediaPlayerMessageLevelInfo    MediaPlayerMessageLevel = "info"
	MediaPlayerMessageLevelDebug   MediaPlayerMessageLevel = "debug"
)

// IsValid reports whether the value is a known enum value.
func (t MediaPlayerMessageLevel) IsValid() bool {
	switch t {
	case MediaPlayerMessageLevelError:
		return true
	case MediaPlayerMessageLevelWarning:
		return true
	case MediaPlayerMessageLevelInfo:
		return true
	case MediaPlayerMessageLevelDebug:
		return true
	}
	return false
}

// Values returns all known values of MediaPlayerMessageLevel.
func (t MediaPlayerMessageLevel) Values() []MediaPlayerMessageLevel {
	return []MediaPlayerMessageLevel{
		MediaPlayerMessageLevelError,
		MediaPlayerMessageLevelWarning,
		MediaPlayerMessageLevelInfo,
		MediaPlayerMessageLevelDebug,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t MediaPlayerMessageLevel) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *MediaPlayerMessageLevel) UnmarshalText(data []byte) error {
	*t = MediaPlayerMessageLevel(data)
	return nil
}

// String returns the string representation.
func (t MediaPlayerMessageLevel) String() string {
	return string(t)
}
