// Code generated by bonkgen. DO NOT EDIT.

package proto

// MemoryPressureLevel Memory pressure level.
type MemoryPressureLevel string

const (
	MemoryPressureLevelModerate MemoryPressureLevel = "moderate"
	MemoryPressureLevelCritical MemoryPressureLevel = "critical"
)

// IsValid reports whether the value is a known enum value.
func (t MemoryPressureLevel) IsValid() bool {
	switch t {
	case MemoryPressureLevelModerate:
		return true
	case MemoryPressureLevelCritical:
		return true
	}
	return false
}

// Values returns all known values of MemoryPressureLevel.
func (t MemoryPressureLevel) Values() []MemoryPressureLevel {
	return []MemoryPressureLevel{
		MemoryPressureLevelModerate,
		MemoryPressureLevelCritical,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t MemoryPressureLevel) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *MemoryPressureLevel) UnmarshalText(data []byte) error {
	*t = MemoryPressureLevel(data)
	return nil
}

// String returns the string representation.
func (t MemoryPressureLevel) String() string {
	return string(t)
}

// MemorySamplingProfileNode Heap profile sample.
type MemorySamplingProfileNode struct {
	// Size Size of the sampled allocation.
	Size float64 `json:"size"`
	// Total Total bytes attributed to this sample.
	Total float64 `json:"total"`
	// Stack Execution stack at the point of allocation.
	Stack []string `json:"stack"`
}

// MemorySamplingProfile Array of heap profile samples.
type MemorySamplingProfile struct {
	Samples []MemorySamplingProfileNode `json:"samples"`
	Modules []MemoryModule              `json:"modules"`
}

// MemoryModule Executable module information
type MemoryModule struct {
	// Name Name of the module.
	Name string `json:"name"`
	// UUID UUID of the module.
	UUID string `json:"uuid"`
	// BaseAddress Base address where the module is loaded into memory. Encoded as a decimal
	// or hexadecimal (0x prefixed) string.
	BaseAddress string `json:"baseAddress"`
	// Size Size of the module in bytes.
	Size float64 `json:"size"`
}

// MemoryDOMCounter DOM object counter data.
type MemoryDOMCounter struct {
	// Name Object name. Note: object names should be presumed volatile and clients should not expect
	// the returned names to be consistent across runs.
	Name string `json:"name"`
	// Count Object count.
	Count int64 `json:"count"`
}
