// Code generated by bonkgen. DO NOT EDIT.

package proto

import "context"

// NetworkSetAcceptedEncodingsParams Sets a list of content encodings that will be accepted. Empty list means no encoding is accepted.
type NetworkSetAcceptedEncodingsParams struct {
	// Encodings List of accepted content encodings.
	Encodings []NetworkContentEncoding `json:"encodings"`
}

// NetworkSetAcceptedEncodings creates a new NetworkSetAcceptedEncodingsParams.
func NetworkSetAcceptedEncodings(encodings []NetworkContentEncoding) *NetworkSetAcceptedEncodingsParams {
	return &NetworkSetAcceptedEncodingsParams{
		Encodings: encodings,
	}
}

// Do executes Network.setAcceptedEncodings.
func (p *NetworkSetAcceptedEncodingsParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandSetAcceptedEncodings, p, nil)
}

// NetworkClearAcceptedEncodingsOverrideParams Clears accepted encodings set by setAcceptedEncodings
type NetworkClearAcceptedEncodingsOverrideParams struct{}

// NetworkClearAcceptedEncodingsOverride creates a new NetworkClearAcceptedEncodingsOverrideParams.
func NetworkClearAcceptedEncodingsOverride() *NetworkClearAcceptedEncodingsOverrideParams {
	return &NetworkClearAcceptedEncodingsOverrideParams{}
}

// Do executes Network.clearAcceptedEncodingsOverride.
func (p *NetworkClearAcceptedEncodingsOverrideParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandClearAcceptedEncodingsOverride, p, nil)
}

// NetworkCanClearBrowserCacheParams Tells whether clearing browser cache is supported.
type NetworkCanClearBrowserCacheParams struct{}

// NetworkCanClearBrowserCacheReturns holds the return values for canClearBrowserCache.
type NetworkCanClearBrowserCacheReturns struct {
	// Result True if browser cache can be cleared.
	Result bool `json:"result"`
}

// NetworkCanClearBrowserCache creates a new NetworkCanClearBrowserCacheParams.
func NetworkCanClearBrowserCache() *NetworkCanClearBrowserCacheParams {
	return &NetworkCanClearBrowserCacheParams{}
}

// Do executes Network.canClearBrowserCache.
func (p *NetworkCanClearBrowserCacheParams) Do(ctx context.Context) (*NetworkCanClearBrowserCacheReturns, error) {
	var res NetworkCanClearBrowserCacheReturns
	if err := Execute(ctx, NetworkCommandCanClearBrowserCache, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NetworkCanClearBrowserCookiesParams Tells whether clearing browser cookies is supported.
type NetworkCanClearBrowserCookiesParams struct{}

// NetworkCanClearBrowserCookiesReturns holds the return values for canClearBrowserCookies.
type NetworkCanClearBrowserCookiesReturns struct {
	// Result True if browser cookies can be cleared.
	Result bool `json:"result"`
}

// NetworkCanClearBrowserCookies creates a new NetworkCanClearBrowserCookiesParams.
func NetworkCanClearBrowserCookies() *NetworkCanClearBrowserCookiesParams {
	return &NetworkCanClearBrowserCookiesParams{}
}

// Do executes Network.canClearBrowserCookies.
func (p *NetworkCanClearBrowserCookiesParams) Do(ctx context.Context) (*NetworkCanClearBrowserCookiesReturns, error) {
	var res NetworkCanClearBrowserCookiesReturns
	if err := Execute(ctx, NetworkCommandCanClearBrowserCookies, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NetworkCanEmulateNetworkConditionsParams Tells whether emulation of network conditions is supported.
type NetworkCanEmulateNetworkConditionsParams struct{}

// NetworkCanEmulateNetworkConditionsReturns holds the return values for canEmulateNetworkConditions.
type NetworkCanEmulateNetworkConditionsReturns struct {
	// Result True if emulation of network conditions is supported.
	Result bool `json:"result"`
}

// NetworkCanEmulateNetworkConditions creates a new NetworkCanEmulateNetworkConditionsParams.
func NetworkCanEmulateNetworkConditions() *NetworkCanEmulateNetworkConditionsParams {
	return &NetworkCanEmulateNetworkConditionsParams{}
}

// Do executes Network.canEmulateNetworkConditions.
func (p *NetworkCanEmulateNetworkConditionsParams) Do(ctx context.Context) (*NetworkCanEmulateNetworkConditionsReturns, error) {
	var res NetworkCanEmulateNetworkConditionsReturns
	if err := Execute(ctx, NetworkCommandCanEmulateNetworkConditions, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NetworkClearBrowserCacheParams Clears browser cache.
type NetworkClearBrowserCacheParams struct{}

// NetworkClearBrowserCache creates a new NetworkClearBrowserCacheParams.
func NetworkClearBrowserCache() *NetworkClearBrowserCacheParams {
	return &NetworkClearBrowserCacheParams{}
}

// Do executes Network.clearBrowserCache.
func (p *NetworkClearBrowserCacheParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandClearBrowserCache, p, nil)
}

// NetworkClearBrowserCookiesParams Clears browser cookies.
type NetworkClearBrowserCookiesParams struct{}

// NetworkClearBrowserCookies creates a new NetworkClearBrowserCookiesParams.
func NetworkClearBrowserCookies() *NetworkClearBrowserCookiesParams {
	return &NetworkClearBrowserCookiesParams{}
}

// Do executes Network.clearBrowserCookies.
func (p *NetworkClearBrowserCookiesParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandClearBrowserCookies, p, nil)
}

// NetworkContinueInterceptedRequestParams Response to Network.requestIntercepted which either modifies the request to continue with any
// modifications, or blocks it, or completes it with the provided response bytes. If a network
// fetch occurs as a result which encounters a redirect an additional Network.requestIntercepted
// event will be sent with the same InterceptionId.
// Deprecated, use Fetch.continueRequest, Fetch.fulfillRequest and Fetch.failRequest instead.
type NetworkContinueInterceptedRequestParams struct {
	InterceptionID NetworkInterceptionID `json:"interceptionId"`
	// ErrorReason If set this causes the request to fail with the given reason. Passing `Aborted` for requests
	// marked with `isNavigationRequest` also cancels the navigation. Must not be set in response
	// to an authChallenge.
	ErrorReason NetworkErrorReason `json:"errorReason,omitempty,omitzero"`
	// RawResponse If set the requests completes using with the provided base64 encoded raw response, including
	// HTTP status line and headers etc... Must not be set in response to an authChallenge.
	RawResponse []byte `json:"rawResponse,omitempty,omitzero"`
	// URL If set the request url will be modified in a way that's not observable by page. Must not be
	// set in response to an authChallenge.
	URL string `json:"url,omitempty,omitzero"`
	// Method If set this allows the request method to be overridden. Must not be set in response to an
	// authChallenge.
	Method string `json:"method,omitempty,omitzero"`
	// PostData If set this allows postData to be set. Must not be set in response to an authChallenge.
	PostData string `json:"postData,omitempty,omitzero"`
	// Headers If set this allows the request headers to be changed. Must not be set in response to an
	// authChallenge.
	Headers NetworkHeaders `json:"headers,omitempty,omitzero"`
	// AuthChallengeResponse Response to a requestIntercepted with an authChallenge. Must not be set otherwise.
	AuthChallengeResponse NetworkAuthChallengeResponse `json:"authChallengeResponse,omitempty,omitzero"`
}

// NetworkContinueInterceptedRequest creates a new NetworkContinueInterceptedRequestParams.
func NetworkContinueInterceptedRequest(interceptionID NetworkInterceptionID) *NetworkContinueInterceptedRequestParams {
	return &NetworkContinueInterceptedRequestParams{
		InterceptionID: interceptionID,
	}
}

// WithErrorReason sets the errorReason parameter.
func (p *NetworkContinueInterceptedRequestParams) WithErrorReason(errorReason NetworkErrorReason) *NetworkContinueInterceptedRequestParams {
	p.ErrorReason = errorReason
	return p
}

// WithRawResponse sets the rawResponse parameter.
func (p *NetworkContinueInterceptedRequestParams) WithRawResponse(rawResponse []byte) *NetworkContinueInterceptedRequestParams {
	p.RawResponse = rawResponse
	return p
}

// WithURL sets the url parameter.
func (p *NetworkContinueInterceptedRequestParams) WithURL(url string) *NetworkContinueInterceptedRequestParams {
	p.URL = url
	return p
}

// WithMethod sets the method parameter.
func (p *NetworkContinueInterceptedRequestParams) WithMethod(method string) *NetworkContinueInterceptedRequestParams {
	p.Method = method
	return p
}

// WithPostData sets the postData parameter.
func (p *NetworkContinueInterceptedRequestParams) WithPostData(postData string) *NetworkContinueInterceptedRequestParams {
	p.PostData = postData
	return p
}

// WithHeaders sets the headers parameter.
func (p *NetworkContinueInterceptedRequestParams) WithHeaders(headers NetworkHeaders) *NetworkContinueInterceptedRequestParams {
	p.Headers = headers
	return p
}

// WithAuthChallengeResponse sets the authChallengeResponse parameter.
func (p *NetworkContinueInterceptedRequestParams) WithAuthChallengeResponse(authChallengeResponse NetworkAuthChallengeResponse) *NetworkContinueInterceptedRequestParams {
	p.AuthChallengeResponse = authChallengeResponse
	return p
}

// Do executes Network.continueInterceptedRequest.
func (p *NetworkContinueInterceptedRequestParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandContinueInterceptedRequest, p, nil)
}

// NetworkDeleteCookiesParams Deletes browser cookies with matching name and url or domain/path/partitionKey pair.
type NetworkDeleteCookiesParams struct {
	// Name Name of the cookies to remove.
	Name string `json:"name"`
	// URL If specified, deletes all the cookies with the given name where domain and path match
	// provided URL.
	URL string `json:"url,omitempty,omitzero"`
	// Domain If specified, deletes only cookies with the exact domain.
	Domain string `json:"domain,omitempty,omitzero"`
	// Path If specified, deletes only cookies with the exact path.
	Path string `json:"path,omitempty,omitzero"`
	// PartitionKey If specified, deletes only cookies with the the given name and partitionKey where
	// all partition key attributes match the cookie partition key attribute.
	PartitionKey NetworkCookiePartitionKey `json:"partitionKey,omitempty,omitzero"`
}

// NetworkDeleteCookies creates a new NetworkDeleteCookiesParams.
func NetworkDeleteCookies(name string) *NetworkDeleteCookiesParams {
	return &NetworkDeleteCookiesParams{
		Name: name,
	}
}

// WithURL sets the url parameter.
func (p *NetworkDeleteCookiesParams) WithURL(url string) *NetworkDeleteCookiesParams {
	p.URL = url
	return p
}

// WithDomain sets the domain parameter.
func (p *NetworkDeleteCookiesParams) WithDomain(domain string) *NetworkDeleteCookiesParams {
	p.Domain = domain
	return p
}

// WithPath sets the path parameter.
func (p *NetworkDeleteCookiesParams) WithPath(path string) *NetworkDeleteCookiesParams {
	p.Path = path
	return p
}

// WithPartitionKey sets the partitionKey parameter.
func (p *NetworkDeleteCookiesParams) WithPartitionKey(partitionKey NetworkCookiePartitionKey) *NetworkDeleteCookiesParams {
	p.PartitionKey = partitionKey
	return p
}

// Do executes Network.deleteCookies.
func (p *NetworkDeleteCookiesParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandDeleteCookies, p, nil)
}

// NetworkDisableParams Disables network tracking, prevents network events from being sent to the client.
type NetworkDisableParams struct{}

// NetworkDisable creates a new NetworkDisableParams.
func NetworkDisable() *NetworkDisableParams {
	return &NetworkDisableParams{}
}

// Do executes Network.disable.
func (p *NetworkDisableParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandDisable, p, nil)
}

// NetworkEmulateNetworkConditionsParams Activates emulation of network conditions. This command is deprecated in favor of the emulateNetworkConditionsByRule
// and overrideNetworkState commands, which can be used together to the same effect.
type NetworkEmulateNetworkConditionsParams struct {
	// Offline True to emulate internet disconnection.
	Offline bool `json:"offline"`
	// Latency Minimum latency from request sent to response headers received (ms).
	Latency float64 `json:"latency"`
	// DownloadThroughput Maximal aggregated download throughput (bytes/sec). -1 disables download throttling.
	DownloadThroughput float64 `json:"downloadThroughput"`
	// UploadThroughput Maximal aggregated upload throughput (bytes/sec).  -1 disables upload throttling.
	UploadThroughput float64 `json:"uploadThroughput"`
	// ConnectionType Connection type if known.
	ConnectionType NetworkConnectionType `json:"connectionType,omitempty,omitzero"`
	// PacketLoss WebRTC packet loss (percent, 0-100). 0 disables packet loss emulation, 100 drops all the packets.
	PacketLoss float64 `json:"packetLoss,omitempty,omitzero"`
	// PacketQueueLength WebRTC packet queue length (packet). 0 removes any queue length limitations.
	PacketQueueLength int64 `json:"packetQueueLength,omitempty,omitzero"`
	// PacketReordering WebRTC packetReordering feature.
	PacketReordering bool `json:"packetReordering,omitempty,omitzero"`
}

// NetworkEmulateNetworkConditions creates a new NetworkEmulateNetworkConditionsParams.
func NetworkEmulateNetworkConditions(offline bool, latency float64, downloadThroughput float64, uploadThroughput float64) *NetworkEmulateNetworkConditionsParams {
	return &NetworkEmulateNetworkConditionsParams{
		Offline:            offline,
		Latency:            latency,
		DownloadThroughput: downloadThroughput,
		UploadThroughput:   uploadThroughput,
	}
}

// WithConnectionType sets the connectionType parameter.
func (p *NetworkEmulateNetworkConditionsParams) WithConnectionType(connectionType NetworkConnectionType) *NetworkEmulateNetworkConditionsParams {
	p.ConnectionType = connectionType
	return p
}

// WithPacketLoss sets the packetLoss parameter.
func (p *NetworkEmulateNetworkConditionsParams) WithPacketLoss(packetLoss float64) *NetworkEmulateNetworkConditionsParams {
	p.PacketLoss = packetLoss
	return p
}

// WithPacketQueueLength sets the packetQueueLength parameter.
func (p *NetworkEmulateNetworkConditionsParams) WithPacketQueueLength(packetQueueLength int64) *NetworkEmulateNetworkConditionsParams {
	p.PacketQueueLength = packetQueueLength
	return p
}

// WithPacketReordering sets the packetReordering parameter.
func (p *NetworkEmulateNetworkConditionsParams) WithPacketReordering(packetReordering bool) *NetworkEmulateNetworkConditionsParams {
	p.PacketReordering = packetReordering
	return p
}

// Do executes Network.emulateNetworkConditions.
func (p *NetworkEmulateNetworkConditionsParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandEmulateNetworkConditions, p, nil)
}

// NetworkEmulateNetworkConditionsByRuleParams Activates emulation of network conditions for individual requests using URL match patterns. Unlike the deprecated
// Network.emulateNetworkConditions this method does not affect `navigator` state. Use Network.overrideNetworkState to
// explicitly modify `navigator` behavior.
type NetworkEmulateNetworkConditionsByRuleParams struct {
	// Offline True to emulate internet disconnection.
	Offline bool `json:"offline"`
	// MatchedNetworkConditions Configure conditions for matching requests. If multiple entries match a request, the first entry wins.  Global
	// conditions can be configured by leaving the urlPattern for the conditions empty. These global conditions are
	// also applied for throttling of p2p connections.
	MatchedNetworkConditions []NetworkNetworkConditions `json:"matchedNetworkConditions"`
}

// NetworkEmulateNetworkConditionsByRuleReturns holds the return values for emulateNetworkConditionsByRule.
type NetworkEmulateNetworkConditionsByRuleReturns struct {
	// RuleIds An id for each entry in matchedNetworkConditions. The id will be included in the requestWillBeSentExtraInfo for
	// requests affected by a rule.
	RuleIds []string `json:"ruleIds"`
}

// NetworkEmulateNetworkConditionsByRule creates a new NetworkEmulateNetworkConditionsByRuleParams.
func NetworkEmulateNetworkConditionsByRule(offline bool, matchedNetworkConditions []NetworkNetworkConditions) *NetworkEmulateNetworkConditionsByRuleParams {
	return &NetworkEmulateNetworkConditionsByRuleParams{
		Offline:                  offline,
		MatchedNetworkConditions: matchedNetworkConditions,
	}
}

// Do executes Network.emulateNetworkConditionsByRule.
func (p *NetworkEmulateNetworkConditionsByRuleParams) Do(ctx context.Context) (*NetworkEmulateNetworkConditionsByRuleReturns, error) {
	var res NetworkEmulateNetworkConditionsByRuleReturns
	if err := Execute(ctx, NetworkCommandEmulateNetworkConditionsByRule, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NetworkOverrideNetworkStateParams Override the state of navigator.onLine and navigator.connection.
type NetworkOverrideNetworkStateParams struct {
	// Offline True to emulate internet disconnection.
	Offline bool `json:"offline"`
	// Latency Minimum latency from request sent to response headers received (ms).
	Latency float64 `json:"latency"`
	// DownloadThroughput Maximal aggregated download throughput (bytes/sec). -1 disables download throttling.
	DownloadThroughput float64 `json:"downloadThroughput"`
	// UploadThroughput Maximal aggregated upload throughput (bytes/sec).  -1 disables upload throttling.
	UploadThroughput float64 `json:"uploadThroughput"`
	// ConnectionType Connection type if known.
	ConnectionType NetworkConnectionType `json:"connectionType,omitempty,omitzero"`
}

// NetworkOverrideNetworkState creates a new NetworkOverrideNetworkStateParams.
func NetworkOverrideNetworkState(offline bool, latency float64, downloadThroughput float64, uploadThroughput float64) *NetworkOverrideNetworkStateParams {
	return &NetworkOverrideNetworkStateParams{
		Offline:            offline,
		Latency:            latency,
		DownloadThroughput: downloadThroughput,
		UploadThroughput:   uploadThroughput,
	}
}

// WithConnectionType sets the connectionType parameter.
func (p *NetworkOverrideNetworkStateParams) WithConnectionType(connectionType NetworkConnectionType) *NetworkOverrideNetworkStateParams {
	p.ConnectionType = connectionType
	return p
}

// Do executes Network.overrideNetworkState.
func (p *NetworkOverrideNetworkStateParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandOverrideNetworkState, p, nil)
}

// NetworkEnableParams Enables network tracking, network events will now be delivered to the client.
type NetworkEnableParams struct {
	// MaxTotalBufferSize Buffer size in bytes to use when preserving network payloads (XHRs, etc).
	// This is the maximum number of bytes that will be collected by this
	// DevTools session.
	MaxTotalBufferSize int64 `json:"maxTotalBufferSize,omitempty,omitzero"`
	// MaxResourceBufferSize Per-resource buffer size in bytes to use when preserving network payloads (XHRs, etc).
	MaxResourceBufferSize int64 `json:"maxResourceBufferSize,omitempty,omitzero"`
	// MaxPostDataSize Longest post body size (in bytes) that would be included in requestWillBeSent notification
	MaxPostDataSize int64 `json:"maxPostDataSize,omitempty,omitzero"`
	// ReportDirectSocketTraffic Whether DirectSocket chunk send/receive events should be reported.
	ReportDirectSocketTraffic bool `json:"reportDirectSocketTraffic,omitempty,omitzero"`
	// EnableDurableMessages Enable storing response bodies outside of renderer, so that these survive
	// a cross-process navigation. Requires maxTotalBufferSize to be set.
	// Currently defaults to false. This field is being deprecated in favor of the dedicated
	// configureDurableMessages command, due to the possibility of deadlocks when awaiting
	// Network.enable before issuing Runtime.runIfWaitingForDebugger.
	EnableDurableMessages bool `json:"enableDurableMessages,omitempty,omitzero"`
}

// NetworkEnable creates a new NetworkEnableParams.
func NetworkEnable() *NetworkEnableParams {
	return &NetworkEnableParams{}
}

// WithMaxTotalBufferSize sets the maxTotalBufferSize parameter.
func (p *NetworkEnableParams) WithMaxTotalBufferSize(maxTotalBufferSize int64) *NetworkEnableParams {
	p.MaxTotalBufferSize = maxTotalBufferSize
	return p
}

// WithMaxResourceBufferSize sets the maxResourceBufferSize parameter.
func (p *NetworkEnableParams) WithMaxResourceBufferSize(maxResourceBufferSize int64) *NetworkEnableParams {
	p.MaxResourceBufferSize = maxResourceBufferSize
	return p
}

// WithMaxPostDataSize sets the maxPostDataSize parameter.
func (p *NetworkEnableParams) WithMaxPostDataSize(maxPostDataSize int64) *NetworkEnableParams {
	p.MaxPostDataSize = maxPostDataSize
	return p
}

// WithReportDirectSocketTraffic sets the reportDirectSocketTraffic parameter.
func (p *NetworkEnableParams) WithReportDirectSocketTraffic(reportDirectSocketTraffic bool) *NetworkEnableParams {
	p.ReportDirectSocketTraffic = reportDirectSocketTraffic
	return p
}

// WithEnableDurableMessages sets the enableDurableMessages parameter.
func (p *NetworkEnableParams) WithEnableDurableMessages(enableDurableMessages bool) *NetworkEnableParams {
	p.EnableDurableMessages = enableDurableMessages
	return p
}

// Do executes Network.enable.
func (p *NetworkEnableParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandEnable, p, nil)
}

// NetworkConfigureDurableMessagesParams Configures storing response bodies outside of renderer, so that these survive
// a cross-process navigation.
// If maxTotalBufferSize is not set, durable messages are disabled.
type NetworkConfigureDurableMessagesParams struct {
	// MaxTotalBufferSize Buffer size in bytes to use when preserving network payloads (XHRs, etc).
	MaxTotalBufferSize int64 `json:"maxTotalBufferSize,omitempty,omitzero"`
	// MaxResourceBufferSize Per-resource buffer size in bytes to use when preserving network payloads (XHRs, etc).
	MaxResourceBufferSize int64 `json:"maxResourceBufferSize,omitempty,omitzero"`
}

// NetworkConfigureDurableMessages creates a new NetworkConfigureDurableMessagesParams.
func NetworkConfigureDurableMessages() *NetworkConfigureDurableMessagesParams {
	return &NetworkConfigureDurableMessagesParams{}
}

// WithMaxTotalBufferSize sets the maxTotalBufferSize parameter.
func (p *NetworkConfigureDurableMessagesParams) WithMaxTotalBufferSize(maxTotalBufferSize int64) *NetworkConfigureDurableMessagesParams {
	p.MaxTotalBufferSize = maxTotalBufferSize
	return p
}

// WithMaxResourceBufferSize sets the maxResourceBufferSize parameter.
func (p *NetworkConfigureDurableMessagesParams) WithMaxResourceBufferSize(maxResourceBufferSize int64) *NetworkConfigureDurableMessagesParams {
	p.MaxResourceBufferSize = maxResourceBufferSize
	return p
}

// Do executes Network.configureDurableMessages.
func (p *NetworkConfigureDurableMessagesParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandConfigureDurableMessages, p, nil)
}

// NetworkGetAllCookiesParams Returns all browser cookies. Depending on the backend support, will return detailed cookie
// information in the `cookies` field.
// Deprecated. Use Storage.getCookies instead.
type NetworkGetAllCookiesParams struct{}

// NetworkGetAllCookiesReturns holds the return values for getAllCookies.
type NetworkGetAllCookiesReturns struct {
	// Cookies Array of cookie objects.
	Cookies []NetworkCookie `json:"cookies"`
}

// NetworkGetAllCookies creates a new NetworkGetAllCookiesParams.
func NetworkGetAllCookies() *NetworkGetAllCookiesParams {
	return &NetworkGetAllCookiesParams{}
}

// Do executes Network.getAllCookies.
func (p *NetworkGetAllCookiesParams) Do(ctx context.Context) (*NetworkGetAllCookiesReturns, error) {
	var res NetworkGetAllCookiesReturns
	if err := Execute(ctx, NetworkCommandGetAllCookies, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NetworkGetCertificateParams Returns the DER-encoded certificate.
type NetworkGetCertificateParams struct {
	// Origin Origin to get certificate for.
	Origin string `json:"origin"`
}

// NetworkGetCertificateReturns holds the return values for getCertificate.
type NetworkGetCertificateReturns struct {
	TableNames []string `json:"tableNames"`
}

// NetworkGetCertificate creates a new NetworkGetCertificateParams.
func NetworkGetCertificate(origin string) *NetworkGetCertificateParams {
	return &NetworkGetCertificateParams{
		Origin: origin,
	}
}

// Do executes Network.getCertificate.
func (p *NetworkGetCertificateParams) Do(ctx context.Context) (*NetworkGetCertificateReturns, error) {
	var res NetworkGetCertificateReturns
	if err := Execute(ctx, NetworkCommandGetCertificate, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NetworkGetCookiesParams Returns all browser cookies for the current URL. Depending on the backend support, will return
// detailed cookie information in the `cookies` field.
type NetworkGetCookiesParams struct {
	// Urls The list of URLs for which applicable cookies will be fetched.
	// If not specified, it's assumed to be set to the list containing
	// the URLs of the page and all of its subframes.
	Urls []string `json:"urls,omitempty,omitzero"`
}

// NetworkGetCookiesReturns holds the return values for getCookies.
type NetworkGetCookiesReturns struct {
	// Cookies Array of cookie objects.
	Cookies []NetworkCookie `json:"cookies"`
}

// NetworkGetCookies creates a new NetworkGetCookiesParams.
func NetworkGetCookies() *NetworkGetCookiesParams {
	return &NetworkGetCookiesParams{}
}

// WithUrls sets the urls parameter.
func (p *NetworkGetCookiesParams) WithUrls(urls []string) *NetworkGetCookiesParams {
	p.Urls = urls
	return p
}

// Do executes Network.getCookies.
func (p *NetworkGetCookiesParams) Do(ctx context.Context) (*NetworkGetCookiesReturns, error) {
	var res NetworkGetCookiesReturns
	if err := Execute(ctx, NetworkCommandGetCookies, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NetworkGetResponseBodyParams Returns content served for the given request.
type NetworkGetResponseBodyParams struct {
	// RequestID Identifier of the network request to get content for.
	RequestID RequestID `json:"requestId"`
}

// NetworkGetResponseBodyReturns holds the return values for getResponseBody.
type NetworkGetResponseBodyReturns struct {
	// Body Response body.
	Body string `json:"body"`
	// Base64Encoded True, if content was sent as base64.
	Base64Encoded bool `json:"base64Encoded"`
}

// NetworkGetResponseBody creates a new NetworkGetResponseBodyParams.
func NetworkGetResponseBody(requestID RequestID) *NetworkGetResponseBodyParams {
	return &NetworkGetResponseBodyParams{
		RequestID: requestID,
	}
}

// Do executes Network.getResponseBody.
func (p *NetworkGetResponseBodyParams) Do(ctx context.Context) (*NetworkGetResponseBodyReturns, error) {
	var res NetworkGetResponseBodyReturns
	if err := Execute(ctx, NetworkCommandGetResponseBody, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NetworkGetRequestPostDataParams Returns post data sent with the request. Returns an error when no data was sent with the request.
type NetworkGetRequestPostDataParams struct {
	// RequestID Identifier of the network request to get content for.
	RequestID RequestID `json:"requestId"`
}

// NetworkGetRequestPostDataReturns holds the return values for getRequestPostData.
type NetworkGetRequestPostDataReturns struct {
	// PostData Request body string, omitting files from multipart requests
	PostData string `json:"postData"`
	// Base64Encoded True, if content was sent as base64.
	Base64Encoded bool `json:"base64Encoded"`
}

// NetworkGetRequestPostData creates a new NetworkGetRequestPostDataParams.
func NetworkGetRequestPostData(requestID RequestID) *NetworkGetRequestPostDataParams {
	return &NetworkGetRequestPostDataParams{
		RequestID: requestID,
	}
}

// Do executes Network.getRequestPostData.
func (p *NetworkGetRequestPostDataParams) Do(ctx context.Context) (*NetworkGetRequestPostDataReturns, error) {
	var res NetworkGetRequestPostDataReturns
	if err := Execute(ctx, NetworkCommandGetRequestPostData, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NetworkGetResponseBodyForInterceptionParams Returns content served for the given currently intercepted request.
type NetworkGetResponseBodyForInterceptionParams struct {
	// InterceptionID Identifier for the intercepted request to get body for.
	InterceptionID NetworkInterceptionID `json:"interceptionId"`
}

// NetworkGetResponseBodyForInterceptionReturns holds the return values for getResponseBodyForInterception.
type NetworkGetResponseBodyForInterceptionReturns struct {
	// Body Response body.
	Body string `json:"body"`
	// Base64Encoded True, if content was sent as base64.
	Base64Encoded bool `json:"base64Encoded"`
}

// NetworkGetResponseBodyForInterception creates a new NetworkGetResponseBodyForInterceptionParams.
func NetworkGetResponseBodyForInterception(interceptionID NetworkInterceptionID) *NetworkGetResponseBodyForInterceptionParams {
	return &NetworkGetResponseBodyForInterceptionParams{
		InterceptionID: interceptionID,
	}
}

// Do executes Network.getResponseBodyForInterception.
func (p *NetworkGetResponseBodyForInterceptionParams) Do(ctx context.Context) (*NetworkGetResponseBodyForInterceptionReturns, error) {
	var res NetworkGetResponseBodyForInterceptionReturns
	if err := Execute(ctx, NetworkCommandGetResponseBodyForInterception, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NetworkTakeResponseBodyForInterceptionAsStreamParams Returns a handle to the stream representing the response body. Note that after this command,
// the intercepted request can't be continued as is -- you either need to cancel it or to provide
// the response body. The stream only supports sequential read, IO.read will fail if the position
// is specified.
type NetworkTakeResponseBodyForInterceptionAsStreamParams struct {
	InterceptionID NetworkInterceptionID `json:"interceptionId"`
}

// NetworkTakeResponseBodyForInterceptionAsStreamReturns holds the return values for takeResponseBodyForInterceptionAsStream.
type NetworkTakeResponseBodyForInterceptionAsStreamReturns struct {
	Stream IOStreamHandle `json:"stream"`
}

// NetworkTakeResponseBodyForInterceptionAsStream creates a new NetworkTakeResponseBodyForInterceptionAsStreamParams.
func NetworkTakeResponseBodyForInterceptionAsStream(interceptionID NetworkInterceptionID) *NetworkTakeResponseBodyForInterceptionAsStreamParams {
	return &NetworkTakeResponseBodyForInterceptionAsStreamParams{
		InterceptionID: interceptionID,
	}
}

// Do executes Network.takeResponseBodyForInterceptionAsStream.
func (p *NetworkTakeResponseBodyForInterceptionAsStreamParams) Do(ctx context.Context) (*NetworkTakeResponseBodyForInterceptionAsStreamReturns, error) {
	var res NetworkTakeResponseBodyForInterceptionAsStreamReturns
	if err := Execute(ctx, NetworkCommandTakeResponseBodyForInterceptionAsStream, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NetworkReplayXHRParams This method sends a new XMLHttpRequest which is identical to the original one. The following
// parameters should be identical: method, url, async, request body, extra headers, withCredentials
// attribute, user, password.
type NetworkReplayXHRParams struct {
	// RequestID Identifier of XHR to replay.
	RequestID RequestID `json:"requestId"`
}

// NetworkReplayXHR creates a new NetworkReplayXHRParams.
func NetworkReplayXHR(requestID RequestID) *NetworkReplayXHRParams {
	return &NetworkReplayXHRParams{
		RequestID: requestID,
	}
}

// Do executes Network.replayXHR.
func (p *NetworkReplayXHRParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandReplayXHR, p, nil)
}

// NetworkSearchInResponseBodyParams Searches for given string in response content.
type NetworkSearchInResponseBodyParams struct {
	// RequestID Identifier of the network response to search.
	RequestID RequestID `json:"requestId"`
	// Query String to search for.
	Query string `json:"query"`
	// CaseSensitive If true, search is case sensitive.
	CaseSensitive bool `json:"caseSensitive,omitempty,omitzero"`
	// IsRegex If true, treats string parameter as regex.
	IsRegex bool `json:"isRegex,omitempty,omitzero"`
}

// NetworkSearchInResponseBodyReturns holds the return values for searchInResponseBody.
type NetworkSearchInResponseBodyReturns struct {
	// Result List of search matches.
	Result []DebuggerSearchMatch `json:"result"`
}

// NetworkSearchInResponseBody creates a new NetworkSearchInResponseBodyParams.
func NetworkSearchInResponseBody(requestID RequestID, query string) *NetworkSearchInResponseBodyParams {
	return &NetworkSearchInResponseBodyParams{
		RequestID: requestID,
		Query:     query,
	}
}

// WithCaseSensitive sets the caseSensitive parameter.
func (p *NetworkSearchInResponseBodyParams) WithCaseSensitive(caseSensitive bool) *NetworkSearchInResponseBodyParams {
	p.CaseSensitive = caseSensitive
	return p
}

// WithIsRegex sets the isRegex parameter.
func (p *NetworkSearchInResponseBodyParams) WithIsRegex(isRegex bool) *NetworkSearchInResponseBodyParams {
	p.IsRegex = isRegex
	return p
}

// Do executes Network.searchInResponseBody.
func (p *NetworkSearchInResponseBodyParams) Do(ctx context.Context) (*NetworkSearchInResponseBodyReturns, error) {
	var res NetworkSearchInResponseBodyReturns
	if err := Execute(ctx, NetworkCommandSearchInResponseBody, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NetworkSetBlockedURLsParams Blocks URLs from loading.
type NetworkSetBlockedURLsParams struct {
	// URLPatterns Patterns to match in the order in which they are given. These patterns
	// also take precedence over any wildcard patterns defined in `urls`.
	URLPatterns []NetworkBlockPattern `json:"urlPatterns,omitempty,omitzero"`
	// Urls URL patterns to block. Wildcards ('*') are allowed.
	Urls []string `json:"urls,omitempty,omitzero"`
}

// NetworkSetBlockedURLs creates a new NetworkSetBlockedURLsParams.
func NetworkSetBlockedURLs() *NetworkSetBlockedURLsParams {
	return &NetworkSetBlockedURLsParams{}
}

// WithURLPatterns sets the urlPatterns parameter.
func (p *NetworkSetBlockedURLsParams) WithURLPatterns(urlPatterns []NetworkBlockPattern) *NetworkSetBlockedURLsParams {
	p.URLPatterns = urlPatterns
	return p
}

// WithUrls sets the urls parameter.
func (p *NetworkSetBlockedURLsParams) WithUrls(urls []string) *NetworkSetBlockedURLsParams {
	p.Urls = urls
	return p
}

// Do executes Network.setBlockedURLs.
func (p *NetworkSetBlockedURLsParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandSetBlockedURLs, p, nil)
}

// NetworkSetBypassServiceWorkerParams Toggles ignoring of service worker for each request.
type NetworkSetBypassServiceWorkerParams struct {
	// Bypass Bypass service worker and load from network.
	Bypass bool `json:"bypass"`
}

// NetworkSetBypassServiceWorker creates a new NetworkSetBypassServiceWorkerParams.
func NetworkSetBypassServiceWorker(bypass bool) *NetworkSetBypassServiceWorkerParams {
	return &NetworkSetBypassServiceWorkerParams{
		Bypass: bypass,
	}
}

// Do executes Network.setBypassServiceWorker.
func (p *NetworkSetBypassServiceWorkerParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandSetBypassServiceWorker, p, nil)
}

// NetworkSetCacheDisabledParams Toggles ignoring cache for each request. If `true`, cache will not be used.
type NetworkSetCacheDisabledParams struct {
	// CacheDisabled Cache disabled state.
	CacheDisabled bool `json:"cacheDisabled"`
}

// NetworkSetCacheDisabled creates a new NetworkSetCacheDisabledParams.
func NetworkSetCacheDisabled(cacheDisabled bool) *NetworkSetCacheDisabledParams {
	return &NetworkSetCacheDisabledParams{
		CacheDisabled: cacheDisabled,
	}
}

// Do executes Network.setCacheDisabled.
func (p *NetworkSetCacheDisabledParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandSetCacheDisabled, p, nil)
}

// NetworkSetCookieParams Sets a cookie with the given cookie data; may overwrite equivalent cookies if they exist.
type NetworkSetCookieParams struct {
	// Name Cookie name.
	Name string `json:"name"`
	// Value Cookie value.
	Value string `json:"value"`
	// URL The request-URI to associate with the setting of the cookie. This value can affect the
	// default domain, path, source port, and source scheme values of the created cookie.
	URL string `json:"url,omitempty,omitzero"`
	// Domain Cookie domain.
	Domain string `json:"domain,omitempty,omitzero"`
	// Path Cookie path.
	Path string `json:"path,omitempty,omitzero"`
	// Secure True if cookie is secure.
	Secure bool `json:"secure,omitempty,omitzero"`
	// HTTPOnly True if cookie is http-only.
	HTTPOnly bool `json:"httpOnly,omitempty,omitzero"`
	// SameSite Cookie SameSite type.
	SameSite NetworkCookieSameSite `json:"sameSite,omitempty,omitzero"`
	// Expires Cookie expiration date, session cookie if not set
	Expires TimeSinceEpoch `json:"expires,omitempty,omitzero"`
	// Priority Cookie Priority type.
	Priority NetworkCookiePriority `json:"priority,omitempty,omitzero"`
	// SourceScheme Cookie source scheme type.
	SourceScheme NetworkCookieSourceScheme `json:"sourceScheme,omitempty,omitzero"`
	// SourcePort Cookie source port. Valid values are {-1, [1, 65535]}, -1 indicates an unspecified port.
	// An unspecified port value allows protocol clients to emulate legacy cookie scope for the port.
	// This is a temporary ability and it will be removed in the future.
	SourcePort int64 `json:"sourcePort,omitempty,omitzero"`
	// PartitionKey Cookie partition key. If not set, the cookie will be set as not partitioned.
	PartitionKey NetworkCookiePartitionKey `json:"partitionKey,omitempty,omitzero"`
}

// NetworkSetCookieReturns holds the return values for setCookie.
type NetworkSetCookieReturns struct {
	// Success Always set to true. If an error occurs, the response indicates protocol error.
	Success bool `json:"success"`
}

// NetworkSetCookie creates a new NetworkSetCookieParams.
func NetworkSetCookie(name string, value string) *NetworkSetCookieParams {
	return &NetworkSetCookieParams{
		Name:  name,
		Value: value,
	}
}

// WithURL sets the url parameter.
func (p *NetworkSetCookieParams) WithURL(url string) *NetworkSetCookieParams {
	p.URL = url
	return p
}

// WithDomain sets the domain parameter.
func (p *NetworkSetCookieParams) WithDomain(domain string) *NetworkSetCookieParams {
	p.Domain = domain
	return p
}

// WithPath sets the path parameter.
func (p *NetworkSetCookieParams) WithPath(path string) *NetworkSetCookieParams {
	p.Path = path
	return p
}

// WithSecure sets the secure parameter.
func (p *NetworkSetCookieParams) WithSecure(secure bool) *NetworkSetCookieParams {
	p.Secure = secure
	return p
}

// WithHTTPOnly sets the httpOnly parameter.
func (p *NetworkSetCookieParams) WithHTTPOnly(httpOnly bool) *NetworkSetCookieParams {
	p.HTTPOnly = httpOnly
	return p
}

// WithSameSite sets the sameSite parameter.
func (p *NetworkSetCookieParams) WithSameSite(sameSite NetworkCookieSameSite) *NetworkSetCookieParams {
	p.SameSite = sameSite
	return p
}

// WithExpires sets the expires parameter.
func (p *NetworkSetCookieParams) WithExpires(expires TimeSinceEpoch) *NetworkSetCookieParams {
	p.Expires = expires
	return p
}

// WithPriority sets the priority parameter.
func (p *NetworkSetCookieParams) WithPriority(priority NetworkCookiePriority) *NetworkSetCookieParams {
	p.Priority = priority
	return p
}

// WithSourceScheme sets the sourceScheme parameter.
func (p *NetworkSetCookieParams) WithSourceScheme(sourceScheme NetworkCookieSourceScheme) *NetworkSetCookieParams {
	p.SourceScheme = sourceScheme
	return p
}

// WithSourcePort sets the sourcePort parameter.
func (p *NetworkSetCookieParams) WithSourcePort(sourcePort int64) *NetworkSetCookieParams {
	p.SourcePort = sourcePort
	return p
}

// WithPartitionKey sets the partitionKey parameter.
func (p *NetworkSetCookieParams) WithPartitionKey(partitionKey NetworkCookiePartitionKey) *NetworkSetCookieParams {
	p.PartitionKey = partitionKey
	return p
}

// Do executes Network.setCookie.
func (p *NetworkSetCookieParams) Do(ctx context.Context) (*NetworkSetCookieReturns, error) {
	var res NetworkSetCookieReturns
	if err := Execute(ctx, NetworkCommandSetCookie, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NetworkSetCookiesParams Sets given cookies.
type NetworkSetCookiesParams struct {
	// Cookies Cookies to be set.
	Cookies []NetworkCookieParam `json:"cookies"`
}

// NetworkSetCookies creates a new NetworkSetCookiesParams.
func NetworkSetCookies(cookies []NetworkCookieParam) *NetworkSetCookiesParams {
	return &NetworkSetCookiesParams{
		Cookies: cookies,
	}
}

// Do executes Network.setCookies.
func (p *NetworkSetCookiesParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandSetCookies, p, nil)
}

// NetworkSetExtraHTTPHeadersParams Specifies whether to always send extra HTTP headers with the requests from this page.
type NetworkSetExtraHTTPHeadersParams struct {
	// Headers Map with extra HTTP headers.
	Headers NetworkHeaders `json:"headers"`
}

// NetworkSetExtraHTTPHeaders creates a new NetworkSetExtraHTTPHeadersParams.
func NetworkSetExtraHTTPHeaders(headers NetworkHeaders) *NetworkSetExtraHTTPHeadersParams {
	return &NetworkSetExtraHTTPHeadersParams{
		Headers: headers,
	}
}

// Do executes Network.setExtraHTTPHeaders.
func (p *NetworkSetExtraHTTPHeadersParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandSetExtraHTTPHeaders, p, nil)
}

// NetworkSetAttachDebugStackParams Specifies whether to attach a page script stack id in requests
type NetworkSetAttachDebugStackParams struct {
	// Enabled Whether to attach a page script stack for debugging purpose.
	Enabled bool `json:"enabled"`
}

// NetworkSetAttachDebugStack creates a new NetworkSetAttachDebugStackParams.
func NetworkSetAttachDebugStack(enabled bool) *NetworkSetAttachDebugStackParams {
	return &NetworkSetAttachDebugStackParams{
		Enabled: enabled,
	}
}

// Do executes Network.setAttachDebugStack.
func (p *NetworkSetAttachDebugStackParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandSetAttachDebugStack, p, nil)
}

// NetworkSetRequestInterceptionParams Sets the requests to intercept that match the provided patterns and optionally resource types.
// Deprecated, please use Fetch.enable instead.
type NetworkSetRequestInterceptionParams struct {
	// Patterns Requests matching any of these patterns will be forwarded and wait for the corresponding
	// continueInterceptedRequest call.
	Patterns []NetworkRequestPattern `json:"patterns"`
}

// NetworkSetRequestInterception creates a new NetworkSetRequestInterceptionParams.
func NetworkSetRequestInterception(patterns []NetworkRequestPattern) *NetworkSetRequestInterceptionParams {
	return &NetworkSetRequestInterceptionParams{
		Patterns: patterns,
	}
}

// Do executes Network.setRequestInterception.
func (p *NetworkSetRequestInterceptionParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandSetRequestInterception, p, nil)
}

// NetworkSetUserAgentOverrideParams Allows overriding user agent with the given string.
type NetworkSetUserAgentOverrideParams struct {
	// UserAgent User agent to use.
	UserAgent string `json:"userAgent"`
	// AcceptLanguage Browser language to emulate.
	AcceptLanguage string `json:"acceptLanguage,omitempty,omitzero"`
	// Platform The platform navigator.platform should return.
	Platform string `json:"platform,omitempty,omitzero"`
	// UserAgentMetadata To be sent in Sec-CH-UA-* headers and returned in navigator.userAgentData
	UserAgentMetadata EmulationUserAgentMetadata `json:"userAgentMetadata,omitempty,omitzero"`
}

// NetworkSetUserAgentOverride creates a new NetworkSetUserAgentOverrideParams.
func NetworkSetUserAgentOverride(userAgent string) *NetworkSetUserAgentOverrideParams {
	return &NetworkSetUserAgentOverrideParams{
		UserAgent: userAgent,
	}
}

// WithAcceptLanguage sets the acceptLanguage parameter.
func (p *NetworkSetUserAgentOverrideParams) WithAcceptLanguage(acceptLanguage string) *NetworkSetUserAgentOverrideParams {
	p.AcceptLanguage = acceptLanguage
	return p
}

// WithPlatform sets the platform parameter.
func (p *NetworkSetUserAgentOverrideParams) WithPlatform(platform string) *NetworkSetUserAgentOverrideParams {
	p.Platform = platform
	return p
}

// WithUserAgentMetadata sets the userAgentMetadata parameter.
func (p *NetworkSetUserAgentOverrideParams) WithUserAgentMetadata(userAgentMetadata EmulationUserAgentMetadata) *NetworkSetUserAgentOverrideParams {
	p.UserAgentMetadata = userAgentMetadata
	return p
}

// Do executes Network.setUserAgentOverride.
func (p *NetworkSetUserAgentOverrideParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandSetUserAgentOverride, p, nil)
}

// NetworkStreamResourceContentParams Enables streaming of the response for the given requestId.
// If enabled, the dataReceived event contains the data that was received during streaming.
type NetworkStreamResourceContentParams struct {
	// RequestID Identifier of the request to stream.
	RequestID RequestID `json:"requestId"`
}

// NetworkStreamResourceContentReturns holds the return values for streamResourceContent.
type NetworkStreamResourceContentReturns struct {
	// BufferedData Data that has been buffered until streaming is enabled.
	BufferedData []byte `json:"bufferedData"`
}

// NetworkStreamResourceContent creates a new NetworkStreamResourceContentParams.
func NetworkStreamResourceContent(requestID RequestID) *NetworkStreamResourceContentParams {
	return &NetworkStreamResourceContentParams{
		RequestID: requestID,
	}
}

// Do executes Network.streamResourceContent.
func (p *NetworkStreamResourceContentParams) Do(ctx context.Context) (*NetworkStreamResourceContentReturns, error) {
	var res NetworkStreamResourceContentReturns
	if err := Execute(ctx, NetworkCommandStreamResourceContent, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NetworkGetSecurityIsolationStatusParams Returns information about the COEP/COOP isolation status.
type NetworkGetSecurityIsolationStatusParams struct {
	// FrameID If no frameId is provided, the status of the target is provided.
	FrameID FrameID `json:"frameId,omitempty,omitzero"`
}

// NetworkGetSecurityIsolationStatusReturns holds the return values for getSecurityIsolationStatus.
type NetworkGetSecurityIsolationStatusReturns struct {
	Status NetworkSecurityIsolationStatus `json:"status"`
}

// NetworkGetSecurityIsolationStatus creates a new NetworkGetSecurityIsolationStatusParams.
func NetworkGetSecurityIsolationStatus() *NetworkGetSecurityIsolationStatusParams {
	return &NetworkGetSecurityIsolationStatusParams{}
}

// WithFrameID sets the frameId parameter.
func (p *NetworkGetSecurityIsolationStatusParams) WithFrameID(frameID FrameID) *NetworkGetSecurityIsolationStatusParams {
	p.FrameID = frameID
	return p
}

// Do executes Network.getSecurityIsolationStatus.
func (p *NetworkGetSecurityIsolationStatusParams) Do(ctx context.Context) (*NetworkGetSecurityIsolationStatusReturns, error) {
	var res NetworkGetSecurityIsolationStatusReturns
	if err := Execute(ctx, NetworkCommandGetSecurityIsolationStatus, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NetworkEnableReportingAPIParams Enables tracking for the Reporting API, events generated by the Reporting API will now be delivered to the client.
// Enabling triggers 'reportingApiReportAdded' for all existing reports.
type NetworkEnableReportingAPIParams struct {
	// Enable Whether to enable or disable events for the Reporting API
	Enable bool `json:"enable"`
}

// NetworkEnableReportingAPI creates a new NetworkEnableReportingAPIParams.
func NetworkEnableReportingAPI(enable bool) *NetworkEnableReportingAPIParams {
	return &NetworkEnableReportingAPIParams{
		Enable: enable,
	}
}

// Do executes Network.enableReportingApi.
func (p *NetworkEnableReportingAPIParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandEnableReportingAPI, p, nil)
}

// NetworkEnableDeviceBoundSessionsParams Sets up tracking device bound sessions and fetching of initial set of sessions.
type NetworkEnableDeviceBoundSessionsParams struct {
	// Enable Whether to enable or disable events.
	Enable bool `json:"enable"`
}

// NetworkEnableDeviceBoundSessions creates a new NetworkEnableDeviceBoundSessionsParams.
func NetworkEnableDeviceBoundSessions(enable bool) *NetworkEnableDeviceBoundSessionsParams {
	return &NetworkEnableDeviceBoundSessionsParams{
		Enable: enable,
	}
}

// Do executes Network.enableDeviceBoundSessions.
func (p *NetworkEnableDeviceBoundSessionsParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandEnableDeviceBoundSessions, p, nil)
}

// NetworkFetchSchemefulSiteParams Fetches the schemeful site for a specific origin.
type NetworkFetchSchemefulSiteParams struct {
	// Origin The URL origin.
	Origin string `json:"origin"`
}

// NetworkFetchSchemefulSiteReturns holds the return values for fetchSchemefulSite.
type NetworkFetchSchemefulSiteReturns struct {
	// SchemefulSite The corresponding schemeful site.
	SchemefulSite string `json:"schemefulSite"`
}

// NetworkFetchSchemefulSite creates a new NetworkFetchSchemefulSiteParams.
func NetworkFetchSchemefulSite(origin string) *NetworkFetchSchemefulSiteParams {
	return &NetworkFetchSchemefulSiteParams{
		Origin: origin,
	}
}

// Do executes Network.fetchSchemefulSite.
func (p *NetworkFetchSchemefulSiteParams) Do(ctx context.Context) (*NetworkFetchSchemefulSiteReturns, error) {
	var res NetworkFetchSchemefulSiteReturns
	if err := Execute(ctx, NetworkCommandFetchSchemefulSite, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NetworkLoadNetworkResourceParams Fetches the resource and returns the content.
type NetworkLoadNetworkResourceParams struct {
	// FrameID Frame id to get the resource for. Mandatory for frame targets, and
	// should be omitted for worker targets.
	FrameID FrameID `json:"frameId,omitempty,omitzero"`
	// URL URL of the resource to get content for.
	URL string `json:"url"`
	// Options Options for the request.
	Options NetworkLoadNetworkResourceOptions `json:"options"`
}

// NetworkLoadNetworkResourceReturns holds the return values for loadNetworkResource.
type NetworkLoadNetworkResourceReturns struct {
	Resource NetworkLoadNetworkResourcePageResult `json:"resource"`
}

// NetworkLoadNetworkResource creates a new NetworkLoadNetworkResourceParams.
func NetworkLoadNetworkResource(url string, options NetworkLoadNetworkResourceOptions) *NetworkLoadNetworkResourceParams {
	return &NetworkLoadNetworkResourceParams{
		URL:     url,
		Options: options,
	}
}

// WithFrameID sets the frameId parameter.
func (p *NetworkLoadNetworkResourceParams) WithFrameID(frameID FrameID) *NetworkLoadNetworkResourceParams {
	p.FrameID = frameID
	return p
}

// Do executes Network.loadNetworkResource.
func (p *NetworkLoadNetworkResourceParams) Do(ctx context.Context) (*NetworkLoadNetworkResourceReturns, error) {
	var res NetworkLoadNetworkResourceReturns
	if err := Execute(ctx, NetworkCommandLoadNetworkResource, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NetworkSetCookieControlsParams Sets Controls for third-party cookie access
// Page reload is required before the new cookie behavior will be observed
type NetworkSetCookieControlsParams struct {
	// EnableThirdPartyCookieRestriction Whether 3pc restriction is enabled.
	EnableThirdPartyCookieRestriction bool `json:"enableThirdPartyCookieRestriction"`
	// DisableThirdPartyCookieMetadata Whether 3pc grace period exception should be enabled; false by default.
	DisableThirdPartyCookieMetadata bool `json:"disableThirdPartyCookieMetadata"`
	// DisableThirdPartyCookieHeuristics Whether 3pc heuristics exceptions should be enabled; false by default.
	DisableThirdPartyCookieHeuristics bool `json:"disableThirdPartyCookieHeuristics"`
}

// NetworkSetCookieControls creates a new NetworkSetCookieControlsParams.
func NetworkSetCookieControls(enableThirdPartyCookieRestriction bool, disableThirdPartyCookieMetadata bool, disableThirdPartyCookieHeuristics bool) *NetworkSetCookieControlsParams {
	return &NetworkSetCookieControlsParams{
		EnableThirdPartyCookieRestriction: enableThirdPartyCookieRestriction,
		DisableThirdPartyCookieMetadata:   disableThirdPartyCookieMetadata,
		DisableThirdPartyCookieHeuristics: disableThirdPartyCookieHeuristics,
	}
}

// Do executes Network.setCookieControls.
func (p *NetworkSetCookieControlsParams) Do(ctx context.Context) error {
	return Execute(ctx, NetworkCommandSetCookieControls, p, nil)
}

// Network command names.
const (
	NetworkCommandSetAcceptedEncodings                    Method = "Network.setAcceptedEncodings"
	NetworkCommandClearAcceptedEncodingsOverride          Method = "Network.clearAcceptedEncodingsOverride"
	NetworkCommandCanClearBrowserCache                    Method = "Network.canClearBrowserCache"
	NetworkCommandCanClearBrowserCookies                  Method = "Network.canClearBrowserCookies"
	NetworkCommandCanEmulateNetworkConditions             Method = "Network.canEmulateNetworkConditions"
	NetworkCommandClearBrowserCache                       Method = "Network.clearBrowserCache"
	NetworkCommandClearBrowserCookies                     Method = "Network.clearBrowserCookies"
	NetworkCommandContinueInterceptedRequest              Method = "Network.continueInterceptedRequest"
	NetworkCommandDeleteCookies                           Method = "Network.deleteCookies"
	NetworkCommandDisable                                 Method = "Network.disable"
	NetworkCommandEmulateNetworkConditions                Method = "Network.emulateNetworkConditions"
	NetworkCommandEmulateNetworkConditionsByRule          Method = "Network.emulateNetworkConditionsByRule"
	NetworkCommandOverrideNetworkState                    Method = "Network.overrideNetworkState"
	NetworkCommandEnable                                  Method = "Network.enable"
	NetworkCommandConfigureDurableMessages                Method = "Network.configureDurableMessages"
	NetworkCommandGetAllCookies                           Method = "Network.getAllCookies"
	NetworkCommandGetCertificate                          Method = "Network.getCertificate"
	NetworkCommandGetCookies                              Method = "Network.getCookies"
	NetworkCommandGetResponseBody                         Method = "Network.getResponseBody"
	NetworkCommandGetRequestPostData                      Method = "Network.getRequestPostData"
	NetworkCommandGetResponseBodyForInterception          Method = "Network.getResponseBodyForInterception"
	NetworkCommandTakeResponseBodyForInterceptionAsStream Method = "Network.takeResponseBodyForInterceptionAsStream"
	NetworkCommandReplayXHR                               Method = "Network.replayXHR"
	NetworkCommandSearchInResponseBody                    Method = "Network.searchInResponseBody"
	NetworkCommandSetBlockedURLs                          Method = "Network.setBlockedURLs"
	NetworkCommandSetBypassServiceWorker                  Method = "Network.setBypassServiceWorker"
	NetworkCommandSetCacheDisabled                        Method = "Network.setCacheDisabled"
	NetworkCommandSetCookie                               Method = "Network.setCookie"
	NetworkCommandSetCookies                              Method = "Network.setCookies"
	NetworkCommandSetExtraHTTPHeaders                     Method = "Network.setExtraHTTPHeaders"
	NetworkCommandSetAttachDebugStack                     Method = "Network.setAttachDebugStack"
	NetworkCommandSetRequestInterception                  Method = "Network.setRequestInterception"
	NetworkCommandSetUserAgentOverride                    Method = "Network.setUserAgentOverride"
	NetworkCommandStreamResourceContent                   Method = "Network.streamResourceContent"
	NetworkCommandGetSecurityIsolationStatus              Method = "Network.getSecurityIsolationStatus"
	NetworkCommandEnableReportingAPI                      Method = "Network.enableReportingApi"
	NetworkCommandEnableDeviceBoundSessions               Method = "Network.enableDeviceBoundSessions"
	NetworkCommandFetchSchemefulSite                      Method = "Network.fetchSchemefulSite"
	NetworkCommandLoadNetworkResource                     Method = "Network.loadNetworkResource"
	NetworkCommandSetCookieControls                       Method = "Network.setCookieControls"
)
