// Code generated by bonkgen. DO NOT EDIT.

package proto

// OverlayEventInspectNodeRequested Fired when the node should be inspected. This happens after call to `setInspectMode` or when
// user manually inspects an element.
type OverlayEventInspectNodeRequested struct {
	// BackendNodeID Id of the node to inspect.
	BackendNodeID BackendNodeID `json:"backendNodeId"`
}

// OverlayEventNodeHighlightRequested Fired when the node should be highlighted. This happens after call to `setInspectMode`.
type OverlayEventNodeHighlightRequested struct {
	NodeID NodeID `json:"nodeId"`
}

// OverlayEventScreenshotRequested Fired when user asks to capture screenshot of some area on the page.
type OverlayEventScreenshotRequested struct {
	// Viewport Viewport to capture, in device independent pixels (dip).
	Viewport PageViewport `json:"viewport"`
}

// OverlayEventInspectPanelShowRequested Fired when user asks to show the Inspect panel.
type OverlayEventInspectPanelShowRequested struct {
	// BackendNodeID Id of the node to show in the panel.
	BackendNodeID BackendNodeID `json:"backendNodeId"`
}

// OverlayEventInspectedElementWindowRestored Fired when user asks to restore the Inspected Element floating window.
type OverlayEventInspectedElementWindowRestored struct {
	// BackendNodeID Id of the node to restore the floating window for.
	BackendNodeID BackendNodeID `json:"backendNodeId"`
}

// OverlayEventInspectModeCanceled Fired when user cancels the inspect mode.
type OverlayEventInspectModeCanceled struct{}

// Overlay event names.
const (
	OverlayEventInspectNodeRequestedMethod           Method = "Overlay.inspectNodeRequested"
	OverlayEventNodeHighlightRequestedMethod         Method = "Overlay.nodeHighlightRequested"
	OverlayEventScreenshotRequestedMethod            Method = "Overlay.screenshotRequested"
	OverlayEventInspectPanelShowRequestedMethod      Method = "Overlay.inspectPanelShowRequested"
	OverlayEventInspectedElementWindowRestoredMethod Method = "Overlay.inspectedElementWindowRestored"
	OverlayEventInspectModeCanceledMethod            Method = "Overlay.inspectModeCanceled"
)
