// Code generated by bonkgen. DO NOT EDIT.

package proto

// PerformanceEventMetrics Current values of the metrics.
type PerformanceEventMetrics struct {
	// Metrics Current values of the metrics.
	Metrics []PerformanceMetric `json:"metrics"`
	// Title Timestamp title.
	Title string `json:"title"`
}

// Performance event names.
const (
	PerformanceEventMetricsMethod Method = "Performance.metrics"
)
