// Code generated by bonkgen. DO NOT EDIT.

package proto

// PreloadEventRuleSetUpdated Upsert. Currently, it is only emitted when a rule set added.
type PreloadEventRuleSetUpdated struct {
	RuleSet PreloadRuleSet `json:"ruleSet"`
}

type PreloadEventRuleSetRemoved struct {
	ID PreloadRuleSetID `json:"id"`
}

// PreloadEventPreloadEnabledStateUpdated Fired when a preload enabled state is updated.
type PreloadEventPreloadEnabledStateUpdated struct {
	DisabledByPreference                        bool `json:"disabledByPreference"`
	DisabledByDataSaver                         bool `json:"disabledByDataSaver"`
	DisabledByBatterySaver                      bool `json:"disabledByBatterySaver"`
	DisabledByHoldbackPrefetchSpeculationRules  bool `json:"disabledByHoldbackPrefetchSpeculationRules"`
	DisabledByHoldbackPrerenderSpeculationRules bool `json:"disabledByHoldbackPrerenderSpeculationRules"`
}

// PreloadEventPrefetchStatusUpdated Fired when a prefetch attempt is updated.
type PreloadEventPrefetchStatusUpdated struct {
	Key        PreloadPreloadingAttemptKey `json:"key"`
	PipelineID PreloadPreloadPipelineID    `json:"pipelineId"`
	// InitiatingFrameID The frame id of the frame initiating prefetch.
	InitiatingFrameID FrameID                 `json:"initiatingFrameId"`
	PrefetchURL       string                  `json:"prefetchUrl"`
	Status            PreloadPreloadingStatus `json:"status"`
	PrefetchStatus    PreloadPrefetchStatus   `json:"prefetchStatus"`
	RequestID         RequestID               `json:"requestId"`
}

// PreloadEventPrerenderStatusUpdated Fired when a prerender attempt is updated.
type PreloadEventPrerenderStatusUpdated struct {
	Key             PreloadPreloadingAttemptKey `json:"key"`
	PipelineID      PreloadPreloadPipelineID    `json:"pipelineId"`
	Status          PreloadPreloadingStatus     `json:"status"`
	PrerenderStatus PreloadPrerenderFinalStatus `json:"prerenderStatus,omitempty,omitzero"`
	// DisallowedMojoInterface This is used to give users more information about the name of Mojo interface
	// that is incompatible with prerender and has caused the cancellation of the attempt.
	DisallowedMojoInterface string                              `json:"disallowedMojoInterface,omitempty,omitzero"`
	MismatchedHeaders       []PreloadPrerenderMismatchedHeaders `json:"mismatchedHeaders,omitempty,omitzero"`
}

// PreloadEventPreloadingAttemptSourcesUpdated Send a list of sources for all preloading attempts in a document.
type PreloadEventPreloadingAttemptSourcesUpdated struct {
	LoaderID                 LoaderID                         `json:"loaderId"`
	PreloadingAttemptSources []PreloadPreloadingAttemptSource `json:"preloadingAttemptSources"`
}

// Preload event names.
const (
	PreloadEventRuleSetUpdatedMethod                  Method = "Preload.ruleSetUpdated"
	PreloadEventRuleSetRemovedMethod                  Method = "Preload.ruleSetRemoved"
	PreloadEventPreloadEnabledStateUpdatedMethod      Method = "Preload.preloadEnabledStateUpdated"
	PreloadEventPrefetchStatusUpdatedMethod           Method = "Preload.prefetchStatusUpdated"
	PreloadEventPrerenderStatusUpdatedMethod          Method = "Preload.prerenderStatusUpdated"
	PreloadEventPreloadingAttemptSourcesUpdatedMethod Method = "Preload.preloadingAttemptSourcesUpdated"
)
