// Code generated by bonkgen. DO NOT EDIT.

package proto

import "encoding/json"

// RuntimeEventBindingCalled Notification is issued every time when binding is called.
type RuntimeEventBindingCalled struct {
	Name    string `json:"name"`
	Payload string `json:"payload"`
	// ExecutionContextID Identifier of the context where the call was made.
	ExecutionContextID RuntimeExecutionContextID `json:"executionContextId"`
}

// RuntimeEventConsoleAPICalled Issued when console API was called.
type RuntimeEventConsoleAPICalled struct {
	// Type Type of the call.
	Type RuntimeConsoleAPICalledType `json:"type"`
	// Args Call arguments.
	Args []RuntimeRemoteObject `json:"args"`
	// ExecutionContextID Identifier of the context where the call was made.
	ExecutionContextID RuntimeExecutionContextID `json:"executionContextId"`
	// Timestamp Call timestamp.
	Timestamp RuntimeTimestamp `json:"timestamp"`
	// StackTrace Stack trace captured when the call was made. The async stack chain is automatically reported for
	// the following call types: `assert`, `error`, `trace`, `warning`. For other types the async call
	// chain can be retrieved using `Debugger.getStackTrace` and `stackTrace.parentId` field.
	StackTrace RuntimeStackTrace `json:"stackTrace,omitempty"`
	// Context Console context descriptor for calls on non-default console context (not console.*):
	// 'anonymous#unique-logger-id' for call on unnamed context, 'name#unique-logger-id' for call
	// on named context.
	Context string `json:"context,omitempty"`
}

// RuntimeEventExceptionRevoked Issued when unhandled exception was revoked.
type RuntimeEventExceptionRevoked struct {
	// Reason Reason describing why exception was revoked.
	Reason string `json:"reason"`
	// ExceptionID The id of revoked exception, as reported in `exceptionThrown`.
	ExceptionID int64 `json:"exceptionId"`
}

// RuntimeEventExceptionThrown Issued when exception was thrown and unhandled.
type RuntimeEventExceptionThrown struct {
	// Timestamp Timestamp of the exception.
	Timestamp        RuntimeTimestamp        `json:"timestamp"`
	ExceptionDetails RuntimeExceptionDetails `json:"exceptionDetails"`
}

// RuntimeEventExecutionContextCreated Issued when new execution context is created.
type RuntimeEventExecutionContextCreated struct {
	// Context A newly created execution context.
	Context RuntimeExecutionContextDescription `json:"context"`
}

// RuntimeEventExecutionContextDestroyed Issued when execution context is destroyed.
type RuntimeEventExecutionContextDestroyed struct {
	// ExecutionContextID Id of the destroyed context
	ExecutionContextID RuntimeExecutionContextID `json:"executionContextId"`
	// ExecutionContextUniqueID Unique Id of the destroyed context
	ExecutionContextUniqueID string `json:"executionContextUniqueId"`
}

// RuntimeEventExecutionContextsCleared Issued when all executionContexts were cleared in browser
type RuntimeEventExecutionContextsCleared struct{}

// RuntimeEventInspectRequested Issued when object should be inspected (for example, as a result of inspect() command line API
// call).
type RuntimeEventInspectRequested struct {
	Object RuntimeRemoteObject `json:"object"`
	Hints  json.RawMessage     `json:"hints"`
	// ExecutionContextID Identifier of the context where the call was made.
	ExecutionContextID RuntimeExecutionContextID `json:"executionContextId,omitempty"`
}

// Runtime event names.
const (
	RuntimeEventBindingCalledMethod             Method = "Runtime.bindingCalled"
	RuntimeEventConsoleAPICalledMethod          Method = "Runtime.consoleAPICalled"
	RuntimeEventExceptionRevokedMethod          Method = "Runtime.exceptionRevoked"
	RuntimeEventExceptionThrownMethod           Method = "Runtime.exceptionThrown"
	RuntimeEventExecutionContextCreatedMethod   Method = "Runtime.executionContextCreated"
	RuntimeEventExecutionContextDestroyedMethod Method = "Runtime.executionContextDestroyed"
	RuntimeEventExecutionContextsClearedMethod  Method = "Runtime.executionContextsCleared"
	RuntimeEventInspectRequestedMethod          Method = "Runtime.inspectRequested"
)
