// Code generated by bonkgen. DO NOT EDIT.

package proto

import "context"

// RuntimeAwaitPromiseParams Add handler to promise with given promise object id.
type RuntimeAwaitPromiseParams struct {
	// PromiseObjectID Identifier of the promise.
	PromiseObjectID RemoteObjectID `json:"promiseObjectId"`
	// ReturnByValue Whether the result is expected to be a JSON object that should be sent by value.
	ReturnByValue bool `json:"returnByValue,omitempty"`
	// GeneratePreview Whether preview should be generated for the result.
	GeneratePreview bool `json:"generatePreview,omitempty"`
}

// RuntimeAwaitPromiseReturns holds the return values for awaitPromise.
type RuntimeAwaitPromiseReturns struct {
	// Result Promise result. Will contain rejected value if promise was rejected.
	Result RuntimeRemoteObject `json:"result"`
	// ExceptionDetails Exception details if stack strace is available.
	ExceptionDetails RuntimeExceptionDetails `json:"exceptionDetails,omitempty"`
}

// RuntimeAwaitPromise creates a new RuntimeAwaitPromiseParams.
func RuntimeAwaitPromise(promiseObjectID RemoteObjectID) *RuntimeAwaitPromiseParams {
	return &RuntimeAwaitPromiseParams{
		PromiseObjectID: promiseObjectID,
	}
}

// WithReturnByValue sets the returnByValue parameter.
func (p *RuntimeAwaitPromiseParams) WithReturnByValue(returnByValue bool) *RuntimeAwaitPromiseParams {
	p.ReturnByValue = returnByValue
	return p
}

// WithGeneratePreview sets the generatePreview parameter.
func (p *RuntimeAwaitPromiseParams) WithGeneratePreview(generatePreview bool) *RuntimeAwaitPromiseParams {
	p.GeneratePreview = generatePreview
	return p
}

// Do executes Runtime.awaitPromise.
func (p *RuntimeAwaitPromiseParams) Do(ctx context.Context) (*RuntimeAwaitPromiseReturns, error) {
	var res RuntimeAwaitPromiseReturns
	if err := Execute(ctx, RuntimeCommandAwaitPromise, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// RuntimeCallFunctionOnParams Calls function with given declaration on the given object. Object group of the result is
// inherited from the target object.
type RuntimeCallFunctionOnParams struct {
	// FunctionDeclaration Declaration of the function to call.
	FunctionDeclaration string `json:"functionDeclaration"`
	// ObjectID Identifier of the object to call function on. Either objectId or executionContextId should
	// be specified.
	ObjectID RemoteObjectID `json:"objectId,omitempty"`
	// Arguments Call arguments. All call arguments must belong to the same JavaScript world as the target
	// object.
	Arguments []RuntimeCallArgument `json:"arguments,omitempty"`
	// Silent In silent mode exceptions thrown during evaluation are not reported and do not pause
	// execution. Overrides `setPauseOnException` state.
	Silent bool `json:"silent,omitempty"`
	// ReturnByValue Whether the result is expected to be a JSON object which should be sent by value.
	// Can be overriden by `serializationOptions`.
	ReturnByValue bool `json:"returnByValue,omitempty"`
	// GeneratePreview Whether preview should be generated for the result.
	GeneratePreview bool `json:"generatePreview,omitempty"`
	// UserGesture Whether execution should be treated as initiated by user in the UI.
	UserGesture bool `json:"userGesture,omitempty"`
	// AwaitPromise Whether execution should `await` for resulting value and return once awaited promise is
	// resolved.
	AwaitPromise bool `json:"awaitPromise,omitempty"`
	// ExecutionContextID Specifies execution context which global object will be used to call function on. Either
	// executionContextId or objectId should be specified.
	ExecutionContextID RuntimeExecutionContextID `json:"executionContextId,omitempty"`
	// ObjectGroup Symbolic group name that can be used to release multiple objects. If objectGroup is not
	// specified and objectId is, objectGroup will be inherited from object.
	ObjectGroup string `json:"objectGroup,omitempty"`
	// ThrowOnSideEffect Whether to throw an exception if side effect cannot be ruled out during evaluation.
	ThrowOnSideEffect bool `json:"throwOnSideEffect,omitempty"`
	// UniqueContextID An alternative way to specify the execution context to call function on.
	// Compared to contextId that may be reused across processes, this is guaranteed to be
	// system-unique, so it can be used to prevent accidental function call
	// in context different than intended (e.g. as a result of navigation across process
	// boundaries).
	// This is mutually exclusive with `executionContextId`.
	UniqueContextID string `json:"uniqueContextId,omitempty"`
	// SerializationOptions Specifies the result serialization. If provided, overrides
	// `generatePreview` and `returnByValue`.
	SerializationOptions RuntimeSerializationOptions `json:"serializationOptions,omitempty"`
}

// RuntimeCallFunctionOnReturns holds the return values for callFunctionOn.
type RuntimeCallFunctionOnReturns struct {
	// Result Call result.
	Result RuntimeRemoteObject `json:"result"`
	// ExceptionDetails Exception details.
	ExceptionDetails RuntimeExceptionDetails `json:"exceptionDetails,omitempty"`
}

// RuntimeCallFunctionOn creates a new RuntimeCallFunctionOnParams.
func RuntimeCallFunctionOn(functionDeclaration string) *RuntimeCallFunctionOnParams {
	return &RuntimeCallFunctionOnParams{
		FunctionDeclaration: functionDeclaration,
	}
}

// WithObjectID sets the objectId parameter.
func (p *RuntimeCallFunctionOnParams) WithObjectID(objectID RemoteObjectID) *RuntimeCallFunctionOnParams {
	p.ObjectID = objectID
	return p
}

// WithArguments sets the arguments parameter.
func (p *RuntimeCallFunctionOnParams) WithArguments(arguments []RuntimeCallArgument) *RuntimeCallFunctionOnParams {
	p.Arguments = arguments
	return p
}

// WithSilent sets the silent parameter.
func (p *RuntimeCallFunctionOnParams) WithSilent(silent bool) *RuntimeCallFunctionOnParams {
	p.Silent = silent
	return p
}

// WithReturnByValue sets the returnByValue parameter.
func (p *RuntimeCallFunctionOnParams) WithReturnByValue(returnByValue bool) *RuntimeCallFunctionOnParams {
	p.ReturnByValue = returnByValue
	return p
}

// WithGeneratePreview sets the generatePreview parameter.
func (p *RuntimeCallFunctionOnParams) WithGeneratePreview(generatePreview bool) *RuntimeCallFunctionOnParams {
	p.GeneratePreview = generatePreview
	return p
}

// WithUserGesture sets the userGesture parameter.
func (p *RuntimeCallFunctionOnParams) WithUserGesture(userGesture bool) *RuntimeCallFunctionOnParams {
	p.UserGesture = userGesture
	return p
}

// WithAwaitPromise sets the awaitPromise parameter.
func (p *RuntimeCallFunctionOnParams) WithAwaitPromise(awaitPromise bool) *RuntimeCallFunctionOnParams {
	p.AwaitPromise = awaitPromise
	return p
}

// WithExecutionContextID sets the executionContextId parameter.
func (p *RuntimeCallFunctionOnParams) WithExecutionContextID(executionContextID RuntimeExecutionContextID) *RuntimeCallFunctionOnParams {
	p.ExecutionContextID = executionContextID
	return p
}

// WithObjectGroup sets the objectGroup parameter.
func (p *RuntimeCallFunctionOnParams) WithObjectGroup(objectGroup string) *RuntimeCallFunctionOnParams {
	p.ObjectGroup = objectGroup
	return p
}

// WithThrowOnSideEffect sets the throwOnSideEffect parameter.
func (p *RuntimeCallFunctionOnParams) WithThrowOnSideEffect(throwOnSideEffect bool) *RuntimeCallFunctionOnParams {
	p.ThrowOnSideEffect = throwOnSideEffect
	return p
}

// WithUniqueContextID sets the uniqueContextId parameter.
func (p *RuntimeCallFunctionOnParams) WithUniqueContextID(uniqueContextID string) *RuntimeCallFunctionOnParams {
	p.UniqueContextID = uniqueContextID
	return p
}

// WithSerializationOptions sets the serializationOptions parameter.
func (p *RuntimeCallFunctionOnParams) WithSerializationOptions(serializationOptions RuntimeSerializationOptions) *RuntimeCallFunctionOnParams {
	p.SerializationOptions = serializationOptions
	return p
}

// Do executes Runtime.callFunctionOn.
func (p *RuntimeCallFunctionOnParams) Do(ctx context.Context) (*RuntimeCallFunctionOnReturns, error) {
	var res RuntimeCallFunctionOnReturns
	if err := Execute(ctx, RuntimeCommandCallFunctionOn, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// RuntimeCompileScriptParams Compiles expression.
type RuntimeCompileScriptParams struct {
	// Expression Expression to compile.
	Expression string `json:"expression"`
	// SourceURL Source url to be set for the script.
	SourceURL string `json:"sourceURL"`
	// PersistScript Specifies whether the compiled script should be persisted.
	PersistScript bool `json:"persistScript"`
	// ExecutionContextID Specifies in which execution context to perform script run. If the parameter is omitted the
	// evaluation will be performed in the context of the inspected page.
	ExecutionContextID RuntimeExecutionContextID `json:"executionContextId,omitempty"`
}

// RuntimeCompileScriptReturns holds the return values for compileScript.
type RuntimeCompileScriptReturns struct {
	// ScriptID Id of the script.
	ScriptID RuntimeScriptID `json:"scriptId,omitempty"`
	// ExceptionDetails Exception details.
	ExceptionDetails RuntimeExceptionDetails `json:"exceptionDetails,omitempty"`
}

// RuntimeCompileScript creates a new RuntimeCompileScriptParams.
func RuntimeCompileScript(expression string, sourceURL string, persistScript bool) *RuntimeCompileScriptParams {
	return &RuntimeCompileScriptParams{
		Expression:    expression,
		SourceURL:     sourceURL,
		PersistScript: persistScript,
	}
}

// WithExecutionContextID sets the executionContextId parameter.
func (p *RuntimeCompileScriptParams) WithExecutionContextID(executionContextID RuntimeExecutionContextID) *RuntimeCompileScriptParams {
	p.ExecutionContextID = executionContextID
	return p
}

// Do executes Runtime.compileScript.
func (p *RuntimeCompileScriptParams) Do(ctx context.Context) (*RuntimeCompileScriptReturns, error) {
	var res RuntimeCompileScriptReturns
	if err := Execute(ctx, RuntimeCommandCompileScript, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// RuntimeDisableParams Disables reporting of execution contexts creation.
type RuntimeDisableParams struct{}

// RuntimeDisable creates a new RuntimeDisableParams.
func RuntimeDisable() *RuntimeDisableParams {
	return &RuntimeDisableParams{}
}

// Do executes Runtime.disable.
func (p *RuntimeDisableParams) Do(ctx context.Context) error {
	return Execute(ctx, RuntimeCommandDisable, p, nil)
}

// RuntimeDiscardConsoleEntriesParams Discards collected exceptions and console API calls.
type RuntimeDiscardConsoleEntriesParams struct{}

// RuntimeDiscardConsoleEntries creates a new RuntimeDiscardConsoleEntriesParams.
func RuntimeDiscardConsoleEntries() *RuntimeDiscardConsoleEntriesParams {
	return &RuntimeDiscardConsoleEntriesParams{}
}

// Do executes Runtime.discardConsoleEntries.
func (p *RuntimeDiscardConsoleEntriesParams) Do(ctx context.Context) error {
	return Execute(ctx, RuntimeCommandDiscardConsoleEntries, p, nil)
}

// RuntimeEnableParams Enables reporting of execution contexts creation by means of `executionContextCreated` event.
// When the reporting gets enabled the event will be sent immediately for each existing execution
// context.
type RuntimeEnableParams struct{}

// RuntimeEnable creates a new RuntimeEnableParams.
func RuntimeEnable() *RuntimeEnableParams {
	return &RuntimeEnableParams{}
}

// Do executes Runtime.enable.
func (p *RuntimeEnableParams) Do(ctx context.Context) error {
	return Execute(ctx, RuntimeCommandEnable, p, nil)
}

// RuntimeEvaluateParams Evaluates expression on global object.
type RuntimeEvaluateParams struct {
	// Expression Expression to evaluate.
	Expression string `json:"expression"`
	// ObjectGroup Symbolic group name that can be used to release multiple objects.
	ObjectGroup string `json:"objectGroup,omitempty"`
	// IncludeCommandLineAPI Determines whether Command Line API should be available during the evaluation.
	IncludeCommandLineAPI bool `json:"includeCommandLineAPI,omitempty"`
	// Silent In silent mode exceptions thrown during evaluation are not reported and do not pause
	// execution. Overrides `setPauseOnException` state.
	Silent bool `json:"silent,omitempty"`
	// ContextID Specifies in which execution context to perform evaluation. If the parameter is omitted the
	// evaluation will be performed in the context of the inspected page.
	// This is mutually exclusive with `uniqueContextId`, which offers an
	// alternative way to identify the execution context that is more reliable
	// in a multi-process environment.
	ContextID RuntimeExecutionContextID `json:"contextId,omitempty"`
	// ReturnByValue Whether the result is expected to be a JSON object that should be sent by value.
	ReturnByValue bool `json:"returnByValue,omitempty"`
	// GeneratePreview Whether preview should be generated for the result.
	GeneratePreview bool `json:"generatePreview,omitempty"`
	// UserGesture Whether execution should be treated as initiated by user in the UI.
	UserGesture bool `json:"userGesture,omitempty"`
	// AwaitPromise Whether execution should `await` for resulting value and return once awaited promise is
	// resolved.
	AwaitPromise bool `json:"awaitPromise,omitempty"`
	// ThrowOnSideEffect Whether to throw an exception if side effect cannot be ruled out during evaluation.
	// This implies `disableBreaks` below.
	ThrowOnSideEffect bool `json:"throwOnSideEffect,omitempty"`
	// Timeout Terminate execution after timing out (number of milliseconds).
	Timeout RuntimeTimeDelta `json:"timeout,omitempty"`
	// DisableBreaks Disable breakpoints during execution.
	DisableBreaks bool `json:"disableBreaks,omitempty"`
	// ReplMode Setting this flag to true enables `let` re-declaration and top-level `await`.
	// Note that `let` variables can only be re-declared if they originate from
	// `replMode` themselves.
	ReplMode bool `json:"replMode,omitempty"`
	// AllowUnsafeEvalBlockedByCSP The Content Security Policy (CSP) for the target might block 'unsafe-eval'
	// which includes eval(), Function(), setTimeout() and setInterval()
	// when called with non-callable arguments. This flag bypasses CSP for this
	// evaluation and allows unsafe-eval. Defaults to true.
	AllowUnsafeEvalBlockedByCSP bool `json:"allowUnsafeEvalBlockedByCSP,omitempty"`
	// UniqueContextID An alternative way to specify the execution context to evaluate in.
	// Compared to contextId that may be reused across processes, this is guaranteed to be
	// system-unique, so it can be used to prevent accidental evaluation of the expression
	// in context different than intended (e.g. as a result of navigation across process
	// boundaries).
	// This is mutually exclusive with `contextId`.
	UniqueContextID string `json:"uniqueContextId,omitempty"`
	// SerializationOptions Specifies the result serialization. If provided, overrides
	// `generatePreview` and `returnByValue`.
	SerializationOptions RuntimeSerializationOptions `json:"serializationOptions,omitempty"`
}

// RuntimeEvaluateReturns holds the return values for evaluate.
type RuntimeEvaluateReturns struct {
	// Result Evaluation result.
	Result RuntimeRemoteObject `json:"result"`
	// ExceptionDetails Exception details.
	ExceptionDetails RuntimeExceptionDetails `json:"exceptionDetails,omitempty"`
}

// RuntimeEvaluate creates a new RuntimeEvaluateParams.
func RuntimeEvaluate(expression string) *RuntimeEvaluateParams {
	return &RuntimeEvaluateParams{
		Expression: expression,
	}
}

// WithObjectGroup sets the objectGroup parameter.
func (p *RuntimeEvaluateParams) WithObjectGroup(objectGroup string) *RuntimeEvaluateParams {
	p.ObjectGroup = objectGroup
	return p
}

// WithIncludeCommandLineAPI sets the includeCommandLineAPI parameter.
func (p *RuntimeEvaluateParams) WithIncludeCommandLineAPI(includeCommandLineAPI bool) *RuntimeEvaluateParams {
	p.IncludeCommandLineAPI = includeCommandLineAPI
	return p
}

// WithSilent sets the silent parameter.
func (p *RuntimeEvaluateParams) WithSilent(silent bool) *RuntimeEvaluateParams {
	p.Silent = silent
	return p
}

// WithContextID sets the contextId parameter.
func (p *RuntimeEvaluateParams) WithContextID(contextID RuntimeExecutionContextID) *RuntimeEvaluateParams {
	p.ContextID = contextID
	return p
}

// WithReturnByValue sets the returnByValue parameter.
func (p *RuntimeEvaluateParams) WithReturnByValue(returnByValue bool) *RuntimeEvaluateParams {
	p.ReturnByValue = returnByValue
	return p
}

// WithGeneratePreview sets the generatePreview parameter.
func (p *RuntimeEvaluateParams) WithGeneratePreview(generatePreview bool) *RuntimeEvaluateParams {
	p.GeneratePreview = generatePreview
	return p
}

// WithUserGesture sets the userGesture parameter.
func (p *RuntimeEvaluateParams) WithUserGesture(userGesture bool) *RuntimeEvaluateParams {
	p.UserGesture = userGesture
	return p
}

// WithAwaitPromise sets the awaitPromise parameter.
func (p *RuntimeEvaluateParams) WithAwaitPromise(awaitPromise bool) *RuntimeEvaluateParams {
	p.AwaitPromise = awaitPromise
	return p
}

// WithThrowOnSideEffect sets the throwOnSideEffect parameter.
func (p *RuntimeEvaluateParams) WithThrowOnSideEffect(throwOnSideEffect bool) *RuntimeEvaluateParams {
	p.ThrowOnSideEffect = throwOnSideEffect
	return p
}

// WithTimeout sets the timeout parameter.
func (p *RuntimeEvaluateParams) WithTimeout(timeout RuntimeTimeDelta) *RuntimeEvaluateParams {
	p.Timeout = timeout
	return p
}

// WithDisableBreaks sets the disableBreaks parameter.
func (p *RuntimeEvaluateParams) WithDisableBreaks(disableBreaks bool) *RuntimeEvaluateParams {
	p.DisableBreaks = disableBreaks
	return p
}

// WithReplMode sets the replMode parameter.
func (p *RuntimeEvaluateParams) WithReplMode(replMode bool) *RuntimeEvaluateParams {
	p.ReplMode = replMode
	return p
}

// WithAllowUnsafeEvalBlockedByCSP sets the allowUnsafeEvalBlockedByCSP parameter.
func (p *RuntimeEvaluateParams) WithAllowUnsafeEvalBlockedByCSP(allowUnsafeEvalBlockedByCSP bool) *RuntimeEvaluateParams {
	p.AllowUnsafeEvalBlockedByCSP = allowUnsafeEvalBlockedByCSP
	return p
}

// WithUniqueContextID sets the uniqueContextId parameter.
func (p *RuntimeEvaluateParams) WithUniqueContextID(uniqueContextID string) *RuntimeEvaluateParams {
	p.UniqueContextID = uniqueContextID
	return p
}

// WithSerializationOptions sets the serializationOptions parameter.
func (p *RuntimeEvaluateParams) WithSerializationOptions(serializationOptions RuntimeSerializationOptions) *RuntimeEvaluateParams {
	p.SerializationOptions = serializationOptions
	return p
}

// Do executes Runtime.evaluate.
func (p *RuntimeEvaluateParams) Do(ctx context.Context) (*RuntimeEvaluateReturns, error) {
	var res RuntimeEvaluateReturns
	if err := Execute(ctx, RuntimeCommandEvaluate, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// RuntimeGetIsolateIDParams Returns the isolate id.
type RuntimeGetIsolateIDParams struct{}

// RuntimeGetIsolateIDReturns holds the return values for getIsolateId.
type RuntimeGetIsolateIDReturns struct {
	// ID The isolate id.
	ID string `json:"id"`
}

// RuntimeGetIsolateID creates a new RuntimeGetIsolateIDParams.
func RuntimeGetIsolateID() *RuntimeGetIsolateIDParams {
	return &RuntimeGetIsolateIDParams{}
}

// Do executes Runtime.getIsolateId.
func (p *RuntimeGetIsolateIDParams) Do(ctx context.Context) (*RuntimeGetIsolateIDReturns, error) {
	var res RuntimeGetIsolateIDReturns
	if err := Execute(ctx, RuntimeCommandGetIsolateID, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// RuntimeGetHeapUsageParams Returns the JavaScript heap usage.
// It is the total usage of the corresponding isolate not scoped to a particular Runtime.
type RuntimeGetHeapUsageParams struct{}

// RuntimeGetHeapUsageReturns holds the return values for getHeapUsage.
type RuntimeGetHeapUsageReturns struct {
	// UsedSize Used JavaScript heap size in bytes.
	UsedSize float64 `json:"usedSize"`
	// TotalSize Allocated JavaScript heap size in bytes.
	TotalSize float64 `json:"totalSize"`
	// EmbedderHeapUsedSize Used size in bytes in the embedder's garbage-collected heap.
	EmbedderHeapUsedSize float64 `json:"embedderHeapUsedSize"`
	// BackingStorageSize Size in bytes of backing storage for array buffers and external strings.
	BackingStorageSize float64 `json:"backingStorageSize"`
}

// RuntimeGetHeapUsage creates a new RuntimeGetHeapUsageParams.
func RuntimeGetHeapUsage() *RuntimeGetHeapUsageParams {
	return &RuntimeGetHeapUsageParams{}
}

// Do executes Runtime.getHeapUsage.
func (p *RuntimeGetHeapUsageParams) Do(ctx context.Context) (*RuntimeGetHeapUsageReturns, error) {
	var res RuntimeGetHeapUsageReturns
	if err := Execute(ctx, RuntimeCommandGetHeapUsage, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// RuntimeGetPropertiesParams Returns properties of a given object. Object group of the result is inherited from the target
// object.
type RuntimeGetPropertiesParams struct {
	// ObjectID Identifier of the object to return properties for.
	ObjectID RemoteObjectID `json:"objectId"`
	// OwnProperties If true, returns properties belonging only to the element itself, not to its prototype
	// chain.
	OwnProperties bool `json:"ownProperties,omitempty"`
	// AccessorPropertiesOnly If true, returns accessor properties (with getter/setter) only; internal properties are not
	// returned either.
	AccessorPropertiesOnly bool `json:"accessorPropertiesOnly,omitempty"`
	// GeneratePreview Whether preview should be generated for the results.
	GeneratePreview bool `json:"generatePreview,omitempty"`
	// NonIndexedPropertiesOnly If true, returns non-indexed properties only.
	NonIndexedPropertiesOnly bool `json:"nonIndexedPropertiesOnly,omitempty"`
}

// RuntimeGetPropertiesReturns holds the return values for getProperties.
type RuntimeGetPropertiesReturns struct {
	// Result Object properties.
	Result []RuntimePropertyDescriptor `json:"result"`
	// InternalProperties Internal object properties (only of the element itself).
	InternalProperties []RuntimeInternalPropertyDescriptor `json:"internalProperties,omitempty"`
	// PrivateProperties Object private properties.
	PrivateProperties []RuntimePrivatePropertyDescriptor `json:"privateProperties,omitempty"`
	// ExceptionDetails Exception details.
	ExceptionDetails RuntimeExceptionDetails `json:"exceptionDetails,omitempty"`
}

// RuntimeGetProperties creates a new RuntimeGetPropertiesParams.
func RuntimeGetProperties(objectID RemoteObjectID) *RuntimeGetPropertiesParams {
	return &RuntimeGetPropertiesParams{
		ObjectID: objectID,
	}
}

// WithOwnProperties sets the ownProperties parameter.
func (p *RuntimeGetPropertiesParams) WithOwnProperties(ownProperties bool) *RuntimeGetPropertiesParams {
	p.OwnProperties = ownProperties
	return p
}

// WithAccessorPropertiesOnly sets the accessorPropertiesOnly parameter.
func (p *RuntimeGetPropertiesParams) WithAccessorPropertiesOnly(accessorPropertiesOnly bool) *RuntimeGetPropertiesParams {
	p.AccessorPropertiesOnly = accessorPropertiesOnly
	return p
}

// WithGeneratePreview sets the generatePreview parameter.
func (p *RuntimeGetPropertiesParams) WithGeneratePreview(generatePreview bool) *RuntimeGetPropertiesParams {
	p.GeneratePreview = generatePreview
	return p
}

// WithNonIndexedPropertiesOnly sets the nonIndexedPropertiesOnly parameter.
func (p *RuntimeGetPropertiesParams) WithNonIndexedPropertiesOnly(nonIndexedPropertiesOnly bool) *RuntimeGetPropertiesParams {
	p.NonIndexedPropertiesOnly = nonIndexedPropertiesOnly
	return p
}

// Do executes Runtime.getProperties.
func (p *RuntimeGetPropertiesParams) Do(ctx context.Context) (*RuntimeGetPropertiesReturns, error) {
	var res RuntimeGetPropertiesReturns
	if err := Execute(ctx, RuntimeCommandGetProperties, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// RuntimeGlobalLexicalScopeNamesParams Returns all let, const and class variables from global scope.
type RuntimeGlobalLexicalScopeNamesParams struct {
	// ExecutionContextID Specifies in which execution context to lookup global scope variables.
	ExecutionContextID RuntimeExecutionContextID `json:"executionContextId,omitempty"`
}

// RuntimeGlobalLexicalScopeNamesReturns holds the return values for globalLexicalScopeNames.
type RuntimeGlobalLexicalScopeNamesReturns struct {
	Names []string `json:"names"`
}

// RuntimeGlobalLexicalScopeNames creates a new RuntimeGlobalLexicalScopeNamesParams.
func RuntimeGlobalLexicalScopeNames() *RuntimeGlobalLexicalScopeNamesParams {
	return &RuntimeGlobalLexicalScopeNamesParams{}
}

// WithExecutionContextID sets the executionContextId parameter.
func (p *RuntimeGlobalLexicalScopeNamesParams) WithExecutionContextID(executionContextID RuntimeExecutionContextID) *RuntimeGlobalLexicalScopeNamesParams {
	p.ExecutionContextID = executionContextID
	return p
}

// Do executes Runtime.globalLexicalScopeNames.
func (p *RuntimeGlobalLexicalScopeNamesParams) Do(ctx context.Context) (*RuntimeGlobalLexicalScopeNamesReturns, error) {
	var res RuntimeGlobalLexicalScopeNamesReturns
	if err := Execute(ctx, RuntimeCommandGlobalLexicalScopeNames, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type RuntimeQueryObjectsParams struct {
	// PrototypeObjectID Identifier of the prototype to return objects for.
	PrototypeObjectID RemoteObjectID `json:"prototypeObjectId"`
	// ObjectGroup Symbolic group name that can be used to release the results.
	ObjectGroup string `json:"objectGroup,omitempty"`
}

// RuntimeQueryObjectsReturns holds the return values for queryObjects.
type RuntimeQueryObjectsReturns struct {
	// Objects Array with objects.
	Objects RuntimeRemoteObject `json:"objects"`
}

// RuntimeQueryObjects creates a new RuntimeQueryObjectsParams.
func RuntimeQueryObjects(prototypeObjectID RemoteObjectID) *RuntimeQueryObjectsParams {
	return &RuntimeQueryObjectsParams{
		PrototypeObjectID: prototypeObjectID,
	}
}

// WithObjectGroup sets the objectGroup parameter.
func (p *RuntimeQueryObjectsParams) WithObjectGroup(objectGroup string) *RuntimeQueryObjectsParams {
	p.ObjectGroup = objectGroup
	return p
}

// Do executes Runtime.queryObjects.
func (p *RuntimeQueryObjectsParams) Do(ctx context.Context) (*RuntimeQueryObjectsReturns, error) {
	var res RuntimeQueryObjectsReturns
	if err := Execute(ctx, RuntimeCommandQueryObjects, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// RuntimeReleaseObjectParams Releases remote object with given id.
type RuntimeReleaseObjectParams struct {
	// ObjectID Identifier of the object to release.
	ObjectID RemoteObjectID `json:"objectId"`
}

// RuntimeReleaseObject creates a new RuntimeReleaseObjectParams.
func RuntimeReleaseObject(objectID RemoteObjectID) *RuntimeReleaseObjectParams {
	return &RuntimeReleaseObjectParams{
		ObjectID: objectID,
	}
}

// Do executes Runtime.releaseObject.
func (p *RuntimeReleaseObjectParams) Do(ctx context.Context) error {
	return Execute(ctx, RuntimeCommandReleaseObject, p, nil)
}

// RuntimeReleaseObjectGroupParams Releases all remote objects that belong to a given group.
type RuntimeReleaseObjectGroupParams struct {
	// ObjectGroup Symbolic object group name.
	ObjectGroup string `json:"objectGroup"`
}

// RuntimeReleaseObjectGroup creates a new RuntimeReleaseObjectGroupParams.
func RuntimeReleaseObjectGroup(objectGroup string) *RuntimeReleaseObjectGroupParams {
	return &RuntimeReleaseObjectGroupParams{
		ObjectGroup: objectGroup,
	}
}

// Do executes Runtime.releaseObjectGroup.
func (p *RuntimeReleaseObjectGroupParams) Do(ctx context.Context) error {
	return Execute(ctx, RuntimeCommandReleaseObjectGroup, p, nil)
}

// RuntimeRunIfWaitingForDebuggerParams Tells inspected instance to run if it was waiting for debugger to attach.
type RuntimeRunIfWaitingForDebuggerParams struct{}

// RuntimeRunIfWaitingForDebugger creates a new RuntimeRunIfWaitingForDebuggerParams.
func RuntimeRunIfWaitingForDebugger() *RuntimeRunIfWaitingForDebuggerParams {
	return &RuntimeRunIfWaitingForDebuggerParams{}
}

// Do executes Runtime.runIfWaitingForDebugger.
func (p *RuntimeRunIfWaitingForDebuggerParams) Do(ctx context.Context) error {
	return Execute(ctx, RuntimeCommandRunIfWaitingForDebugger, p, nil)
}

// RuntimeRunScriptParams Runs script with given id in a given context.
type RuntimeRunScriptParams struct {
	// ScriptID Id of the script to run.
	ScriptID RuntimeScriptID `json:"scriptId"`
	// ExecutionContextID Specifies in which execution context to perform script run. If the parameter is omitted the
	// evaluation will be performed in the context of the inspected page.
	ExecutionContextID RuntimeExecutionContextID `json:"executionContextId,omitempty"`
	// ObjectGroup Symbolic group name that can be used to release multiple objects.
	ObjectGroup string `json:"objectGroup,omitempty"`
	// Silent In silent mode exceptions thrown during evaluation are not reported and do not pause
	// execution. Overrides `setPauseOnException` state.
	Silent bool `json:"silent,omitempty"`
	// IncludeCommandLineAPI Determines whether Command Line API should be available during the evaluation.
	IncludeCommandLineAPI bool `json:"includeCommandLineAPI,omitempty"`
	// ReturnByValue Whether the result is expected to be a JSON object which should be sent by value.
	ReturnByValue bool `json:"returnByValue,omitempty"`
	// GeneratePreview Whether preview should be generated for the result.
	GeneratePreview bool `json:"generatePreview,omitempty"`
	// AwaitPromise Whether execution should `await` for resulting value and return once awaited promise is
	// resolved.
	AwaitPromise bool `json:"awaitPromise,omitempty"`
}

// RuntimeRunScriptReturns holds the return values for runScript.
type RuntimeRunScriptReturns struct {
	// Result Run result.
	Result RuntimeRemoteObject `json:"result"`
	// ExceptionDetails Exception details.
	ExceptionDetails RuntimeExceptionDetails `json:"exceptionDetails,omitempty"`
}

// RuntimeRunScript creates a new RuntimeRunScriptParams.
func RuntimeRunScript(scriptID RuntimeScriptID) *RuntimeRunScriptParams {
	return &RuntimeRunScriptParams{
		ScriptID: scriptID,
	}
}

// WithExecutionContextID sets the executionContextId parameter.
func (p *RuntimeRunScriptParams) WithExecutionContextID(executionContextID RuntimeExecutionContextID) *RuntimeRunScriptParams {
	p.ExecutionContextID = executionContextID
	return p
}

// WithObjectGroup sets the objectGroup parameter.
func (p *RuntimeRunScriptParams) WithObjectGroup(objectGroup string) *RuntimeRunScriptParams {
	p.ObjectGroup = objectGroup
	return p
}

// WithSilent sets the silent parameter.
func (p *RuntimeRunScriptParams) WithSilent(silent bool) *RuntimeRunScriptParams {
	p.Silent = silent
	return p
}

// WithIncludeCommandLineAPI sets the includeCommandLineAPI parameter.
func (p *RuntimeRunScriptParams) WithIncludeCommandLineAPI(includeCommandLineAPI bool) *RuntimeRunScriptParams {
	p.IncludeCommandLineAPI = includeCommandLineAPI
	return p
}

// WithReturnByValue sets the returnByValue parameter.
func (p *RuntimeRunScriptParams) WithReturnByValue(returnByValue bool) *RuntimeRunScriptParams {
	p.ReturnByValue = returnByValue
	return p
}

// WithGeneratePreview sets the generatePreview parameter.
func (p *RuntimeRunScriptParams) WithGeneratePreview(generatePreview bool) *RuntimeRunScriptParams {
	p.GeneratePreview = generatePreview
	return p
}

// WithAwaitPromise sets the awaitPromise parameter.
func (p *RuntimeRunScriptParams) WithAwaitPromise(awaitPromise bool) *RuntimeRunScriptParams {
	p.AwaitPromise = awaitPromise
	return p
}

// Do executes Runtime.runScript.
func (p *RuntimeRunScriptParams) Do(ctx context.Context) (*RuntimeRunScriptReturns, error) {
	var res RuntimeRunScriptReturns
	if err := Execute(ctx, RuntimeCommandRunScript, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// RuntimeSetAsyncCallStackDepthParams Enables or disables async call stacks tracking.
type RuntimeSetAsyncCallStackDepthParams struct {
	// MaxDepth Maximum depth of async call stacks. Setting to `0` will effectively disable collecting async
	// call stacks (default).
	MaxDepth int64 `json:"maxDepth"`
}

// RuntimeSetAsyncCallStackDepth creates a new RuntimeSetAsyncCallStackDepthParams.
func RuntimeSetAsyncCallStackDepth(maxDepth int64) *RuntimeSetAsyncCallStackDepthParams {
	return &RuntimeSetAsyncCallStackDepthParams{
		MaxDepth: maxDepth,
	}
}

// Do executes Runtime.setAsyncCallStackDepth.
func (p *RuntimeSetAsyncCallStackDepthParams) Do(ctx context.Context) error {
	return Execute(ctx, RuntimeCommandSetAsyncCallStackDepth, p, nil)
}

type RuntimeSetCustomObjectFormatterEnabledParams struct {
	Enabled bool `json:"enabled"`
}

// RuntimeSetCustomObjectFormatterEnabled creates a new RuntimeSetCustomObjectFormatterEnabledParams.
func RuntimeSetCustomObjectFormatterEnabled(enabled bool) *RuntimeSetCustomObjectFormatterEnabledParams {
	return &RuntimeSetCustomObjectFormatterEnabledParams{
		Enabled: enabled,
	}
}

// Do executes Runtime.setCustomObjectFormatterEnabled.
func (p *RuntimeSetCustomObjectFormatterEnabledParams) Do(ctx context.Context) error {
	return Execute(ctx, RuntimeCommandSetCustomObjectFormatterEnabled, p, nil)
}

type RuntimeSetMaxCallStackSizeToCaptureParams struct {
	Size int64 `json:"size"`
}

// RuntimeSetMaxCallStackSizeToCapture creates a new RuntimeSetMaxCallStackSizeToCaptureParams.
func RuntimeSetMaxCallStackSizeToCapture(size int64) *RuntimeSetMaxCallStackSizeToCaptureParams {
	return &RuntimeSetMaxCallStackSizeToCaptureParams{
		Size: size,
	}
}

// Do executes Runtime.setMaxCallStackSizeToCapture.
func (p *RuntimeSetMaxCallStackSizeToCaptureParams) Do(ctx context.Context) error {
	return Execute(ctx, RuntimeCommandSetMaxCallStackSizeToCapture, p, nil)
}

// RuntimeTerminateExecutionParams Terminate current or next JavaScript execution.
// Will cancel the termination when the outer-most script execution ends.
type RuntimeTerminateExecutionParams struct{}

// RuntimeTerminateExecution creates a new RuntimeTerminateExecutionParams.
func RuntimeTerminateExecution() *RuntimeTerminateExecutionParams {
	return &RuntimeTerminateExecutionParams{}
}

// Do executes Runtime.terminateExecution.
func (p *RuntimeTerminateExecutionParams) Do(ctx context.Context) error {
	return Execute(ctx, RuntimeCommandTerminateExecution, p, nil)
}

// RuntimeAddBindingParams If executionContextId is empty, adds binding with the given name on the
// global objects of all inspected contexts, including those created later,
// bindings survive reloads.
// Binding function takes exactly one argument, this argument should be string,
// in case of any other input, function throws an exception.
// Each binding function call produces Runtime.bindingCalled notification.
type RuntimeAddBindingParams struct {
	Name string `json:"name"`
	// ExecutionContextID If specified, the binding would only be exposed to the specified
	// execution context. If omitted and `executionContextName` is not set,
	// the binding is exposed to all execution contexts of the target.
	// This parameter is mutually exclusive with `executionContextName`.
	// Deprecated in favor of `executionContextName` due to an unclear use case
	// and bugs in implementation (crbug.com/1169639). `executionContextId` will be
	// removed in the future.
	ExecutionContextID RuntimeExecutionContextID `json:"executionContextId,omitempty"`
	// ExecutionContextName If specified, the binding is exposed to the executionContext with
	// matching name, even for contexts created after the binding is added.
	// See also `ExecutionContext.name` and `worldName` parameter to
	// `Page.addScriptToEvaluateOnNewDocument`.
	// This parameter is mutually exclusive with `executionContextId`.
	ExecutionContextName string `json:"executionContextName,omitempty"`
}

// RuntimeAddBinding creates a new RuntimeAddBindingParams.
func RuntimeAddBinding(name string) *RuntimeAddBindingParams {
	return &RuntimeAddBindingParams{
		Name: name,
	}
}

// WithExecutionContextID sets the executionContextId parameter.
func (p *RuntimeAddBindingParams) WithExecutionContextID(executionContextID RuntimeExecutionContextID) *RuntimeAddBindingParams {
	p.ExecutionContextID = executionContextID
	return p
}

// WithExecutionContextName sets the executionContextName parameter.
func (p *RuntimeAddBindingParams) WithExecutionContextName(executionContextName string) *RuntimeAddBindingParams {
	p.ExecutionContextName = executionContextName
	return p
}

// Do executes Runtime.addBinding.
func (p *RuntimeAddBindingParams) Do(ctx context.Context) error {
	return Execute(ctx, RuntimeCommandAddBinding, p, nil)
}

// RuntimeRemoveBindingParams This method does not remove binding function from global object but
// unsubscribes current runtime agent from Runtime.bindingCalled notifications.
type RuntimeRemoveBindingParams struct {
	Name string `json:"name"`
}

// RuntimeRemoveBinding creates a new RuntimeRemoveBindingParams.
func RuntimeRemoveBinding(name string) *RuntimeRemoveBindingParams {
	return &RuntimeRemoveBindingParams{
		Name: name,
	}
}

// Do executes Runtime.removeBinding.
func (p *RuntimeRemoveBindingParams) Do(ctx context.Context) error {
	return Execute(ctx, RuntimeCommandRemoveBinding, p, nil)
}

// RuntimeGetExceptionDetailsParams This method tries to lookup and populate exception details for a
// JavaScript Error object.
// Note that the stackTrace portion of the resulting exceptionDetails will
// only be populated if the Runtime domain was enabled at the time when the
// Error was thrown.
type RuntimeGetExceptionDetailsParams struct {
	// ErrorObjectID The error object for which to resolve the exception details.
	ErrorObjectID RemoteObjectID `json:"errorObjectId"`
}

// RuntimeGetExceptionDetailsReturns holds the return values for getExceptionDetails.
type RuntimeGetExceptionDetailsReturns struct {
	ExceptionDetails RuntimeExceptionDetails `json:"exceptionDetails,omitempty"`
}

// RuntimeGetExceptionDetails creates a new RuntimeGetExceptionDetailsParams.
func RuntimeGetExceptionDetails(errorObjectID RemoteObjectID) *RuntimeGetExceptionDetailsParams {
	return &RuntimeGetExceptionDetailsParams{
		ErrorObjectID: errorObjectID,
	}
}

// Do executes Runtime.getExceptionDetails.
func (p *RuntimeGetExceptionDetailsParams) Do(ctx context.Context) (*RuntimeGetExceptionDetailsReturns, error) {
	var res RuntimeGetExceptionDetailsReturns
	if err := Execute(ctx, RuntimeCommandGetExceptionDetails, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// Runtime command names.
const (
	RuntimeCommandAwaitPromise                    Method = "Runtime.awaitPromise"
	RuntimeCommandCallFunctionOn                  Method = "Runtime.callFunctionOn"
	RuntimeCommandCompileScript                   Method = "Runtime.compileScript"
	RuntimeCommandDisable                         Method = "Runtime.disable"
	RuntimeCommandDiscardConsoleEntries           Method = "Runtime.discardConsoleEntries"
	RuntimeCommandEnable                          Method = "Runtime.enable"
	RuntimeCommandEvaluate                        Method = "Runtime.evaluate"
	RuntimeCommandGetIsolateID                    Method = "Runtime.getIsolateId"
	RuntimeCommandGetHeapUsage                    Method = "Runtime.getHeapUsage"
	RuntimeCommandGetProperties                   Method = "Runtime.getProperties"
	RuntimeCommandGlobalLexicalScopeNames         Method = "Runtime.globalLexicalScopeNames"
	RuntimeCommandQueryObjects                    Method = "Runtime.queryObjects"
	RuntimeCommandReleaseObject                   Method = "Runtime.releaseObject"
	RuntimeCommandReleaseObjectGroup              Method = "Runtime.releaseObjectGroup"
	RuntimeCommandRunIfWaitingForDebugger         Method = "Runtime.runIfWaitingForDebugger"
	RuntimeCommandRunScript                       Method = "Runtime.runScript"
	RuntimeCommandSetAsyncCallStackDepth          Method = "Runtime.setAsyncCallStackDepth"
	RuntimeCommandSetCustomObjectFormatterEnabled Method = "Runtime.setCustomObjectFormatterEnabled"
	RuntimeCommandSetMaxCallStackSizeToCapture    Method = "Runtime.setMaxCallStackSizeToCapture"
	RuntimeCommandTerminateExecution              Method = "Runtime.terminateExecution"
	RuntimeCommandAddBinding                      Method = "Runtime.addBinding"
	RuntimeCommandRemoveBinding                   Method = "Runtime.removeBinding"
	RuntimeCommandGetExceptionDetails             Method = "Runtime.getExceptionDetails"
)
