// Code generated by bonkgen. DO NOT EDIT.

package proto

// SchemaDomain Description of the protocol domain.
type SchemaDomain struct {
	// Name Domain name.
	Name string `json:"name"`
	// Version Domain version.
	Version string `json:"version"`
}
