// Code generated by bonkgen. DO NOT EDIT.

package proto

import "context"

// SchemaGetDomainsParams Returns supported domains.
type SchemaGetDomainsParams struct{}

// SchemaGetDomainsReturns holds the return values for getDomains.
type SchemaGetDomainsReturns struct {
	// Domains List of supported domains.
	Domains []SchemaDomain `json:"domains"`
}

// SchemaGetDomains creates a new SchemaGetDomainsParams.
func SchemaGetDomains() *SchemaGetDomainsParams {
	return &SchemaGetDomainsParams{}
}

// Do executes Schema.getDomains.
func (p *SchemaGetDomainsParams) Do(ctx context.Context) (*SchemaGetDomainsReturns, error) {
	var res SchemaGetDomainsReturns
	if err := Execute(ctx, SchemaCommandGetDomains, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// Schema command names.
const (
	SchemaCommandGetDomains Method = "Schema.getDomains"
)
