// Code generated by bonkgen. DO NOT EDIT.

package proto

import "context"

type ServiceWorkerDeliverPushMessageParams struct {
	Origin         string                      `json:"origin"`
	RegistrationID ServiceWorkerRegistrationID `json:"registrationId"`
	Data           string                      `json:"data"`
}

// ServiceWorkerDeliverPushMessage creates a new ServiceWorkerDeliverPushMessageParams.
func ServiceWorkerDeliverPushMessage(origin string, registrationID ServiceWorkerRegistrationID, data string) *ServiceWorkerDeliverPushMessageParams {
	return &ServiceWorkerDeliverPushMessageParams{
		Origin:         origin,
		RegistrationID: registrationID,
		Data:           data,
	}
}

// Do executes ServiceWorker.deliverPushMessage.
func (p *ServiceWorkerDeliverPushMessageParams) Do(ctx context.Context) error {
	return Execute(ctx, ServiceWorkerCommandDeliverPushMessage, p, nil)
}

type ServiceWorkerDisableParams struct{}

// ServiceWorkerDisable creates a new ServiceWorkerDisableParams.
func ServiceWorkerDisable() *ServiceWorkerDisableParams {
	return &ServiceWorkerDisableParams{}
}

// Do executes ServiceWorker.disable.
func (p *ServiceWorkerDisableParams) Do(ctx context.Context) error {
	return Execute(ctx, ServiceWorkerCommandDisable, p, nil)
}

type ServiceWorkerDispatchSyncEventParams struct {
	Origin         string                      `json:"origin"`
	RegistrationID ServiceWorkerRegistrationID `json:"registrationId"`
	Tag            string                      `json:"tag"`
	LastChance     bool                        `json:"lastChance"`
}

// ServiceWorkerDispatchSyncEvent creates a new ServiceWorkerDispatchSyncEventParams.
func ServiceWorkerDispatchSyncEvent(origin string, registrationID ServiceWorkerRegistrationID, tag string, lastChance bool) *ServiceWorkerDispatchSyncEventParams {
	return &ServiceWorkerDispatchSyncEventParams{
		Origin:         origin,
		RegistrationID: registrationID,
		Tag:            tag,
		LastChance:     lastChance,
	}
}

// Do executes ServiceWorker.dispatchSyncEvent.
func (p *ServiceWorkerDispatchSyncEventParams) Do(ctx context.Context) error {
	return Execute(ctx, ServiceWorkerCommandDispatchSyncEvent, p, nil)
}

type ServiceWorkerDispatchPeriodicSyncEventParams struct {
	Origin         string                      `json:"origin"`
	RegistrationID ServiceWorkerRegistrationID `json:"registrationId"`
	Tag            string                      `json:"tag"`
}

// ServiceWorkerDispatchPeriodicSyncEvent creates a new ServiceWorkerDispatchPeriodicSyncEventParams.
func ServiceWorkerDispatchPeriodicSyncEvent(origin string, registrationID ServiceWorkerRegistrationID, tag string) *ServiceWorkerDispatchPeriodicSyncEventParams {
	return &ServiceWorkerDispatchPeriodicSyncEventParams{
		Origin:         origin,
		RegistrationID: registrationID,
		Tag:            tag,
	}
}

// Do executes ServiceWorker.dispatchPeriodicSyncEvent.
func (p *ServiceWorkerDispatchPeriodicSyncEventParams) Do(ctx context.Context) error {
	return Execute(ctx, ServiceWorkerCommandDispatchPeriodicSyncEvent, p, nil)
}

type ServiceWorkerEnableParams struct{}

// ServiceWorkerEnable creates a new ServiceWorkerEnableParams.
func ServiceWorkerEnable() *ServiceWorkerEnableParams {
	return &ServiceWorkerEnableParams{}
}

// Do executes ServiceWorker.enable.
func (p *ServiceWorkerEnableParams) Do(ctx context.Context) error {
	return Execute(ctx, ServiceWorkerCommandEnable, p, nil)
}

type ServiceWorkerSetForceUpdateOnPageLoadParams struct {
	ForceUpdateOnPageLoad bool `json:"forceUpdateOnPageLoad"`
}

// ServiceWorkerSetForceUpdateOnPageLoad creates a new ServiceWorkerSetForceUpdateOnPageLoadParams.
func ServiceWorkerSetForceUpdateOnPageLoad(forceUpdateOnPageLoad bool) *ServiceWorkerSetForceUpdateOnPageLoadParams {
	return &ServiceWorkerSetForceUpdateOnPageLoadParams{
		ForceUpdateOnPageLoad: forceUpdateOnPageLoad,
	}
}

// Do executes ServiceWorker.setForceUpdateOnPageLoad.
func (p *ServiceWorkerSetForceUpdateOnPageLoadParams) Do(ctx context.Context) error {
	return Execute(ctx, ServiceWorkerCommandSetForceUpdateOnPageLoad, p, nil)
}

type ServiceWorkerSkipWaitingParams struct {
	ScopeURL string `json:"scopeURL"`
}

// ServiceWorkerSkipWaiting creates a new ServiceWorkerSkipWaitingParams.
func ServiceWorkerSkipWaiting(scopeURL string) *ServiceWorkerSkipWaitingParams {
	return &ServiceWorkerSkipWaitingParams{
		ScopeURL: scopeURL,
	}
}

// Do executes ServiceWorker.skipWaiting.
func (p *ServiceWorkerSkipWaitingParams) Do(ctx context.Context) error {
	return Execute(ctx, ServiceWorkerCommandSkipWaiting, p, nil)
}

type ServiceWorkerStartWorkerParams struct {
	ScopeURL string `json:"scopeURL"`
}

// ServiceWorkerStartWorker creates a new ServiceWorkerStartWorkerParams.
func ServiceWorkerStartWorker(scopeURL string) *ServiceWorkerStartWorkerParams {
	return &ServiceWorkerStartWorkerParams{
		ScopeURL: scopeURL,
	}
}

// Do executes ServiceWorker.startWorker.
func (p *ServiceWorkerStartWorkerParams) Do(ctx context.Context) error {
	return Execute(ctx, ServiceWorkerCommandStartWorker, p, nil)
}

type ServiceWorkerStopAllWorkersParams struct{}

// ServiceWorkerStopAllWorkers creates a new ServiceWorkerStopAllWorkersParams.
func ServiceWorkerStopAllWorkers() *ServiceWorkerStopAllWorkersParams {
	return &ServiceWorkerStopAllWorkersParams{}
}

// Do executes ServiceWorker.stopAllWorkers.
func (p *ServiceWorkerStopAllWorkersParams) Do(ctx context.Context) error {
	return Execute(ctx, ServiceWorkerCommandStopAllWorkers, p, nil)
}

type ServiceWorkerStopWorkerParams struct {
	VersionID string `json:"versionId"`
}

// ServiceWorkerStopWorker creates a new ServiceWorkerStopWorkerParams.
func ServiceWorkerStopWorker(versionID string) *ServiceWorkerStopWorkerParams {
	return &ServiceWorkerStopWorkerParams{
		VersionID: versionID,
	}
}

// Do executes ServiceWorker.stopWorker.
func (p *ServiceWorkerStopWorkerParams) Do(ctx context.Context) error {
	return Execute(ctx, ServiceWorkerCommandStopWorker, p, nil)
}

type ServiceWorkerUnregisterParams struct {
	ScopeURL string `json:"scopeURL"`
}

// ServiceWorkerUnregister creates a new ServiceWorkerUnregisterParams.
func ServiceWorkerUnregister(scopeURL string) *ServiceWorkerUnregisterParams {
	return &ServiceWorkerUnregisterParams{
		ScopeURL: scopeURL,
	}
}

// Do executes ServiceWorker.unregister.
func (p *ServiceWorkerUnregisterParams) Do(ctx context.Context) error {
	return Execute(ctx, ServiceWorkerCommandUnregister, p, nil)
}

type ServiceWorkerUpdateRegistrationParams struct {
	ScopeURL string `json:"scopeURL"`
}

// ServiceWorkerUpdateRegistration creates a new ServiceWorkerUpdateRegistrationParams.
func ServiceWorkerUpdateRegistration(scopeURL string) *ServiceWorkerUpdateRegistrationParams {
	return &ServiceWorkerUpdateRegistrationParams{
		ScopeURL: scopeURL,
	}
}

// Do executes ServiceWorker.updateRegistration.
func (p *ServiceWorkerUpdateRegistrationParams) Do(ctx context.Context) error {
	return Execute(ctx, ServiceWorkerCommandUpdateRegistration, p, nil)
}

// ServiceWorker command names.
const (
	ServiceWorkerCommandDeliverPushMessage        Method = "ServiceWorker.deliverPushMessage"
	ServiceWorkerCommandDisable                   Method = "ServiceWorker.disable"
	ServiceWorkerCommandDispatchSyncEvent         Method = "ServiceWorker.dispatchSyncEvent"
	ServiceWorkerCommandDispatchPeriodicSyncEvent Method = "ServiceWorker.dispatchPeriodicSyncEvent"
	ServiceWorkerCommandEnable                    Method = "ServiceWorker.enable"
	ServiceWorkerCommandSetForceUpdateOnPageLoad  Method = "ServiceWorker.setForceUpdateOnPageLoad"
	ServiceWorkerCommandSkipWaiting               Method = "ServiceWorker.skipWaiting"
	ServiceWorkerCommandStartWorker               Method = "ServiceWorker.startWorker"
	ServiceWorkerCommandStopAllWorkers            Method = "ServiceWorker.stopAllWorkers"
	ServiceWorkerCommandStopWorker                Method = "ServiceWorker.stopWorker"
	ServiceWorkerCommandUnregister                Method = "ServiceWorker.unregister"
	ServiceWorkerCommandUpdateRegistration        Method = "ServiceWorker.updateRegistration"
)
