// Code generated by bonkgen. DO NOT EDIT.

package proto

import "encoding/json"

// StorageEventCacheStorageContentUpdated A cache's contents have been modified.
type StorageEventCacheStorageContentUpdated struct {
	// Origin Origin to update.
	Origin string `json:"origin"`
	// StorageKey Storage key to update.
	StorageKey string `json:"storageKey"`
	// BucketID Storage bucket to update.
	BucketID string `json:"bucketId"`
	// CacheName Name of cache in origin.
	CacheName string `json:"cacheName"`
}

// StorageEventCacheStorageListUpdated A cache has been added/deleted.
type StorageEventCacheStorageListUpdated struct {
	// Origin Origin to update.
	Origin string `json:"origin"`
	// StorageKey Storage key to update.
	StorageKey string `json:"storageKey"`
	// BucketID Storage bucket to update.
	BucketID string `json:"bucketId"`
}

// StorageEventIndexedDBContentUpdated The origin's IndexedDB object store has been modified.
type StorageEventIndexedDBContentUpdated struct {
	// Origin Origin to update.
	Origin string `json:"origin"`
	// StorageKey Storage key to update.
	StorageKey string `json:"storageKey"`
	// BucketID Storage bucket to update.
	BucketID string `json:"bucketId"`
	// DatabaseName Database to update.
	DatabaseName string `json:"databaseName"`
	// ObjectStoreName ObjectStore to update.
	ObjectStoreName string `json:"objectStoreName"`
}

// StorageEventIndexedDBListUpdated The origin's IndexedDB database list has been modified.
type StorageEventIndexedDBListUpdated struct {
	// Origin Origin to update.
	Origin string `json:"origin"`
	// StorageKey Storage key to update.
	StorageKey string `json:"storageKey"`
	// BucketID Storage bucket to update.
	BucketID string `json:"bucketId"`
}

// StorageEventInterestGroupAccessed One of the interest groups was accessed. Note that these events are global
// to all targets sharing an interest group store.
type StorageEventInterestGroupAccessed struct {
	AccessTime  TimeSinceEpoch                 `json:"accessTime"`
	Type        StorageInterestGroupAccessType `json:"type"`
	OwnerOrigin string                         `json:"ownerOrigin"`
	Name        string                         `json:"name"`
	// ComponentSellerOrigin For topLevelBid/topLevelAdditionalBid, and when appropriate,
	// win and additionalBidWin
	ComponentSellerOrigin string `json:"componentSellerOrigin,omitempty,omitzero"`
	// Bid For bid or somethingBid event, if done locally and not on a server.
	Bid         float64 `json:"bid,omitempty,omitzero"`
	BidCurrency string  `json:"bidCurrency,omitempty,omitzero"`
	// UniqueAuctionID For non-global events --- links to interestGroupAuctionEvent
	UniqueAuctionID StorageInterestGroupAuctionID `json:"uniqueAuctionId,omitempty,omitzero"`
}

// StorageEventInterestGroupAuctionEventOccurred An auction involving interest groups is taking place. These events are
// target-specific.
type StorageEventInterestGroupAuctionEventOccurred struct {
	EventTime       TimeSinceEpoch                       `json:"eventTime"`
	Type            StorageInterestGroupAuctionEventType `json:"type"`
	UniqueAuctionID StorageInterestGroupAuctionID        `json:"uniqueAuctionId"`
	// ParentAuctionID Set for child auctions.
	ParentAuctionID StorageInterestGroupAuctionID `json:"parentAuctionId,omitempty,omitzero"`
	// AuctionConfig Set for started and configResolved
	AuctionConfig json.RawMessage `json:"auctionConfig,omitempty,omitzero"`
}

// StorageEventInterestGroupAuctionNetworkRequestCreated Specifies which auctions a particular network fetch may be related to, and
// in what role. Note that it is not ordered with respect to
// Network.requestWillBeSent (but will happen before loadingFinished
// loadingFailed).
type StorageEventInterestGroupAuctionNetworkRequestCreated struct {
	Type      StorageInterestGroupAuctionFetchType `json:"type"`
	RequestID RequestID                            `json:"requestId"`
	// Auctions This is the set of the auctions using the worklet that issued this
	// request.  In the case of trusted signals, it's possible that only some of
	// them actually care about the keys being queried.
	Auctions []StorageInterestGroupAuctionID `json:"auctions"`
}

// StorageEventSharedStorageAccessed Shared storage was accessed by the associated page.
// The following parameters are included in all events.
type StorageEventSharedStorageAccessed struct {
	// AccessTime Time of the access.
	AccessTime TimeSinceEpoch `json:"accessTime"`
	// Scope Enum value indicating the access scope.
	Scope StorageSharedStorageAccessScope `json:"scope"`
	// Method Enum value indicating the Shared Storage API method invoked.
	Method StorageSharedStorageAccessMethod `json:"method"`
	// MainFrameID DevTools Frame Token for the primary frame tree's root.
	MainFrameID FrameID `json:"mainFrameId"`
	// OwnerOrigin Serialization of the origin owning the Shared Storage data.
	OwnerOrigin string `json:"ownerOrigin"`
	// OwnerSite Serialization of the site owning the Shared Storage data.
	OwnerSite string `json:"ownerSite"`
	// Params The sub-parameters wrapped by `params` are all optional and their
	// presence/absence depends on `type`.
	Params StorageSharedStorageAccessParams `json:"params"`
}

// StorageEventSharedStorageWorkletOperationExecutionFinished A shared storage run or selectURL operation finished its execution.
// The following parameters are included in all events.
type StorageEventSharedStorageWorkletOperationExecutionFinished struct {
	// FinishedTime Time that the operation finished.
	FinishedTime TimeSinceEpoch `json:"finishedTime"`
	// ExecutionTime Time, in microseconds, from start of shared storage JS API call until
	// end of operation execution in the worklet.
	ExecutionTime int64 `json:"executionTime"`
	// Method Enum value indicating the Shared Storage API method invoked.
	Method StorageSharedStorageAccessMethod `json:"method"`
	// OperationID ID of the operation call.
	OperationID string `json:"operationId"`
	// WorkletTargetID Hex representation of the DevTools token used as the TargetID for the
	// associated shared storage worklet.
	WorkletTargetID TargetTargetID `json:"workletTargetId"`
	// MainFrameID DevTools Frame Token for the primary frame tree's root.
	MainFrameID FrameID `json:"mainFrameId"`
	// OwnerOrigin Serialization of the origin owning the Shared Storage data.
	OwnerOrigin string `json:"ownerOrigin"`
}

type StorageEventStorageBucketCreatedOrUpdated struct {
	BucketInfo StorageStorageBucketInfo `json:"bucketInfo"`
}

type StorageEventStorageBucketDeleted struct {
	BucketID string `json:"bucketId"`
}

type StorageEvent struct{}

type StorageEventAttributionReportingSourceRegistered struct {
	Registration StorageAttributionReportingSourceRegistration       `json:"registration"`
	Result       StorageAttributionReportingSourceRegistrationResult `json:"result"`
}

type StorageEventAttributionReportingTriggerRegistered struct {
	Registration StorageAttributionReportingTriggerRegistration `json:"registration"`
	EventLevel   StorageAttributionReportingEventLevelResult    `json:"eventLevel"`
	Aggregatable StorageAttributionReportingAggregatableResult  `json:"aggregatable"`
}

type StorageEventAttributionReportingReportSent struct {
	URL    string                                  `json:"url"`
	Body   json.RawMessage                         `json:"body"`
	Result StorageAttributionReportingReportResult `json:"result"`
	// NetError If result is `sent`, populated with net/HTTP status.
	NetError       int64  `json:"netError,omitempty,omitzero"`
	NetErrorName   string `json:"netErrorName,omitempty,omitzero"`
	HTTPStatusCode int64  `json:"httpStatusCode,omitempty,omitzero"`
}

type StorageEventAttributionReportingVerboseDebugReportSent struct {
	URL            string            `json:"url"`
	Body           []json.RawMessage `json:"body,omitempty,omitzero"`
	NetError       int64             `json:"netError,omitempty,omitzero"`
	NetErrorName   string            `json:"netErrorName,omitempty,omitzero"`
	HTTPStatusCode int64             `json:"httpStatusCode,omitempty,omitzero"`
}

// Storage event names.
const (
	StorageEventCacheStorageContentUpdatedMethod                     Method = "Storage.cacheStorageContentUpdated"
	StorageEventCacheStorageListUpdatedMethod                        Method = "Storage.cacheStorageListUpdated"
	StorageEventIndexedDBContentUpdatedMethod                        Method = "Storage.indexedDBContentUpdated"
	StorageEventIndexedDBListUpdatedMethod                           Method = "Storage.indexedDBListUpdated"
	StorageEventInterestGroupAccessedMethod                          Method = "Storage.interestGroupAccessed"
	StorageEventInterestGroupAuctionEventOccurredMethod              Method = "Storage.interestGroupAuctionEventOccurred"
	StorageEventInterestGroupAuctionNetworkRequestCreatedMethod      Method = "Storage.interestGroupAuctionNetworkRequestCreated"
	StorageEventSharedStorageAccessedMethod                          Method = "Storage.sharedStorageAccessed"
	StorageEventSharedStorageWorkletOperationExecutionFinishedMethod Method = "Storage.sharedStorageWorkletOperationExecutionFinished"
	StorageEventStorageBucketCreatedOrUpdatedMethod                  Method = "Storage.storageBucketCreatedOrUpdated"
	StorageEventStorageBucketDeletedMethod                           Method = "Storage.storageBucketDeleted"
	StorageEventMethod                                               Method = "Storage."
	StorageEventAttributionReportingSourceRegisteredMethod           Method = "Storage.attributionReportingSourceRegistered"
	StorageEventAttributionReportingTriggerRegisteredMethod          Method = "Storage.attributionReportingTriggerRegistered"
	StorageEventAttributionReportingReportSentMethod                 Method = "Storage.attributionReportingReportSent"
	StorageEventAttributionReportingVerboseDebugReportSentMethod     Method = "Storage.attributionReportingVerboseDebugReportSent"
)
