// Code generated by bonkgen. DO NOT EDIT.

package proto

// TetheringEventAccepted Informs that port was successfully bound and got a specified connection id.
type TetheringEventAccepted struct {
	// Port Port number that was successfully bound.
	Port int64 `json:"port"`
	// ConnectionID Connection id to be used.
	ConnectionID string `json:"connectionId"`
}

// Tethering event names.
const (
	TetheringEventAcceptedMethod Method = "Tethering.accepted"
)
