// Code generated by bonkgen. DO NOT EDIT.

package proto

// WebAudioGraphObjectID An unique ID for a graph object (AudioContext, AudioNode, AudioParam) in Web Audio API
type WebAudioGraphObjectID string

// String returns the WebAudioGraphObjectID as a string.
func (t WebAudioGraphObjectID) String() string {
	return string(t)
}

// WebAudioContextType Enum of BaseAudioContext types
type WebAudioContextType string

const (
	WebAudioContextTypeRealtime WebAudioContextType = "realtime"
	WebAudioContextTypeOffline  WebAudioContextType = "offline"
)

// IsValid reports whether the value is a known enum value.
func (t WebAudioContextType) IsValid() bool {
	switch t {
	case WebAudioContextTypeRealtime:
		return true
	case WebAudioContextTypeOffline:
		return true
	}
	return false
}

// Values returns all known values of WebAudioContextType.
func (t WebAudioContextType) Values() []WebAudioContextType {
	return []WebAudioContextType{
		WebAudioContextTypeRealtime,
		WebAudioContextTypeOffline,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t WebAudioContextType) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *WebAudioContextType) UnmarshalText(data []byte) error {
	*t = WebAudioContextType(data)
	return nil
}

// String returns the string representation.
func (t WebAudioContextType) String() string {
	return string(t)
}

// WebAudioContextState Enum of AudioContextState from the spec
type WebAudioContextState string

const (
	WebAudioContextStateSuspended   WebAudioContextState = "suspended"
	WebAudioContextStateRunning     WebAudioContextState = "running"
	WebAudioContextStateClosed      WebAudioContextState = "closed"
	WebAudioContextStateInterrupted WebAudioContextState = "interrupted"
)

// IsValid reports whether the value is a known enum value.
func (t WebAudioContextState) IsValid() bool {
	switch t {
	case WebAudioContextStateSuspended:
		return true
	case WebAudioContextStateRunning:
		return true
	case WebAudioContextStateClosed:
		return true
	case WebAudioContextStateInterrupted:
		return true
	}
	return false
}

// Values returns all known values of WebAudioContextState.
func (t WebAudioContextState) Values() []WebAudioContextState {
	return []WebAudioContextState{
		WebAudioContextStateSuspended,
		WebAudioContextStateRunning,
		WebAudioContextStateClosed,
		WebAudioContextStateInterrupted,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t WebAudioContextState) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *WebAudioContextState) UnmarshalText(data []byte) error {
	*t = WebAudioContextState(data)
	return nil
}

// String returns the string representation.
func (t WebAudioContextState) String() string {
	return string(t)
}

// WebAudioNodeType Enum of AudioNode types
type WebAudioNodeType string

// String returns the WebAudioNodeType as a string.
func (t WebAudioNodeType) String() string {
	return string(t)
}

// WebAudioChannelCountMode Enum of AudioNode::ChannelCountMode from the spec
type WebAudioChannelCountMode string

const (
	WebAudioChannelCountModeClampedMax WebAudioChannelCountMode = "clamped-max"
	WebAudioChannelCountModeExplicit   WebAudioChannelCountMode = "explicit"
	WebAudioChannelCountModeMax        WebAudioChannelCountMode = "max"
)

// IsValid reports whether the value is a known enum value.
func (t WebAudioChannelCountMode) IsValid() bool {
	switch t {
	case WebAudioChannelCountModeClampedMax:
		return true
	case WebAudioChannelCountModeExplicit:
		return true
	case WebAudioChannelCountModeMax:
		return true
	}
	return false
}

// Values returns all known values of WebAudioChannelCountMode.
func (t WebAudioChannelCountMode) Values() []WebAudioChannelCountMode {
	return []WebAudioChannelCountMode{
		WebAudioChannelCountModeClampedMax,
		WebAudioChannelCountModeExplicit,
		WebAudioChannelCountModeMax,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t WebAudioChannelCountMode) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *WebAudioChannelCountMode) UnmarshalText(data []byte) error {
	*t = WebAudioChannelCountMode(data)
	return nil
}

// String returns the string representation.
func (t WebAudioChannelCountMode) String() string {
	return string(t)
}

// WebAudioChannelInterpretation Enum of AudioNode::ChannelInterpretation from the spec
type WebAudioChannelInterpretation string

const (
	WebAudioChannelInterpretationDiscrete WebAudioChannelInterpretation = "discrete"
	WebAudioChannelInterpretationSpeakers WebAudioChannelInterpretation = "speakers"
)

// IsValid reports whether the value is a known enum value.
func (t WebAudioChannelInterpretation) IsValid() bool {
	switch t {
	case WebAudioChannelInterpretationDiscrete:
		return true
	case WebAudioChannelInterpretationSpeakers:
		return true
	}
	return false
}

// Values returns all known values of WebAudioChannelInterpretation.
func (t WebAudioChannelInterpretation) Values() []WebAudioChannelInterpretation {
	return []WebAudioChannelInterpretation{
		WebAudioChannelInterpretationDiscrete,
		WebAudioChannelInterpretationSpeakers,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t WebAudioChannelInterpretation) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *WebAudioChannelInterpretation) UnmarshalText(data []byte) error {
	*t = WebAudioChannelInterpretation(data)
	return nil
}

// String returns the string representation.
func (t WebAudioChannelInterpretation) String() string {
	return string(t)
}

// WebAudioParamType Enum of AudioParam types
type WebAudioParamType string

// String returns the WebAudioParamType as a string.
func (t WebAudioParamType) String() string {
	return string(t)
}

// WebAudioAutomationRate Enum of AudioParam::AutomationRate from the spec
type WebAudioAutomationRate string

const (
	WebAudioAutomationRateARate WebAudioAutomationRate = "a-rate"
	WebAudioAutomationRateKRate WebAudioAutomationRate = "k-rate"
)

// IsValid reports whether the value is a known enum value.
func (t WebAudioAutomationRate) IsValid() bool {
	switch t {
	case WebAudioAutomationRateARate:
		return true
	case WebAudioAutomationRateKRate:
		return true
	}
	return false
}

// Values returns all known values of WebAudioAutomationRate.
func (t WebAudioAutomationRate) Values() []WebAudioAutomationRate {
	return []WebAudioAutomationRate{
		WebAudioAutomationRateARate,
		WebAudioAutomationRateKRate,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t WebAudioAutomationRate) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *WebAudioAutomationRate) UnmarshalText(data []byte) error {
	*t = WebAudioAutomationRate(data)
	return nil
}

// String returns the string representation.
func (t WebAudioAutomationRate) String() string {
	return string(t)
}

// WebAudioContextRealtimeData Fields in AudioContext that change in real-time.
type WebAudioContextRealtimeData struct {
	// CurrentTime The current context time in second in BaseAudioContext.
	CurrentTime float64 `json:"currentTime"`
	// RenderCapacity The time spent on rendering graph divided by render quantum duration,
	// and multiplied by 100. 100 means the audio renderer reached the full
	// capacity and glitch may occur.
	RenderCapacity float64 `json:"renderCapacity"`
	// CallbackIntervalMean A running mean of callback interval.
	CallbackIntervalMean float64 `json:"callbackIntervalMean"`
	// CallbackIntervalVariance A running variance of callback interval.
	CallbackIntervalVariance float64 `json:"callbackIntervalVariance"`
}

// WebAudioBaseAudioContext Protocol object for BaseAudioContext
type WebAudioBaseAudioContext struct {
	ContextID    WebAudioGraphObjectID       `json:"contextId"`
	ContextType  WebAudioContextType         `json:"contextType"`
	ContextState WebAudioContextState        `json:"contextState"`
	RealtimeData WebAudioContextRealtimeData `json:"realtimeData,omitempty"`
	// CallbackBufferSize Platform-dependent callback buffer size.
	CallbackBufferSize float64 `json:"callbackBufferSize"`
	// MaxOutputChannelCount Number of output channels supported by audio hardware in use.
	MaxOutputChannelCount float64 `json:"maxOutputChannelCount"`
	// SampleRate Context sample rate.
	SampleRate float64 `json:"sampleRate"`
}

// WebAudioAudioListener Protocol object for AudioListener
type WebAudioAudioListener struct {
	ListenerID WebAudioGraphObjectID `json:"listenerId"`
	ContextID  WebAudioGraphObjectID `json:"contextId"`
}

// WebAudioAudioNode Protocol object for AudioNode
type WebAudioAudioNode struct {
	NodeID                WebAudioGraphObjectID         `json:"nodeId"`
	ContextID             WebAudioGraphObjectID         `json:"contextId"`
	NodeType              WebAudioNodeType              `json:"nodeType"`
	NumberOfInputs        float64                       `json:"numberOfInputs"`
	NumberOfOutputs       float64                       `json:"numberOfOutputs"`
	ChannelCount          float64                       `json:"channelCount"`
	ChannelCountMode      WebAudioChannelCountMode      `json:"channelCountMode"`
	ChannelInterpretation WebAudioChannelInterpretation `json:"channelInterpretation"`
}

// WebAudioAudioParam Protocol object for AudioParam
type WebAudioAudioParam struct {
	ParamID      WebAudioGraphObjectID  `json:"paramId"`
	NodeID       WebAudioGraphObjectID  `json:"nodeId"`
	ContextID    WebAudioGraphObjectID  `json:"contextId"`
	ParamType    WebAudioParamType      `json:"paramType"`
	Rate         WebAudioAutomationRate `json:"rate"`
	DefaultValue float64                `json:"defaultValue"`
	MinValue     float64                `json:"minValue"`
	MaxValue     float64                `json:"maxValue"`
}
