// Code generated by bonkgen. DO NOT EDIT.

package proto

import "context"

// WebAudioEnableParams Enables the WebAudio domain and starts sending context lifetime events.
type WebAudioEnableParams struct{}

// WebAudioEnable creates a new WebAudioEnableParams.
func WebAudioEnable() *WebAudioEnableParams {
	return &WebAudioEnableParams{}
}

// Do executes WebAudio.enable.
func (p *WebAudioEnableParams) Do(ctx context.Context) error {
	return Execute(ctx, WebAudioCommandEnable, p, nil)
}

// WebAudioDisableParams Disables the WebAudio domain.
type WebAudioDisableParams struct{}

// WebAudioDisable creates a new WebAudioDisableParams.
func WebAudioDisable() *WebAudioDisableParams {
	return &WebAudioDisableParams{}
}

// Do executes WebAudio.disable.
func (p *WebAudioDisableParams) Do(ctx context.Context) error {
	return Execute(ctx, WebAudioCommandDisable, p, nil)
}

// WebAudioGetRealtimeDataParams Fetch the realtime data from the registered contexts.
type WebAudioGetRealtimeDataParams struct {
	ContextID WebAudioGraphObjectID `json:"contextId"`
}

// WebAudioGetRealtimeDataReturns holds the return values for getRealtimeData.
type WebAudioGetRealtimeDataReturns struct {
	RealtimeData WebAudioContextRealtimeData `json:"realtimeData"`
}

// WebAudioGetRealtimeData creates a new WebAudioGetRealtimeDataParams.
func WebAudioGetRealtimeData(contextID WebAudioGraphObjectID) *WebAudioGetRealtimeDataParams {
	return &WebAudioGetRealtimeDataParams{
		ContextID: contextID,
	}
}

// Do executes WebAudio.getRealtimeData.
func (p *WebAudioGetRealtimeDataParams) Do(ctx context.Context) (*WebAudioGetRealtimeDataReturns, error) {
	var res WebAudioGetRealtimeDataReturns
	if err := Execute(ctx, WebAudioCommandGetRealtimeData, p, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// WebAudio command names.
const (
	WebAudioCommandEnable          Method = "WebAudio.enable"
	WebAudioCommandDisable         Method = "WebAudio.disable"
	WebAudioCommandGetRealtimeData Method = "WebAudio.getRealtimeData"
)
