// Code generated by bonkgen. DO NOT EDIT.

package proto

type WebAuthnAuthenticatorID string

// String returns the WebAuthnAuthenticatorID as a string.
func (t WebAuthnAuthenticatorID) String() string {
	return string(t)
}

type WebAuthnAuthenticatorProtocol string

const (
	WebAuthnAuthenticatorProtocolU2f   WebAuthnAuthenticatorProtocol = "u2f"
	WebAuthnAuthenticatorProtocolCtap2 WebAuthnAuthenticatorProtocol = "ctap2"
)

// IsValid reports whether the value is a known enum value.
func (t WebAuthnAuthenticatorProtocol) IsValid() bool {
	switch t {
	case WebAuthnAuthenticatorProtocolU2f:
		return true
	case WebAuthnAuthenticatorProtocolCtap2:
		return true
	}
	return false
}

// Values returns all known values of WebAuthnAuthenticatorProtocol.
func (t WebAuthnAuthenticatorProtocol) Values() []WebAuthnAuthenticatorProtocol {
	return []WebAuthnAuthenticatorProtocol{
		WebAuthnAuthenticatorProtocolU2f,
		WebAuthnAuthenticatorProtocolCtap2,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t WebAuthnAuthenticatorProtocol) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *WebAuthnAuthenticatorProtocol) UnmarshalText(data []byte) error {
	*t = WebAuthnAuthenticatorProtocol(data)
	return nil
}

// String returns the string representation.
func (t WebAuthnAuthenticatorProtocol) String() string {
	return string(t)
}

type WebAuthnCtap2Version string

const (
	WebAuthnCtap2VersionCtap20 WebAuthnCtap2Version = "ctap2_0"
	WebAuthnCtap2VersionCtap21 WebAuthnCtap2Version = "ctap2_1"
	WebAuthnCtap2VersionCtap22 WebAuthnCtap2Version = "ctap2_2"
)

// IsValid reports whether the value is a known enum value.
func (t WebAuthnCtap2Version) IsValid() bool {
	switch t {
	case WebAuthnCtap2VersionCtap20:
		return true
	case WebAuthnCtap2VersionCtap21:
		return true
	case WebAuthnCtap2VersionCtap22:
		return true
	}
	return false
}

// Values returns all known values of WebAuthnCtap2Version.
func (t WebAuthnCtap2Version) Values() []WebAuthnCtap2Version {
	return []WebAuthnCtap2Version{
		WebAuthnCtap2VersionCtap20,
		WebAuthnCtap2VersionCtap21,
		WebAuthnCtap2VersionCtap22,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t WebAuthnCtap2Version) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *WebAuthnCtap2Version) UnmarshalText(data []byte) error {
	*t = WebAuthnCtap2Version(data)
	return nil
}

// String returns the string representation.
func (t WebAuthnCtap2Version) String() string {
	return string(t)
}

type WebAuthnAuthenticatorTransport string

const (
	WebAuthnAuthenticatorTransportUsb      WebAuthnAuthenticatorTransport = "usb"
	WebAuthnAuthenticatorTransportNfc      WebAuthnAuthenticatorTransport = "nfc"
	WebAuthnAuthenticatorTransportBle      WebAuthnAuthenticatorTransport = "ble"
	WebAuthnAuthenticatorTransportCable    WebAuthnAuthenticatorTransport = "cable"
	WebAuthnAuthenticatorTransportInternal WebAuthnAuthenticatorTransport = "internal"
)

// IsValid reports whether the value is a known enum value.
func (t WebAuthnAuthenticatorTransport) IsValid() bool {
	switch t {
	case WebAuthnAuthenticatorTransportUsb:
		return true
	case WebAuthnAuthenticatorTransportNfc:
		return true
	case WebAuthnAuthenticatorTransportBle:
		return true
	case WebAuthnAuthenticatorTransportCable:
		return true
	case WebAuthnAuthenticatorTransportInternal:
		return true
	}
	return false
}

// Values returns all known values of WebAuthnAuthenticatorTransport.
func (t WebAuthnAuthenticatorTransport) Values() []WebAuthnAuthenticatorTransport {
	return []WebAuthnAuthenticatorTransport{
		WebAuthnAuthenticatorTransportUsb,
		WebAuthnAuthenticatorTransportNfc,
		WebAuthnAuthenticatorTransportBle,
		WebAuthnAuthenticatorTransportCable,
		WebAuthnAuthenticatorTransportInternal,
	}
}

// MarshalText satisfies the encoding.TextMarshaler interface.
func (t WebAuthnAuthenticatorTransport) MarshalText() ([]byte, error) {
	return []byte(t), nil
}

// UnmarshalText satisfies the encoding.TextUnmarshaler interface.
func (t *WebAuthnAuthenticatorTransport) UnmarshalText(data []byte) error {
	*t = WebAuthnAuthenticatorTransport(data)
	return nil
}

// String returns the string representation.
func (t WebAuthnAuthenticatorTransport) String() string {
	return string(t)
}

type WebAuthnVirtualAuthenticatorOptions struct {
	Protocol WebAuthnAuthenticatorProtocol `json:"protocol"`
	// Ctap2Version Defaults to ctap2_0. Ignored if |protocol| == u2f.
	Ctap2Version WebAuthnCtap2Version           `json:"ctap2Version,omitempty"`
	Transport    WebAuthnAuthenticatorTransport `json:"transport"`
	// HasResidentKey Defaults to false.
	HasResidentKey bool `json:"hasResidentKey,omitempty"`
	// HasUserVerification Defaults to false.
	HasUserVerification bool `json:"hasUserVerification,omitempty"`
	// HasLargeBlob If set to true, the authenticator will support the largeBlob extension.
	// https://w3c.github.io/webauthn#largeBlob
	// Defaults to false.
	HasLargeBlob bool `json:"hasLargeBlob,omitempty"`
	// HasCredBlob If set to true, the authenticator will support the credBlob extension.
	// https://fidoalliance.org/specs/fido-v2.1-rd-20201208/fido-client-to-authenticator-protocol-v2.1-rd-20201208.html#sctn-credBlob-extension
	// Defaults to false.
	HasCredBlob bool `json:"hasCredBlob,omitempty"`
	// HasMinPinLength If set to true, the authenticator will support the minPinLength extension.
	// https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#sctn-minpinlength-extension
	// Defaults to false.
	HasMinPinLength bool `json:"hasMinPinLength,omitempty"`
	// HasPrf If set to true, the authenticator will support the prf extension.
	// https://w3c.github.io/webauthn/#prf-extension
	// Defaults to false.
	HasPrf bool `json:"hasPrf,omitempty"`
	// HasHmacSecret If set to true, the authenticator will support the hmac-secret extension.
	// https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#sctn-hmac-secret-extension
	// Defaults to false.
	HasHmacSecret bool `json:"hasHmacSecret,omitempty"`
	// HasHmacSecretMc If set to true, the authenticator will support the hmac-secret-mc extension.
	// https://fidoalliance.org/specs/fido-v2.2-rd-20241003/fido-client-to-authenticator-protocol-v2.2-rd-20241003.html#sctn-hmac-secret-make-cred-extension
	// Defaults to false.
	HasHmacSecretMc bool `json:"hasHmacSecretMc,omitempty"`
	// AutomaticPresenceSimulation If set to true, tests of user presence will succeed immediately.
	// Otherwise, they will not be resolved. Defaults to true.
	AutomaticPresenceSimulation bool `json:"automaticPresenceSimulation,omitempty"`
	// IsUserVerified Sets whether User Verification succeeds or fails for an authenticator.
	// Defaults to false.
	IsUserVerified bool `json:"isUserVerified,omitempty"`
	// DefaultBackupEligibility Credentials created by this authenticator will have the backup
	// eligibility (BE) flag set to this value. Defaults to false.
	// https://w3c.github.io/webauthn/#sctn-credential-backup
	DefaultBackupEligibility bool `json:"defaultBackupEligibility,omitempty"`
	// DefaultBackupState Credentials created by this authenticator will have the backup state
	// (BS) flag set to this value. Defaults to false.
	// https://w3c.github.io/webauthn/#sctn-credential-backup
	DefaultBackupState bool `json:"defaultBackupState,omitempty"`
}

type WebAuthnCredential struct {
	CredentialID         []byte `json:"credentialId"`
	IsResidentCredential bool   `json:"isResidentCredential"`
	// RpID Relying Party ID the credential is scoped to. Must be set when adding a
	// credential.
	RpID string `json:"rpId,omitempty"`
	// PrivateKey The ECDSA P-256 private key in PKCS#8 format.
	PrivateKey []byte `json:"privateKey"`
	// UserHandle An opaque byte sequence with a maximum size of 64 bytes mapping the
	// credential to a specific user.
	UserHandle []byte `json:"userHandle,omitempty"`
	// SignCount Signature counter. This is incremented by one for each successful
	// assertion.
	// See https://w3c.github.io/webauthn/#signature-counter
	SignCount int64 `json:"signCount"`
	// LargeBlob The large blob associated with the credential.
	// See https://w3c.github.io/webauthn/#sctn-large-blob-extension
	LargeBlob []byte `json:"largeBlob,omitempty"`
	// BackupEligibility Assertions returned by this credential will have the backup eligibility
	// (BE) flag set to this value. Defaults to the authenticator's
	// defaultBackupEligibility value.
	BackupEligibility bool `json:"backupEligibility,omitempty"`
	// BackupState Assertions returned by this credential will have the backup state (BS)
	// flag set to this value. Defaults to the authenticator's
	// defaultBackupState value.
	BackupState bool `json:"backupState,omitempty"`
	// UserName The credential's user.name property. Equivalent to empty if not set.
	// https://w3c.github.io/webauthn/#dom-publickeycredentialentity-name
	UserName string `json:"userName,omitempty"`
	// UserDisplayName The credential's user.displayName property. Equivalent to empty if
	// not set.
	// https://w3c.github.io/webauthn/#dom-publickeycredentialuserentity-displayname
	UserDisplayName string `json:"userDisplayName,omitempty"`
}
